은행창구 관리앱 [STEP 1] Logan, Sunny
tasty-code/ios-bank-manager pull request #15
Opened 2023-02-21 16:44 UTC by SunnnySong

# [STEP 1] Bank Manager : Sunny Logan

>안녕하세요 코리(@corykim0829)🤗 이번 3주동안의 프로젝트를 진행하게될 Team SUGAN의 Sunny와 Logan 이에요!😊 만나서 너무 반가워요😆 이번 Step1의 요구사항중 Unit Test를 작성하는 부분은 저희가 시간에 쫓기다보니 구현하지 못했어요..🥹 그래도 나머지 부분은 최대한 열심히 구현했어요! 아직 초반이라 볼 건 많지 않으시겠지만 좋은리뷰 부탁드려요!! 🥰

---
### 🌼 요구사항
- 은행에 도착한 고객이 임시로 대기할 대기열(큐, Queue) 타입을 직접 구현합니다.

- Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다
- Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용합니다
- Queue 타입이 예상한대로 동작하는지 Unit Test를 통해 동작을 검증합니다
- Queue에 구현해야 할 필수 기능
Enqueue, Dequeue, Clear, Peek, isEmpty
---
### 🌱 구현사항
- 저희는 Queue를 구현할때 protocol을 사용해서 Queue 형식의 동작이 필요한 객체들이 채택해서 사용할 수 있도록 해봤어요
```swift
protocol Queue {
    associatedtype T
    
    func enqueue(_ newData: T)
    func dequeue() -> T?
    func clear()
    func peek() -> T?
    func isEmpty() -> Bool
}
```
<br>
- 위의 Queue protocol을 채택한 타입은 아래처럼 구현돼요

```swift
final class WaitingManager<T>: Queue {
    
    private let queue: LinkedList = LinkedList<T>()
    
    func enqueue(_ newData: T) {
        queue.append(newData)
    }
    
    func dequeue() -> T? {
        return queue.removeFirst()
    }
    
    func clear() {
        queue.removeAll()
    }
    
    func peek() -> T? {
        return queue.showFirst()
    }
    
    func isEmpty() -> Bool {
        return queue.isEmpty
    }
}
```
---
### 😰 구현을 위해 도전했던 방법들
이번주에 진행했던, 진행할 주제들이 모두 '객체지향', 'POP'와 관련된 수업이에요. 그래서 이번 Step1 구현에 있어서 이 점을 최대한 반영해서 코드를 작성하고 싶었어요. 

먼저 이번 요구사항을 보며 어떤 요소를 프로토콜로 만들 수 있을지 생각해보았고, 저희는 Linked-list 구현에 필요한 Node, Queue를 protocol로 구현해보자 했어요.

##### 1. Node protocol 구현
```swift
protocol Node {
    associatedtype T
    var value: T { get }
    var next: Self? { get set }
}
``` 

<br>

##### 2. LinkedlistNode class 구현
```swift
final class LinkedlistNode<T>: Node {
    var value: T?
    var next: LinkedlistNode?

    init(value: T? = nil, next: LinkedlistNode? = nil) {
        self.value = value
        self.next = next
    }
}
```
Linkedlist는 Node를 연결한 list 형식이에요. LinkedlistNode는 Node protocol을 준수해서 Linked-list 자료형을 구현했어요.

<br>

##### 3. Queue의 method 관련 protocol 구현
```swift
protocol QueueDataStructure {
    associatedtype Item
    associatedtype T
    var front: Item? { get set }
    
    mutating func enqueue(_ newItem: Item)
    mutating func dequeue() -> Item?
}
```
Queue는 Item이 추가되고, 삭제되는 자료구조이에요. Queue의 종류는 다양하지만 종류와 관계 없이 Queue라면 공통으로 갖고 있는 메서드들을 protocol로 만들고자 했어요. peek, isEmpty 등 Queue의 메서드들이 존재했지만, 예시를 위해 일단 enqueue, dequeue만 구현했어요. 

Queue에 들어오는 item에 어떤 타입이든 가능하게 만들기 위해 ``제네릭``으로 구현했어요.

<br>

##### 4. extension QueueDataStructure에 구체적 메소드 구현하기
```swift
extension QueueDataStructure where Item == LinkedlistNode<T> {
    mutating func enqueue(_ newItem: Item) {
        if front == nil {
            front = newItem
            return
        }
        
        var node = front
        while node?.next != nil {
            node = node?.next
        }

        node?.next = newItem
    }
    
    mutating func dequeue() -> Item? {
        guard front != nil else {
            return nil
        }

        let result = front
        front = front?.next

        return result
    }
}
```
Linked-list는 LinkedlistNode를 사용하기 때문에 위의 코드를 작성해보았어요. <br>
Linked-list를 사용해 Queue를 만들게 되면, Queue에 추가되고 삭제되는 Item은 ``LinkedlistNode``가 될 것이라 생각했어요.
제네릭으로 구현한 Queue protocol 에서 ```Item == LinkedlistNode```일 경우, enqueue와 dequeue를 LinkedList에서 Node가 추가되고 삭제되는 방식으로 구체화하여 코드를 구현했어요. 

<br>

##### 5. Queue를 사용해 은행 대기열 구현하기
```swift
struct WaitingManager<T>: QueueDataStructure {
    var front: LinkedlistNode<T>?
    
   mutating func join(_ customer: T) {
        let newNode = LinkedlistNode(value: customer)
        self.enqueue(newNode)
    }
    
    mutating func release() -> T? {
        let result = self.dequeue()
        return result?.value
    }
}
```
은행 대기열은 Queue 데이터 구조를 사용해야 하기 때문에 ```QueueDataStructure``` protocol을 채택해요. <br>

```QueueDataStructure``` protocol을 채택하면서, 동시에 protocol의 제네릭 타입인 Item이 ```LinkedlistNode<T>```이기 때문에 extension으로 구현한 enqueue와 dequeue 메서드를 사용 가능하게 되요.
<br>

마지막으로 queue에 데이터를 추가하기 쉽게 join, release 메서드를 추가했어요.
join 함수는 LinkedlistNode 타입이 아닌 제네릭 타입으로 받고, 그 데이터를 LinkedlistNode 인스턴스로 만들어 추가하는 방식으로 구현했어요. release 함수도 동일하게 LinkedlistNode 타입으로 받은 return value를 제네릭 타입으로 바꿔주었어요. 

<br>

##### 😭 이 방식을 포기한 이유와 궁금한 점

이 코드에는 ```Node``` protocol을 채택한 ```LinkedlistNode``` class와 ```QueueDataStructure``` protocol을 채택한 ```WaitingManager``` struct가 존재해요. 이번 Step1 요구사항에서는 Linked-list 타입과 Queue 타입을 직접 구현하라고 되어있어요. 

일단, LinkedlistNode를 사용해 WaitingManager을 구현하는 방식이 Linked-list 타입과 Queue타입을 직접 구현한 것인가 확신이 들지 않았어요. '직접 구현'이라는 말이 ```struct Array``` 처럼 타입을 만들어야 하는 건지 의문이 들었어요.
<br>

두 번째 이유로는 ```protocol extension``` 이었어요. ```QueueDataStructure```에 extension으로 추가한 enqueue, dequeue코드가 오히려 LinkedList 타입의 역할을 과도하게 침범한 것은 아닐까? 하는 생각이 들었어요.
<br>

저희 모두 저번 계산기 프로젝트에서 Linked-list 자료구조를 사용해본 경험이 있어서 이번 프로젝트땐, 그 때와 다른 구조로 코드를 작성해보고자 했던 생각이 여기까지 흐르게 되었어요🥲   

위 방법에 대한 코리의 생각은 어떤가요? 저희의 결론은 위 방법보단 PR에 적혀있는 방법이 더 데이터 타입 별 역할이 잘 구분되어져 있다고 생각해 선택했지만 어떤 코드가 좋은 코드인지, 효율적인 코드인지 분간이 가지 않아 어려운 것 같아요🥹 

이 방식에 대한 코리의 의견을 남겨주신다면 감사하겠습니다😁

---
### 질문 🤔
- `LinkedList`를 구현함에 있어서 처음엔 `Struct`로 구현했다가 마지막에 `Class`로 바꾸게 됐는데 이유는 `Struct`가 많은 레퍼런스를 가지게 되면 성능이 떨어지게 된다는 말을 들었기 떄문입니다 코리의 의견은 어떤지 궁금해요

2023-02-22 14:06 UTC, corykim0829 requested changes
수고하셨습니다! 
프로토콜로 구현하려는 시도들과 기록들을 남겨둔게 보기 좋네요 👍


> 일단, LinkedlistNode를 사용해 WaitingManager를 구현하는 방식이 Linked-list 타입과 Queue타입을 직접 구현한 것인가 확신이 들지 않았어요. '직접 구현'이라는 말이 struct Array 처럼 타입을 만들어야 하는 건지 의문이 들었어요.

struct나 class로 구현해야하는지 궁금해하시는 것 같은데 맞을까요?. 프로토콜도 타입이기 때문에 괜찮습니다.

> 두 번째 이유로는 protocol extension 이었어요. QueueDataStructure에 extension으로 추가한 enqueue, dequeue코드가 오히려 LinkedList 타입의 역할을 과도하게 침범한 것은 아닐까? 하는 생각이 들었어요.
저희 모두 저번 계산기 프로젝트에서 Linked-list 자료구조를 사용해본 경험이 있어서 이번 프로젝트땐, 그 때와 다른 구조로 코드를 작성해보고자 했던 생각이 여기까지 흐르게 되었어요🥲
위 방법에 대한 코리의 생각은 어떤가요? 저희의 결론은 위 방법보단 PR에 적혀있는 방법이 더 데이터 타입 별 역할이 잘 구분되어져 있다고 생각해 선택했지만 어떤 코드가 좋은 코드인지, 효율적인 코드인지 분간이 가지 않아 어려운 것 같아요🥹
이 방식에 대한 코리의 의견을 남겨주신다면 감사하겠습니다😁

제 생각에는 protocol, struct, class가 만들어진 목적을 알아본다면, 이 고민에 도움이 될 것 같다는 드네요!
어떻게 구현하던지 동작이 된다면 문제가 없지만, 더 나아가서 더 좋은 코드로 작성하기 위해서는 어떤 타입을 사용해야할지 장단점을 직접 따져보면 어떨까요?

Queue를 프로토콜로 구현하신 것도 다른 타입으로 구현했을 때와의 장단점을 비교해보면 좋을 것 같습니다!

---

> LinkedList를 구현함에 있어서 처음엔 Struct로 구현했다가 마지막에 Class로 바꾸게 됐는데 이유는 Struct가 많은 레퍼런스를 가지게 되면 성능이 떨어지게 된다는 말을 들었기 떄문입니다 코리의 의견은 어떤지 궁금해요

이 부분은 제가 직접 답을 해드리기보다는 직접 알아보시는게 도움이 될 것 같네요! class와 struct의 차이점을 비교해보면 좋을 것 같아요. 또 Swift에서 사용되는 다른 Collection들은 어떤 구조로 되어있는지 살펴보면 좋을 것 같습니다 😊

---

이 PR에 커멘트로 답변 남겨주시고, 같이 이야기해보면 좋을 것 같네요! 😊

2023-02-22 14:06 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    let value:T
`:`과 타입 사이에 공백 처리해주세요!

2023-02-26 07:22 UTC, SunnnySong commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    let value:T
네! 😁

2023-02-26 16:51 UTC, SunnnySong commented
코리의 리뷰를 받고 로건과 제가 주말을 struct/class를 열심히 공부해봤습니다! 제일 자주, 많이 사용하는 struct/class인데도 심도 있게 공부해보니 쉬운 내용이 아니여서 깜짝 놀랐었어요🥲  분명 공부했던 개념들이었는데 다시 보니깐 헷갈렸던 부분들을 확실하게 집고 넘어갈 수 있어 유익한 시간이었어요. 기본적인 개념 설명 대신 인상적이었던 키워드를 중심으로 간략하게 작성해보려 해요😀

## Race condition
- class의 Reference type은 변경 가능한 상태(mutable state)를 공유하고 있기 때문에 경쟁 상태(Race condition)가 돼요. 
    class의 경쟁상태에서 불변성을 보호하기 위해 lock을 걸게 되면, lock을 하기 위해 추가적인 자원이 소모되고, 코드가 느려지고, 교착 상태에 빠질 가능성이 있어요.
- value type은 값이 전달될 때 값이 복사되므로 원래의 데이터는 격리되요. 때문에 경쟁 조건을 방지할 수 있어요.
-  하지만 value type이 thread-safe하다고 말할 순 없어요. value type을 thread-safe하게 사용하기 위해선 dispatch queues와 같은 동기화 메커니즘이 필요해요.

## COW(Copy On Write)
- Value type 중 Collection은 Copy-on-write 최적화를 사용해요.
-  COW는 value type의 인스턴스를 생성할 때 즉시 새로운 값으로 복사하는 것이 아닌, 기존 주소를 계속 가리키다가 변경사항이 생겼을 경우 그 때 값 복사를 실행하는 것이에요.
 - 하지만 Collection이라고 무조건 COW 최적화를 실행하는 것은 아니에요. COW 최적화는 Swift compiler의 속성이지 Swift language 속성이 아니기 때문이에요.
    Collection의 복사 빈도수가 적거나, 메모리를 차지하는 비율이 적은 경우에는 최적화를 실행하지 않을 수도 있어요.😀

## Linked List의 구현 방법 
써니와 며칠간 타입들의 차이와 효율적인 사용에 대해 공부하고 논의한 결과 Linked List는 클래스로 구현되는것이 적절하다고 최종 판단 했어요.
- Linked List의 경우엔 해당 노드들이 각자의 주소값을 가지고 있고 추가와 삭제가 수시로 일어나는 상황이기 때문에 결국 새롭게 인스턴스를 생성하는 일이 빈번해져 메모리적인 효율성이 떨어질 수 있다고 생각했습니다. 뿐만 아니라 저희가 구현한 Linked List는 Reference타입인 Node가 head 와 tail 두개로 구성되어 있기 때문에 하나 이상의 Reference타입으로 인해 메모리에서 매번 Overhead가 발생하기 때문에 Struct로 구현하는건 적절하지 않을 수 있다 생각했어요. 
- 이걸 Class로 구현할 경우 결국 참조값만 전달 받게 되므로 불필요한 복사와 생성이 일d어나지 않게 될 것이므로 성능적인 측면에서 자원관리에 Struct 보다는 더 유리하다고 생각했어요.

## Queue를 프로토콜로 구현했을때의 장단점
-  Queue 의 동작이 필요한 구현체는 언제든 Queue 프로토콜을 채택, 준수함으로써 언제든지 Queue를 구현함에 용이하게 이용될 수 있습니다.
 - 의존성에 있어 조금더 유연할 수 있습니다. 특정 타입에 의존하는게 아닌 추상타입인 Queue Protocol에 의존하기 때문에 언제든 의존된 객체를 변경하는데 자유롭기 때문입니다.

2023-02-27 11:30 UTC, corykim0829 commented
알아보시고 공부하느라 수고 많으셨습니다!

클래스와 구조체를 선택할 때 도움이 됐으면 좋겠네요!

---

> Queue를 프로토콜로 구현했을때의 장단점

프로토콜의 장점을 중심으로 잘 설명해주신 것 같아요! 

제 생각에는 Queue를 프로토콜로 구현하게 되면, 프로토콜을 채택하면 구현부를 다시 작성해줘야하는 번거로움이 있다고 생각해요. extension을 사용하여 프로토콜의 기본 구현이 가능하지만 깔끔해 보이지는 않는 것 같아요.

또한 Queue의 동작은 enqueue, dequeue등 필요한 동작들은 대부분 같은 일을 하기 때문에 프로토콜의 유연함이 큰 장점으로 다가오지는 않는 것 같습니다.

2023-02-27 11:30 UTC, merged