[STEP1] 루키, 또바기
tasty-code/ios-bank-manager pull request #2
Opened 2022-10-12 06:00 UTC by moonsoungjin

@jaemuYeo 
# 구현
- Node타입 구현
- LinkedList타입 구현
- Queue 타입 구현
- Unit Test 작성

2022-10-12 08:50 UTC, jaemuYeo requested changes
루키 또바기 고생많았습니다!!
LinkedList와 Queue 타입을 너무 잘 구현해주었어요!
조금은 아쉬운 부분이 있어서 코멘트 남겨놓았습니다!!
확인해보시고 반영후 재요청 해주세요~~

앞으로는 프로젝트 시작할때 MVC 또는 다른 아키텍처별로 그룹화 해놓는 습관을 들이면 좋습니다!

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var head: Node<T>?
head와 tail프로퍼티는 외부에서 접근가능한 프로퍼티 인가요??

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    init() {}
init을 한것과 하지않은 것의 차이는 무엇인가요?

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var peek: T? {
헤드의 값을 리턴하는데 peek이라는 네이밍이 어울릴까요??

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func push(_ value: T) {
해당 메서드가 외부에서 사용되지 않는다면 은닉화해주세요!

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func removeLast() -> T? {
head 값을 빼내는 것은 removeFirst이지 않을까요?

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = nil
head와 tail 둘다 nil로 해주는 이유는 무엇인가요?

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    init(value: T, next: Node? = nil) {
next에 nil을 기본값으로 준 이유는 무엇인가요??
그리고 옵셔널프로퍼티는 기본값이 없어도 init하지 않아도 된답니다 :)

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +class Queue<T> {
해당 타입을 클래스로 선언한 이유는 무엇인가요??

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private var queue: LinkedList = LinkedList<T>()
타입명시하지 않고 간결하게 `private var queue = LinkedList<T>()` 로 해주어도 좋아요 ㅎㅎ

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        return queue.removeLast()
큐의 특징은 선입선출인데 리스트의 마지막 값을 빼주는 건가요?

2022-10-12 08:50 UTC, jaemuYeo commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +    func test_큐에_10을_인큐했을_때_정상적으로_값이_들어가는지() {
~지 로 끝나기보다는 ~ 한다로 끝나면 좋을 거같아요 ㅎㅎ
'test_큐에_10을_인큐했을_때_정상적으로_값이_들어간다'

2022-10-13 00:40 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var head: Node<T>?
아닙니다

2022-10-13 00:43 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    init() {}
구조체를 선언할때 기본적으로 init이 설정되는데 이 코드에선 init에 프로퍼티의 초기값을 설정하지 않았기 때문에 차이가 없는것 같습니다

2022-10-13 00:47 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var peek: T? {
firstValue라는 이름으로 바꿔주겠습니다

2022-10-13 00:48 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func push(_ value: T) {
넵!

2022-10-13 00:58 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func removeLast() -> T? {
넵 그런것 같습니다

2022-10-13 01:12 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private var queue: LinkedList = LinkedList<T>()
넵!

2022-10-13 01:12 UTC, chaeyoon1101 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = nil
head와 tail을 모두 nil로 해주면 연결된 리스트들이 모두 없어지기에 nil로 해주는것 같습니다

2022-10-13 01:16 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    init(value: T, next: Node? = nil) {
next에 값이 없을때 nil이 들어가야해서 기본값으로 nil을 줬습니다

2022-10-13 01:22 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +class Queue<T> {
아직 구조체보다는 클래스가 익숙해 클래스를 사용했지만
구조체로 바꾼다면 속도가 더 빨라질것 같습니다
구조체로 한번 바꿔보겠습니다

2022-10-13 01:22 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        return queue.removeLast()
위에서 수정해서 바꿨습니다

2022-10-13 01:23 UTC, moonsoungjin commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +    func test_큐에_10을_인큐했을_때_정상적으로_값이_들어가는지() {
넵!!

2022-10-14 02:13 UTC, jaemuYeo reviewed
루키 또바기 스텝1 고생많았습니다!!
Unit test도 너무 잘 해주었네요 💯
다음 스텝도 기대할게요 ㅎㅎ 😀

2022-10-14 02:13 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    private mutating func push(_ value: T) {
기능 분리 좋아요 👍

2022-10-14 02:13 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            guard head != nil else {
들여쓰기가 한번 더 되었네요! 확인해주세요~

2022-10-14 02:13 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            let Node = self.head
상수나 변수의 네이밍은 소문자로 하는 것이 좋습니다 😀

2022-10-14 02:13 UTC, merged

2022-10-14 04:34 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    private mutating func push(_ value: T) {
넵!

2022-10-14 04:35 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            guard head != nil else {
넵!

2022-10-14 04:36 UTC, moonsoungjin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            let Node = self.head
넵!