은행창구 관리앱 [STEP 2] Blue, Lust3r
tasty-code/ios-bank-manager pull request #20
Opened 2023-02-27 08:15 UTC by calledBlu

안녕하세요! Corn(@protocorn93)🍿!
💫**TEAM BLUST3R**💫의 Blue, Lust3r입니다!

콘이 남겨주신 STEP 1 리뷰를 참고하여 많이 학습할 수 있었습니다!
부족한 부분을 알려주셔서 학습하는 데 많은 도움이 되었어요!

이번 STEP에서는 코드 작성 전 **순서도**와 **UML**을 그려보면서
구현해야 할 것들과 코드의 흐름에 대해서 많이 논의해보고
코드를 작성할 수 있어서 좋은 시간이었습니다 :)

최근 protocol, extension을 학습하여 프로토콜 초기구현을 많이 해보려고 노력했습니다!

STEP 2 리뷰도 잘 부탁드립니다! 감사합니다! 🙇🏻🙇🏻

## 🧑🏼‍💻 작업 목록

**[ STEP 2 ] 타입 구현 및 콘솔앱 구현**

- [x] 타입 구현
    - [x] 은행에는 n명의 은행원 근무
    - [x] 고객의 대기열은 Step 1에서 구현한 Queue 타입 활용
    - [x] 모든 고객의 업무가 끝나면 은행업무를 마감 및 관련 메세지 출력
    - [x] 은행원은 고객의 업무 처리
    - [x] 각 고객의 업무를 처리하는 데 걸리는 시간 0.7초
    - [x] 대기중인 고객의 업무처리 관련한 문구 출력
- [x] 콘솔앱 구현
    - [x] STEP 2의 은행에는 한 명의 은행원이 근무
    - [x] 은행원은 한 번에 한 명의 고객의 업무를 처리
    - [x] 앱을 실행하면 두 개의 메뉴를 출력
    - [x] 사용자가 1을 입력하면 은행을 개점
        - [x] 10~30명의 고객 방문
        - [x] 10~30 사이의 임의의 수를 생성
        - [x] 모든 고객의 업무 처리 시 은행문이 닫히고 다시 메뉴 출력
    - [x] 사용자가 2를 입력하면 프로그램 종료

## ➡️ 순서도
<img src="https://user-images.githubusercontent.com/71758542/221508777-e20a2a42-a8ae-4eaf-9a2d-95c99ec8f80a.png" height="700">

## 🏗️ UML
<img src="https://user-images.githubusercontent.com/71758542/221498398-8b8694fc-9de5-499e-a374-9e0285f3cef3.png" height="700">

## 📚 학습 키워드 및 학습 내용

### 1. 재귀함수, 꼬리재귀함수
- `재귀함수`
    - 함수 내에서 해당 함수를 호출하는 것
    - 스택에 함수 호출을 하나씩 쌓고 거꾸로 반환 값을 넘기며 계산을 수행
    - 필수 요소: 함수 탈줄 초건, 함수 호출, 리턴 값
    - 대표적인 예: 팩토리얼
    - 단점: 값이 커서 함수 호출을 아주 많이 해야 할 경우 stack overflow 발생
- `꼬리재귀함수`
    - 함수를 호출하면서 스택을 재사용하는 것
    - 스택을 재사용하기 때문에 메모리를 아낄 수 있음
    - 컴파일 시점보다 런타임 시점에 이득을 얻음
    - 일반적인 재귀함수의 단점인 stack overflow를 방지할 수 있는 함수
    - return에 함수 호출 이외에 다른 연산자가 붙지 않는 경우에 적용
- **재귀 함수와 반복문의 장단점 비교**
    ||재귀 함수|반복문|
    |:---:|:---:|:---:|
    |👍 **장점**|상대적으로 코드가 간결|상대적으로 속도가 빠름|
    |👎 **단점**|메모리를 많이 사용, 상대적으로 속도가 느림|상대적으로 복잡한 코드|

### 2. 값 타입, 참조 타입
- `Struct`
    - 값 타입: 데이터를 전달할 때 값을 복사하여 전달
    - 상속 불가
    - Swift 대부분의 큰 뼈대는 모두 구조체로 구성
- `Class`
    - 참조 타입: 데이터를 전달할 때 값의 메모리 위치를 전달
    - 단일 상속
    - Apple 프레임워크 대부분의 큰 뼈대는 모두 클래스로 구성
- **구조체와 클래스 중 어떤 것을 사용해야 할까?** (출처: [Apple 공식문서](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes))
    - 프로젝트의 성격과 데이터의 활용도에 따라 선택해서 사용함
    - 기본적으로 구조체를 사용
    - Objective-C와 상호 운용성이 필요한 경우 클래스 사용
    - 모델링 중인 데이터의 ID를 제어해야 하는 경우 클래스 사용
    - 프로토콜과 함께 구현체를 공유하여 행동을 채택하는 경우 구조체를 사용
    - 다음 조건 중 하나 이상에 해당한다면 구조체를 사용할 것을 권장
        - 연관된 값의 집합을 캡슐화하는 것만이 목적일 때
        - 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할 때
        - 구조체에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당할 때
        - 다른 타입으로부터 상속받거나 자신을 상속할 필요가 없을 때

## 🤔 고민과 해결
### 1. Queue 연결 타입 문제 해결
- 처음 customerQueue에 customer의 수(random)만큼 `enqueue`를 해줄 때, `Node<Customer>`를 넣어줬기 때문에 디버깅 과정에서 head와 node가 각각 data와 next를 갖고 있는 문제가 있었습니다.
넣어줘야 하는 데이터 타입에 대해 다시 고민했고, enqueue 자체가 Node를 Queue에 넣어주는 것이기 때문에 value에 데이터 타입인 Customer를 넣어주면 된다는 결론을 낼 수 있었습니다.
그렇게 해서 다음과 같은 코드를 구현하여 enqueue 작업을 정상적으로 할 수 있었습니다.
    ```swift
    for waitingNumber in 1...maxCount {
        customerQueue.enqueue(value: Customer(waitingOrder: waitingNumber))
    }
    ```

### 2. 메뉴 반복 문제 해결
- 메인 메뉴를 어떻게 반복을 할까 고민을 하다 while 반복문으로 감싸는 것 대신 재귀함수를 사용하여 메뉴를 출력하고 수행하는 메서드를 불러오면 되겠다는 생각을 했습니다.
결과값에 함수 출력만 있는 꼬리재귀로 코드의 간결화는 물론 재귀함수에 비해 안정성을 높일 수 있었습니다.
    ```swift
    switch SystemMenu(rawValue: userInput) {
        case .open:
            bank.open()
            return execute()
        case .close:
            break
        case .none:
            break
    }
    ```

### 3. Bankmanager 역할 분리
- 기존에는 main에서 BankManager의 `startBusiness()` 메서드만 호출하고, BankManager가 모든 일을 처리했습니다.
그러나 기술명세상에서는 은행원이 고객의 일을 처리해야 하고, 은행 타입 구현이 명시되어 있어 분리를 하게 되었습니다.
최종적으로 Bank 타입을 구현하면서 BankManager는 전체적인 반복되는 업무 틀만 관리하는 역할을 하고, Bank는 CustomerQueue를 생성하여 큐 내부에 존재하는 고객의 대기번호를 은행원에게 전달하여 일을 처리할 수 있는 역할을 합니다.

## 🙋🏻 질문 거리
### 1. 전반적인 네이밍
- 최대한 실제 상황에 맞게, API 가이드라인에 맞춰 네이밍을 수정하였습니다.
혹시 네이밍만 보고 역할을 파악하기 어려운 것이 있다면 코멘트 부탁드립니다!
코멘트 주신 부분에 대해서 더 고민해보고 수정하도록 하겠습니다.

### 2. `usleep()` vs `Thread.sleep()`
- 처음에는 `usleep()`에 시간을 주어 0.7초를 지연시켰습니다. 하지만 `rawValue` 그대로 입력하여 메세지 출력간 delay를 주는 것보다 현재 Step에서는 main 스레드에서만 작업이 진행되고 있기 때문에(한 명의 은행원이 customer queue를 담당) customer 한 명이 은행원과 업무를 보는 동안에는 다른 customer는 대기를 해야하는 상황이 main 스레드의 동기적 처리와 비슷하다고 판단하였습니다.
그래서 `Thread`의 `sleep` 기능을 활용하여 은행원이 갖고 있는 `processingTime`을 파라미터로 메세지 출력간 delay를 주는 방식을 사용하게 되었습니다.
`usleep()`메서드와 `Thread.sleep()`메서드가 사용자가 체감하기에는 동일한 로직으로 수행되는 것처럼 보이는데 콘의 경우에는 어떤 메서드를 사용하실 것 같으며 그 이유는 무엇인지 여쭤봐도 될까요?

2023-03-01 02:07 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 

몇 가지 생각이 들었어요.

1. 프로그램의 서비스 시나리오와 프로그램의 시나리오가 동일시 되는 것 같아요. 은행원이 일하는 것이 프로그램 전체가 멈춰야 하는 것과는 별개라고 생각해요. 프로그램 안에서 은행원이 업무를 처리하는 것과는 별개로 프로그램은 멈추지 말아야 하는 것 같아요. 여기서는 은행원이 0.7초 동안 업무를 처리한다고 하지만, 사실 이게 네트워크 요청을 하고 응답을 받는데까지 0.7초가 걸리는 것과 동일하거든요. 네트워크 요청을 하고 응답이 올때까지 앱이 완전 얼어있어야 하는지 생각해보면 좋을 것 같아요. 그리고 이를 어떻게 처리해야하는지에 대해서 학습해보시면 좋을 것 같아요. 
2. 추상화를 성실히 수행하신 부분 인상 깊어요! 다만 추상화를 하신 목적이 잘 드러나지는 않는 것 같아요. 이들을 추상화해서 어떤 이점을 가져가려고 하신지도 잘 모르겠어요. 이게 진짜 추상화가 필요한지에 대해서도 한번 고민해보면 좋을 것 같아요. 물론 지금은 이에 대한 기준이 명확하지 않을 수 있어요. 이건 저도 마찬가지에요. 그럼에도 나름의 이유를 한번 잘 찾아보시면 좋을 것 같아요.

--- 

## 질문

1. 네이밍에 대한 코멘트는 남겨놓았습니다. 
2. 이 두 선택지에서 현재 프로그램에서 무엇을 사용하는지는 딱히 크게 중요한 것 같지는 않아요. 두 분이 말씀해주신 의도대로 `Thread.sleep`이 좀 더 편리해보이긴 해요!

2023-03-01 02:07 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/Message.swift
> +enum Message: CustomStringConvertible {
개인적으론`Message`의 역할이 모호한 것 같아요. 모든 출력을 담당하는 것 같아요. 그럴 필요가 있을까 싶네요. 

메뉴 출력은 `SystemMenu`가 담당해도 충분해보여요. `workStart`, `workComplete`, `bankClose`도 결이 다른 것 같아요. 이는 `Bank` 객체 안에서 처리해도 무방해보여요. `Message`의 역할이 오히려 모호해서 여기에 모든걸 다 위치시켜야만 할 것 같아요.

2023-03-01 02:07 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +protocol Manageable {
네이밍을 좀 더 명확하게 해주시면 좋을 것 같아요. `Workable`, `Receivable`도 마찬가지에요

2023-03-01 02:07 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +}
protocol extension을 통해 기본 구현으로 두신 이유가 궁금해요. `Manageable`을 채택한 객체는 100% 동일한 로직을 가져야하는 것일까요?

2023-03-01 02:07 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +        }
`for-in`이 아닌 `forEach`로 구현해보시면 좋을 것 같아요.

2023-03-01 02:07 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Workable.swift
> +    static var processingTime: Double { get }
`processingTime`을 추상화하시기로 한 결정한 이유가 무엇일까요?

2023-03-01 02:07 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +    var waitingOrder: Int
물론 프로토콜로 접근하면 get만 가능하겠지만 그럼에도 `let`으로 선언해주시는게 좀 더 안전할 것 같아요.

2023-03-01 02:07 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Receivable.swift
> +protocol Receivable {
마찬가지로 네이밍이 너무 모호해요. 추상화를 학습하고 연습하시다보니 이렇게 너무 많은것을 축약해버린 것 같기도 해요. 그리고 추상화를 진행하는 이유에 대해서도 고민해볼 필요가 있어요. 

사용자 input을 받는 행위를 추상화한 이유가 궁금해요.

2023-03-02 05:16 UTC, calledBlu commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/Message.swift
> +enum Message: CustomStringConvertible {
콘이 리뷰해주신 것을 보고 각 객체의 역할을 다시 생각해 보았어요.

- BankManager → 시스템 실행, 메뉴를 출력하도록 SystemMenu 호출, 메뉴 반복 실행
- SystemMenu → case로 메뉴를 가지고 있음, 메뉴 출력을 담당
- Bank → BankManager에서 1번 메뉴 실행 시 작동, 고객 수/고객 대기열(큐) 생성, Banker가 일을 할 수 있도록 호출, 고객 Queue가 비어있을 때(모든 업무가 종료됐을 때) 종료 메세지 출력
- Banker → 업무처리를 담당, 업무 시작/완료 메세지 출력

다시 고민해 본 역할에 따라서 Message에 있는 일부 역할을 분산시켜 보았습니다.

- 시스템 메뉴를 출력하는 역할 → `show()`메서드로 구현 후 `SystemMenu`로 이동
- 전체 업무 종료 시 종료 메세지 출력하는 역할(`bankClose`) → `printWorkFinishMessage`로 네이밍 변경 후 `Bank`로 이동
- 업무 시작/완료 메세지 출력하는 역할(`workStart`, `workComplete`) → Banker의 역할로 생각하여 `Banker`가 채택하고 있는 `Workable` 프로토콜로 이동
- 전체 역할 분산 후 `Message` 파일 삭제

저희가 다시 고민하고 역할을 재분배해 본 부분에 대한 콘의 의견이 궁금합니다 :)

2023-03-02 05:17 UTC, llimental commented
> 1. 프로그램의 서비스 시나리오와 프로그램의 시나리오가 동일시 되는 것 같아요. 은행원이 일하는 것이 프로그램 전체가 멈춰야 하는 것과는 별개라고 생각해요. 프로그램 안에서 은행원이 업무를 처리하는 것과는 별개로 프로그램은 멈추지 말아야 하는 것 같아요. 여기서는 은행원이 0.7초 동안 업무를 처리한다고 하지만, 사실 이게 네트워크 요청을 하고 응답을 받는데까지 0.7초가 걸리는 것과 동일하거든요. 네트워크 요청을 하고 응답이 올때까지 앱이 완전 얼어있어야 하는지 생각해보면 좋을 것 같아요. 그리고 이를 어떻게 처리해야하는지에 대해서 학습해보시면 좋을 것 같아요.
- 프로그램 전체가 어는 것은 인지했지만 해당 스텝 코드에서는 0.7초를 줄 수 있는 방법이 얼리는 것밖에 떠오르지 않았던 것 같습니다. 다음 요구사항 키워드에 동시성 프로그래밍이 있어 코멘트 달아주신 내용을 고려하여 진행하도록 하겠습니다!🙌🏻

> 2. 추상화를 성실히 수행하신 부분 인상 깊어요! 다만 추상화를 하신 목적이 잘 드러나지는 않는 것 같아요. 이들을 추상화해서 어떤 이점을 가져가려고 하신지도 잘 모르겠어요. 이게 진짜 추상화가 필요한지에 대해서도 한번 고민해보면 좋을 것 같아요. 물론 지금은 이에 대한 기준이 명확하지 않을 수 있어요. 이건 저도 마찬가지에요. 그럼에도 나름의 이유를 한번 잘 찾아보시면 좋을 것 같아요.
- 추상화를 학습한 후 이를 적용해보기 위해 추상화가 꼭 필요하지 않은 부분에서도 사용했던 것 같습니다. 콘이 코멘트해주신 부분 다시 살펴본 후 어떤 이점이 있는지, 진짜 필요한 부분인지 다시 한번 생각해보겠습니다!

2023-03-02 05:17 UTC, calledBlu commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +protocol Manageable {
프토토콜에 정의된 역할에 따라 프로토콜 네이밍을 조금 더 명확하게 수정해 보았습니다.

- `Workable` -> `BankerProtocol`
    - 은행원이 하는 일을 정의한 protocol이므로 Banker + Protocol이 적합하다고 생각하였습니다.
- `Manageable` -> `CustomerManageable`
    - 어떤 것을 관리할 수 있는가에 대해 명확하지 못했던 네이밍인 것 같아서 고객을 관리한다를 명시하기 위해 Customer를 붙여 보았습니다!
- `Receivable` -> `UserInputReceivable`
    - 위 내용과 마찬가지로 어떤 것을 받을 수 있는 프로토콜인지 역할이 애매하다고 생각되어 UserInput을 붙여주었습니다.

> 해당 커밋: 20acb6d4105eb8bc32b409645777804d0d5dce32

2023-03-02 05:19 UTC, calledBlu commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Workable.swift
> +    static var processingTime: Double { get }
처음에는 `Banker`에게 필요한 것이 무엇일까 생각해 보다가, 은행원이 업무를 처리한다면 당연히 업무 처리 소요시간이 필요하지 않을까?라는 생각을 하게 되었고 그렇다면 `processingTime`은 `Banker`가 공통적으로 가지고 있는 요소이기 때문에 protocol에 포함이 되어야 한다고 생각하여 추상화하기로 결정하였습니다.

2023-03-02 05:19 UTC, calledBlu commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +    var waitingOrder: Int
프로토콜을 우선시 생각하다보니 get만 가능하다는 전제 하에 안전성을 고려하지 못하고 var를 썼던 것 같습니다.
콘의 리뷰를 바탕으로 생각해보니 고객의 대기번호가 바뀔 일은 없어서 let으로 수정해 주는 게 더 안전할 것 같아서 수정하였습니다 :)

> 해당 커밋: a12d8235b153ad714b7209c806d5a39f600dd62e

2023-03-02 05:19 UTC, llimental commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +}
현재 `CustomerManageable`을 채택한 객체는 Bank 하나이고 그 Bank가 하는 것 중, 이건 은행이라면 공통적으로 해야 하는 일이겠다 싶은 것을 `protocol`로 정의했습니다(고객의 수 생성, 그 수를 바탕으로 고객 대기열 만들기). 또한 해당 기능은 Bank 내부에 작성되어 있는 것보다 `protocol + extension`을 통해 초기구현을 하고 프로토콜을 채택하여 사용하는 것이 좋다고 생각하였습니다.
현재로서는 은행이 하나인 상황을 가정했지만, 다른 Bank 인스턴스가 생성되더라도 그 인스턴스 역시 기존에 있는 Bank와 다른 역할을 하는 것이 아니기 때문에 `CustomerManageable`을 통해 동일한 로직을 진행하는 것이 좋다고 생각해 위와 같이 구현했었습니다 😀

2023-03-02 05:20 UTC, calledBlu commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Receivable.swift
> +protocol Receivable {
추상화하지 않고 사용하는 경우 readLine()으로 사용자의 입력을 받아오고 guard-else문으로 옵셔널 언래핑하는 코드가
BankManager 내부에 담겨야 하는데, 이를 BankManager 내부의 메서드로 직접 구현하는 것보다
이를 추상화하고 초기구현하여 사용하는 게 더 깔끔하지 않을까 하는 생각으로 진행하였습니다.

물론 저희의 코드에서 사용자의 입력을 받아오는 행위는 BankManager만 수행하지만,
추후 공개될 STEP에서 별도로 사용할 수 있는 경우가 발생할 수도 있고, 아예 필요하지 않은 경우가 있을 수 있어서
protocol 초기 구현 후 채택하는 방식으로 진행해 보았습니다.

2023-03-02 05:22 UTC, llimental commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +        }
- Range자체나 그것을 담은 상수를 사용해서 forEach를 사용할 수 있었습니다.
두 키워드를 학습해보니, 둘 사이에는 다음과 같은 차이가 있었습니다.
1. You cannot use a break or continue statement to exit the current call of the body closure or skip subsequent calls.
→ forEach는 for-in과 다르게 break나 continue를 통해 현재 호출을 탈출하거나 다음 호출을 스킵할 수 없습니다.
2. Using the return statement in the body closure will exit only from the current call to body, not from any outer scope, and won’t skip subsequent calls.
→ for-in은 return 사용 시 전체가 종료되지만, forEach는 해당 호출에서만 종료되고 다음 호출은 건너뛰지 않습니다.
- 또한 forEach의 definition을 Xcode에서 보면 다음과 같이 나와있습니다.
    
    > Calls the given closure on each element in the sequence in the same order as a `for`
    -`in` loop.
    > 
    
    forEach에서 수행되는 작업은 for-in과 동일한 순서로 각 요소에서 클로저를 호출합니다.
    
    여기까지만 보면 `1…maxCount`라는 범위만 따로 프로퍼티로 지정해서 사용하면 둘은 똑같은 작업을 하는 것으로 봤습니다. 다만 forEach는 for-in과 다르게 이전 결과를 별도의 프로퍼티에 저장할 필요 없이 함수 호출을 할 수 있는 장점이 있어 함수형 프로그래밍에 적합하다는 것을 알게 되었습니다.
    이번 프로젝트에서도 Array를 작업한 것을 가지고 이 반복문을 썼다면 forEach를 사용하면 좋을텐데, 해당 범위를 가진 프로퍼티를 사용하든, 아니면 range 표기법으로 사용하든 두 경우 다 같은 코드로 진행할 수 있어 어떤 차이점을 기대할 수 있을지 여쭤보고 싶습니다!
    
```Swift
func makeCustomerQueue(maxCount: Int) -> LinkedQueue<Customer> {
        let customerQueue = LinkedQueue<Customer>()
        let waitingNumberRange = 1...maxCount

	waitingNumberRange.forEach { waitingNumber in
		customerQueue.enqueue(value: Customer(waitingOrder: waitingNumber))
        }
				
	for waitingNumber in waitingNumberRange {
		customerQueue.enqueue(value: Customer(waitingOrder: waitingNumber))
	}

	(1...maxCount).forEach { waitingNumber in
		customerQueue.enqueue(value: Customer(waitingOrder: waitingNumber))
        }

	for waitingNumber in (1...maxCount) {
		customerQueue.enqueue(value: Customer(waitingOrder: waitingNumber))
	}

        return customerQueue
}
```

2023-03-02 05:27 UTC, calledBlu commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +        }
> 해당 커밋: 8de71cd6ad76f28d58dba5816b87017724e3fd01

2023-03-03 01:14 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/Message.swift
> +enum Message: CustomStringConvertible {
오! 네네 좀 더 깔끔해진 것 같아요. 현재 단계에선 관련 문구는 해당 객체가 출력해주는게 좋을 것 같아요. 👍

2023-03-03 01:17 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +}
네네 잘 설명해주신 덕에 의도는 충분히 잘 이해했어요! 다만 이미 프로토콜로 잘 추상화를 진행해주셔서, protocol extension을 통해 공통 로직을 구현하는 것은 이후에 동일한 역할을 하는 객체가 필요해졌을 때 구현해도 될 것 같아요. 이건 제 개인적인 생각이지만 처음 코드를 보았을 때 구현체가 어디있는지 조금 헷갈렸어요. 이 부분은 별도로 수정 해주시지 않아도 됩니다!

2023-03-03 01:23 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Manageable.swift
> +        }
관련해서 충분히 학습해주셨네요 👍 딱히 어떤 차이점을 두고 남긴 코멘트는 아니었어요. 고차함수를 적극적으로 활용해보시길 바라는 마음에 남긴 코멘트였습니다. 고차함수에 대해서도 충분히 학습을 해보신 것 같네요! 👍

2023-03-03 06:41 UTC, merged