[STEP 3] 은행창구 관리앱 ― Miro, Jenna
tasty-code/ios-bank-manager pull request #23
Opened 2023-03-06 07:29 UTC by ueunli

> 안녕하세요 제이크(@jryoun1)~! 🙌🏻 
> STEP2에서 짚어주신 내용을 통하여 정말 많은 것을 느끼고 배울 수 있었어요! ☺️
이번 스텝에서 처음으로 비동기 작업을 해보며 많은 어려움이 있었지만, 최대한 요구사항에 맞게 로직을 구현해보았어요! 이번 STEP도 잘 부탁드려요! 🙇‍♂️🙇‍♂️~~

---
# 구현사항
은행원이 하나인 은행을 관리하기 위한 타입 구현 & 콘솔앱 구현
- [x] 동기 비동기의 활용
- [x] 타입 추상화 및 일반화

### 👾 새로 구현한 타입들
> 요구사항: STEP2의 `Bank` 기능 확장 -- 은행원·은행업무의 종류가 2가지씩
- **Customer** 
: 예금, 대출 업무 중 은행에 방문한 목적을 담는 프로퍼티 존재
- **Timer**
: 은행에서 은행원들이 업무를 하는 동안 걸리는 총 시간을 계산해주는 구조체
- **BankingService**
: 은행이 제공하는 서비스인 예금, 대출 업무와 해당 업무들을 하는 데 걸리는 시간 프로퍼티를 담는 열거형
- **Array Extension**
: Bank의 clerks 배열의 초기화에 BankingService를 받아 사용하기 위해 정의(참고. **고민과 해결 02 확장성 보완**), 안전하게 서브스크립트하기

### 👾 동시성 프로그래밍
> 요구사항: 각 은행원은 한 번에 한 가지 업무만 전담하여 수행하며, 모든 은행업무는 비동기적으로 이루어지도록 구현할 것
- **은행 확장**
   - Bank의 은행원을 `clerks` 하나로 통합
      ```Swift
      private let clerks: [BankClerkProtocol]
      ```
   - 예금담당 은행원은 2명, 대출담당 은행원은 1명
      ```Swift
      var bank = Bank(clerks: .deposit(2), .loan(1))
      ```
- **다중 처리**
   - 동시성 프로그래밍 구현을 위해 사용한 방법: `GCD`
   - 모든 업무는 비동기 작업으로 처리하되, 
   모든 은행원이 담당 업무에 맞는 작업을 한 번에 하나씩 연속적으로 맡도록, 비동기 작업이 처리될 스레드의 종류와 개수를 제한
   - 비동기로 작업들이 전부 끝나야만 은행 문이 닫힘

　
　
 
# 고민과 해결🤔

## 👾 01.　안전하게 서브스크립트하기
- Bank 구조체에는 대출 업무를 담당하는 은행원 배열과 예금 업무를 담당하는 은행원 배열이 존재해요. 해당 배열에 접근을 할 때, 안전하게 배열의 요소에 접근을 하기위하여 아래와 같은 코드를 활용해보았어요!
    ```swift
    extension Array where Element: BankClerkProtocol {
        subscript(safe index: Int) -> Element? {
            guard index <= self.count else { return nil }
            return self[index]
        }
    }
    ```

## 👾 02.　확장성 보완
1. **`BankClerkProtocol` 정의**
   - 2종류의 은행원 구조체를 묶어줄 BankClerkProtocol을 정의
   - 종류별 은행원 배열의 요소타입을 각 구조체가 아닌 BankClerkProtocol로 명시
2. **`Bank`의 이니셜라이저 매개변수 타입 수정**
   - **[기존]** Bank생성자가 직접 은행원들(인스턴스 배열)을 받음
      ```Swift
      var bank = Bank(clerksForDeposit: [BankClerkForDeposit(), BankClerkForDeposit()], clerksForLoan: [BankClerkForLoan()])
      ```
   - **[수정 A]** 은행원의 인원 수(`Int`)만 받음
      - 요구사항에는 종류별 은행원의 인원 수가 정해져 있지만, 앞으로의 확장성을 고려하여 은행원의 수가 유동적이도록 만듦
      - 인원 수만 입력해 주면 알아서 종류별 은행원 배열에 일정 수의 객체를 생성해 넣어주도록 구현
      ```Swift
      var bank = Bank(numberOfClerksForDeposit: 2, numberOfClerksForLoan: 1)
      ```
   - **[수정 B]** BankingService의 case로, 종류별 인원 수를 한번에 받음
      - 은행원의 '인원 수' 확장 가능 ⇒ '종류 및 종류별 인원 수' 확장 가능 
      - BankingService의 케이스별 연관값을 이용
        | (참고) | BankingService 열거형 구현 과정　|
        |:--:|:--|
        |**초기구현**|String원시값("예금", "대출")과 Double계산속성(0.7초, 1.1초)을 갖는 열거형
        |**변경 후**|Int연관값 하나씩(`인원 수`)과 String계산속성(`업무 명`) & Double계산속성(`소요시간`)을 갖는 열거형
      ```Swift
      var bank = Bank(clerks: .deposit(2), .loan(1))
      ```

> 🌱 [수정 A]의 부수효과로, `handleAllCustomers()`메서드의 `SRP`뿐 아니라 `OCP`에 관해서도 진지하게 고민할 필요가 있었어요. 
> - 안 그래도 반복되는 코드와 맡은 역할이 많은 함수였는데, 은행원 수를 컴파일 시점에 알 수 없게 되었어요. 
> - 각 은행원에 대한 비동기작업 선언이 메서드 body에 일일이 하드코딩되어 있던 상황이기에(~`8979b26`), 요구받은 기획서의 은행원 수가 바뀌면 기존 코드를 수정해줘야 하므로 OCP를 심각하게 위배하게 되어요😭
> 
> ➡ 이에 관한 구체적인 리팩토링 과정은 아래 [**비동기 관련 고민과 해결**]에 상술했어요!

> 🌱 [수정 B]를 거치며, 저희가 해결해야 할 확장성 이슈 -- *‘은행업무의 종류가 늘어날 경우’*, *‘은행업무별 은행원의 수가 달라질 경우’* 중 후자를 해결했어요!

> 🌱 지난 번 조언 주셨던 '손님 인원 수 범위도 런타임에 입력받게 하는 기능'에 관해서는 저희가 Bank구조체의 프로퍼티 및 생성자 구성, 프로젝트 요구사항에 관해 고민이 길어져 이번에 반영하지 못했어요ㅠㅠ 
> 
> ➡ 다음 스텝 진행하면서 괜찮은 아이디어가 떠오르면 적용해 볼게요 :-D

　
## 👾 03.　총 소요시간 계산
### 문제 상황
   |   |   |
   |:--:|:---|
   | **기존 구현** | - 시간 나타낼 수 있는 여러 타입을 알아보다가`CFAbsoluteTime`이라는 타입을 사용하게 되었어요.<br>- `CFAbsoluteTimeGetCurrent()`를 특정 타이밍에 직접 호출&할당해줬어요. |
   |**문제점**|- 의존하는 타입 명이 생각보다 여러 군데에 등장해요.<br>- BankClerk에서 작업지연을 위해 쓴 `usleep()`은 매개변수가 `usleep_t`라 형식이 다르고(0.7초 = 700000), 무엇보다 유사한 논리(시간 관련) 구현에 일관되지 않은 타입을 여럿 쓰고 있다는 점이 마음에 걸렸어요. (`Double`, `usleep_t`, `CFAbsoluteTime`) |

### 해결 방법
**[`CFAbsoluteTime` 대체] --- `Timer` 구조체**
- 외부/모르는 코드를 가져와 사용할 때는 우리가 필요로 하는 기능만 선택적으로 떼어와, 직접 만든 익숙한 구현 안에 담아서 사용하면 좋다고 배웠어요.
- 마침 속성과 메서드 조합이므로, 이 일을 맡길(=숨겨줄) 별도의 타입을 만들었어요.
- 이제 Bank는 `Timer`타입의 프로퍼티를 가지며, Timer는 위 타입의 수많은 메서드 중 저희가 필요한 특정 기능인 `CFAbsoluteTimeGetCurrent()`함수만 담고 있어요.

**[`usleep_t` 대체] --- `sleep(forTimeInterval:)` 메서드**
- 비동기 공부를 하다가 `Thread.sleep(forTimeInterval:)` 메서드를 알게 되었어요. 공식문서를 통해 학습 수 사용하였는데, 그 과정은 아래와 같아요. ⬇
- 타입메서드 형태라, 아래 설명에서 'the thread'가 어떤 스레드를 말하는지 특정하기 어려웠어요.
  > Sleeps the thread for a given time interval
-  흔한 단어고 async·await검색 결과와 섞여서 찾기 힘들었지만, 결국
 'current thread'를 말하며, 비동기 클로저 안에서 호출되면 '그 비동기 작업이 처리되고 있는 스레드'를 뜻한다는 결론을 내릴 수 있었어요. 
- 뭔지 알게 되었으므로 우리 프로젝트에도 적용하기로 했어요. 
이 메서드의 인풋타입은 `TimeInterval`이라고 되어있지만 공식문서에 따르면 `Double`의 typealias이에요. 

> 🌱 이로써 프로젝트의 시간 관련 로직 모두를 Double류 타입으로 수행할 수 있게 되었어요! 
> 따라서 논리적 일관성을 챙기고 타입 변환의 수고를 덜게 되었어요.

　
## 👾 04.　비동기 작업
### ✔　DispatchGroup(), DispatchWorkItem, DispatchSemaphore()
- 저희는 대출 업무를 담당하는 은행원 1명, 예금 업무를 담당하는 은행원 2명이 비동기적으로 하나의 큐에서 손님을 추출하여 serve()메소드를 호출할 수 있도록 해주었어요.
> 그리고 아래는 저희가 사용한 비동기 메소드, 객체들이에요 👇
    -  DispatchGroup()
    -  DispatchSemaphore()
    - DispatchQueue.global().async(group:execute:)

#### DispatchGroup(),DispatchQueue.global().async()
- 저희는 모든 비동기 작업들이 완료가 되어야지 클로징 메세지를 출력하고, 메뉴 선택 메세지를 출력하고 싶었어요.
- 따라서 각각의 task를 하나의 그룹으로 묶어주었고,  `wait()`메소드를 통하여 비동기 작업들이 다 끝나기 전까지 기다리도록 했어요!

#### DispatchSemaphore()
- 저희는 아래와 같이 `semaphore`를 활용하여 하나의 스레드만 접근을 할 수 있도록 제한을 하여 race condition이 일어나지 않도록 했어요.
    ```swift
    let semaphore = DispatchSemaphore(value: 1)
    ...
    semaphore.wait()
    guard let customer = extractCustomerFromQueue() as? Customer else { return }
    semaphore.signal()
    ```

### ✔　‼️비동기 작업 중 생긴 이슈‼️
- 저희는 아래와 같은 코드를 통하여 task1, task2, task3 작업을 각각 비동기로 처리할 수 있도록 했어요.(최종 코드와는 다른 부분이 많아요!)
    ```swift
    let task1 = DispatchWorkItem {
                while !queue.isEmpty() {
                    guard (queue.peekFirst() as? Customer)?.purposeOfVisit == .deposit else { continue }

                    semaphore.wait()
                    guard let customer = extractCustomerFromQueue() as? Customer else { return }
                    semaphore.signal()

                    guard let clerk = clerksForDeposit[safe: 0] else { return }
                    clerk.serve(customer)
                }
            }

    let task2 = DispatchWorkItem {
        ...
    }

    let task3 = DispatchWorkItem {
        ...
    }

    DispatchQueue.global().async(group: tasks, execute: task1)
    DispatchQueue.global().async(group: tasks, execute: task2)
    DispatchQueue.global().async(group: tasks, execute: task3)
    ```
위와 같은 코드로 콘솔앱을 실행할 경우,모든 손님들을 serve한 이후에 적은 확률로 아래와 같은 Thread 에러가 생겼어요.
    <details>
    <summary style="color:red"><strong>lldb 디버깅 과정 🤖 (토글 가능‼️)</strong></summary>
      <code>po numberOfCustomers</code>는 이미지에 포함되지 않았지만 총 5명으로 나왔었습니다!(즉, 모든 고객에 대해 업무가 완료된 직후)
        <image src="https://i.imgur.com/60lovi1.png"></image>
    </details>

- **저희가 판단한 문제 발생 상황은 아래와 같아요!**
    - lldb를 통하여 디버깅을 해봤을 때, 모든 customer의 업무가 완료가 된 후에, 에러가 발생함을 알 수 있었어요.그리고, `dispatch_semaphore_dispose`라는 lldb 문구를 통하여 semaphore의 활용에서 문제가 발생했음을 유추할 수 있었어요.
- **저희가 생각한 에러 발생 이유는 아래와 같아요!**
    - 아래의 코드에서 dequeue할 손님이 없을 경우, else문을 타게 되어 return이 돼요. return을 하게 되면 `semaphore.signal()`을 만나지 못하여 thread 에러가 발생해요(semaphore.wait()과 semaphore.signal()은 쌍으로 존재해야되니까!)
    - 처음엔 아래 코드에서, 'Customer로의 타입캐스팅이 실패할 리 없는데 애초에 return이 될 일이 있을까?' 생각했지만, 문제는 의외로extractCustomerFromQueue()였어요. 손님 수가 은행원 수로 나누어 떨어진다면, 간혹 손님이 더 없어도 while문이 돌아가는 경우가 발생한 거예요!
    ```swift
    guard let customer = extractCustomerFromQueue() as? Customer else { return }
    ```
- 💥 **따라서, 이렇게 해결했어요!**
    - else문에서도 return되기 전에 `semaphore.signal()`을 호출 할 수 있도록 하여 해당 문제를 해결할 수 있었어요.
    ```swift
    guard let customer = extractCustomerFromQueue() as? Customer else {
                         semaphore.signal()
                         return }
    ```

　
## 👾 05.　비동기 작업 분리
### `handleAllCustomers()` 메서드 로직 분리
> 반복코드가 가장 많으며 OCP 개선 시급한 [ㄱ]을 우선으로 분리 ➡️ **`1번`**, 
> 마찬가지로 OCP위배 및 반복코드가 있는 [ㄴ~ㄷ]을 그 다음으로 분리 ➡️ **`2번`**, 
> `handleAllCustomers()`는 남은 [ㄹ]만 맡도록 했어요.

| 구분 |   | 처리 |
|:---:|:----|:---:|
|ㄱ| DispatchWorkItem을 생성하는 로직 | 분리 |
|ㄴ| DispatchGroup을 생성하는 로직 | 분리 |
|ㄷ| 생성된 DispatchWorkItem들이 지정된 DispatchGroup소속으로 실행되도록 세팅하는 로직 | 분리 |
|ㄹ| DispatchGroup [...]

2023-03-07 09:13 UTC, jryoun1 requested changes
step3 정말 고생하셨습니다~ 
많은 공부, 많은 시도를 한 것을 pr에 정말 너무 잘 담아주셨네요 👍🏻👏
덕분에 코드리뷰를 하면서 어떠한 의도를 가지고 작성했는지를 잘 알 수 있었습니다.

몇가지 코멘트 남겨드렸으니 확인부탁드려요~
### sos관련 답변
1. 해당 코드 부분 코멘트에 남겨두었습니다 🙏🏻
2. 따로 분리하는 것이 좋아보입니다! 다만 이때 SeriviceAsynchronizer init에서 모든것을 다 생성하기 보다는 주입을 통해 semaphore의 개수를 받는다던지 할 수 있을 것 같네요. 
이 과정에서 주입해줄때 매개변수의 default 값을 주게되면 사용하는 쪽에서는 필요에 의해서만 해당 값을 변경해주면 되니까 이러한 부분도 고려해보시면 좋을 것 같아요. 
```Swift
// defualt를 준다는 것은 아래처럼 작성되는 것을 말씀드린겁니다~ 
init(semaphoreCount: Int = 1) {
   self.semaphore = DispatchSemaphore(value: semaphoreCount)
}
```

Tips
Github에서 코드 블럭을 작성하실 때 
```Swift
//```(사용할 언어) 
// 내부에 코드를 작성하면됩니다 (키워드가 색상으로 표시됩니다)
// ```

// e.g. Swift라면
// ```Swift
func makeCodeBlock() {
   //
}
// ```
```

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    bank.close()
아주 추상화가 잘 되었네요 👏

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Timer/Timer.swift
> +    }
함수명만 봐서는 무언가를 더할 것 같은데 내부 동작과는 다른것 같습니다. 🙏🏻

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Extensions/ArrayExtension.swift
> +    }
배열에서 안전하게 접근하는것 너무 좋네요 💯

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Extensions/ArrayExtension.swift
> +        self = clerks.flatMap { $0 }
고차 함수도 잘 사용해보셨군요 👏

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer/Customer.swift
> +    let purposeOfVisit: BankingService?
purpose로 네이밍해도 충분할 것 같아요 🙏

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        self.timer = Timer()
손님과 손님의 수를 은행 내부에서 생성하는 것도 조금은 어색해 보여요!
현재 구조라면 손님은 은행이 있어야지만 존재할 수 있어보이는데, 사실은 손님은 은행이 없어도 생성될 수 있는 개체인 것 같아요. 
따라서 손님도 점원과 마찬가지로 외부에서 주입되는건 어떨까요?

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer/Customer.swift
> +class Customer: Node<String> {
Customer 클래스는 상속받을 일이 있을까요? 🙋‍♂️

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +}
프로토콜을 활용해서 타입을 추상화해준것 너무 좋네요 💯👍🏻

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            }
이정도로는 가독성이 크게 떨어진다고 생각이 들지는 않아서 크게 고민하지 않으셔도 될 것 같습니다. 
guard 문으로 뎁스도 잘 줄여주신 것 같네요 👍🏻

만약 더 줄어보고 싶다면 while문을 따로 `직원에게 일을 분배하는 함수`로 네이밍을 짓고 빼면 한 뎁스 줄어들게 될 것 같아보이긴하네요.

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +                guard let customer = extractCustomerFromQueue() as? Customer else { semaphore.signal(); return }
extractCustomerFromQueue()를 그냥 customers.dequeue()로 바로 쓸수 있을 것 같은데 함수로 뺀 이유가 궁금합니다!

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        return group
DispatchGroup, DispatchWorkItem을 제대로 공부해보시고 사용하신 것 같아서 좋네요 👏👍🏻

2023-03-07 09:13 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankingService.swift
> +enum BankingService: CaseIterable, Equatable {
업무의 종류도 따로 타입으로 만들어주신것도 좋네요 💯👏

2023-03-09 05:50 UTC, longlivedrgn commented on BankManagerConsoleApp/BankManagerConsoleApp/Timer/Timer.swift
> +    }
총 소요시간임을 뜻하는 totalTime으로 함수 명을 변경했어요! ☺️
> 해당커밋: 644d50d

2023-03-09 05:51 UTC, ueunli commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer/Customer.swift
> +class Customer: Node<String> {
깜빡했어요😅 final키워드 추가했습니다!!

> 해당커밋: f500512

2023-03-09 05:52 UTC, longlivedrgn commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer/Customer.swift
> +    let purposeOfVisit: BankingService?
`purpose`만으로도 변수의 의미를 표현할 수 있을 거 같아서 `purpose`로 변수 명을 변경했어요! ☺️
> 해당커밋: 644d50d

2023-03-09 05:53 UTC, ueunli commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +                guard let customer = extractCustomerFromQueue() as? Customer else { semaphore.signal(); return }
비동기 처리 전, dequeue()하기, dequeue()를 반복하기 ― 2가지 기능을 분리하고자 따로 작성했던 부분인데, 이제는 그럴 필요가 없어져 말씀해주신 대로 그냥 customers.dequeue()가 좋겠다 판단했어요! 해당 함수는 생략했습니다😄

> 해당커밋: eb6984d

2023-03-09 06:01 UTC, longlivedrgn commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        self.timer = Timer()
저희가 생각했을 때도, 은행의 생성자에의해 손님의 인원이 정해지는 현재의 로직이 어색하다고 생각했어요!🥲
다만, 손님 수를 정하려면 인원 수의 범위를 알아야되는데, 최대/최소 수용인원은 은행 객체의 속성이라 은행이 생성되지 전에는 외부에서 알 수 없어요! 그래서 은행의 생성자 매개변수에게 손님 수를 정해서 인자로 주입해 줄 수 있는 외부 객체 혹은 로직을 만들어주기 어려웠어요 🥲 이런 고민을 해결할 수 있는 좋은 대안이 있을까요?

2023-03-09 07:21 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        self.timer = Timer()
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/45090197/223949353-c8ea270a-4fdf-47f7-bb7f-a00ebadf34d9.png">
요 부분은 기획서를 어떻게 보는지 관점에 따라서 조금 다르게 생각할 수 있을 것 같습니다. 
min/max가 은행의 최대 수용인원이라면 은행이 가지고 있는 것이 맞을 것 같습니다. 다만 저는 은행의 최대수용인원이라기보다는 해당 값이 그냥 은행에 올 수 있는 손님의 random한 숫자라고 생각했고, 그렇기에 사실상 은행이 몇명이 올 지를 스스로 정한다기 보다는 주입을 받는 것이 좋을 것 같다고 생각했습니다. 

만약 은행의 최대 수용인원이라면, 손님의 숫자를 랜덤으로 받고 그 수가 은행의 최대 수용인원을 넘는다면 추가로 돌려보내거나 하는 처리도 필요해보입니다. (물론 현실세계와 코딩세계가 개념적으로 무조건 동일하다고 볼 수는 없지만 뭔가 처리가 있다면 더 좋겠죠 🙂)

2023-03-09 08:19 UTC, jryoun1 approved these changes
수정해주신 부분 확인했습니다. 👍🏻💯
손님 숫자에 관련된 부분은 코멘트에 추가 답변 남겨드렸습니다 🙏🏻

해당 부분은 추후 스텝에서 같이 고려해보시고 적용여부를 결정해도 될 것 같아보여서 이번 스텝은 여기서 머지하겠습니다 💪🏻

2023-03-09 08:19 UTC, merged