[STEP3]  Team SUGAN BankManager
tasty-code/ios-bank-manager pull request #24
Opened 2023-03-07 06:44 UTC by SunnnySong

<img src="https://user-images.githubusercontent.com/85678496/223342224-81547552-4049-4ade-8232-243df013cb18.png" width=100>

> 오랜만에 안녕하세요! 코리(@corykim0829)😆 강건너 TEAM SUGAN: Beyond the Livers!! 선장 **Sunny**와 선원 **Logan** 입니다~ 😎 ⛵️ 
저희 새싹 내에 최고의 짤을 한번 넣어봤어요! ㅎㅎ
<br>이번 Step3에서는 GCD에 대한 학습을 하는데에 많은 시간을 썼어요! 덕분에 어느정도 많이 감을 잡은것 같아요! 이번에도 좋은 리뷰 잘 부탁드립니다~! 🥰

## 핵심 구현
- Teller 생성
    - Teller object가 생성될 때 task를 지정하고, task에 따라 semaphore를 생성했어요.
    - Step2에서 BankManager가 했던 work를 Teller에서 구현했어요.
    
- 비동기 코드
    - while문을 사용해 `waitingQueue.dequeue()`가 nil이 되기 전까지 클로저를 반복 실행해요.
    - 프로젝트 요구사항은 예금 은행원이 2명, 대출 은행원이 2명으로 나와있어요. 손님들의 각 Task에 따라 동시에 손님 응대를 할 수 있도록 `DispatchQueue.global().async`를 사용했어요.
    - 만약 모든 은행원이 손님을 응대하고 있다면 그 다음 손님은 앞 손님의 일이 끝날 때까지 대기해야해요. 즉, thread에 접근하는 손님들의 제어가 필요해요. 저희는 이 부분을 `DispatchSemaphore`를 사용했어요. 예금, 대출 별 은행원 수가 다르기 때문에 2개의 `DispatchSemaphore`를 만들었어요. 

- completionHandler 사용 
    - BankManager의 `dealCustomer`메서드와  Teller의 `work`메서드가 `completionHandler`를 사용하여 손님 일 처리 과정의 "시작"과 "끝"을 알려주도록 구현했어요.
    - 이로써 Console 버전에서는 출력을, UI버전에서는 새로운 할당을 할 수 있을거라 기대해요.

## 🧐 Q: 질문
#### 1. guard else문의 return 처리하기 
`Task` 파일의 `getRandomTask` 메서드에요.
해당 매서드에서 만약 옵셔널을 푸는것이 실패를 한다면 기본값으로 deposit을 반환하도록 구현 했어요. 

이유는 만약 nil을 반환하게 된다면 이후에 `getRandomTask` 매서드가 쓰일때 매번 옵서녈 바인딩을 해줘야하는 수고가 들어가기 때문이에요. 이를 피하고자 처음부터 옵셔널이 아닌 값을 던져주고 싶었어요.
```swift
    static func getRandomTask() -> Task {
        let tasks = Task.allCases
        guard let task = tasks.randomElement() else { return Task.deposit }
        return task
    }
```

<br>

#### 2. enum의 Nasted type

해당 프로젝트의 `CustomerConstant`와 `Task`는 사실 `BankAbility`라는 enum 타입 안에 2개의 enum을 Nasted type으로 선언하여 카테고리화 시켰었어요. 코드를 나누는게 좋겠다는 생각이 들어 변경했는데 이에 대한 코리의 의견이 궁금해요!

<br>

- Before

```swift
enum BankAbility {

    enum CustomerConstant {
        
        static let min: UInt = 10
        static let max: UInt = 30

    }
    
    enum taskType: CaseIterable {
        
        case deposit
        case loan
        
    }
    
}

extension BankAbility {
    
    static var numberOfCustomer: UInt {
        guard let customerSum = (CustomerConstant.min...CustomerConstant.max).randomElement() else { return 0 }
        return customerSum
    }
    
    static func getRandomTask() -> taskType {
        let tasks = taskType.allCases
        guard let task = tasks.randomElement() else { return taskType.deposit }
        return task
    }
    
    static func taskDuration(of taskType:BankAbility.taskType) -> Double {
        switch taskType {
        case .deposit:
            return 0.7
        case .loan:
            return 1.1
        }
    }
    
}
```
<br>

- After

```swift
enum Task: String, CaseIterable {
    
    case deposit = "예금"
    case loan = "대출"
    
    var numberOfTeller: UInt {
        switch self {
        case .deposit:
            return 2
        case .loan:
            return 1
        }
    }
    
}

extension Task {
    
    static func getRandomTask() -> Task {
        let tasks = Task.allCases
        guard let task = tasks.randomElement() else { return Task.deposit }
        return task
    }
    
    static func duration(of task: Task) -> Double {
        switch task {
        case .deposit:
            return 0.7
        case .loan:
            return 1.1
        }
    }
    
}
```
```swift
enum CustomerConstant {
    
    static let min: UInt = 10
    static let max: UInt = 13
    
    static var numberOfCustomer: UInt {
        guard let customerSum = (CustomerConstant.min...CustomerConstant.max).randomElement() else { return 0 }
        return customerSum
    }
    
}
```

<br>

#### 3. completionHandler 관련 질문
```Swift
 func work(completion: (Bool)->Void) {
    semaphore.wait()
    completion(true)
    Task.duration(of: task).sleep()
    completion(false)
    semaphore.signal()
}

private func dealCustomer(group: DispatchGroup, completion: @escaping (CustomerInfo, Bool)->Void) {
        let queue = DispatchQueue.global()
        var tellers = [Task:Teller]()
        
        Task.allCases.forEach { task in
            tellers[task] = Teller(task: task)
        }
        
        while let customer = waitingQueue.dequeue() {
            group.enter()
            guard let teller = tellers[customer.task] else { return }
            
            queue.async(group: group) {
                teller.work() { bool in
                    completion(customer, bool)
                }
            }
            
            group.leave()
        }
    }
```
Step3에서는 일을 하는 주체가 Teller로 변경되었어요. Teller의 work 메서드는 `한명의 손님 응대를 시작할 때` 그리고 `손님 응대를 끝냈을 때` report() 메서드를 실행시켜야 해요. 

이 부분에 대해 어떻게 구현해야 할지 고민을 하다가 `completionHandler`를 사용했어요. completionHandler를 사용해 Bool 값으로 손님 응대가 시작인지, 종료인지 알려주는 방식이에요. 

BankManager의 `dealCustomer()` 메서드는 비동기로 `teller.work`를 실행시켜요. 여기서도 completionHandler를 사용한 이유는 역할 분리 때문이었어요. dequeue를 통해 teller에게 일을 하도록 시키는 `dealCustomer()` 메서드에서 report까지 한다면 한 가지 메서드에 두 가지의 활동이 있다고 생각했어요. 
때문에 또 한번의 completionHandler로 `CustomerInfo`와 Bool 값을 전달했어요. 이렇게 역할을 분담한 코드는 추후 UI를 구현할 때에도 중복되는 코드 작성 없이 동작을 실행시킬 수 있을 것이라 생각해요.

저희는 completionHandler를 알람? 데이터를 전달해주는 알람과 같이 사용했어요. 이와 같이 역할을 분리할 때 다른 메서드에 알람을 전달해 주기 위한 방식이 completionHandler 이 최선일까요?🤔 코리가 생각하는 더 좋은 방식이 있다면 알려주세요!

<br>

### Step4에서 구현

일이 모두 끝난 이후, finalReport()를 실행합니다. 이때 손님의 총 수와 일을 처리하는데 걸린 총 시간을 print() 합니다. 

저희가 비동기로 작동하는 로직을 생각하지 못하고 손님 별 작업 시간을 모두 합산해 총 걸린 시간으로 print 했어요. 뒤늦게 비동기로 작동한 것을 떠올리고 총 시간을 Timer을 사용해 구하여 했지만, 시간이 좀 걸릴거 같아 Step4에서 구현하기로 했어요!
이 부분은 양해 부탁드립니다🥲

2023-03-07 13:53 UTC, corykim0829 requested changes
수고 많으셨습니다!! 

Task, CustomerInfo, Teller 객체를 분리하고 Teller가 일을 처리하려고 로직을 작성한 부분이 좋았습니다!

조금만 더 정리하면서 개선하면 좋을 것 같습니다!

---

> 1. guard else문의 return 처리하기

randomElement()를 사용하지 않고 처리하는 법을 고민해보면 좋을 것 같아요.

> 2. enum의 Nasted type
이번에 변경한게 더 깔끔하네요!

> 3. completionHandler 관련 질문

completionHandler를 사용한 것은 좋지만, 코드만 봤을 때 Bool값이 의미하는 바를 바로 파악하기 어려운 것 같네요. teller work로부터 넘어오는 completion의 Bool부터 가독성이 떨어지는 것 같아요.
파라미터를 사용하거나 다른 방법을 생각해보면 좋을 것 같아요.

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/CustomerInfo.swift
>  struct CustomerInfo {
CustomerInfo보다는 프로퍼티가 Customer의 정보를 보여줘서 Customer가 더 깔끔한 것 같아요.

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/CustomerInfo.swift
> +        self.task =  Task.getRandomTask()
지금은 요구사항 특성 상 이렇게 구현하신 것 같지만, 외부에서 랜덤 Task값을 만들어서 Customer 객체에게 넘겨주는게 좋을 것 같네요

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/Teller.swift
> +    let task: Task
teller가 굳이 task를 가지고 있을 필요는 없는 것 같아요. Customer가 가지고 있는 task 정보를 넘겨받아서 처리하는 방식으로 처리하면 어떨까요?

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/Teller.swift
> +    let semaphore: DispatchSemaphore
세마포어로 처리한 부분 좋습니다 👍

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    private func dealCustomer(group: DispatchGroup, completion: @escaping (CustomerInfo, Bool)->Void) {
closure 파라미터 타입 명시 부분에 -> 좌우로 여백을 주면 좋겠네요 :)

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +        var tellers = [Task:Teller]()
딕셔너리에서 `[Task: Teller]()`와 같이 `:`뒤에 공백을 주는게 좋겠네요!

딕셔너리는 옵셔널처리의 번거로움이 있는데, 딕셔너리를 사용하지 않고 처리할 수 있는 방법을 생각하면 더 좋을 것 같네요!

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    private func generateWaiting(customers: UInt, to waitingQueue: WaitingQueue<CustomerInfo>) {
이미 BankManager 구조체에 waitingQueue가 프로퍼티로 있는데, 여기서 파라미터로 처리하는 이유가 있나요?

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +            totalDuration += Task.duration(of: result.task)
Task의 duration을 구하는 과정을 조금 더 단순화시킬 수 있을 것 같아요!

2023-03-07 13:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +        dealCustomer(group: group) { result,bool  in
completion으로 넘어오는 값을 result, bool로 처리하면 어떤 값을 의미하는지 유추하기 힘들 것 같아요.
수정하면 좋겠네요!

2023-03-08 01:31 UTC, SunnnySong commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/CustomerInfo.swift
>  struct CustomerInfo {
넵 수정했습니다!

2023-03-08 01:31 UTC, SunnnySong commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/CustomerInfo.swift
> +        self.task =  Task.getRandomTask()
네! 수정 완료했습니다

2023-03-08 01:35 UTC, SunnnySong commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/Teller.swift
> +    let semaphore: DispatchSemaphore
👍

2023-03-08 01:39 UTC, SunnnySong commented on BankManagerConsoleApp/BankManagerConsoleApp/BankSystem/Teller.swift
> +    let task: Task
넵 변경했습니다~

2023-03-08 02:16 UTC, sloDevz commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    private func generateWaiting(customers: UInt, to waitingQueue: WaitingQueue<CustomerInfo>) {
아 이전에 설계했던 흔적입니다 깜빡하고 지우질 못했던거 같아요 😅
수정했습니다!

2023-03-08 08:33 UTC, sloDevz commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +            totalDuration += Task.duration(of: result.task)
Timer를 쓰게되는 Step4에서 구현하도록 하겠습니다!😁

2023-03-08 08:44 UTC, sloDevz commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +        var tellers = [Task:Teller]()
저희가 처음에는 `Task`를 두 가지로만 가정하고 구현했지만 이후에 들었던 생각이 은행이 성장해서 `Task`가 더욱 많아질 때 거기에 따르는 수정사항들을 최소화 시키기위해서 이렇게 작성했습니다.
`Task` 와 `duration`만 정의해주면 `Task`가 몇개이든 알아서 돌아가도록 했던것인데 그 과정에서 처음엔 `Teller`들의 집합체를 `[Teller]` (배열)로 했다가 `dequeue`된 커스터머의 `Task`에 맞는 `Teller`를 탐색하기 위해서 배열을 쭉 훑는 작업 자체가 마음에 들지 않아서 `Hashable`한 `Dictionary`를 선택했던 것 입니다. 이런 이유에서도 `Dictionary`는 바람직 하지 않을까요?

2023-03-08 12:53 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +        var tellers = [Task:Teller]()
그렇군요! 추후 확장성을 고려하면 Dictionary 사용도 좋은 것 같습니다! 👍

2023-03-08 12:54 UTC, corykim0829 approved these changes
수고 많으셨습니다!
다음 스텝 진행하시면 됩니다 :)

---

궁금한 부분이 있는데, TellerProvidable의 역할은 무엇인가요?

2023-03-08 12:54 UTC, merged

2023-03-08 13:03 UTC, sloDevz commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +        var tellers = [Task:Teller]()
감사합니다! 😆