[STEP3] 은행창구 관리앱 ― D.O, Joo
tasty-code/ios-bank-manager pull request #25
Opened 2023-03-07 06:50 UTC by ohdair

# STEP3 PR

안녕하세요🙋‍♂️ @wonhee009

이번 STEP3 에서는 `비동기 동작의 구현 및 적용`이 중점이였어요.! 

두 개의 큐(예금queue, 대출queue)를 생성하고 비동기 동작을 하도록 구현해보았어요

고객 업무 로직에서는 `dequeue`와 `clientsPerDay` 동시 접근을 막기 위해 `Semaphore`를 사용했어요

이후 비동기 동작을 기다리기 위해 `DispatchGroup`을 사용하였어요

## **Step 2 : 타입 구현 및 콘솔앱 구현**
<img src="https://user-images.githubusercontent.com/79438622/223344588-ceffe2ac-6036-4d98-9dd1-2c7010d79de1.png" width="80%">
<img src="https://user-images.githubusercontent.com/79438622/223344614-c0da0547-a69c-4da4-a53c-2d5124d3b1a0.png" width="80%">

### 다중처리

- [x]  은행에는 3명의 은행원이 근무합니다.
- [x]  2명의 은행원은 예금업무를, 1명의 은행원은 대출업무를 처리합니다
- [x]  고객의 업무 종류는 고객 생성시 임의로 지정합니다
- [x]  한 명의 은행원은 한 명의 고객을 응대할 수 있습니다
- [x]  고객이 원하는 업무의 종류와 소요시간 → 예금 : 0.7초, 대출 : 1.1초
- [x]  대기중인 고객 업무처리 시작시 출력 메세지: "3번 고객 대출업무 시작"
- [x]  고객의 업무를 처리 완료시 출력 메세지: "11번 고객 예금업무 완료"

### **스텝 핵심 경험**

- 동기(Synchronous)와 비동기(Asynchronous)의 이해
- 동시성 프로그래밍 개념의 이해
- 동시성 프로그래밍을 위한 기반기술(GCD, Operation) 등의 이해
- 스레드(Thread) 개념에 대한 이해
- GCD를 활용한 동시성 프로그래밍 구현
- 동기(Synchronous)와 비동기(Asynchronous) 동작의 구현 및 적용
- Queue의 활용
- 타입 추상화 및 일반화

# 질문

1️⃣ 메서드 안에 중첩 메서드를 사용하지 않았지만, Bank라는 특정 메서드의 일을 구분짓기 위해서 여러 함수들로 분리가 되는데, 아래와 같이 중첩 메서드를 사용해도 괜찮은지 궁금해요. 

```swift
private func startBanking() {
    assignBanking()
    dispatchGroup.wait()

    private func assignBanking() {
        bankTeller.forEach { teller in
            serveClient(teller)
        }
    }
}
```

2️⃣ Dictionary 구조에서 열거형의 모든 경우로 값을 넣어준 다음에 특정 타입의 값을 불러온다면 값이 있다는 것을 확실하지만 XCode에서는 optional로 가져오면서 반환을 하기 위해서 `??` 혹은 `!` 를 쓰는 것보다는 `fatalerror`를 사용하는 것에 대해서 어떻게 생각하시나요? 

```swift
struct BankQueue {
    private var queue: [BankingType: Queue<Client>] = [:]
    
    init() {
        BankingType.allCases.forEach { bankingType in
            queue[bankingType] = Queue<Client>()
        }
    }

    func queue(type: BankingType) -> Queue<Client> {
        guard let result = queue[type] else {
            fatalError("Failed to create queue")
        }
        return result
    }
```

3️⃣ 특정 메서드에서 여러 메서드를 실행한다면, 관련 메서드가 너무 많다 판단하여 `extension`으로 분리를 하는 것은 좋은 방법인지 궁금해요. 만약 하게 된다면 아래의 코드와 같이 하려고 생각을 했는데, 라자냐는 어떻게 생각하시나요?

```swift
// mark: - startBanking 
extension Bank {
    func startBanking() {
        assignBanking()
        serveClient()
        ...
    }
    func assignBanking() { }
    func startBanking() { }
}
```

2023-03-07 23:34 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인 부탁드려요.

- 중첩 메서드를 사용해도 괜찮습니다.
- fatalError가 사용자 입장에서 보면 사용성이 좋지 않습니다. 따라서, 실제 서비스에서는 fatalError를 호출하는 일은 거의 없을거 같구요. 보통은 에러 알럿이나 스펙에 명시되어 있다면 기본 값을 지정해주는 등의 방식으로 우회합니다.
- 이 부분에 대해서는 스타일의 차이일거 같습니다. 저는 개인적으로 delegate를 채택하는거와 같이 프로토콜을 채택하는 경우는 관련 메서드를 extension으로 분리하는 편인데요. 그 외에는 거의 분리하지 않고는 있습니다. (개인적으로 코드를 파악하는데에 extension으로 분리/!분리를 통해 외부와의 연결성을 파악하는 편여서요.)

2023-03-07 23:34 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Teller.swift
>      }
`Constant`에 정의한 tellerProcessingTime을 가져오는 방식으로 되어 있는데요.
tellerProcessingTime이 `Teller`에만 필요한 부분인데 관련 사항은 `Constant`에 있어 이후 `BankingType`이 추가/수정 될 때마다 여러벌을 관리해야할거 같습니다.
해당 프로퍼티를 `Teller`에서만 사용하는만큼 `Constants`보다는 `private extension`을 사용하여 `Teller`에 정의해두고 사용하는건 어떤가요?

2023-03-07 23:34 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankQueue.swift
> +        }
예금의 경우 value가 2여야하는거 아닌가요?.?

2023-03-07 23:34 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private let bankTeller: [Teller] = {
프로퍼티 정의 순서의 기준이 있을까요?
보통은 static > public > private 순으로 순서를 하긴 합니다.
이런 정의 순서도 코드를 파악하는데 의미를 갖고 있으니 순서에 대해서도 기준을 정하면 좋을거 같습니다~

2023-03-07 23:34 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private static var clientsPerDay = 0
private인데 static인게 의미가 있나요?.?

2023-03-07 23:34 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            let queue = bankQueue.queue(type: teller.type)
`bankQueue.queue(type: _)`이 어떤 역할을 하는 메서드인지 네이밍만으로는 드러나지 않는거 같습니다.
좀 더 명확한 네이밍이 있을까요?

2023-03-08 01:15 UTC, ohdair commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankQueue.swift
> +        }
예금을 담당하는 직원(thread)이 여러명이 되면 `Critical Section`에 접근 할 수도 있기 때문에 `Race Condition`이 발생하게 됩니다. 같은 고객(data)을 두 명 이상의 직원이 처리를 하려고 하기 때문에 semaphore를 이용하여  단 하나의 thread만 접근하여  dequeue 하도록 만들었습니다.

2023-03-08 01:22 UTC, ohdair commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private let bankTeller: [Teller] = {
순서를 신경 안썼는데, 기준에 대해서 고민을 하였고 내용을 찾아서 숙지했어요. 감사합니다

2023-03-08 01:26 UTC, doshkor commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private static var clientsPerDay = 0
내부 로직에서 값이 변경될 수 있도록 static 을 붙이고 외부에서 접근할 수 없도록 private 를 붙였어요

clientPerDay 속성은 dequeue 시마다 변경되는 속성이에요. 그래서 구조체의 속성 변경시마다 mutating 키워드를 붙여야 하고, 
그렇게 되면 Bank 객체 생성시 var bank = Bank(), 즉 var 키워드를 사용해서 선언을 해야되더라구요. 업무를 수행하는 객체로써의 bank 가 var 로 선언되어 변경될 수 있다는 의미를 갖는 것보다 let 으로 선언되는게 자연스럽다고 생각했어요

2023-03-08 02:03 UTC, doshkor commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Teller.swift
>      }
`Teller` 구조체 내부에 `enum Constants`를 생성해서 상수를 관리하게 변경해보았어요

2023-03-08 02:13 UTC, ohdair commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            let queue = bankQueue.queue(type: teller.type)
좀 더 명확하게 나타내기 위하여 `bankQueue.queue(for:)`로 표현했어요. 

혹시 라자냐가 생각하는 더 나은 네이밍이 있을까요?

2023-03-08 03:05 UTC, wonhee009 requested changes

2023-03-08 03:05 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private static var clientsPerDay = 0
`static`이 타입 프로퍼티라서 은행A, 은행B를 정의해도 `clientsPerDay`는 하나로 운영될텐데요. 이 부분이 의도한 바가 맞을까요?
또한, 저는 보통 static을 사용할때 외부에 (열려 있어서) 의해 변경될 수 있는 값이지만 타입별로 하나의 프로퍼티로 관리되어야 할때가 static 사용의 기준이라고 생각하는데요.
- `private var clientsPerDay`로는 스펙 구현이 어려운지 궁금합니다.
- var보다는 let이 좀 더 자연스러울거 같다는 부분 저도 공감합니다. 그렇다면 Bank가 꼭 struct일 필요가 있는지도 궁금하네요.

2023-03-08 03:05 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Teller.swift
>      }
``` swift
private extension BankingType {
   var processingTime: UInt32 {
      switch self {
         ...
      }
   }
}
```
이런식으로 enum 자체를 extension 할 수 있을거 같습니다.
이런식으로 작성한 코드와 enum Constants를 통해 작성한 코드 사이에 차이에 대해서도 얘기해보면 좋을거 같습니다.

2023-03-08 03:06 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            let queue = bankQueue.queue(type: teller.type)
bankQueue 자체가 큐일거 같은 네이밍인데요.
큐에서 큐를...? 이라는 느낌여서 네이밍 한 번 다시 확인 부탁드립니다.

2023-03-08 08:24 UTC, ohdair commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Teller.swift
>      }
Constnats로 지정을 해놓으면 매직 스트링을 관리하기 편할 거 같아서 위와 같이 사용했었으나 특정 파일에서만 사용하고 가독성과 유지 관리를 위해서는 라자냐의 말처럼 하는 것이 좋은 거 같아서 특정 값을 어디에 구현을 해야 되는지 고민하게 된 시간이었어요

2023-03-08 08:28 UTC, doshkor commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private static var clientsPerDay = 0
고민하던 부분과 말씀해주신 부분에 대해 고민해본바, Bank 가 `class`로 구현하는 것이 자연스럽다고 생각하고 변경하였습니다

static 타입 프로퍼티를 사용하면 여러 인스턴스 생성시 값을 공유하게 되므로 주의해야 한다는 것을 알게되었습니다

2023-03-08 08:35 UTC, doshkor commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            let queue = bankQueue.queue(type: teller.type)
`bankQueue.get(of: )` 로 변경해보았습니다~🙋‍♂️

2023-03-08 08:39 UTC, wonhee009 approved these changes
수고하셨습니다 :)

2023-03-08 08:39 UTC, merged