은행창구 관리앱 [Step4] Mason, iyeah
tasty-code/ios-bank-manager pull request #28
Opened 2023-03-10 05:28 UTC by qwerty3345

안녕하세요 븨븨 @YebinKim🙇‍♂️ Mason 입니다!

STEP4는 UI 구현에 집중해서 진행하였습니다 :)

# ✅ 요구사항 & 체크리스트

- [x]  Step 3의 은행을 UI 앱으로 전환합니다
    - 이번 프로젝트의 UI구성은 ‘코드'만 사용하여 구현합니다
- [x]  고객 정보를 표현할 커스텀뷰를 구현합니다 - 뷰에 포함될 정보 : 고객번호, 업무종류
- [x]  대기열은 스택뷰를 활용합니다
- [x]  화면 구성 → 업무중인 고객 리스트, 대기중인 고객 리스트업무시간 타이머, 고객 10명 추가 버튼, 초기화 버튼
- [x]  고객 10명 추가 버튼을 통해 임의의 10명의 고객이 추가됩니다
- [x]  초기화 버튼을 누르면 대기중인 고객과 타이머 모두 초기화됩니다
- [x]  모든 업무가 끝나고 대기중인 고객이 없으면 업무시간 타이머는 멈춥니다
- [x]  고객이 추가되어 다시 업무를 처리하면 타이머가 동작합니다
    - 초기화 하기 전까지 업무시간은 초기화하지 않고 누적합니다

### 실행 예
<img width="483" alt="194275759-2282e95d-d3c4-46f4-9516-31f9847c275f" src="https://user-images.githubusercontent.com/59835351/224231233-90607e6e-dfdf-4fea-a6d1-c8afb8896726.png">

# **⁉️ 고민과 해결**

### 1️⃣ 업무 도중 고객 추가의 구현

- 업무를 수행하는 도중에 고객을 추가할 시에 기존의 코드로는 계속해서 새로운 은행원 스레드가 생성되는 문제가 발생했고, 현재 각 은행원이 업무를 마친 상태인지를 확인하는 로직이 필요했습니다.
- 각 은행원에게 업무중/업무끝냄 의 속성을 추가하여 업무를 끝낸 상태일 때만 새로운 업무를 할당하게끔 로직을 변경하였습니다.
- 다만, 로직 상… 은행원이 업무를 수행할 고객 큐가 차있는 상태에서 고객을 할당 받고 1초 정도 업무를 수행한 뒤, 다음 업무를 수행할 “아주 짧은 중간 텀 동안”에 만약 사용자가 고객 추가 버튼을 누른다면 현재 은행원이 업무를 수행하지 않음으로 간주하고 추가 스레드가 발생할 가능성이 예상됩니다.
    
    > 이 부분은 차후 수정 개선 해 나가보도록 하겠습니다.
    > 
    - 이를 위해, 각 은행원을 serial Queue로 구현하고 해당 큐에 손님을 할당하는 것이 로직 상 깔끔할 것 같아서 그렇게 시도 해 보기도 했지만… 기존의 방식으로 문제를 해결 해 보는 것도 좋은 경험이 될 것 같았습니다.

### 2️⃣ Protocol, 의존성주입의 활용

- 기존의 콘솔 코드는 ConsolePresenter에 직접 접근 해 업무 시작/종료를 나타냈었는데, 
Presentable 이라는 프로토콜을 생성하고, 해당 프로토콜을 채택한 프리젠터는 모두 사용자에게 업무 시작/종료의 역할을 나타내게 해 줄 수 있도록 구현하였습니다.
- 또한 의존성 주입을 활용하여, Bank, BankTeller, Presenter 간 관계를 정의했습니다.

2023-03-12 22:01 UTC, YebinKim requested changes
메이슨 안녕하세요! 🙌
은행 창구 매니저 마지막 스텝까지 고생 많으셨어요 🥳🎉
이번 스텝은 지금까지 진행해 온 프로젝트 코드를 바탕으로 UI를 추가하는 것 뿐만 아니라 사용자가 언제든 고객의 수를 추가할 수 있도록 구현하는 기능까지 구현해야 해서 난이도가 쉽지만은 않았을 거 같아요.

**업무 도중 고객 추가의 구현** 기능에 대해서는 문제점에 대해 부딪히고 해결책 또한 고민해보신 거 같아서 리뷰는 이번 스텝의 핵심 경험에 해당하는 것 처럼 동시성 프로그래밍 중 UI 요소 업데이트가 원활히 이루어질 수 있을지를 중심으로 확인했습니다 ☺️

그리고 **Protocol, 의존성주입의 활용** 을 시도하신 점이 눈에 띄었는데요 🤩 Presenter 를 활용해 UI 구현의 책임을 각 뷰와 뷰컨트롤러가 가지게 된 점이 인상깊었어요 👍👍

---

이번 스텝의 핵심 경험은 아래와 같았는데요.
<img width="379" alt="step4" src="https://user-images.githubusercontent.com/38066039/224575864-381737d4-207b-4a27-a161-8c2cbf44ce7a.png">

메모리 누수 관련으로 p1 코멘트가 있어 Request Changes 로 요청 드렸어요!
이미 프로젝트 수행 기간이 지나서 이번 스텝은 코멘트만 확인 후 넘어가거나 간단한 수정만 진행하면 어떨까 합니다 😄 이 부분은 함께 얘기 나눠보아요~

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +
p4;

불필요한 개행이 있는 것으로 보여요 👀

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +
p4;

다른 extension 위에는 개행이 있지 않은데,
여기에만 여러 개행이 있는 것으로 보여요 👀

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        let customers = generateVisitCustomers(withCount: 10)
p3;

`Constant` enum의 `addCustomerButtonTitle`에서 고객의 수와 `withCount` 매개변수의 값으로 넘겨주는 고객의 수가 10으로 하드코딩 된 것으로 보여요!
재사용성이 높도록 변수로 선언해 사용해보면 어떨까요?

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        timerUtil.reset()
질문;

버튼의 selector 메서드는 `DispatchQueue.main.async` 블럭으로 감싸져있지 않네요!
메인 스레드에서 실행됨이 보장되어 있음을 확인하고 사용하신 게 맞을까요?? 👀

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Util/TimerUtil.swift
> +        print(formattedTime)
p3;

`print` 메서드는 로그를 위해 작성하신 걸까요?
로그를 위한 용도였다면 [Logger](https://developer.apple.com/documentation/os/logger)를 사용해 로그로 사용하고자 하는 의도를 명확히 하는 것이 필요해보이고, 로그의 의도가 아니라면 삭제가 필요해보여요 🤔

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    private lazy var bank = Bank(bankTellers: bankTellers, presenter: self)
p1;

강한 참조로 인해 메모리 누수가 발생하고 있네요 👀
요거 디코로 잠시 같이 확인해보면 좋을 거 같아요! 😄

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/View/CustomerStatusLabel.swift
> +final class CustomerStatusLabel: UILabel {
커스텀 뷰를 적절히 활용한 덕분에 `BankViewController` 에서 레이블을 찾고 지우는 동작이 쉬워졌네요! 😆👍

2023-03-12 22:01 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Util/TimerUtil.swift
> +    func setPresenter(presenter: @escaping (String) -> Void) {
p3;

메서드 이름과 매개변수 이름 중 presenter 가 중복되어 읽히네요! 🤔
Swift API Design Guidelines의 [Promote Clear Usage](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage)에 따라 중복되는 네이밍을 지양해보면 어떨까요?
> Omit needless words. Every word in a name should convey salient information at the use site.

2023-03-13 03:27 UTC, qwerty3345 commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        let customers = generateVisitCustomers(withCount: 10)
이후 커밋에서 반영 했습니다 :)
> 해당 커밋: ad4e0e8

2023-03-13 03:30 UTC, qwerty3345 commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +
차후 커밋에서 다른 상수값을 추가해줬습니다 :)

> 해당 커밋: https://github.com/tasty-code/ios-bank-manager/commit/ad4e0e861176efeb569fd485853e8f89cb7f1e04

2023-03-13 03:32 UTC, qwerty3345 commented on BankManagerUIApp/BankManagerUIApp/Util/TimerUtil.swift
> +        print(formattedTime)
불필요한 print였어서 삭제하였습니다..!

2023-03-13 03:35 UTC, qwerty3345 commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    private lazy var bank = Bank(bankTellers: bankTellers, presenter: self)
반영하였습니다! 정말 중요한 부분인데 짚어주셔서 감사해요 :)

> 해당 커밋: cb00fa4

2023-03-13 04:18 UTC, qwerty3345 commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +
수정했습니다!
> 해당 커밋: cb00fa4

2023-03-13 04:20 UTC, qwerty3345 commented on BankManagerUIApp/BankManagerUIApp/Util/TimerUtil.swift
> +    func setPresenter(presenter: @escaping (String) -> Void) {
set(presenter:) 로 하려니, 후행 클로저로 사용 시 불명확해지는 상황이 생겨서
setPresenter(_:) 형태로 변경하였습니다 :)
> 해당 커밋: 07bf607

2023-03-13 04:28 UTC, qwerty3345 commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        timerUtil.reset()
메인스레드에서 addTarget 을 해주었고, 해당 action이 발생하는 상황이 UIButton의 .touchUpInside 로 유저가 터치를 한 상황이기에 메인 스레드에서 실행될 것이라 생각하고 따로 main.async로 처리해주지 않았습니다..!
혹시 관련 내용에 대해 팁을 주실 수 있으실까요~?

2023-03-13 08:20 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        timerUtil.reset()
제가 알고 있기로도 메인 스레드에서 실행됨이 보장된 것이 맞습니다!
의도하고 사용한 게 맞는지 확인차 여쭤봤어요 ☺️ `유저가 터치를 한 상황이기에 메인 스레드에서 실행될 것이라 생각`한 게 맞으셨군요 🤩👍

2023-03-13 08:25 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    private lazy var bank = Bank(bankTellers: bankTellers, presenter: self)
코멘트 반영 고맙습니다! 😄
`Bank` 인스턴스가 해제되기 전까지 `BankViewController`는 여전히 참조 카운트가 유지된다는 점도 확인하고 넘어가면 좋을 거 같아요~

2023-03-13 08:27 UTC, YebinKim approved these changes
메이슨 안녕하세요~
빠르게 수정 진행하느라 고생 많으셨습니다!

이번 스텝은 이대로 머지를 진행하도록 할게요. 3주간 고생 많으셨습니다 😄

2023-03-13 08:27 UTC, merged