은행창구 관리 앱 [Step1] 뉴준성, Howard
tasty-code/ios-bank-manager pull request #30
Opened 2023-10-30 07:31 UTC by JEON-Sungsu

리뷰어 : @zdodev
버드 : @JEON-Sungsu, @newJunsung

## 구현 조건

- 은행에 도착한 고객이 임시로 대기할 대기열(큐, Queue) 타입을 직접 구현합니다.
    - Queue 타입 구현을 위한 Linked-List 타입을 직접 구현합니다.
    - Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용합니다.
    - Queue 타입이 예상한대로 동작하는지 Unit Test를 통해 동작을 검증합니다.
        - Queue에 구현해야 할 필수 기능
            - Enqueue, Dequeue, Clear, Peek, isEmpty

## 프로젝트 구조

```mermaid
classDiagram

class BankManagerConsoleApp {
	BankManager.swift
	main.swift
	Queue.swift
}

class QueueUnitTest {
	QueueUnitTest.swift
}
```

## 코드 설명

```swift
extension Queue {
    private class Node {
        var data: Element
        var pointer: Node?
        
        init(data: Element, pointer: Node? = nil) {
            self.data = data
            self.pointer = pointer
        }
    }
}
```

Queue에서 Node를 Nested Type으로 둔 이유는 다른 사용자는 Queue 클래스 자체가 Black Box이어야 하기 때문입니다. Node 클래스는 Queue 내부에서만 사용하고, 개별적으로 Node를 활용할 수 없습니다. 따라서 굳이 해당 클래스를 노출하여 발생하는 휴먼 에러를 방지하고자 Queue의 NestedType으로 그리고 private으로 접근제어자를 지정하였습니다.

2023-10-30 14:23 UTC, zdodev requested changes
안녕하세요. @JEON-Sungsu , @newJunsung !

은행창구 관리 앱 Step 1 구현 잘해주셨습니다!
구현 및 동작도 기능 명세에 따라 잘 동작하도록 구현해주셨습니다!👍

테스트 부분과 함께 몇 가지 궁금증을 남겨보았습니다!
같이 의견 나눠보면 좋을 것 같습니다.😁

2023-10-30 14:23 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +struct Queue<Element> {
Queue 타입을 `struct` 로 구현한 이유가 궁금합니다!

2023-10-30 14:23 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private class Node {
Node 타입을 `class` 로 구현한 이유가 궁금합니다!

2023-10-30 14:23 UTC, zdodev commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +    func test_Dequeue가_제대로_되는지() {
`제대로`라는 단어가 모호한 의미를 가지고 있는 것 같습니다.
지금 상태에서는 조건(입력)과 결과(출력)를 나타내면 더 좋은 테스트 메서드 이름이 될 것 같아요!
ex) `test_1_더하기_1_은_2다()`
아래 다른 테스트 메서드 이름도 확인해보면 좋을 것 같아요!🙂

2023-10-30 14:23 UTC, zdodev commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +    }
`setUp`, `tearDown` 을 잘 활용해보셨네요!👍

2023-10-30 14:23 UTC, zdodev commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +        }
-1000부터 1000범위 안에 랜덤 숫자를 100번 반복하는 게 dequeue의 전체 기능을 보장해주는지 그리고 유의미한(횟수의) 테스트인지 의문이 듭니다.
단순히 횟수를 많이 그리고 랜덤한 숫자를 대입하는 테스트 보다는, 다양한 상황에서 dequeue가 일어날 수 있는 케이스를 보다 구체적으로 나눠보는 것은 어떨까요?
예를 들면, 큐안에 데이터가 있을 때와 없을 때가 있을 것 같습니다. 더 다양한 상황이 있을 수 있을 것 같습니다.🙂
아래 다른 테스트의 테스트 방식도 확인해보면 좋을 것 같아요!

2023-10-30 14:23 UTC, zdodev commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +    func test_Queue1() {
테스트 이름이 모호합니다!

2023-10-30 14:23 UTC, zdodev commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +    func test_Queue_종합테스트() {
하나의 테스트 메서드에서 종합적으로 테스트 하기 보다는 테스트 하려고 하는 기능 별로 나눠서 테스트 구문을 작성해보면 더 좋을 것 같습니다!

2023-10-31 00:41 UTC, JEON-Sungsu commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private class Node {
하나의 노드는 다음 노드의 주소값을 참조해야하기 때문에, 참조타입인 class로 하였습니다.

2023-10-31 00:42 UTC, newJunsung commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +struct Queue<Element> {
```swift
// 클래스일 경우
class Queue<Element> { }
```

```swift
// 구조체일 경우
```

2023-10-31 01:11 UTC, newJunsung commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +    }
dequeue의 케이스를 세부적으로 나눠서 테스트를 다시 진행했습니다.
(Queue의 요구사항에 있는 다른 요소들도 세부적으로 나눠서 테스트 케이스를 수정했습니다.)

2023-10-31 15:35 UTC, zdodev approved these changes
안녕하세요. @JEON-Sungsu , @newJunsung !

궁금증에 대한 의견을 잘 남겨주셨네요!
그리고 테스트가 더욱 명확하고 의미있는 내용으로 개선되었어요!🙂

2023-10-31 15:35 UTC, zdodev commented on BankManagerConsoleApp/QueueUnitTest/QueueUnitTest.swift
> +        let array = [3, 54, 123,67, 28]
공백을 맞추면 좋을 것 같습니다!🙂

2023-10-31 15:36 UTC, merged