은행 창구 관리 앱 [STEP 1] bello, dora
tasty-code/ios-bank-manager pull request #33
Opened 2023-10-31 01:51 UTC by JinUng41

리뷰어: @forestjae

버드: @JinUng41, @KSK9820

안녕하세요, 숲재!!

은행창구 관리 앱으로 만나뵙게 된 벨로, 도라입니다.

[STEP 1]에서는 연결 리스트로 구현된 큐와 큐에 사용되는 노드 타입을 구현해 보았습니다.

## 프로젝트 요구사항

- [x]  은행에 도착한 고객이 임시로 대기할 대기열(큐, Queue) 타입을 직접 구현합니다.
- [x]  Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다.
- [x]  Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용합니다.
- [x]  Queue 타입이 예상한대로 동작하는지 Unit Test를 통해 동작을 검증합니다.
- [x]  Queue에 구현해야 할 필수 기능
    - Enqueue, Dequeue, Clear, Peek, isEmpty

## 구현 내용

### 구조

```mermaid
classDiagram

class Queue {
	<<struct>>
  - head: Node<T>?
  - tail: Node<T>?
  + isEmpty: Bool
  + peek: T?
  + enqueue(data: T)
  + dequeue() -> T?
  + clear()
}

class Node {
  - data: T
  - next: Node<T>?
  + init(with data: T, next: Node?)
}

Queue --> Node: Nested Type
```

- 외부에서 Node를 임의로 생성하는 것을 막기 위해서 Node를 Queue 내부에 위치하도록 작성하였습니다.
    - 이를 위해 `Node`의 접근 제어자는 `private` , 그리고 Node 인스턴스인 `head` 와 `tail` 은 `private var` 로 선언하였습니다.

### 유닛 테스트

- isEmpty
    - test_queue_isEmpty: 큐가 비었을 때 nil을 반환하는지 확인하는 테스트
    - test_queue_isEmpty_false: 큐에 노드가 있을 때 false를 반환하는지 확인하는 테스트
- peek
    - test_peek_empty_return_nil: 큐가 비었을 때 nil을 반환하는지 확인하는 테스트
    - test_peek_return_1: 큐에 노드가 있을 때 제일 먼저 넣은 값을 반환하는지 확인하는 테스트
    - test_dequeue연산후_peek을_검사: 큐의 노드를 dequeue하고 현재 상황에서 제일 먼저 넣은 노드를 반환하는지 확인하는 테스트
- clear
    - test_celar_peek: 큐가 비어지는지(head와 tail만 갖는지) 확인하는 테스트
- enqueue
    - test_clear_enqueue: clear한 큐에 다시 enqueue를 해도 잘 되는지 확인하는 테스트
- dequeue
    - test_enqueue_dequeue: 무작위 값 여러개를 enqueue하고, dequeue한 값과 같은지 비교하는 테스트

<img width="709" alt="스크린샷 2023-10-31 오전 10 44 06" src="https://github.com/tasty-code/ios-bank-manager/assets/91656206/b4b16776-0cc5-4fe1-b30b-32531140b952">

2023-10-31 12:09 UTC, forestjae requested changes
Queue와 테스트 모두 잘 작성해 주셨습니다.

코멘트 확인 부탁드려요.

2023-10-31 12:09 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private class Node<T> {
Queue는 struct로, Node를 class로 정의하신 이유가 궁금해요

2023-10-31 12:09 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/BankManagerConsoleAppUnitTest.swift
> +            return
return 문을 타게 된다면 테스트의 결과는 어떻게될까요?

2023-10-31 12:09 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/BankManagerConsoleAppUnitTest.swift
> +    }
사용하지 않는 메서드는 삭제해주세요

2023-10-31 12:12 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/BankManagerConsoleAppUnitTest.swift
> +    }
이 테스트의 목적이 무엇인가요? 100번 반복하는 이유가 궁금합니다.

2023-11-01 00:54 UTC, KSK9820 commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/BankManagerConsoleAppUnitTest.swift
> +            return
return 문을 타게 된다면 테스트는 통과를 하게 됩니다. XCTAssertEqual을 실행하지 않고 return문으로 빠져나가기 때문에 틀렸다는 것을 검증할 기회조차 없기 때문입니다. 
제대로된 결과가 아니라 단순히 통과하는 테스트 값을 사용하는 대신, optional 추출을 하지 않고 바로 peek을 해서 검증을 하는 방식으로 수정하였습니다.

2023-11-01 00:58 UTC, KSK9820 commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/BankManagerConsoleAppUnitTest.swift
> +    }
모든 과정에서 enqueue, dequeue가 순차적으로 잘 이루어지는 지를 확인하기 위한 테스트 코드였습니다.
하지만 리뷰어님의 코멘트를 확인하고, 같은 과정을 100번 반복할 필요가 없다고 판단하였습니다. 
그래서 랜덤 인수를 하나만 뽑아 큐에 enqueue하고, dequeue한 결과값과 랜덤 인수가 같은지를 테스트하는 방식으로 수정하였습니다.

2023-11-01 00:58 UTC, KSK9820 commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/BankManagerConsoleAppUnitTest.swift
> +    }
해당 부분 수정하였습니다.

2023-11-01 01:27 UTC, KSK9820 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private class Node<T> {
Node의 next 변수에는 다음 노드의 인스턴스를 참조하는 메모리 주소가 담기기 때문에 class로 정의하였습니다.
Queue를 Struct로 정의한 이유는 Queue가 복사가 일어났을 때 Class 타입이라면 하나의 주소를 여러개의 변수에서 공유하게 됩니다. 그렇기 때문에 각 변수가 각각의 주소를 가지는 struct로 구현하였습니다.

2023-11-01 05:54 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/BankManagerConsoleAppUnitTest.swift
> +            return
xctfail이라는 메서드도 찾아보세요~

2023-11-01 05:54 UTC, merged