은행창구 관리앱 [Step2] 뉴준성,Howard
tasty-code/ios-bank-manager pull request #37
Opened 2023-11-02 01:14 UTC by JEON-Sungsu

리뷰어 : @zdodev
버드 : @newJunsung, @JEON-Sungsu

# Step2 명세서

- 은행에는 n명의 은행원이 근무합니다.
- 은행에는 n명의 고객이 업무처리를 위해 대기합니다.
    - 고객의 대기열은 Step 1에서 구현한 Queue 타입을 활용합니다.
- 모든 고객의 업무가 끝나면 은행업무를 마감합니다.
- 업무를 마감할 때 "업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 XX명이며, 총 업무시간은 XX초입니다."라고 출력합니다.
- 은행원은 고객의 업무를 처리합니다.
- 각 고객의 업무를 처리하는 데 걸리는 시간은 0.7초입니다.
- 은행원이 한 번에 처리할 수 있는 고객은 한 명입니다.
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다.
    - "3번 고객 업무 시작"
- 고객의 업무를 처리하면 아래와 같이 출력합니다.
    - "5번 고객 업무 완료"
- 은행/고객 타입 외에 필요한 타입이 있다면 자유롭게 구현합니다

### **콘솔앱 구현**

- Step 2의 은행에는 한 명의 은행원이 근무합니다.
- 은행원은 한 번에 한 명의 고객의 업무를 처리할 수 있습니다.
- 앱을 실행하면 두 개의 메뉴를 출력합니다.
- `1 : 은행 개점
 2 : 종료`
- 사용자가 1을 입력하면 은행을 개점하고 10명~30명의 고객이 방문합니다. 10~30 사이의 임의의 수 만큼의 고객의 업무를 처리하면 은행문이 닫히고 다시 메뉴를 출력합니다.
- 사용자가 2를 입력하면 프로그램을 종료합니다.

## 프로그램 동작 화면
![bank-step2](https://github.com/tasty-code/ios-bank-manager/assets/63297236/e008c40c-c71d-4d72-a961-1a9e267ab4f4)

## 코드 설명

- Bankable.swift
    
    ```swift
    protocol Bankable: AnyObject {
        var bankClerk: Int { get }
        var processingTime: Double { get }
        
        func taskBegin(customerCount: Int) -> (taskProcessingTime: Double, handledCustomer: Int)
    }
    ```
    
    프로토콜을 활용해서 Bank의 추상화를 진행해봤습니다. 은행마다 은행원의 수와 업무 처리시간이 반드시 필요하지만, 은행마다 수와 처리시간이 다를 수 있기 때문에 프로토콜의 프로퍼티로 넣어줬습니다. 또한 은행마다 업무 처리 방식이 다를 수 있기 때문에, 이 또한 프로토콜의 함수로 넣어줬습니다.
    
    또한 Bankable 프로토콜에 AnyObject를 채택한 이유는 각 은행은 독립적이어야 하기 때문에 Bank를 클래스로 만들어야한다는 생각이 들었습니다. 따라서 클래스만 Bankable 프로토콜을 채택할 수 있게 AnyObject를 채택했습니다.
    

- Bank.swift
    
    ```swift
    class Bank: Bankable {
        ///...
    
        func taskBegin(customerCount: Int) -> (taskProcessingTime: Double, handledCustomer: Int) {
            configureQueue(customerCount: customerCount)
            
            var taskProcessingTime: Double = 0
            var handledCustomer = 0
            
            while !customerQueue.isEmpty {
                guard let customer = customerQueue.dequeue() else {
                    break
                }
                
                print(BankDialogue.start(customer))
                taskProcessingTime += processingTime
                Thread.sleep(forTimeInterval: processingTime)
                print(BankDialogue.finish(customer))
                handledCustomer += 1
            }
            
            clearQueue()
            
            return (taskProcessingTime, handledCustomer)
        }
        
      ///...
        
        private func clearQueue() {
            customerQueue.clear()
        }
    }
    ```
    
    - Thread.sleep메소드를 사용하여 프린트 출력시간을 조절해서 실제 업무가 그만큼의 시간이 소요되게끔 보이게 만들어 주었습니다.
    - Queue의 clear 메소드를 통해 혹시 업무종료 이후에도 남아있을 수 도 있는 노드들을 제거해주도록 하였습니다.

2023-11-03 02:36 UTC, zdodev requested changes
안녕하세요. @newJunsung , @JEON-Sungsu !

Step2 구현 잘해주셨습니다👍
기능명세에 따라 잘 구현해보셨네요!

몇 가지 궁금증을 남겨보았습니다.
간단히 확인해보고 넘어가면 좋을 것 같습니다~🙂

2023-11-03 02:36 UTC, zdodev commented on BankManager.swift
> +class BankManager {
`final` 키워드를 사용해보는 것은 어떨까요? `final` 에 대해서 알아보면 좋을 것 같습니다!🙂

2023-11-03 02:36 UTC, zdodev commented on BankManager.swift
> +    func businessStart() {
메서드 이름을 동사형으로 시작하는 것은 어떨까요?

2023-11-03 02:36 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +struct Customer: CustomStringConvertible {
`CustomStringConvertible` 프로토콜을 채택해보셨네요.👍

2023-11-03 02:36 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/BankDialogue.swift
> +enum BankDialogue: CustomStringConvertible {
출력문 문자열 관리를 위한 `BankDialogue` 타입을 구현해보셨네요.👍

2023-11-03 02:36 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bankable.swift
> +    func taskBegin(customerCount: Int) -> (taskProcessingTime: Double, handledCustomer: Int)
메서드 이름을 동사형으로 시작하는 것은 어떨까요?

2023-11-03 04:19 UTC, newJunsung commented on BankManager.swift
> +    func startBusiness() {
동사를 먼저 앞에 두어 동사형으로 만들었습니다.

2023-11-03 04:20 UTC, newJunsung commented on BankManagerConsoleApp/BankManagerConsoleApp/Bankable.swift
> +    func beginTask(customerCount: Int) -> (taskProcessingTime: Double, handledCustomer: Int)
동사를 먼저 앞에 두어 동사형으로 만들었습니다.

2023-11-03 04:20 UTC, JEON-Sungsu commented on BankManager.swift
> +final class BankManager {
final 키워드 추가하였습니다!

2023-11-03 04:26 UTC, newJunsung commented on BankManager.swift
> +final class BankManager {
final이 상속을 방지하는 역할 뿐만이 아니라, 정적 디스패치를 가능하게도 해줍니다.
정적 디스패치를 통해 해당 함수를 `@inlinable` 등을 통해 최적화도 할 수 있다는 사실을 알게 되었습니다.

2023-11-05 12:47 UTC, zdodev approved these changes
안녕하세요. @newJunsung , @JEON-Sungsu !

Step 2 개선을 잘 진행해보셨네요!
새로운 키워드를 적용해보신 것과 그것에 대한 내용을 적어주신점이 좋았습니다!👍

이번 스텝은 여기서 마무리짓도록 하겠습니다!🎉

2023-11-05 12:47 UTC, merged