[STEP1] 도도, 우노
tasty-code/ios-bank-manager pull request #4
Opened 2022-10-13 02:55 UTC by dddowon

## 구현한 내용
- Node 타입 구현
- Linked-List 타입 구현
- Queue 타입 구현
- Unit Test 작성

## 고민한 내용

1. Queue 타입 구현을 위해 Linked-List를 구현하기 때문에 Queue와 같은 FIFO 방식으로 이루어 질 거 같아 `removeFirst` 메서드를 만들었는데 저희가 알고 있는 Linked-List는 FIFO나 LIFO 방식에 어떠한 방식으로도 속하지 않는다고 생각했기에 `removeLast` 메서드를 작성할지 Queue의 특성인 FIFO 방식을 따라 `removeFirst` 메서드를 작성해야 하는지 고민했습니다. 이에 대한 정확한 개념을 알고 싶습니다!
2. Queue 타입의 `dequeue`를 구현할 때에 Linked-List에서 `removeFirst` 메서드가 `dequeue` 부분에 해당한다고 생각했기에 swift의 내장 함수 `removeFrist` 처럼 지우면서 반환 값을 가지는 메서드를 만들어야 한다고 생각했습니다. 또 이 프로젝트에서 요구하는 기능 중 `peek`이라는 기능이 언제 사용되는지 궁금했는데 저희는 이 `peek`을 어떻게 활용할지 생각하다가 Linked-List에서는 `removeFirst`와 `peek`를 만들고 `dequeue`에 `removeFirst`와 `peek` 기능을 넣어 구현하게되었습니다. 이 방식을 고민했기에 잼킹이 의도한 방법은 무엇인지 궁금합니다!

2022-10-13 08:02 UTC, jaemuYeo requested changes
도도 우노 고생하셨습니다!!
계산기 프로젝트를 하며 타입은 금방 설계할것같았는데
막상 List를 활용해서 구현하려니 머리가 복잡해지죠?? ><
그래도 너무 잘 구현해주었어요~

코드를 통해 코멘트 남겨놓았으니 반영할 부분이 있으면 반영 후 재요청 부탁해요~

## 질문내용

1. 넵!! 지금처럼 removeFirst를 구현해주면 됩니다! 잘하셨어요 👍
remove한 값을 반환해주지 않고 정말로 지우기만 하고있어요~

2. 현재 큐타입에 구현한 것들을 내부적으로 전부 이용할 필요는 없습니다!
코드에도 남겨두었지만 peek은 나중에 쓸일이 있을테니
현재는 코멘트대로 진행해주시면 됩니다!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +class LinkedList<T> {
LinkedList가 클래스로 선언된 이유는 무엇인가요??

클래스로 해야한다면 `final class`에 대해서도 알아보세요!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    private var head: Node<T>?
은닉화 좋아요 👍

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    var isEmptyReturnTrue: Bool {
반환이 true가 될지 false가 될지는 큐에 값이 있는지 없는지에 대해 정해지는데
네이밍은 true만을 위한 것같아요!!
단순하게 isEmpty만으로도 충분한 네이밍 같습니다 🙂

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    func returnFirstValue() -> T? {
해당 메서드 또한 연산 프로퍼티로 구현해도 될거같아요!
단순히 peek을 통해 헤드의 데이터를 받아오는 것 이기때문에
```swift
var first: T? {
    head?.data
}
위와 같은 형태로 간결하게 표현해도 좋을 것같습니다!
```

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    func append(data: T?) {
removeFirst와 같은 네이밍 처럼 현재 메서드도 마지막에 값을 넣는 것이기때문에
`addLast`와 같은 네이밍은 어떤가요??
해당 매개변수의 T타입이 옵셔널이어야 할까요??
큐에서 인큐할때 nil을 넣을 것 같지는 않아요!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        if head == nil || tail == nil {
isEmpty를 활용해보세요!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +            head = Node.init(data: data)
Node.init(data: data) 부분을 Node(data: data) 이렇게 줄여도 된답니다!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        let newNode = Node.init(data: data)
해당 부분에서 prev 없이도 구현해볼 수 있지 않을까요??

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    func removeFirst() {
해당 메서드는 인큐값을 반환해주어야 할 것같아요!
현재는 반환 타입이 없군요~

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        if head == nil || tail == nil { return }
여기서도 isEmpty를 활용해보세요!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        return
반환 타입이 없는데 return 키워드를 붙인 이유는 무엇인가요?

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Node.swift
> +    var prev: Node?
prev 프로퍼티도 사용하셨군요!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Node.swift
> +    var data: T?
data 타입은 옵셔널 타입이어야 할까요?? 🤔

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Queue.swift
> +    private var queue: LinkedList<T> = LinkedList<T>()
이런 경우 타입을 명시하지 않고
`private var queue = LinkedList<T>()` 요렇게 간결하게 표현해주어도 됩니다!

list타입인데 queue로 네이밍 한 이유가 있나요??

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Queue.swift
> +        let returnValue = peek
큐의 특징인 선입선출에 따라 맨 앞의 값을 뽑아내면 되는데
peek을 통해 리턴값은 준 이유는 무엇인가요??

단순히 queue.removeFirst()만으로도 맨 앞의 값을 뺄수있을 거같아요!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +    var list = LinkedList<Int>()
만약 리스타 타입과 큐타입을 테스트한다면 파일을 따로 분리해서 테스트하는 것을 추천드려요!
다만 큐가 정상적으로 동작한다면 프로젝트 요구사항대로 큐타입에 대해서만 테스트 진행해주어도 좋을 거같습니다!

2022-10-13 08:02 UTC, jaemuYeo commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +    func test_LinkedList테스트() {
테스트 케이스를 잘 진행해주었군요!!
예전에도 한번 전달한적 있는 given when then 패턴에 대해 알고계신가요?
unit test를 진행할때 해당 패턴으로 진행하는 방향을 추천드립니다!
네이밍도 참고해보세요!

```swift
func test_list에_3과4를넣었을때_리스트의첫번째값은_3이다 {
// given

// when

// then
}
```

2022-10-14 03:03 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    private var head: Node<T>?
넵

2022-10-14 03:05 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    var isEmptyReturnTrue: Bool {
넵 반영하겠습니다!

2022-10-14 03:06 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    func returnFirstValue() -> T? {
좋은 것 같습니다!

2022-10-14 04:45 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +class LinkedList<T> {
Queue타입이 LinkedList를 인스턴스로 사용할때 LinkedList의 값을 변경하면서 사용한다고 생각했기에 class로 선언한것 이였습니다. 하지만 class로 선언하여 여러곳에서 참조하게되면 메모리관리에 문제가 생길 수 있기에 LinkedList는 Queue타입에서만 사용할 수 있도록 final class를 적용하는것이 좋을것 같습니다!

2022-10-14 04:48 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    func append(data: T?) {
반영해보겠습니다!

2022-10-14 04:48 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        if head == nil || tail == nil {
넵

2022-10-14 04:48 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +            head = Node.init(data: data)
넵 반영하겠습니다!

2022-10-14 04:50 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        let newNode = Node.init(data: data)
음 한번 고민해보고 반영하겠습니다!

2022-10-14 04:50 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        if head == nil || tail == nil { return }
넵 반영하겠습니다!

2022-10-14 04:54 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        let newNode = Node.init(data: data)
코드를 이해해보니 prev 부분을 없애도 될거 같네요

2022-10-14 05:12 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        return
그러네요!

2022-10-14 05:12 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Node.swift
> +    var prev: Node?
😎

2022-10-14 05:13 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Node.swift
> +    var prev: Node?
네 양방향 링크드리스트가 데이터 값을 찾기에 더욱 수월할 거 같아서 prev도 사용했습니다!

2022-10-14 05:13 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Node.swift
> +    var data: T?
옵셔널값이 올필요는 없겠네요! 반영하겠습니다

2022-10-14 05:16 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Queue.swift
> +    private var queue: LinkedList<T> = LinkedList<T>()
저희는 queue에서 사용하기에 queue로 네이밍을 했는데 list타입이기때문에 list가 들어가는 네이밍이 좋겠네요!

2022-10-14 05:17 UTC, dddowon commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +    var list = LinkedList<Int>()
참고하겠습니다!

2022-10-14 05:18 UTC, dddowon commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +    func test_LinkedList테스트() {
참고해보겠습니다!

2022-10-14 05:19 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +    func removeFirst() {
넵 구현했습니다

2022-10-14 05:20 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/Queue.swift
> +        let returnValue = peek
저희가 생각한 바로는 peek에 기능이 첫번째 값을 지우지 않고 반환하는 것이기에 어떤 상황에 사용할지 고민을 하다가, removeFirst메서드는 반환을 하지 않고 지우기만 하는 방향으로 작성한 뒤에 dequeue에서 peek를 같이 사용하여 반환하는것과 지우는 기능을 따로 넣어 사용하였는데, 현재는 removeFirst메서드에 반환하는 기능을 넣어주어 peek와 dequeue를 따로 분리하게끔 처리해 주었습니다!

2022-10-14 06:07 UTC, jaemuYeo reviewed
도도 우노 스텝1 고생하셨습니다!!
열심히 토의하며 진행하는 모습 너무 보기좋아요 ㅎㅎ 👍
다음 스텝도 기대하겠습니다~~

2022-10-14 06:07 UTC, merged