은행 창구 관리 앱 [Step2] 록스, 재닌
tasty-code/ios-bank-manager pull request #40
Opened 2023-11-02 11:56 UTC by KimRoks

리뷰어: @jungseungyeo
버드: @janine-kang, @KimRoks

린생, 안녕하세요!

지난 STEP1의 피드백을 포함한 STEP2의 구현을 완료하여

아래와 같이 STEP2의 PR 요청드립니다! 🙌🏻

잘부탁드립니다 🔥

# Summary

STEP2 연결리스트를 활용한 콘솔앱 구현 

## 구현 사항

- [x]  Queueu의 활용
- [x]  타입 추상화 및 일반화

## 주요 고려 사항

- 객체의 동작을 주요 관점으로 추상화
- OCP를 고려한 DispatchQueue 구현
- 비동기 작업의 효율적 관리를 위한 DisPatchGroup()의 선택적 활용

## 궁금한 점

- 이번 STEP을 진행하면서, 행원 자체를 스레드로 간주하고 별도의 행원 모델을 정의하지 않았습니다. 이로 인해, 이번 스텝에서 행원이 1명인 경우를 처리하기 위해 Serial Queue를 사용하고, 이를 커스텀화하여 async로 작업을 진행했습니다
    
    디스패치 그룹 또는 디스패치 세마포어를 사용하지 않은 채로 async의 진행 완료 시점을 확인해보려고 여러 방법들을 사용해봤는데 결국 원하는 결과를 얻지 못했습니다
    
    결론적으로 저희가 원했던 구현은 비동기의 동기처리였는데요
    
    async/await 키워드를 사용하여 문제를 해결하려고 시도했지만, 이 키워드는 상대적으로 새로 도입되었으며 사용법이 다소 복잡하다고 판단되어 포기하였습니다.
    
    그래서 여쭤보고싶은 부분은 
    

1. 현재 현업에서는 async/await 키워드의 syntax적 복잡함을 감안하고서라도 많이 사용하는 편인가요?
2. Dispatch Group을 사용하지 않고도 completion handler를 통해 원하는 serial queue의 async 작업을 동기적으로 처리할 수 있는 방법이 있을까요?

- 구현과정에서 이중 While문을 사용하게 되었습니다 해당 코드는 어쩌면 코드의 복잡성을 증가시키고 가독성을 해칠 수 있다는 생각이 들었습니다

1. 중첩된 While문은 중첩된 for문, 중첩된 if문과 같이 가독성 측면에서 불리하다고 생각하시나요?
2. 중첩된 While루프를 줄이고 코드를 더 명확하게 만들기 위한 다른 구현 방법이 있었을까요?

이에 대한 린생의 의견이 궁금합니다!

2023-11-03 11:34 UTC, jungseungyeo requested changes
@janine-kang, @KimRoks 고생하셨습니다. 

질문 답변

1.현재 현업에서는 async/await 키워드의 syntax적 복잡함을 감안하고서라도 많이 사용하는 편인가요?

`개인적인 생각은 필요하면 쓰고 필요없으면 쓰고 그런거라고 생각을 하고 있습니다. 저희 회사에서도 async/await를 많이 사용하고 있습니다. 사용하고 생각은 알겠지만 이번 프로젝트에서 Dispatch Group 로 구현이 아직 익숙하지 않으거 같아요.  GCD가 먼저 익숙해 진 다음 사용하는 방법이 좋을거같다는 생각이 좀 드네요. 그래도 명확히 순서는 없어서 꼭 해라마라 할 수 없지만 제 의견은 GCD부터 알고 쓰면 좋을거같네요.`

2.Dispatch Group을 사용하지 않고도 completion handler를 통해 원하는 serial queue의 async 작업을 동기적으로 처리할 수 있는 방법이 있을까요?

`completion handler 를 하기 위해서는 일(Task)객체를 만들고 업무를 직원에게 할당 하고 콜백을 주는 형태로 queue읭 dequeue하여 사용하는 형태로 구현하면 될거같아요. 흠.. 글로 설명하기는 어렵고 코드는 여기서 바로 짜기에는 좀 많은 내용인거같네요. 그래도 글로 좀 더 자세히 설명하자면, 업무라는 객체가 일을 은행원에게 주면 은행원이 일을 처리하합니다. 업무가 끝나면 completion handler 롤 통해 은행원에게 이벤트를 전달하고 은행원은 업무가 끝나면 queue쌓여있는 업무(task)를 가지고 오는 구조를 하면 될 거같아요. 전역 변수에 업무가 queue로 존재하고 은행원이 콜백을 하는 형식으로 업무를 처리하면 될거같네요.. ㅎㅎ.. 잘 설명이 된 건지 모르겠네요 ㅠ`

while문 질문

1.중첩된 While문은 중첩된 for문, 중첩된 if문과 같이 가독성 측면에서 불리하다고 생각하시나요?
`가능하다면 분리하면 좋습니다. 중첩된 while문은 시간복잡도에서 n제곱을 가지게 되어서 좋지 않습니다.  저희 경우 라면 처음 시작 하는 부분의 while문을 없애고 Bank.open() { [weak self] in self?.run() }와 같이 재귀를 사용하는 방법도 고려할거같아요.`

2.중첩된 While루프를 줄이고 코드를 더 명확하게 만들기 위한 다른 구현 방법이 있었을까요?
`중접된 while의 문제를 해결하는 방법이 좋은거 같아요. 일을 실행하는 중첩 while문이 문제가 크게 없어 보여 어디를 개선하면 좋을지 나오지는 않지만 중첩 반복문을 없애기 위해서는 위 1번에서 제시한 방법이 좋은거같아요 ㅎㅎ`

조금 수정이 필요한 부분이 보여요 코멘트 보시고 수정부탁드립니다.

2023-11-03 11:34 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Controllers/BankManager.swift
> +                switch userInput {
userInput의 대한 값을 enum 화 하면 좋을거같아요. enum으로 정의를 하여 switch문을 작성하면 default값이 생략되어서 좋고
혹시 다른 동작이 추가 되더라도 default가 없기 때문에 오류를 잡을 수 있습니다.

2023-11-03 11:34 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Controllers/BankManager.swift
> +    private var isRunning: Bool = false
isRundding이 없고 2번인 경우 return으로 빠져나오는 건 어떤가요? isRunning값이 다른 곳에서 변경이 될수도 있을거같네요.

2023-11-03 11:34 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private func lineUpCustomer() {
private으로 외부에 노출안해도 되는 함수는 은닉화를 잘하신거같아요 ㅎㅎ

2023-11-03 11:34 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        sleep(UInt32(0.7))
이렇게 작성되면 0으로 동작될거같아요. 0.7로 동작되게 수정해주세요.
Int는 0, 1, 2로 되어서 소수점을 표현할수가 없습니다. ㅠ

2023-11-03 11:34 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankManagerConsoleAppTest.swift
>          XCTAssertTrue(sut.isEmpty)
모든 test코드는 give when then 패턴을 가지고 있어야 합니다.
또 함수명을 정확히 끝내주세요.

2023-11-03 11:34 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        entranceCount = numberOfCustomer
고객의 수를 받는 것은 좋은데 고객이 Int가 아닌 모델로 변경하여 가지고 있는 형태는 어떤가요? 
꼭 변경 할 필요는 없긴한데 의견이 궁금합니다.

2023-11-03 11:34 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        let group = DispatchGroup()
질문: DispatchGroup, DispatchQueue은 무엇인가요?

2023-11-06 01:08 UTC, KimRoks commented on BankManagerConsoleApp/BankManagerConsoleApp/Controllers/BankManager.swift
> +    private var isRunning: Bool = false
이중 while문을 재귀함수로 대체하고 isRunning 또한 삭제 조치하였습니다!

2023-11-06 01:25 UTC, KimRoks commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankManagerConsoleAppTest.swift
>          XCTAssertTrue(sut.isEmpty)
테스트 케이스의 네이밍을 더 명확한 의미전달이 되도록 변경하였습니다

2023-11-06 02:43 UTC, janine-kang commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        sleep(UInt32(0.7))
아하 그렇네요! Int라고 쓰여진 부분 보고 알아차렸어야 했는데 😅 이 부분 usleep() 이용하여 변경했습니다 !

2023-11-06 05:47 UTC, KimRoks commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        let group = DispatchGroup()
DispatchQueue는 동시성 프로그래밍을 위한 GCD의 기능 중 하나로 FIFO로 작동합니다
Serial/Concurrent, sync/async등을 설정해줄 수 있습니다
DispatchGroup을 통해 이러한 작업들을 그룹지어서 판단할 수 있는 도구이며,
두 개념의 가장 큰 차이점은 묶여진 작업들간의 상태를 추적 가능 여부입니다.

2023-11-06 06:56 UTC, janine-kang commented on BankManagerConsoleApp/BankManagerConsoleApp/Controllers/BankManager.swift
> +                switch userInput {
```
func launch() {
        print(Prompt.appLaunch, terminator: " ")
        if let userInput = readLine() {
            switch Menu(rawValue: userInput) {
            case .onGoing:
                bank.open(with: numberOfCustomer)
                launch()
                
            case .finished:
                return
                
            default:
                return 
            }
        }
    }
```
```
enum Menu: String {
    case onGoing = "1"
    case finished = "2"
}
```

이 부분에 실행과 종료에 대한 enum을 추가했습니다!
다만, userInput으로 들어오는 모든 String을 하나의 enum에서 처리할 수 없어 default 값을 사용하게 되었습니다 🥲 혹시 default값이 생략될 수 있으려면 어떻게 처리해야하는 지 알 수 있을까요?

2023-11-06 07:01 UTC, janine-kang commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        entranceCount = numberOfCustomer
이 부분은 다음 STEP을 진행하면서 변경 가능성이 있다고 생각하여 우선은 남겨두었습니다.
고객의 수를 넘기게 된 이유는 방문할 고객의 수를 정의하는 역할이 Bank 타입에게 적합하지 않다고 생각하였기 때문인데요.
다시 생각해보니 Bank 내에서 고객의 수를 넘겨받은 후 진행되는 Customer 생성 과정이 있는게 위에서 말한 Bank의 역할에 맞지 않는 것 같다고 판단이 되네요! 특히 확장성을 생각해보면 구조상의 결함이 맞는 것 같습니다 ^^; 이 부분은 다음 스텝 진행하면서 좀 더 고민해보도록 하겠습니다!

2023-11-06 07:03 UTC, janine-kang commented
> 고생하셨습니다.
> 
> 질문 답변
> 
> 1.현재 현업에서는 async/await 키워드의 syntax적 복잡함을 감안하고서라도 많이 사용하는 편인가요?
> 
> `개인적인 생각은 필요하면 쓰고 필요없으면 쓰고 그런거라고 생각을 하고 있습니다. 저희 회사에서도 async/await를 많이 사용하고 있습니다. 사용하고 생각은 알겠지만 이번 프로젝트에서 Dispatch Group 로 구현이 아직 익숙하지 않으거 같아요. GCD가 먼저 익숙해 진 다음 사용하는 방법이 좋을거같다는 생각이 좀 드네요. 그래도 명확히 순서는 없어서 꼭 해라마라 할 수 없지만 제 의견은 GCD부터 알고 쓰면 좋을거같네요.`
> 
> 2.Dispatch Group을 사용하지 않고도 completion handler를 통해 원하는 serial queue의 async 작업을 동기적으로 처리할 수 있는 방법이 있을까요?
> 
> `completion handler 를 하기 위해서는 일(Task)객체를 만들고 업무를 직원에게 할당 하고 콜백을 주는 형태로 queue읭 dequeue하여 사용하는 형태로 구현하면 될거같아요. 흠.. 글로 설명하기는 어렵고 코드는 여기서 바로 짜기에는 좀 많은 내용인거같네요. 그래도 글로 좀 더 자세히 설명하자면, 업무라는 객체가 일을 은행원에게 주면 은행원이 일을 처리하합니다. 업무가 끝나면 completion handler 롤 통해 은행원에게 이벤트를 전달하고 은행원은 업무가 끝나면 queue쌓여있는 업무(task)를 가지고 오는 구조를 하면 될 거같아요. 전역 변수에 업무가 queue로 존재하고 은행원이 콜백을 하는 형식으로 업무를 처리하면 될거같네요.. ㅎㅎ.. 잘 설명이 된 건지 모르겠네요 ㅠ`
> 
> while문 질문
> 
> 1.중첩된 While문은 중첩된 for문, 중첩된 if문과 같이 가독성 측면에서 불리하다고 생각하시나요? `가능하다면 분리하면 좋습니다. 중첩된 while문은 시간복잡도에서 n제곱을 가지게 되어서 좋지 않습니다. 저희 경우 라면 처음 시작 하는 부분의 while문을 없애고 Bank.open() { [weak self] in self?.run() }와 같이 재귀를 사용하는 방법도 고려할거같아요.`
> 
> 2.중첩된 While루프를 줄이고 코드를 더 명확하게 만들기 위한 다른 구현 방법이 있었을까요? `중접된 while의 문제를 해결하는 방법이 좋은거 같아요. 일을 실행하는 중첩 while문이 문제가 크게 없어 보여 어디를 개선하면 좋을지 나오지는 않지만 중첩 반복문을 없애기 위해서는 위 1번에서 제시한 방법이 좋은거같아요 ㅎㅎ`
> 
> 조금 수정이 필요한 부분이 보여요 코멘트 보시고 수정부탁드립니다.

2번에 대해서 구현 설명해주신 부분은, 말씀해주신대로 아직 GCD나 async/await 자체에 대한 연습이 더 필요한 것 같아 프로젝트를 끝내고 나서 좀 더 알아보고 연습해보도록 하겠습니다 🙇🏻‍♀️ 감사해요 린생!

2023-11-06 13:56 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Controllers/BankManager.swift
> +                switch userInput {
```
    func launch() {
        print(Prompt.appLaunch, terminator: " ")
        if let userInput = readLine(), let menu = Menu(rawValue: userInput) {
            switch menu {
            case .onGoing:
                bank.open(with: numberOfCustomer)
                launch()
                
            case .finished:
                return

            }
        }
    }
```
위와 같이 Menu를 init?(rawValue: String)으로되어 있어서 옵셔널 바인딩을 통해서 menu 값을 가져온다면 default는 없어질수있어요 ㅎㅎ

2023-11-06 13:56 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Controllers/BankManager.swift
> +    private var isRunning: Bool = false
좋습니다 ㅎㅎ

2023-11-06 13:56 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Controllers/BankManager.swift
> +    private var isRunning: Bool = false
앞으로 수정한 commit 링크도 포함하면 더욱 좋을거같아요 ㅎㅎ

2023-11-06 13:57 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        entranceCount = numberOfCustomer
좋습니다 ㅎㅎ 다음 스텝에서 기대하고 있겠습니다 :)

2023-11-06 14:00 UTC, jungseungyeo commented
고생하셨습니다 다음 스텝 진행해도 좋을거같습니다.

제가 의견드렸던 Bank 모델을 다음 스텝에서 진행 부탁드립니다 :) 
감사합니다.

2023-11-06 14:00 UTC, jungseungyeo approved these changes

2023-11-06 14:01 UTC, merged