은행 창구 관리 앱 [Step2] 요한, 망고, 밤삭
tasty-code/ios-bank-manager pull request #43
Opened 2023-11-03 08:32 UTC by Dongjun-developer

# 은행창구 관리 앱

리뷰어: @jryoun1
## 팀원:busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/Dongjun-developer"><img src="https://avatars.githubusercontent.com/u/97822621?v=4" width="90" height="90"></a> | <a href="https://github.com/bamsak"><img src="https://avatars.githubusercontent.com/u/114239407?v=4" width=90></a> | <a href="https://github.com/dpwns1234"><img src="https://avatars.githubusercontent.com/u/52391722?v=4" width=90></a> |
| ---- | ---------- | --------- | --------- |
| in Github | [@DongJun](https://github.com/Dongjun-developer) | [@bamsak](https://github.com/bamsak) | [@dpwns1234](https://github.com/dpwns1234) |
| in SeSAC | 망고 | 밤삭 | 요한 |

안녕하세요 제이크!
은행창구 관리 앱 STEP2 PR 보냅니다. 잘 부탁드립니다-!!

## 파일구조:file_folder:
- BankManagerConsoleApp
- Model
    -  BankManager.swift
    -  Bank.swift
    -  Client.swift
- Utility
    - Queue.swift
    - Script.swift
- main.swift
- BankManagerConsoleAppTests
    - BankManagerConsoleApp.swift

## 프로젝트 진행 과정
- **DispatchSemaphore** / **DispatchGroup**을 사용한 이유와 역할
    - Semaphore를 사용해 고객의 업무 처리의 접근할 수 있는 스레드의 수를 제한할 수 있었습니다. 저희는 이 스레드의 수를 은행원의 수로 생각하여 다음과 같이 구현하였습니다.
    ```swift
        init(_ clerkCount: Int) {
            self.semaphore = DispatchSemaphore(value: clerkCount)
        }

        ...

         while self.clientQueue.isEmpty == false {
                self.semaphore.wait()
                guard let client = self.clientQueue.dequeue() else { return }
                DispatchQueue.global().async(group: group) {
                    self.task(for: client)
                    self.semaphore.signal()
                }
            }
    ```
    위의 코드와 같이 semaphore.wait() / semaphore.signal() 을 통해 `DispatchQueue.global().async()`를 사용하더라도 스레드가 미리 제한한 수만큼만 코드에 접근할 수 있기 때문에 은행원의 수를 제한한 코드를 구현할 수 있었습니다.
    
    - DispatchGroup을 사용해 다른 스레드에서 실행중인 고객의 업무를 기다리고, 마감 메세지를 순서에 맞게 출력할 수 있었습니다.
    ```swift
        let group = DispatchGroup()
        
        while self.clientQueue.isEmpty == false {
            ...
            DispatchQueue.global().async(group: group) {
                self.task(for: client)
                self.semaphore.signal()
            }
        }
        
        group.wait()
    ```

    DispatchQueue.global().async(**group: group**)을 통해 고객의 업무를 처리하는 스레드를 한 group으로 그룹핑해주고, clientQueue가 비어서 while문을 빠져 나와도 `group.wait()`를 통해서 모든 스레드가 고객 업무를 처리할 때까지 기다려줄 수 있었습니다.
    
    

## 프로젝트 하면서 고민한 점

- **현재 Bank를 구조체로 구현 하였는데 구조체로 구현한 이유**

    - 내부에 프로퍼티를 `BankManager`만을 가지고 사실상 `BankManager의 메소드`와, `자체 메소드`만을 사용하기 때문에 `static Dispatch`로 성능상 이점을 가지게 될 것 같았습니다.
    또한, Bank 내부에 다른 프로퍼티들을 가지고 그 프로퍼티의 값을 자주 변경해주는 경우가 없어서 struct로 구현하였습니다.

다음과 같은 이유로 구조체로 구현하였는데 struct와 class를 사용함에 있어서 저희의 접근이 맞는지 제이크의 의견을 여쭙고 싶습니다.

2023-11-06 13:45 UTC, jryoun1 requested changes
step2 고생하셨습니다 👏 💯 
DispatchQueue, DispatchGroup, DispatchSemaphore까지 사용해 보시다니 대단합니다 👍 
대부분 잘 구현해주신 것 같아요.

다만 아직 각 객체들의 역할이 명확하지 않은 것 같아서 관련해서 코멘트를 남겨두었습니다! 🙏 
세 분이서 생각하신 각 객체들의 역할과 그 역할에 따른 프로퍼티, 함수를 잘 가지고 있는지 확인부탁드려요! 

<img width="300" alt="image" src="https://github.com/tasty-code/ios-bank-manager/assets/45090197/73f1a8d4-8d9d-4ba3-b0b5-326219fa630d">

⚠️ ⚠️  또한 프로젝트 규칙이 팀원들이 커밋을 번갈아가면서 작업을 해야하는 것으로 알고 있는데, 
지금 commit을 봤을 때는 한 분만 보내고 계신것 같아서 이 부분도 앞으로의 수정 작업 및 다음 step 작업에서 지켜주세요!!  

### 고민한점

> 현재 Bank를 구조체로 구현 하였는데 구조체로 구현한 이유
내부에 프로퍼티를 BankManager만을 가지고 사실상 BankManager의 메소드와, 자체 메소드만을 사용하기 때문에 static Dispatch로 성능상 이점을 가지게 될 것 같았습니다.
또한, Bank 내부에 다른 프로퍼티들을 가지고 그 프로퍼티의 값을 자주 변경해주는 경우가 없어서 struct로 구현하였습니다.
다음과 같은 이유로 구조체로 구현하였는데 struct와 class를 사용함에 있어서 저희의 접근이 맞는지 제이크의 의견을 여쭙고 싶습니다.

넵 말씀해주신 것처럼 내부에서의 값들의 변경에 대해서 참조를 통해서 트래킹할 필요가 없다면 struct를 사용하는 것이 성능상에 이점이 있을 수도 있을 것 같네요.

다만 struct 내부에 reference 객체를 포함한다면 struct 내에서 referenece를 하는 개수 만큼 결국 reference count에 비용을 지불해야하기에 크게 performance 적으로 장점이 되지 않을 수 있습니다!
관련해서는 [WWDC2016: Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/)를 확인해보시면 좋을 것 같아요!

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
은행이 은행원의 수를 주입받는 것 좋네요! 
여기서 은행이 은행원 자체도 주입을 받는 것은 어떨까요? 
예를 들면 은행원이 수행해야하는 역할들을 protocol로 추상화하고, 그 추상화된 protocol을 구체화한 객체를 외부에서 생성해서 주입해보는 방식을 통해서 Bank 객체가 BankManager 객체 자체를 몰라도 되면 의존성이 더 잘 분리될 것 같네요.

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        }
유저의 입력을 받아서 처리하는 부분이 bank의 역할이 적절할까요?  
세 분이 생각하시는 bank의 역할은 어떤 것일까요? 🙋‍♂️

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
위의 코멘트와 비슷한 맥락입니다!
은행이 고객을 생성하는 것은 이상한 것 같습니다.
고객의 수가 필요하다면 이를 외부에서 주입받는 것이 더 자연스럽지 않을까요?

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
enum을 사용하셔서 유저의 입력에 대해서 잘 분류하셨군요 👍 💯

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
이 부분도 은행의 역할이 맞을지 다시 한 번 고민해봐주세요 🙏 
유저와의 communication을 담당하는 객체가 있고, 은행은 은행의 업무만 있으면 좋을 것 같습니다!

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            self.bankManager.recept(client: Client(id: i, spendTime: 0.7))
bankManager의 recept 함수를 사용하는 곳에서 가독성을 조금 더 개선해 볼 수 있을 것 같아요 🙏 
정답은 없으니 세분이 어느 것이 더 가독성이 좋은지 논의해보시면 좋을 것 같네요 :) 
```Swift
let client = Client(id: i, spendTime: 0.7)
self.bankManager.recept(for: client)
```

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    }
고객이 본인의 업무가 얼마나 걸리는지 spendTime을 들고 있는건 어색한 것 같습니다. 🤔 
은행에서 가능한 업무의 종류들이 있고, 그 종류를 client에 주입해주는 것은 어떨까요? 🙏🏻

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    }
고객이 스스로 thread를 sleep시키는 것도 어색해보입니다.
은행원이 해당 고객이 어떤 업무를 가지고 있는지 확인하고, 은행원이 이를 sleep시키는 것이 더 자연스럽지 않을까요? 

맨 처음 은행의 역할을 여쭤본 것처럼, 세 분이 생각하시는 고객의 역할은 어떤 것일까요?
또한 그 역할을 수행하기 위해서는 어떤 값과 함수를 고객이라는 객체가 가져야할까요.

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Utility/Queue.swift
> +    }
함수에서 연산프로퍼티로 변경하신 이유가 궁금합니다 🙋‍♂️
세 분은 어떤 기준으로 연산프로퍼티와 함수를 사용하실까요?

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Utility/Script.swift
> +            return "잘 못된 입력입니다."
space가 하나 들어가 있네요 :)

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Utility/Script.swift
> +    case bankSettlementMessage(count: Int, totalWorkTime: String)
script를 잘 모아두셨네요 👏 💯 
물론 앱 내부에서 사용되는 script 상수들을 한 곳에 모아두고 관리할 수도 있지만, 
만약 특정 객체에서만 사용될 것 같은 script는 해당 객체내에서 관리해도 괜찮을 것 같습니다! 

이 부분은 위 코멘트들에서 남겨드린 각 객체들의 역할에 대해서 고민해 보시면서 전반적으로 앱 전체에서 사용될 수 있는 script인지, 아니면 특정 객체에서만 사용하는지에 따라서 분리해보셔도 좋을 것 같네요 :)

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Utility/Script.swift
> +enum Script: CustomStringConvertible {
CustomStringConvertible도 잘 사용해보셨네요 👍 💯

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Utility/Script.swift
> +enum Script: CustomStringConvertible {
여기만 import와 타입 사이에 줄바꿈이 없네요 :) 
이런 별거 아닌 것 같은 컨벤션들을 잘 챙겨주는게, 은근 가독성에 영향이 있는 것 같아요 ㅎㅎ 
프로젝트 진행하시면서 세분이 정하신 컨벤션을 최대한 잘 지켜보시면 좋을 것 같네요.

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +final class BankManager {
여기는 줄바꿈이 2개군요!!

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        self.semaphore = DispatchSemaphore(value: clerkCount)
DispatchSemaphore를 사용해보셨네요 👏 💯 
각각의 은행원을 생성하신 것이 아닌 하나의 manager에 DispatchSemaphore를 사용해서 스레드를 은행원으로 생각하신 특별한 이유가 있을까요? 🙋‍♂️ 
별 이유 없이 그냥 진짜 궁금해서 여쭤보는 겁니다 🙏 ㅎㅎ

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        let group = DispatchGroup()
DispatchGroup까지 사용해보셨군요 👏 💯

2023-11-06 13:45 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +final class BankManager {
은행, 고객처럼 은행원의 역할도 한 번 고민해봐주세요 🙏

2023-11-07 02:17 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Utility/Queue.swift
> +    }
peek이 Swift Array의 last와 비슷한 기능 (Array의 경우 마지막 Element, Queue의 peek경우 첫번째 노드의 데이터 값)을 한다고 생각하여 Array의 last가 연산프로퍼티로 구현되어 있어서 변경을 했습니다.
연산 프로퍼티의 경우 보통 환경에 따라 바뀔 가능성이 있는 Bool타입의 경우에 함수보단 연산프로퍼티로의 구현을 많이 하는 것 같습니다!
이렇게 다시 바꿔놓고 보니 peek의 경우 LinkedList의 기능이 아닌 Queue의 기능이라 따로 함수로 구현하는 것이 맞기도 하다는 생각도 듭니다!

2023-11-07 02:19 UTC, Dongjun-developer commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            self.bankManager.recept(client: Client(id: i, spendTime: 0.7))
네 저희는 알려주신 내용으로 수정하였습니다.😄

2023-11-07 06:11 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    }
Client내부의 spendTime 프로퍼티를 제거하고 BankManager에서 하도록 변경했습니다.
은행에서 가능한 업무의 종류를 Client에 넣어주는 작업은 STEP3의 내용인 것 같아 STEP3에서 구현해보려고 합니다!

2023-11-07 06:12 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Utility/Script.swift
> +    case bankSettlementMessage(count: Int, totalWorkTime: String)
각 객체에 필요한 Script끼리 묶어서 관리하도록 분리하여 변경했습니다!

2023-11-07 06:13 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
따로 BankProcess라는 객체를 구현하여 해당 객체로 사용자와 커뮤니케이션을 하는 기능을 분리 하였습니다!

2023-11-07 06:14 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
사용자의 입력을 받는 객체에서 고객의 수를 생성하여 주입하도록 변경했습니다!

2023-11-07 06:17 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
BankManagable 이라는 프로토콜을 생성하여 BankManager가 해당 프로토콜을 채택하고,
Bank에서의  BankManager 프로퍼티를 BankManagable의 타입으로 선언하여 의존성을 BankManager에 직접 갖는 것이 아닌 BankManagable 프로토콜로 가지고 의존성 주입받는 것으로 변경하여 적용하였습니다.

2023-11-07 06:19 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        }
저희는 Bank의 역할을 사람들이 들어왔을 때, 접수를 받으며, 은행 업무를 보는 BankManager에게 일을 시키는 것으로 보았습니다. 하지만 유저의 입력 받는 부분은 Bank의 역할이 아니라고 생각되어 BankProcess 클래스로 분리하여 적용했습니다!

2023-11-07 06:22 UTC, bamsak commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        self.semaphore = DispatchSemaphore(value: clerkCount)
n명의 은행원이 일하는 모습과 멀티 스레드로 동작하는 양상이 비슷하다고 생각했습니다. 
그래서 하나의 스레드가 한 명의 은행원이라 생각하였고, 하나의 manager에서 여러 명의 은행원을 DispatchSemaphore를 사용해서 은행원 수를 관리하려고 하였습니다!

2023-11-07 09:12 UTC, jryoun1 approved these changes
수정해주신 부분 확인했습니다! 
나머지는 step3 진행하면서 반영해도 될 것 같아서 여기서 머지하겠습니다!

2023-11-07 09:12 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankProcess.swift
> +//  File.swift
파일명이 일치하지 않는 것 같네요 :)

2023-11-07 09:12 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
bankManager를 추상화해서 주입받도록 하셨군요 👏 💯 
Bank가 이제 bankManager가 어떤 구체 타입인지 몰라도 되니까 bankManager와의 의존도도 낮아졌네요 👍

2023-11-07 09:12 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/BankManagable.swift
> +}
👏

2023-11-07 09:16 UTC, merged

2023-11-08 01:48 UTC, Dongjun-developer commented on BankManagerConsoleApp/BankManagerConsoleApp/BankProcess.swift
> +//  File.swift
수정했습니다:)