은행 창구 관리 앱 [Step3] 범, 랄라
tasty-code/ios-bank-manager pull request #44
Opened 2023-11-06 08:20 UTC by rarlala

# 은행창구 관리앱 [ Step 3 ]

안녕하세요~! @corykim0829
3번째 PR을 요청드리게 되었습니다!

## 구현 사항
- Step 3의 은행에는 3명의 은행원이 근무합니다.
    - 2명의 은행원은 예금업무를, 1명의 은행원은 대출업무를 처리합니다.
    - 고객의 업무 종류는 고객 생성시 임의로 지정합니다.
- 한 명의 은행원은 한 명의 고객을 응대할 수 있습니다.
- 고객이 원하는 업무의 종류와 소요시간은 아래와 같습니다.
    - 대출 : 1.1초
    - 예금 : 0.7초
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다.
    - "3번 고객 대출업무 시작"
- 고객의 업무를 처리하면 아래와 같이 출력합니다.
    - "11번 고객 예금업무 완료"

## 고민한 점
- 예금, 적금 업무를 하는 은행원들을 하나의 타입으로 관리할 수 있도록 Tellers 타입을 만들었습니다.
- Queue를 어떻게 나눠서 처리할지에 대해 고민해보았습니다. 예금과 대출 각각의 큐로 2개로 나눠서 예금 은행원은 예금 고객 큐, 대출 은행원은 대출 고객 큐를 보는 것이 맞다고 생각해 2개의 큐를 만들어 작업했습니다.

## 궁금한 점
- [Step2 리뷰 링크](https://github.com/tasty-code/ios-bank-manager/pull/42/files/318ceebed438f6a72953ecdd43b9b8760a43be07#r1382571899)에서 로직이 부자연스럽다 tellerCount가 2명 이상되면 작동하지 않는 것 같다고 리뷰해주셨는데요. 고민해보니 DispatchSemaphore를 tellerCount로 설정한 부분이 문제라고 생각해 DispatchSemaphore value를 1로 변경했습니다. 이 부분을 말씀해주신게 맞을까요?

- semaphore.signal()의 위치에 따른 실행 결과가 이해되지 않습니다.
![semaphore위치 상단.gif](https://hackmd.io/_uploads/BJEv5f876.gif)
    - 첫 번째 경우는 정상적으로 실행이 되었습니다.
- ![semaphore위치 하단.gif](https://hackmd.io/_uploads/SkwAjfUQT.gif)
    - 두 번째 경우에는 마지막 업무 완료가 뜨고 더 이상 진행이 불가능 합니다.
    - 단지 print문 밑으로 signal을 내린 옮긴 것인데 왜 이렇게 작동하는지 모르겠습니다.
 
- `BankManager`에서 예금, 대출업무에 해당하는 각각의 Tellers, Queue를 생성해 작업했습니다. `startTask` 메서드에서 중복 코드를 줄이기 위해 아래와 같이 코드를 작성했습니다. 아래와 같이 코드를 작성하게 되면 추후 적금, 보험이 추가되어 확장을 시킨다고 할 때 각각 생성되는 코드가 길어지게 되는데요. 이 부분에 대해 개선하고 싶다는 생각이 듭니다! 어떻게 개선할 수 있을지 코리의 의견을 듣고 싶습니다!
```swift=
private func startTask() {
        let depositWork = (depositTellers, depositCustomerQueue)
        let loanWork = (loanTellers, loanCustomerQueue)
        
        let group = DispatchGroup()
        
        [depositWork, loanWork].forEach { (tellers, queue) in
            group.enter()
            DispatchQueue.global().async {
                tellers.doTask(queue: queue)
                group.leave()
            }
        }
        
        group.wait()
    }
```

2023-11-07 09:24 UTC, corykim0829 requested changes
수고 많으셨습니다!!

> Step2 리뷰에서 로직이 부자연스럽다 tellerCount가 2명 이상되면 작동하지 않는 것 같다고 리뷰해주셨는데요. 고민해보니 DispatchSemaphore를 tellerCount로 설정한 부분이 문제라고 생각해 DispatchSemaphore value를 1로 변경했습니다. 이 부분을 말씀해주신게 맞을까요?
> semaphore.signal()의 위치에 따른 실행 결과가 이해되지 않습니다.

➡️ 가장 먼저 DispatchSemaphore value 값을 현재 어떤 의도로 쓰셨는지를 정리해주셨으면 좋겠습니다! 왜 처음에는 tellerCount로 value를 잡았고, 이번에는 왜 1로 고정시켰는지 궁금합니다!

> BankManager에서 예금, 대출업무에 해당하는 각각의 Tellers, Queue를 생성해 작업했습니다. startTask 메서드에서 중복 코드를 줄이기 위해 아래와 같이 코드를 작성했습니다. 아래와 같이 코드를 작성하게 되면 추후 적금, 보험이 추가되어 확장을 시킨다고 할 때 각각 생성되는 코드가 길어지게 되는데요. 이 부분에 대해 개선하고 싶다는 생각이 듭니다! 어떻게 개선할 수 있을지 코리의 의견을 듣고 싶습니다!

➡️ 좋은 고민이에요! 현재는 작업에 따라 Queue를 나누셨고 해당 큐에 따라 Teller를 생성시켜서 처리하고 있어서 확장에는 취약한 구조로 보입니다.
Queue와 Teller를 mapping 해줄 무언가가 있다면 코드를 줄일 수는 있을 것 같습니다. 하지만 코드를 줄이는게 꼭 중요한게 아니여서 이 부분은 아직 고민하지 않는게 좋은 것 같습니다.

제가 생각했을 때에는 현재 TellerCount를 기준으로 for문이 돌아가고 그 안에서 queue가 돌아가는게 아쉬운 부분인 것 같아요.

현재 실질적인 데이터를 상징하는 사용자 Queue를 중심으로 데이터를 처리하는 로직으로 방향을 잡으면 좋을 것 같아요!

2023-11-07 09:24 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Tellers.swift
> +        let semaphore = DispatchSemaphore(value: 1)
> DispatchSemaphore를 tellerCount로 설정한 부분이 문제라고 생각해 DispatchSemaphore value를 1로 변경했습니다. 이 부분을 말씀해주신게 맞을까요?

DispatchSemaphore value의 값은 왜 1로 바꿨나요?
이렇게 변경한 이유가 궁금해요!

2023-11-07 09:24 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/TypeOfWork.swift
> +    var time: UInt32 {
시간이나 이름을 따로 프로퍼티로 처리한게 좋습니다!

2023-11-09 01:12 UTC, rarlala commented on BankManagerConsoleApp/BankManagerConsoleApp/TypeOfWork.swift
> +    var time: UInt32 {
감사합니다 :)

2023-11-09 01:18 UTC, snowy-summer commented on BankManagerConsoleApp/BankManagerConsoleApp/Tellers.swift
> +        let semaphore = DispatchSemaphore(value: 1)
맨 처음에는 은행원 1명이 업무가 끝날때까지 기다리는 것이 아니라 dequeue만 하면 접근이 가능해야 하니까 tellerCount로 설정을 했습니다.  
하지만 수정 전 코드에서, tellerCount로 하는경우에 동일한 번호를 예금 은행원들이 처리 하는 경우가 있어서  1로 수정을 했습니다.
그리고 for문을 제거하고 wait의 위치를 변경함으로써 맨 처음 의도대로 작동이 되도록 tellerCount로 변경했습니다. 

value : tellerCount -> 1 -> tellerCount

2023-11-10 05:54 UTC, corykim0829 approved these changes
수고하셨습니다!

남겨드린 커멘트는 다음 스텝 진행하면서 수정해주시면 될 것 같아요!

2023-11-10 05:54 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Tellers.swift
> +        var workingTellerCount = 0
workingTellerCount가 불필요해보입니다.
현재 업무 개수를 처리하는 곳은 어디인가요?

2023-11-10 05:54 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Tellers.swift
> +            }
이 부분도 semaphore를 wait하지 않으면 signal 예외 처리를 할 필요가 없기 때문에, 다음과 같이 바꾸면 예외처리를 좀 더 줄일 수 있어요. 참고만하세요!

```suggestion
             guard let data = queue.dequeue() else {
                 return
             }
            semaphore.wait()

2023-11-10 05:54 UTC, merged

2023-11-10 06:33 UTC, rarlala commented on BankManagerConsoleApp/BankManagerConsoleApp/Tellers.swift
> +        var workingTellerCount = 0
오! for문을 없애고 일하는 은행원의 수를 관리해 돌아가게 해야한다고 생각해 workingTellerCount를 추가해서 작업했었습니다!

현재 업무 개수라는 의미를 정확히 무엇을 말씀하시는지 잘 모르겠습니다.
다만, 업무에 대한 처리는 doTask 메서드에서 진행되고
남아있는 고객의 수는 Queue에 들어가있는 Node의 갯수라고 생각합니다.

workingTellerCount를 추가하지 않아도 DispatchSemaphore의 value로 관리되므로 workingTellerCount가 불필요한 것을 확인했습니다!

감사합니다!

2023-11-10 06:40 UTC, snowy-summer commented on BankManagerConsoleApp/BankManagerConsoleApp/Tellers.swift
> +            }
예전처럼 dequeue할 때 비동기 처리를 안하기 때문에 semaphore.wait의 위치를 guard문 밑으로 옮겨서 불필요한 예외처리가 필요 없어 보이네요. 
감사합니다.