은행창구 관리앱 [STEP3] 뉴준성, Howard
tasty-code/ios-bank-manager pull request #45
Opened 2023-11-07 01:58 UTC by JEON-Sungsu

리뷰어 : @zdodev

# STEP3

## Step3 명세서

- Step 3의 은행에는 3명의 은행원이 근무합니다.
    - 2명의 은행원은 예금업무를, 1명의 은행원은 대출업무를 처리합니다.
    - 고객의 업무 종류는 고객 생성시 임의로 지정합니다.
- 한 명의 은행원은 한 명의 고객을 응대할 수 있습니다.
- 고객이 원하는 업무의 종류와 소요시간은 아래와 같습니다.
    - 대출 : 1.1초
    - 예금 : 0.7초
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다.
    - "3번 고객 대출업무 시작"
- 고객의 업무를 처리하면 아래와 같이 출력합니다.
    - "11번 고객 예금업무 완료"

## 프로그램 동작 화면

![bankManager_STEP3](https://github.com/tasty-code/ios-bank-manager/assets/63297236/dce88b6a-4827-4f73-92ed-8ba000243603)

## 코드 설명

### BankTask

```swift
protocol BankTask {
    static var semaphore: DispatchSemaphore { get }
    static var dispatchQueue: DispatchQueue { get }
    
    var name: String { get }
    var processingTime: Double { get }
    
    init()
}
```

예금 업무와 대출 업무에 대한 프로토콜입니다.
`semaphore`는 각각의 업무에 대한 은행원을 배치하고자 부여했고,
`dispatchQueue`는 디버깅할 때, 어떤 queue인지 확인하고자 부여했습니다.
`name`과 `processingTime`은 각각 **이름**과 **업무를 처리하는데 걸리는 시간**을 의미합니다!

이렇게 추상화를 한 이유는, OCP 원칙을 준수하고 싶었기 때문입니다.
추후에 새로운 업무가 추가된다면, BankTask 프로토콜을 준수하는 타입을 만들어주기만 하면 됩니다.

```swift
struct StockTask: BankTask {
    static let semaphore: DispatchSemaphore = DispatchSemaphore(value: 3)
    static let dispatchQueue: DispatchQueue = DispatchQueue(label: "StockQueue", attributes: .concurrent)
    var name: String = "주식"
    var processingTime: Double = 0.5
}
```

### Bankable

```swift
protocol Bankable: AnyObject {
    var customerQueue: Queue<Customer> { get }
    var group: DispatchGroup { get }
    
    func beginTask() -> (taskProcessingTime: Double, handledCustomer: Int)
    
    func assignTask(_ customer: Customer, group: DispatchGroup)
}

extension Bankable {
    func assignTask(_ customer: Customer, group: DispatchGroup) {
        let task = customer.task
        let semaphore = type(of: task).semaphore
        let queue = type(of: task).dispatchQueue
        
        queue.async(group: group) {
            semaphore.wait()
            print(BankDialogue.start(customer, task: task))
            Thread.sleep(forTimeInterval: task.processingTime)
            print(BankDialogue.finish(customer, task: task))
            semaphore.signal()
        }
    }
}
```

Bankable 프로토콜의 경우, 비동기로 실행되는 스레드가 명령들을 모두 처리해야 할 때까지 기다려야 하기 때문에 `group`을 부여해줬습니다. `beginTask`는 은행이 개점되고 어떻게 실행되어야 할지를 나타내는 함수입니다. 그리고 `assignTask`의 경우, 고객의 업무에 따라 어떤 식으로 대응해야하는지를 나타내는 함수입니다.

### Bank

```swift
class Bank: Bankable {
		let group: DispatchGroup = DispatchGroup()
    private(set) var customerQueue: Queue<Customer>
// ...
    func beginTask() -> (taskProcessingTime: Double, handledCustomer: Int) {
        handledCustomer = 0
        addRandomCustomers(Int.random(in: 10...30), taskTypes: LoanTask.self, DepositTask.self)
        
        let start = CFAbsoluteTimeGetCurrent()
        while !customerQueue.isEmpty {
            if let customer = customerQueue.dequeue() {
                assignTask(customer, group: group)
                handledCustomer += 1
            }
        }
        
        group.wait()
        
        let end = CFAbsoluteTimeGetCurrent() - start
        
        return (Double(end), handledCustomer)
    }
}
```

Bankable 프로토콜을 채택했기 때문에, `group`, `customerQueue`, `beginTask`를 만들줬습니다.
`beginTask`에서 비동기 스레드가 다 돌기도 전에 `end`와 `handledCustomer`를 리턴할 수도 있기 때문에,
`group.wait()`를 통해 비동기 작업이 끝날 때까지 기다리도록 했습니다.

## 궁금한 점

BankTask를 프로토콜로 추상화하는 과정에서 설계 패턴을 적용해보려 했으나, 마땅히 적용할 만한 패턴이 무엇인지 모르겠습니다. 이런 상황에서 어떤 설계 패턴을 적용할 수 있을까요?

2023-11-07 15:25 UTC, zdodev requested changes
안녕하세요. @JEON-Sungsu , @newJunsung !

Step 3 구현 잘해주셨습니다😁
동시성 프로그래밍과 추상화, 역할 분리를 잘해주셨어요!👍

이번에도 코멘트 간단히 확인해보고 넘어가면 좋을 것 같습니다~😁

2023-11-07 15:25 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private func addRandomCustomers(_ count: Int, taskTypes: BankTask.Type...) {
가변 매개변수를 사용해보셨네요!
고객을 생성하는 로직을 분리한 점도 좋았습니다!👍

2023-11-07 15:25 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            customerQueue.enqueue(Customer(id: i, task: taskTypes.randomElement()!.init()))
강제 옵셔널 언래핑을 사용해보셨네요! `taskTypes` 인자에 항상 값이 있다는 보장이 없어서 충분히 런타임 에러가 발생할 수 있을 것 같습니다.
런타임 에러가 발생하지 않도록 개선해볼 수 있을까요?

2023-11-07 15:25 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/BankTask.swift
> +protocol BankTask {
대출업무와 예금업무를 잘 추상화해보셨네요!👍
특정 패턴에 꼭 맞춰서 구현하기 보다는 지금처럼 상황에 맞게 구현하는 것도 좋은 방법입니다.😁

2023-11-07 15:25 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/BankTask.swift
> +    static var semaphore: DispatchSemaphore { get }
`DispatchSemaphore` 를 사용해보셨네요!👍

2023-11-07 15:25 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bankable.swift
> +    func assignTask(_ customer: Customer, group: DispatchGroup) {
Protocol 기본 구현을 사용해보셨네요!👍

2023-11-07 15:25 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bankable.swift
> +    func assignTask(_ customer: Customer, group: DispatchGroup)
업무 시작과 업무 할당 역할을 분리한 점이 좋았습니다.😁

2023-11-08 00:50 UTC, newJunsung commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            }
가변 매개변수도 다른 매개변수와 같이 반드시 파라미터를 최소 1개는 입력해야하는 것으로 착각한 나머지, 강제 언래핑을 했습니다. `if let` 을 통해 언래핑을 하고 그 타입의 인스턴스를 큐에 넣도록 수정했습니다.

2023-11-08 13:38 UTC, zdodev approved these changes
안녕하세요. @JEON-Sungsu , @newJunsung !

남긴 코멘트에 대해서 좋은 의견과 개선을 해보셨네요!👍

한 스텝 진행하느라 고생하셨습니다~ 
이번 스텝은 여기서 마무리하도록 하겠습니다.🎉

2023-11-08 13:38 UTC, zdodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            }
좋은 해결 방법과 의견이라고 생각합니다.👍

2023-11-08 13:38 UTC, merged