은행창구 관리 앱 [Step 3] Comdori, SwainYun
tasty-code/ios-bank-manager pull request #48
Opened 2023-11-07 06:21 UTC by comdori-wj

# 은행창구 관리 앱 [Step 3] Comdori, SwainYun

리뷰어: @protocorn93
리뷰이: @Remaked-Swain & @comdori-wj

🙋🏻‍♂️ 안녕하세요, 콘!
Step3 프로젝트 요구사항에 맞춰 다음 내용 진행하였습니다.

-----------------------------------------------

## 🍀 구현사항
|항목|내용|
|:--:|:--|
|Teller|은행에서 고객에게 업무를 도와줄 은행원 입니다.|
|Bank|기존 BankManager에서 수행하던 '은행 업무'를 해줍니다.|
|BankManager|프로그램과 은행 전반의 루프를 담당하도록 바뀌었습니다.|

## 📸 스크린샷
![screenshot.png](https://hackmd.io/_uploads/Bkx4ASv76.png)

## 🤔 궁금한 점
### Comdori
```swift
 private func doDepositWork(by worker: BankWorker) {
    DispatchQueue.global().async(group: group) {
        while !customerQueue.isEmpty {
            depositSemaphore.wait()
            guard let client = depositClientQueue.dequeue() else {
                depositSemaphore.signal()
                print("업무를 처리할 예금 고객이 없습니다.")
                return
            }

            depositSemaphore.signal()
            worker.startWork(for: client)
        }
    }
}

private func doLoanWork(by worker: BankWorker) {
    DispatchQueue.global().async(group: group) {
        while !customerQueue.isEmpty {
            loanSemaphore.wait()
            guard let client = loanClientQueue.dequeue() else {
                loanSemaphore.signal()
                print("업무를 처리할 대출 고객이 없습니다.")
                return
            }

            loanSemaphore.signal()
            worker.startWork(for: client)
        }
    }
}
```
Q1. 위의 코드처럼 만약 각각의 `Global DispatchQueue`가 있다면 각각의 업무를 동시에 처리 할 것 이라 생각합니다. 콘의 생각은 어떠신가요?
```swift
private let dispatchLoan = DispatchQueue(label: "Loan", attributes: .concurrent)
private let dispatchDeposit = DispatchQueue(label: "Deposit", attributes: .concurrent)

// ... 생략

dispatchLoan.async(group: dispatchGroup) { [self] in
    while customerQueue.isEmpty == false {
        semaphore.wait()
        guard let customer = customerQueue.peek(), customer.workType == teller.workType else {
            semaphore.signal()
            continue
        }

        guard let customer = customerQueue.dequeue() else { return }

        semaphore.signal()

        teller.service(to: customer) { [self] in
            servicedCustomersCount += 1
            totalServicedTimes += customer.workType.timeCost
        }
    }
}

dispatchDeposit.async(group: dispatchGroup) { [self] in
    while customerQueue.isEmpty == false {
        semaphore.wait()
        guard let customer = customerQueue.peek(), customer.workType == teller.workType else {
            semaphore.signal()
            continue
        }

        guard let customer = customerQueue.dequeue() else { return }

        semaphore.signal()

        teller.service(to: customer) { [self] in
            servicedCustomersCount += 1
            totalServicedTimes += customer.workType.timeCost
        }
    }
}

```
Q2. 위 코드처럼 커스텀 큐를 2개를 만들면 글로벌 큐와 다르게 각각의 큐를 만들어서 동시에 동작하는지 궁금합니다 🤔

### SwainYun
1. **DispatchGroup.notify() 메서드의 사용법**
```swift
dispatchGroup.notify(queue: .main) { [self] in
    InterfaceMessage.printBankDidClose(servicedCustomersCount: servicedCustomersCount, totalServicedTimes: totalServicedTimes)
    completion()
}
```
> 'dispatchGroup에 속한 작업이 종료되면 블럭 내 코드가 실행될 수 있도록 알린다.' 라는 기능으로 이해하고 위와 같이 작성하였는데 제 예상대로 동작하지 않았습니다. 제가 어느 부분을 놓치고 있는 것인지 찾지 못했습니다...

2. **Serial하게 동작하는 이상현상에 대하여**
```swift
final class Bank {
    // 생략...
    
    func work(completion: @escaping () -> Void) {
        gatherCustomers()
        
        tellers.forEach { teller in
            DispatchQueue.global().async(group: dispatchGroup) { [self] in
                while customerQueue.isEmpty == false {
                    semaphore.wait()
                    guard let customer = customerQueue.peek(), customer.workType == teller.workType else {
                        semaphore.signal()
                        continue
                    }
                    
                    guard let customer = customerQueue.dequeue() else { return }
                    
                    semaphore.signal()
                    
                    teller.service(to: customer) { [self] in
                        servicedCustomersCount += 1
                        totalServicedTimes += customer.workType.timeCost
                    }
                }
            }
        }
        
        dispatchGroup.wait()
        InterfaceMessage.printBankDidClose(servicedCustomersCount: servicedCustomersCount, totalServicedTimes: totalServicedTimes)
        completion()
    }
}
```

```swift
extension LinkedList: QueueProtocol {
    // 생략...
    
    func peek() -> Value? {
        return self.tail?.value
    }
}
```
> 위와 같은 코드에서 어떤 경우는 예상한대로 동작하고, 어떤 경우에는 1번 고객, 2번 고객, 3번 고객, 4번 고객... 순서대로 Serial하게 동작했습니다. `guard let customer = customerQueue.peek(), customer.workType == teller.workType else { semaphore.signal(); continue }` 코드에서 문제가 발생하는 것이 확인되어 코드를 검사해보니, Linked-list의 peek() 메서드가 위와 같이 tail의 값을 반환하게 짜여져 있었습니다. `self.head?.value` 를 반환하게 수정하였더니 정상적으로 동작하게 되었습니다.

## Step 3 진행 중 참고한 자료
* [DispatchGroup](https://developer.apple.com/documentation/dispatch/dispatchgroup)

2023-11-08 09:54 UTC, protocorn93 requested changes
쉽지 않은 스탭이었을텐데, 두 분 모두 고생 많으셨어요. 


## 질문 사항

> Q1. 위의 코드처럼 만약 각각의 Global DispatchQueue가 있다면 각각의 업무를 동시에 처리 할 것 이라 생각합니다. 콘의 생각은 어떠신가요?

GCD는 직접 스레드를 다루는 불편함을 해결하기 위해 등장했어요.

DispatchQueue.global() 큐의 특징은 concurrent하다는 것이에요. concurrent하다는 것은 이전 작업이 끝나기 전에 다음 작업을 스케쥴링할 수 있다는 것이에요. 그리고 이 큐는 다수의 스레드를 활용해요. 

좀 더 정확하게 표현한다면 큐는 선입선출로 스레드에 작업을 스케쥴링해요. 다만 어느것이 먼저 시작되고 먼저 끝날지는 알 수 없어요. 

> Q2. 위 코드처럼 커스텀 큐를 2개를 만들면 글로벌 큐와 다르게 각각의 큐를 만들어서 동시에 동작하는지 궁금합니다 🤔

마찬가지로 알 수 없어요. 동시에 시작할 수도 있고 아닐 수도 있어요. 


> DispatchGroup.notify() 메서드의 사용법

notify() 사용을 위해선 dispatch group enter(), leave() 메서드를 적절한 타이밍에 호출해주어야 하는 것으로 알고 있어요. 저도 notify는 활용해본 경험이 없는데, 이건 저도 방법을 좀 더 찾아볼게요.

2023-11-08 09:54 UTC, protocorn93 commented on BankManager.swift
> +            if input == "1" {
Int가 rawValue인 enum으로 메뉴를 모델링하면 읽기 더 좋은 코드가 될 것 같아요.

2023-11-08 09:54 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        return self.head?.value
저도 코드만 보고 peek이 맨 뒤에 것을 반환할것이라고 오해했던 것 같네요.

2023-11-08 09:54 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private let semaphore = DispatchSemaphore(value: 1)
`value` 인자로 넘긴 1은 어떤 것을 의미하나요?

2023-11-08 09:54 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private var tellers: [Teller]
생성자에서 초기화되기 때문에 내부에서 `tailers`에 변화를 줄 것이 아니라면 `let`으로 선언되는게 좋을 것 같아요.

2023-11-08 09:54 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +                    semaphore.signal()
`teller` 작업 후가 아닌 전에 `signal`을 하신 이유가 무엇인가요?

2023-11-08 09:54 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +                while customerQueue.isEmpty == false {
`DispatchQueue.global()`에 전달하는 블록을 별도 메서드로 분리해도 좋을 것 같아요.

2023-11-08 09:54 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Customer.swift
>      init(id: Int) {
생성자에서 workType을 전달해줄 수 있도록 열려있으면 좋겠네요.

2023-11-08 11:56 UTC, Remaked-Swain commented on BankManager.swift
> +            if input == "1" {
```swift
enum InterfaceMenu: Int {
    case run = 1
    case exit
}

final class BankManager {
    // 생략...
    
    func run() {
        do {
            InterfaceMessage.printMenuScript()
            let interfaceMenu = try selectInterfaceMenu()
            if interfaceMenu == .run {
                bank.work { self.run() }
            } else {
                return
            }
        } catch let error {
            print(error)
            run()
        }
    }
}

// MARK: Private Methods
extension BankManager {
    private func selectInterfaceMenu() throws -> InterfaceMenu {
        guard let input = readLine(),
              let integerInput = Int(input),
              integerInput == 1 || integerInput == 2,
              let interfaceMenu = InterfaceMenu(rawValue: integerInput)
        else { throw InterfaceErrorMessage.wrongMenuSelected }
        return interfaceMenu
    }
}
```
> 1. 유저의 상호작용을 통해 선택할 수 있는 메뉴라는 의미에서 InterfaceMenu 열거형을 위와 같이 Int형으로 선언해주었습니다.
> 2. rawValue로 생성하는 것은 실패 가능하기 때문에 옵셔널 바인딩을 겸해서 기존의 `getUserInput()` 메서드를 약간 변경하였습니다.
> 3. 결과적으로 메뉴의 종류를 모델링하여 해당 케이스가 무슨 작업인지 직관적으로 알 수 있게 개선되었습니다! :)

------------------
**추가 개선**


```swift
enum InterfaceMenu: Int {
    case run = 1
    case exit
    
    static func convertStringToInterfaceMenu(_ rawValue: Int) throws -> Self {
        switch rawValue {
        case 1: return .run
        case 2: return .exit
        default: throw InterfaceErrorMessage.wrongMenuSelected
        }
    }
}

extension BankManager {
    private func selectInterfaceMenu() throws -> InterfaceMenu {
        guard let input = readLine(),
              let integerInput = Int(input),
              integerInput == 1 || integerInput == 2,
              let interfaceMenu = try? InterfaceMenu.convertStringToInterfaceMenu(integerInput)
        else { throw InterfaceErrorMessage.wrongMenuSelected }
        return interfaceMenu
    }
}
```
> 열거형의 rawValue를 통한 생성은 옵셔널합니다. 또한 외부에서 원시값을 사용하는 것은 때때로 좋지 않은 효과를 보일 때도 있습니다.
> 따라서 열거형 타입 생성을 위한 rawValue는 열거형 안에서만 통용되도록 만들고 싶었습니다.

2023-11-08 12:01 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        return self.head?.value
자료구조 구현 간에 어떠한 혼란이 있었던 모양입니다.
앞으로 주의하여 코딩해야겠습니다 ㅠㅠ

2023-11-08 12:06 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private let semaphore = DispatchSemaphore(value: 1)
접근 가능한 스레드의 제한 숫자를 의미한다고 생각합니다.
DispatchSemaphore의 wait() 메서드는 스레드 제한수를 1 만큼 감소시키고,
signal() 메서드는 스레드 제한수를 1 만큼 증가시켜 줍니다.

따라서 DispatchSemaphore를 통해 스레드 접근 제한수를 0~1 로 유지시킬 수 있고, 스레드의 공용자원인 customerQueue의 dequeue같은 update작업에 있어서 Race Condition을 예방하고 thread-safe하게 만들어주는 효과를 볼 수 있게 되었습니다!

2023-11-08 12:07 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private var tellers: [Teller]
미처 챙기지 못한 부분인데 감사합니다!!

2023-11-08 12:12 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +                    semaphore.signal()
`teller.service()` 부분 이후에 `signal()`을 하게 되면 concurrent한 글로벌 큐로 넘긴 작업이 단 하나의 스레드만 동작하는 구간으로 되어버리기 때문에 결국 serial하게 동작하는 효과가 생기게 됩니다.

teller의 작업은 concurrent하게 동작하고, 공유자원인 customerQueue에 접근하는 것만은 스레드 제한을 두자는 취지에서 해당 위치에 signal을 호출하기로 결정했습니다.

혹시 콘이 보시는 관점과 다른 부분이 있을까요? 👀

2023-11-08 12:17 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Customer.swift
>      init(id: Int) {
```swift
struct Customer {
    let id: Int
    let workType: WorkType
    
    init(id: Int, workType: WorkType) {
        self.id = id
        self.workType = workType
    }
}

extension Bank {
    private func gatherCustomers() {
        let totalCustomersCount = Int.random(in: 10...30)
        for count in 1...totalCustomersCount {
            guard let randomWorkType = WorkType.allCases.randomElement() else { return }
            let customer = Customer(id: count, workType: randomWorkType)
            customerQueue.enqueue(customer)
        }
    }
}
```
> workType을 주입받을 수 있도록 변경하였습니다.
> 이렇게 하면 특정 작업 종류만을 가진 고객을 만들 수 있게 되어 유닛테스트 시에도 좋겠군요!

2023-11-09 04:04 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +                while customerQueue.isEmpty == false {
**DispatchQueue.global() 코드 블럭 분리**
```swift
final class Bank {
    // 생략...
    
    func work(completion: @escaping () -> Void) {
        gatherCustomers()
        
        tellers.forEach { teller in
            while customerQueue.isEmpty == false {
                guard let customer = customerQueue.dequeue() else { return }
                
                matchUpService(with: customer, on: teller)
            }
        }
        
        dispatchGroup.wait()
        InterfaceMessage.printBankDidClose(servicedCustomersCount: servicedCustomersCount, totalServicedTimes: totalServicedTimes)
        completion()
    }
}

// MARK: Private Methods
extension Bank {
    // 생략...
    
    private func matchUpService(with customer: Customer, on teller: TellerProtocol) {
        DispatchQueue.global().async(group: dispatchGroup) {
            teller.service(to: customer) { [self] in
                servicedCustomersCount += 1
                totalServicedTimes += customer.workType.timeCost
            }
        }
    }
}
```
> 고객을 은행원의 인터페이스로 연결(match)한다는 의미에서 `matchUpService()` 메서드를 위와 같이 만들어주어 기존의 `work()` 메서드의 코드에서 분리할 수 있었습니다.

**세마포어 밸류 조정을 통한 은행원 수 관리**
```swift
protocol TellerProtocol {
    func service(to customer: Customer, completion: @escaping () -> Void)
}

struct Teller: TellerProtocol {
    private let semaphore: DispatchSemaphore
    
    init(tellerCount: Int) {
        self.semaphore = DispatchSemaphore(value: tellerCount)
    }
    
    func service(to customer: Customer, completion: @escaping () -> Void) {
        semaphore.wait()
        InterfaceMessage.printStartWork(customer: customer)
        Thread.sleep(forTimeInterval: customer.workType.timeCost)
        InterfaceMessage.printCompleteWork(customer: customer)
        semaphore.signal()
        completion()
    }
}
```
> 생성 시점에 은행원 수를 주입받아 세마포어 작업 수로 만들어보았습니다.
> 우리 코드에서는 프로토콜로 추상화 시켜줄 필요가 없었으나, 혹여 추후에 `struct LoanTeller`, `struct DepositTeller`처럼 은행원 타입의 다형성을 추구하고자 한다면 TellerProtocol을 통해 다양한 은행원을 만들어낼 수 있습니다.

2023-11-09 06:11 UTC, comdori-wj commented
예금 semaphore를 2개로 주고  코딩하였습니다.
```swift
final class Bank {
    private let customerQueue = Queue<Customer>()
    private let dispatchGroup = DispatchGroup()
    private let dispatchLoan = DispatchQueue(label: "Loan", attributes: .concurrent)
    private let dispatchDeposit = DispatchQueue(label: "Deposit", attributes: .concurrent)
    private let semaphoreLoan = DispatchSemaphore(value: 1)
    private let semaphoreDeposit = DispatchSemaphore(value: 2)
    private var tellers: [Teller]
    private var servicedCustomersCount = 0
    private var totalServicedTimes: TimeInterval = 0.0
    
    init(tellers: [Teller]) {
        self.tellers = tellers
    }
    
    func work(completion: @escaping () -> Void) {
        gatherCustomers()
        
        for i in 0...1 {
            dispatchDeposit.async(group: dispatchGroup) { [self] in
                while customerQueue.isEmpty == false {
                    semaphoreDeposit.wait()
                    guard let customer = customerQueue.dequeue() else { return }
                    semaphoreDeposit.signal()
                    tellers[i].service(to: customer) { [self] in
                        servicedCustomersCount += 1
                        totalServicedTimes += tellers[i].workType.timeCost
                    }
                }
            }
        }
        
        dispatchLoan.async(group: dispatchGroup) { [self] in
            while customerQueue.isEmpty == false {
                semaphoreLoan.wait()
                guard let customer = customerQueue.dequeue() else { return }
                semaphoreLoan.signal()
                tellers[2].service(to: customer) { [self] in
                    servicedCustomersCount += 1
                    totalServicedTimes += tellers[2].workType.timeCost
                }
            }
        }
        
        dispatchGroup.wait()
        InterfaceMessage.printBankDidClose(servicedCustomersCount: servicedCustomersCount, totalServicedTimes: totalServicedTimes)
        completion()
    }
}

// MARK: Private Methods
extension Bank {
    private func gatherCustomers() {
        let totalCustomersCount = Int.random(in: 10...30)
        for count in 1...totalCustomersCount {
            let customer = Customer(id: count)
            customerQueue.enqueue(customer)
        }
    }
}
```
더불어, `커스텀 큐를 2개`로 만들고, 고객의 WorkType도 랜덤에서 `은행원이 지시하는 것`으로 바꿔 보았습니다. 
(고객은 무조건 은행원이 지정한 업무만 봐야함)
이렇게 하면 스텝3조건에 `고객의 업무 종류는 고객 생성시 임의로 지정합니다.` 도 만족합니다.
<img width="593" alt="스크린샷 2023-11-09 오후 3 11 29" src="https://github.com/tasty-code/ios-bank-manager/assets/22284092/1bb74151-2c20-4ac7-b5df-2a80e4fd38f5">

2023-11-09 10:13 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +                    semaphore.signal()
아뇨! 의도가 궁금했어요! ㅎㅎ

2023-11-09 10:26 UTC, merged