[STEP 2] 재근, 씨유
tasty-code/ios-bank-manager pull request #5
Opened 2022-10-13 03:00 UTC by Schro2109

# 구현
- BankManager 타입
- 메뉴 출력
- 업무 진행
- 결과 출력
# BankManager 타입
<img width="397" alt="스크린샷 2022-10-13 오전 11 56 45" src="https://user-images.githubusercontent.com/94955378/195488558-a9aa743d-1567-4c9f-9948-e7d28be38051.png">

# 출력 화면
1. 업무 시작
<img width="292" alt="스크린샷 2022-10-13 오전 11 53 28" src="https://user-images.githubusercontent.com/94955378/195488148-18ff1494-5326-4306-a3e1-61d6689fc4f1.png">
<img width="431" alt="스크린샷 2022-10-13 오전 11 53 38" src="https://user-images.githubusercontent.com/94955378/195488251-3b9068a3-8ada-48cc-99a3-7ecea062e261.png">

2. 종료
<img width="243" alt="스크린샷 2022-10-13 오전 11 53 52" src="https://user-images.githubusercontent.com/94955378/195488377-414e5aa2-40eb-4d0c-8e00-3dd4533d819c.png">

# 함수
showMenu() - 메뉴 출력
start() - 업무 시작
generateRandomClientNumber() - 고객의 수를 10~30 사이의 난수로 지정해 반환
inputClient() - 고객의 수만큼 고객 queue에 enqueue

2022-10-14 05:26 UTC, jaemuYeo requested changes
Step2도 고생많으셨습니다!!
로직에 대한 부분은 잘 동작하는 것을 확인했어요~👍
다만 너무 큰 중요포인트를 놓친 것같아요!!
저희 지금까지 해왔던 타입의 추상화와 일반화가 완전 파괴되어 버렸습니다,, ㅎㅎ
어떤 타입인지도 모를 main.swift 파일에서 모든 것이 돌아가고있어요.
캡슐화가 되어있지않은 곳에서 은닉화 처리도 되었구요 🤔

프로젝트 요구사항을 보며 UML이나 텍스트로 한번 어떤 타입이 필요한지 정리후에
다시한번 진행해보면 좋을 것같아요!
main.swift 파일에는 프로그램을 실행하는 힘스 하나만 호출할 수 있게요!

!! 매직넘버(문자)도 신경써주세요~

2022-10-14 05:26 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +enum Menu {
저의 경우라면 enum-case를 활용했을 것 같아요~
이전에도 말했듯 이렇게 static 상수를 선언하는 것은 여러 곳에서 범용적으로 사용할때 주로 활용하는 방식입니다!

start와 exit라는 네이밍보다도 조금 더 은행의 개점과 폐점에 가까운 네이밍을 해주어도 좋을 것같아요!

2022-10-14 05:26 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    mutating func startWork(for clientNumber: Int) {
해당 일은 BankManager가 하는 것인가요 아니면 Bank가 하는 일인가요?

2022-10-14 05:55 UTC, wormsJJG commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +enum Menu {
넵

2022-10-14 05:55 UTC, wormsJJG commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    mutating func startWork(for clientNumber: Int) {
BankManager를 프로토콜로 구현후 Bank에 상속시키는게 맞을것같네요!

2022-10-14 06:37 UTC, wormsJJG commented
# PR 반영
<img width="649" alt="스크린샷 2022-10-14 오후 3 33 31" src="https://user-images.githubusercontent.com/81068345/195778326-dbd7c42c-d2b2-44bc-bd5b-5ad9e7b33007.png">

<img width="378" alt="스크린샷 2022-10-14 오후 3 33 47" src="https://user-images.githubusercontent.com/81068345/195778389-39b484e7-a51c-48c0-b8fa-616a77365766.png">

<img width="275" alt="스크린샷 2022-10-14 오후 3 34 06" src="https://user-images.githubusercontent.com/81068345/195778445-c5b6e889-64bf-4f07-9b76-2597a7be5079.png">

## 설명
BankManager를 프로토콜로 만들어 Bank가 가지고 있어야하는 변수, 상수를 선언해주고, Bank의 주요 기능들을 함수로 선언 해주었습니다. 그리고, BankManager가 꼭 가지고 있지 않아도 되는 메뉴 보여주기, 랜덤수 뽑아주기, 대기열에 클라이언트 넣어주기 와 같은 서브 기능들을 extension 해주어 함수로 따로 만들어주었습니다.

2022-10-14 06:57 UTC, jaemuYeo requested changes
이 전보다 훨씬 타입설계가 잘 된거같아요!!
제가 생각하는 이번 스텝의 최소 타입들입니다
1. 은행
2. 은행원
3. 고객

타입들간에 서로 어떻게 의존하는지 고민해보며 조금 더 다듬어보면 좋을 거같아요!

2022-10-14 06:57 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    case bankOpen = "1"
rawValue보다 description을 활용해보아도 좋을 거같아요!

2022-10-14 06:57 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var clientNumber: Int = 0
은행에 고객이 항상 상주하나요??
고객 타입이 보이지 않는군요 🤔

2022-10-14 06:57 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        for _ in 1...clientNumber {
1이라는 숫자는 무엇을 의미하나요?

2022-10-14 06:57 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(clientNumber)명이며, 총 업무시간은 \(String(format: "%.2f", workTime))초 입니다.")
String(format: "%.2f", workTime)
이 값도 특정타입에 extension을 통해 다른 무언가를 통해서 코드화 할 수 있으면 좋겠어요~

2022-10-14 06:57 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        workTime += 0.7
0.7이라는 값은 무엇인가요?

2022-10-14 06:57 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/BankManager.swift
> +        Int.random(in: 10...30)
10 ~ 30의 숫자는 무엇을 의미하나요?

2022-10-17 01:48 UTC, wormsJJG commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    case bankOpen = "1"
넵

2022-10-17 01:48 UTC, wormsJJG commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var clientNumber: Int = 0
Client 타입을 따로 만들어야겠네요!

2022-10-17 01:49 UTC, wormsJJG commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        for _ in 1...clientNumber {
1...clientNumber는 범위를 의미하고 그중 1은 최소 범위, 첫번째 고객을 의미하므로 first로 매직넘버를 대채하겠습니다.

2022-10-17 01:49 UTC, Schro2109 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/BankManager.swift
> +        Int.random(in: 10...30)
고객의 최소인원~최대인원을 뜻하는 범위인데 extension을 이용해서 Int.minRange...Int.maxRange로 수정해봤습니다

2022-10-17 01:53 UTC, Schro2109 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        workTime += 0.7
업무에 걸리는 시간이 0.7초라서 저렇게 지정했는데 매직넘버 해결을 위해 extension 을 통해 Double.processingTime으로 표현해봤습니다

2022-10-17 01:56 UTC, Schro2109 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(clientNumber)명이며, 총 업무시간은 \(String(format: "%.2f", workTime))초 입니다.")
BankManager에서 값을 반환하는 함수 roundToString() 을 생성해 코드화 해봤습니다

2022-10-18 07:35 UTC, jaemuYeo reviewed
재근 씨유 고생많았습니다!!
이전보다 훨씬 역할 분담이 잘된것같아요~
타입을 잘 설계해야하는 이유는 의존성 주입과 재사용성 등을 고려해서 복잡한 코드를 피하기 위함입니다!
일반화, 추상화를 하는 과정이 아직은 어려운 부분이 있을텐데 자꾸자꾸 설계하다보면
금방 익숙해질겁니다 👍

POP를 설계할때에도 
잼킹 은행, 재근 은행, 씨유 은행이라는 다른 은행에서
모두 채택해 사용할수있는 공통점들을 잘 구상해보면서
구현해보면 좋을 것같아요!!

코멘트는 구현에 있어 문제가 없기에 다음 스텝을 통해 반영해보세요! 🙂

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Extension/Extension+Int.swift
> +extension Int {
쓰이는 곳들이 범용적이지 않다면 메서드안에 상수로 넣어도 될 것같아요!

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +enum Menu: String {
해당 객체가 Bank 파일에 같이 있는 이유는 무엇인가요?

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var description: String {
```swift
enum Menu {
    case bankOpen
    case BankClose
    
    var description: String {
        switch self {
        case .bankOpen:
            return "1"
        case .BankClose:
            return "2"
        }
    }
}
```

Munu 타입을 String으로 주기보다는 
연산프로퍼티에 String 타입을 주는 것은 어떤가요??

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +
불필요한 개행인 것같습니다!

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            guard let client = queue.dequeue() else {
해당 부분도 역할을 나눠주면 좋을 것같습니다!
`업무가 끝날때`의 행동이군요!

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +
👀

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +
개행하지 않아도 될 것같아요!

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    mutating func bankService(for client: Client) {
해당 메서드는 연산을 하지 않는데 mutating 키워드를 붙인 이유가 있나요?

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +import Foundation
개행이요! 👊

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    init(waitNumber: Int) {
구조체에서는 초기화를 해주지않아도 된답니다!

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/BankManager.swift
> +protocol BankManager {
프로토콜을 활용해보셨네요!! 
Swift에서 프로토콜의 네이밍 가이드를 어떻게 제시하고 있나요??

2022-10-18 07:35 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/BankManager.swift
> +    mutating func showMenu() {
메뉴를 표시해주는 네이밍인데 입력 역할까지 해주고 있네요!

2022-10-18 07:35 UTC, merged