[STEP3] JaeHyeok, 쫑
tasty-code/ios-bank-manager pull request #50
Opened 2023-11-09 07:05 UTC by shlim0

리뷰어: @monsteel
버드: @SimJaeHyeok,@shlim0

토니, 안녕하세요! [STEP 3] PR 드립니다🙌🏻

구조 설명✍🏻
```mermaid
classDiagram
    class Node {
        + data: T << read-only >>
        + next: Node<T>?
    }

	    class Queue {
        - head: Node<T>?
        - tail: Node<T>?
        - accumulatedCount: Int
        + enqueue(data: T)
        + dequeue(): T?
        + clear()
        + peek(): T?
        + isEmpty(): Bool
        + getAccumulatedCount(): Int
    }

    class Customer {
        + id: Int << read-only >>
		    - task: Taskable.Type
    }

    class BankManager {
        - bank: Bank
        + showMenu()
        + checkInput(): Int
        + startMenu(input: Int)
        + run()
        + messageOfOpen()
        + messageOfClose()
        + inputError()
        + close(customerCount: Int)
    }

    class Bank {
        - queueManager: QueueManager
        - bankers: Banker
        - customerCount: Int
				- elapsedTime: Double
        + prepareWork()
        + greetCustomer()
				+ openBank()
        + prepareCloseWork(): (Int, Double)
        - startWork()
				- insert(_ customer: Customer, _ group: DispatchGroup)
				- selectRandomTask(): Taskable.Type
    }

    class Banker {
				+ work(for customer: Customer)
				+ start(_ orderNumber: Int): String << static >>
				+ complete(_ orderNumber: Int): String << static >>
    }

    class QueueManager {
        - queue: Queue<Customer>
        + getQueue(): Queue<Customer>
        + clearQueue()
    }

		class Taskable {
		<< protocol >>
				+ name: String << static >>
				+ semaphore: DispatchSemaphore << static >>
				+ processingTime: Double << static >>
		}

		class DepositTask {
				+ name: String << static / read-only >>
				+ semaphore: DispatchSemaphore << static / read-only >>
				+ processingTime: Double << static / read-only>>
		}
	
		class LoanTask {
				+ name: String << static / read-only >>
				+ semaphore: DispatchSemaphore << static / read-only >>
				+ processingTime: Double << static / read-only>>
		}

    Node --* Queue : contains
		Queue --* QueueManager
    QueueManager --> Customer : contains
    QueueManager --* Bank : manages
		Customer --* Bank
		Banker --* Bank
		Banker --> Customer : interact with
		Bank --* BankManager : manages
		Bank --> Taskable
		BankManager --* main
		Customer --> Taskable
		DepositTask ..|> Taskable
		LoanTask ..|> Taskable
```

---

프로젝트 상세🧾
- Step 3의 은행에는 3명의 은행원이 근무합니다.
- 2명의 은행원은 예금업무를, 1명의 은행원은 대출업무를 처리합니다.
- 고객의 업무 종류는 고객 생성시 임의로 지정합니다.
- 한 명의 은행원은 한 명의 고객을 응대할 수 있습니다.
- 고객이 원하는 업무의 종류와 소요시간은 아래와 같습니다.
  - 대출 : 1.1초
  - 예금 : 0.7초
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다."3번 고객 대출업무 시작"
- 고객의 업무를 처리하면 아래와 같이 출력합니다."11번 고객 예금업무 완료"

---

## 변경 사항

- 은행원 수(예금 2명, 대출 1명)만큼 세마포를 걸었습니다.
    - 스레드가 3개여야 한다고 생각도 했었으나, 프로젝트 명세상 작업이 빨리 끝나는 예금(0.7초)이 대출(1.1초)보다 프로그램 실행 초반에 주로 처리되며 실행 끝에 대출 처리가 몰리는 만큼 스레드가 3개 초과여도 상관없다고 판단했습니다.
    
https://github.com/tasty-code/ios-bank-manager/assets/46235301/875d9173-e86c-4062-8f42-223afe058959

- SOLID 원칙 중, OCP를 적용했습니다.
    - 기존엔 SRP만 최대한 충족시켜보자고 생각하였으나 `switch case`로 길어지는 코드를 리팩토링 하고자 했습니다.
    - 또한, 업무 처리의 경우 DIP를 만족합니다.
- `Bank`
    - `bankers: [Banker]`에서 `banker: Banker`로 변경했습니다. 다른 업무여도 `Banker` 타입만을 통해 처리할 수 있기 때문입니다.
- `Banker`
    - id, task는 `Customer`에서만 사용하는 것으로 변경했습니다. 다른 업무여도 `Banker`가 처리할 수 있으며, 이 때문에 `Identifiable`프로토콜을 채택할 필요도 없어졌습니다.
    - 기존엔 `static let delay: Double = 0.7`과 같이 업무 처리 시간을 은행원이 담당했습니다. R&R에 맞기에 직관적으로 이해할 수 있으나, OCP를 만족하기 위해 제거했습니다.
- 기존 `Task`에 있던 `print()`문을(i.e, "\(orderNumber)번 고객 \(task)업무 시작") `Banker`로 옮겼습니다. OCP를 만족하기 위해 기존 enum 타입이었던 `Task`는 삭제하고 protocol `Taskable`로 변경하였습니다.
- `Taskable`
    - 업무에 따라 변경되는 값들을 프로토콜로 묶었습니다.
    - 이를 통해 같은 로직을 유지하되(close), 업무가 바뀔 때 마다 `Taskable`을 만족하는 업무만 추가(open)해주면 됩니다.
    
    ```swift
    protocol Taskable {
        static var name: String { get }
        static var semaphore: DispatchSemaphore { get }
        static var processingTime: Double { get }
    }
    ```
    
    ```swift
    struct DepositTask: Taskable {
        static let name: String = "입금"
        static let semaphore: DispatchSemaphore = DispatchSemaphore(value: 2)
        static let processingTime: Double = 0.7
    }
    ```
    
    ```swift
    struct LoanTask: Taskable {
        static let name: String = "대출"
        static let semaphore: DispatchSemaphore = DispatchSemaphore(value: 1)
        static let processingTime: Double = 1.1
    }
    ```
    
- `Customer`
    - 따라서, `Customer`가 추가될 때 마다 특정 업무가 무엇인지 구별하여 은행원이 처리할 수 있도록 `task` 변수를 추가했습니다. `Taskable.Type`으로 둔 이유는, `Taskable`이 `static` 변수로만 구성되어 있고 이는, 인스턴스가 아닌 타입에 의존하는 값이기 때문에 이 점을 통일하고자 했습니다.
    
    ```swift
    struct Customer: Identifiable {
        let id: Int
        private(set) var task: Taskable.Type
    }
    ```
    
- `Queue`
    - 또한, `Customer`에서 `id`를 통해 고객 수를 세기 때문에 `accumulatedCount: Int`를 삭제했습니다. 따라서, `func getAccumulatedCount() -> Int`도 삭제했습니다.
    - 고객 수가 10명일 때, 2명-10명 or 1명-9명의 작업 처리만 콘솔창에 띄워주는 버그가 있어 이를 수정하기 위해 `dequeue()`시 뽑을 데이터를 반환하도록 수정했습니다.
    
    ```swift
    @discardableResult
    func dequeue() -> T?{
        let toDequeue = head?.data
        if head != nil {
            head = head?.next
        }
        
        if head == nil {
            tail = nil
            
        }
        return toDequeue
    }
    ```

## 질문 사항 📝

- 현재 구조는 고객이 있는 `queue`에서 뽑은 다음에 `DispatchQueue`로 보내주고 있는데요. 그럼 앞서 언급한 것처럼 스레드 갯수가 3개 초과한 상태로 고객이 대기하게 됩니다. 실생활로 비유를 들자면 대기열에서 뽑혀서 고객이 예금 창구 or 대출 창구 바로 앞에서 앞에 있는 고객의 업무가 끝날 때 까지 대기하고 바로 업무를 보는 방식인데요. 프로젝트 명세를 충실히 이행하기 위해 해당 방식이 맞다고 생각하나, 상식적으로는 다소 거리가 있는 방식인데요. 이에 대해 어떻게 생각하시나요?
    
    ```swift
    private func startWork() {
      let queue = queueManager.getQueue()
      let group = DispatchGroup()
    
      while !queue.isEmpty() {
          **let customer = queue.dequeue()**
          
          guard let customer = customer else {
              return
          }
          
         insert(customer, group)
      }
      group.wait()
    }
    
    private func insert(_ customer: Customer, _ group: DispatchGroup) {
        let task = customer.task
        let semaphore = task.semaphore
        
        DispatchQueue.global().async(group: group) { [self] in
            semaphore.wait()
            banker.work(for: customer)
            semaphore.signal()
        }
    }
    ```

- 그외 프로젝트를 보고 개인적으로 개선했으면 하는 사항있으면 코멘트 부탁드립니다!

- 참고: 해당 프로젝트를 진행하면서 고민했던 사항들입니다.
[참고 자료.pdf](https://github.com/tasty-code/ios-bank-manager/files/13304828/default.pdf)

2023-11-10 18:32 UTC, Monsteel requested changes
안녕하세요 :)
step3 PR리뷰드립니다~

이번 PR에서 힘을 실어주신 부분이 SOLID의 OCP원칙인것 같은데요,
전반적으로 좀 SOLID에 대해 이해하고, OCP 개념을 충분히 코드에 녹여내보는 시간이 되셨을거라 생각합니다.

다만, 단순히 적용해보고 스터디를 해본다는 경험의 관점에서, `다른 팀의 PR을 보고 OCP를 적용해도 좋겠다는 생각이 발단이었다.`고 말씀해주신 부분은 이번 프로젝트에서 충분히 OCP를 적용해볼 수 있는 이유가 되지만, 실제로 은행창구 앱을 개발하는 상황에서 해당 이유는 다소 부족한 부분이 있습니다.

그래서 OCP원칙에 대한 두분의 이야기를 조금 더 들어보고 싶은데요,

이번 스텝에서 OCP를 적용해보셨을 때, 프로젝트에서 어떤 강점이 있다고 느끼셨는지, 그에 비해 약점은 없었는지에 대해 고민하신 부분들을 아래 코멘트로 남겨주시면, OCP원칙, 넘어서 SOLID원칙에 대해 깊게 생각해볼만한 여러 인사이트들을 함께 찾아볼 수 있을것 같습니다. 

`은행 업무 유형이 추가될 때마다 매번 switch case 로 경우의 수를 만들어줘야 하는 애로 사항`이라고 말씀해 주신 부분에서 애로사항이라고 느끼신 부분에 대해 조금 더 자세한 이야기를 들어볼 수 있을까요?

개인적으로, 말씀주신 switch case문의 사용은 누락된 케이스의 발생을 방지하는 순방향이라고 느껴지고 있거든요 :)

코멘트 부탁드리고, 이어서 남겨주신 질문에 대한 제 의견 드립니다 👍 

> 현재 구조는 고객이 있는 queue에서 뽑은 다음에 DispatchQueue로 보내주고 있는데요. 그럼 앞서 언급한 것처럼 스레드 갯수가 3개 초과한 상태로 고객이 대기하게 됩니다. 실생활로 비유를 들자면 대기열에서 뽑혀서 고객이 예금 창구 or 대출 창구 바로 앞에서 앞에 있는 고객의 업무가 끝날 때 까지 대기하고 바로 업무를 보는 방식인데요. 프로젝트 명세를 충실히 이행하기 위해 해당 방식이 맞다고 생각하나, 상식적으로는 다소 거리가 있는 방식인데요. 이에 대해 어떻게 생각하시나요?

==
("말씀주신 상식적으로는 다소 거리가 있는 방식이다"고 해주신 부분에서 상식적인것 == 실생활 로 인지하고 의견드립니다.)

해당 구조에서 의문이 드는 포인트가, `현실과 코드의 괴리`라면, 당연히 의문을 가질 수 있고, 충돌이 되는 지점이 충분히 생길 수 있다고 생각합니다.

전하고 싶은 주된 의도는, "실생활과 코드의 사고 흐름이 일치하지 않는 부분에서 불편함을 느끼실 필요는 전혀 없다"는걸 말씀드리고 싶어요.

왜냐면 `프로그래밍적 사고`, `소프트웨어적 사고`라는 개념들도 있고,
알고리즘을 풀 때 우리가 현실적인 사고 보다는 효율적인 사고들을 선택하는 것과 비슷한 맥락으로 이해해보면 어떨까 합니다.

100% 싱크를 맞추기는 어렵다는 것들이 위와 같은 개념과 현상들로 증명되고 있으니까요.


==

이번 PR의 첫번째 리뷰는 여기까지 하도록 할게요.
확인 부탁드려요. 수고하셨어요!

2023-11-10 18:32 UTC, Monsteel commented on BankManager.swift
@SimJaeHyeok 
마지막 재혁이 남겨준, 213c116cea3fe885fdde2c6891354e66d3fea441 커밋은 이번 STEP에서는
불필요한 수정사항이라고 생각되는데요, 다른 이견 없으시면 해당 커밋 `revert` 부탁드립니다.

이렇게 되면 커밋 히스토리 상, 이번 PR에서 재혁이 이번 프로젝트에서 기여한 부분을 확인하기가 어려운데요,
쫑과 어떻게 이번 PR을 풀어가셨는지, 재혁이 간단하게 코멘트 남겨주시면 감사하겠습니다~

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocols/Taskable.swift
> +}
Task 추상화를 잘 진행해 주셨네요. 

그런데, 이 Task를 구현하지 않고도 다양한 방법들이 있었을것 같은데요,
예를들어 Task struct를 만들어, `depositTask`와 `loanTask`에 해당하는 각각의 `static instance` 를 생성하는 등과 같이요.

아마 OCP 원칙을 Task구현에도 적용해보려 하신것 같은데,
해당 구조에서 Taskable 추상화가 꼭 필요한 부분인지 한번 고민해봐 주시는것도 좋을것 같습니다.

processingTime(delay)이 Task 단위로 넘어온 변화는 아주 좋아보입니다. 👍

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Tasks/DepositTask.swift
> +}
이렇게 선언된 DepositTask는 DepositTask()와 같이 불필요한 인스턴스 생성이 가능합니다.
private init을 구현하거나, enum으로 선언해 불필요한 생성을 방지할 수 있습니다.

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Queue.swift
> +    func dequeue() -> T?{
@discardableResult를 사용해 주셨네요. 적절한 해결책으로 잘 대처해주신것 같습니다. 👍

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>      }
greetCustomer, openBank를 private 함수로 정의해 예상하지 못한 함수의 사용을 방지하는건 어떨까요?

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        self.elapsedTime = timeElapsed
timeElapsed, elapsedTime <- 변수명이 통일되지 않은데에는 다른 이유가 있나요 ?

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
개인적으로 tuple사용은 지양하는 편입니다. 특히 label이 없는 형태는 더더욱 그런 편인데요,

일단은 알아보기 어렵고, 해당 tuple이 사용되는 곳에서 해당 값이 어떤 값인지 확인하려면 구현부를 일일이 확인해야 하는 불편함이 있습니다. 참고해주세요

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Queue.swift
>      }
`accumulatedCount`가 Queue 구현부에서 빠져나온 구조는 아주 좋은것 같습니다. 👍 
실제 사용부의 사용에 따라 core한 구조(이곳에서는 Queue)가 수정되는 방식은 좋지못해 보였었거든요.

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocols/Taskable.swift
> +    static var semaphore: DispatchSemaphore { get }
semaphore의 value는 창구의 수와도 같은데요,

창구(thread)와, 업무(Task)는 다른 개념인데, 창구의 수를 업무가 가지고 있는 지금의 구조는 다소 인지하기에 어려움이 있다는 생각이 드는데요,

이 구조에 대해서 두분의 의견은 어떻게 정리되셨나요 ?
어떻게 인지하셨는지, 괜찮은 구조라고 생각하시는지 등을 중심으로 두분의 의견이 궁금합니다!

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerTests/BankManagerTests.swift
> +        let customer = Customer(id: 999, task: DepositTask.self)
테스트코드이지만,
Customer가 for문안에서 돌지 않고 독립적으로 도는 경우에 Id를 직접 이렇게 입력해야 하는 상황이 발생하고, 이는, 어떤 값을 넣어야 하는지 고민부터 시작해서, 중복에 대해 신경써야하는 피로도도 상당한 구조라고 생각되는데요, Customer의 생성자에서 id를 UUID로 자동으로 지정해주는 방식은 어떠신지 궁금합니다.

2023-11-10 18:32 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Banker.swift
> +}
id == orderNumber이다 라는 전제가 있어야 비로소 해당 구조가 이해가 되었고,
앞서 남긴 id를 UUID로 변경하는 방향에 대해 여쭈어본 리뷰가 무색해지는데요,

사실 이는, id라는 변수에는 해당 고객의 순서를 나타내고 있다는 의미가 포함되어 있지 않아, 해당 전제를 파악하기에 어려움이 있다는 구조적 문제를 나타내는 대목이라는 생각도 듭니다.

id라는 변수가 orderNumber를 나타내고 있음을 조금 더 직관적으로 표현할 수 있는 좋은 방법은 없는지, 없다면 두분은 어떤 인지를 가지고 해당 영역을 바라보고 계신지 공유해주시면, 제가 해당 구조를 이해하는데에 도움이 될 것 같습니다.

2023-11-11 06:57 UTC, shlim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>      }
`private` 키워드 추가를 잊었습니다. 반영했습니다!

2023-11-11 07:09 UTC, shlim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
개인적으로 tuple을 사용하는데 지양하는 의견에 저희팀도 동의합니다.

리팩터링이 미처 다 이뤄지지 않았던 것 같습니다. 수정했습니다!

```swift
func prepareCloseWork() -> Result {
        queueManager.clearQueue()
        let result = Result(customerCount: customerCount, elapsedTime: elapsedTime)
        return result
    }
```

2023-11-11 07:10 UTC, shlim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        self.elapsedTime = timeElapsed
단순한 실수였습니다. `elapsedTime`으로 통일했습니다!

2023-11-11 07:32 UTC, SimJaeHyeok commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocols/Taskable.swift
> +    static var semaphore: DispatchSemaphore { get }
실생활에 접근 하였을 때 업무에 따라 창구가 나눠져있고 업무 별로 은행원들이 배정 되어있기 때문에 업무속에 창구의 수를 두었습니다.
따라서 창구가 업무에 종속된다고 생각해서 `semaphore`를 `Taskable`에 포함시켰습니다.

2023-11-11 07:51 UTC, SimJaeHyeok commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Banker.swift
> +}
말씀 하신대로 고객에게 `id`를 부여할 필요가 없다고 생각하였고 `id`보단 순번이 맞다고 생각하여 `Identifiable` 프로토콜을 채택하지 않고 Customer의 프로퍼티 네이밍을 `id`에서 `orderNumber`로 수정하였습니다.

2023-11-11 08:17 UTC, shlim0 commented on BankManagerConsoleApp/BankManagerTests/BankManagerTests.swift
> +        let customer = Customer(id: 999, task: DepositTask.self)
(아래 답변을 참고) `Customer`에서 `id` 변수를 `orderNumber`로 의미가 좀 더 명확히 전달되게 끔 변경했습니다. 

테스트 코드를 작성할 때, 일일히 `Customer`의 `orderNumber`를 입력하는 일은 꽤 번거로워 보이는데요. 따라서, 테스트 코드 파일 내에 `insertCustomer()`를 추가하여 재사용성을 더 높였습니다.

다만, `Bank`에서 `greetCustomer()`와 비슷한 로직이지만, `private` 함수이기 때문에 테스트 코드에서 호출할 수 없어 별도로 구현했는데요. 이렇게 해도 된다 생각한 이유는 더미 데이터를 만드는 코드라 생각해 문제 없다고 판단했습니다.

```swift
func insertCustomer(until customerCount: Int) -> Queue<Customer> {
        let queue = sut.getQueue()
        
        if customerCount <= 0 {
            return queue
        }
        
        for index in 1...customerCount {
            let newCustomer = Customer(orderNumber: index, task: DepositTask.self)
            
            queue.enqueue(newCustomer)
        }
        
        return queue
    }
```

2023-11-11 08:30 UTC, SimJaeHyeok commented on BankManager.swift
혼동이 와서 STEP3에 커밋이 되었네요 `revert` 하였습니다!

STEP3에 실생활에서의 일의 진행과 컴퓨터적 사고를 접목시킨 설계부분에 많은 기여를 했다고 생각합니다 
구현 중에 독감에 걸리게 되어 동시성 프로그래밍 파트 부분 공부가 지체되었습니다 이번 독감이 이정도로 지속이 될 줄 몰랐습니다 
STEP3 진행에 있어 차질이 있다고 생각하여 쫑에게 양해를 구하고 쫑이 STEP3를 진행을 하고 나은 후에  학습을 진행하였고 코드 설명을 듣고 Refactoring하는 과정에 다시 참여하게 되었습니다. 다음 STEP에선  다시 짝프로그래밍 진행하도록 하겠습니다 죄송합니다

2023-11-11 08:41 UTC, SimJaeHyeok commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocols/Taskable.swift
> +}
지금은 한정적인 업무를 명시 해놓은 상황이고 토니가 말씀하셨던 대로 `switch`문을 사용하게 된다면 한정적인 업무이기 때문에 `default`를 구현할 필요가 없이 가독성이 좋게 코드를 작성할 수 있습니다. 하지만 예를 들어 보험이라는 업무가 추가 되었을 경우엔 또 case를 만들고 추가적인 코드 수정이 불가피해보입니다. 따로 `Taskable` 추상화를 통한다면 그 업무라는 주제로 조금 더 업무에 대한 내용이 한눈에 들어오고 확장이 더욱 용이해 보이기 때문에 `Taskable` 추상화를 하였습니다.

2023-11-11 08:41 UTC, shlim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Tasks/DepositTask.swift
> +}
싱글톤처럼 사용하고자 했는데 `private init`을 붙이지 않았네요. 불필요하게 인스턴스가 생성될 수 있다는 것을 간과하고 수정했습니다!

2023-11-11 08:59 UTC, shlim0 commented
> 안녕하세요 :)
> step3 PR리뷰드립니다~
> 
> 이번 PR에서 힘을 실어주신 부분이 SOLID의 OCP원칙인것 같은데요,
> 전반적으로 좀 SOLID에 대해 이해하고, OCP 개념을 충분히 코드에 녹여내보는 시간이 되셨을거라 생각합니다.
>
> 다만, 단순히 적용해보고 스터디를 해본다는 경험의 관점에서, 다른 팀의 PR을 보고 OCP를 적용해도 좋겠다는 생각이 발단이었다.고 말씀해주신 부분은 이번 프로젝트에서 충분히 OCP를 적용해볼 수 있는 이유가 되지만, 실제로 은행창구 앱을 개발하는 상황에서 해당 이유는 다소 부족한 부분이 있습니다.
> 
> 그래서 OCP원칙에 대한 두분의 이야기를 조금 더 들어보고 싶은데요,
> 
> 이번 스텝에서 OCP를 적용해보셨을 때, 프로젝트에서 어떤 강점이 있다고 느끼셨는지, 그에 비해 약점은 없었는지에 대해 고민하신 부분들을 아래 코멘트로 남겨주시면, OCP원칙, 넘어서 SOLID원칙에 대해 깊게 생각해볼만한 여러 인사이트들을 함께 찾아볼 수 있을것 같습니다.
> 
> 은행 업무 유형이 추가될 때마다 매번 switch case 로 경우의 수를 만들어줘야 하는 애로 사항이라고 말씀해 주신 부분에서 애로사항이라고 느끼신 부분에 대해 조금 더 자세한 이야기를 들어볼 수 있을까요?
> 
> 개인적으로, 말씀주신 switch case문의 사용은 누락된 케이스의 발생을 방지하는 순방향이라고 느껴지고 있거든요 :)
> 
> 코멘트 부탁드리고, 이어서 남겨주신 질문에 대한 제 의견 드립니다 👍

얘기주신 것 처럼 OCP를 배워보는 측면에서 프로젝트에 적용한 것이 시초였습니다. 프로젝트 명세상 OCP를 적용하는 것이 다소 over-engineering 인 것을 인지하고 있었습니다. 그래도 OCP를 적용한 이유는 확장성을 고려했을 때, 매력적이라 느꼈기 때문입니다.

매번 `switch-case`를 사용하는 경우에 대해 얘기해 보겠습니다. `switch-case`가 위치하는 곳은 코드 로직이 위치하는 곳인데 업무 유형(task)가 추가되거나 삭제될 때마다 휴먼 에러가 발생할 가능성이 있습니다. 또한, 길이가 길어지면 가독성이 떨어지며, 업무 유형만 다르고 같은 로직이 반복되는 단점이 있다는 것을 애로사항으로 인지하였습니다.

물론, OCP를 적용해도 업무 유형을 매번 추가해줘야 합니다. 파일 갯수가 늘어나기 때문에 이 점이 안 좋아질 수는 있으나, 로직을 건드리지 않는다는 점이 큰 차이점이라 생각합니다. 또한, 앞서 답변드린 것 처럼 `Taskable`과 같이 프로토콜의 네이밍이 사전에 설명된 상황이 아니라면 혼동스러울 수 있을 것 같습니다. 따라서, 추상화를 하는데 신경써야 이해하는 데 있어 중요하다는 것을 깨달았습니다. 개인적으로 `switch-case`로 명시되면 코드를 이해하는 데 있어 굉장히 직관적이라 생각합니다. 무엇보다도, OCP를 적용하는데 걸리는 시간이 상당했습니다. 처음 적용하는 것이어서 그럴 수도 있겠지만, 초기 cost가 많이 든다는 것은 명백한 단점인 것 같습니다.

2023-11-13 00:36 UTC, Monsteel commented on BankManager.swift
아고.. 🙏 몸조리 잘 하시고 얼른 쾌차하시길 바래요! 😭 코멘트 감사합니다 :)

2023-11-13 00:57 UTC, Monsteel approved these changes
안녕하세요 재혁 쫑 👍 
이번 프로젝트도 수고 많으셨습니다.

코멘트 잘 남겨주시고, 코드에 반영되어야 할 사항들 잘 반영해주셨습니다 👍 

두분의 답변과 별개로 이번 스텝에서 드리고 싶은 말이 있는데요,

원칙, 아키텍쳐 등이 처해있는 문제의 완벽한 해결책이 될수는 없다는 사실을 꼭 인지하고, 원칙을 신봉하기 보다는 하나의 지식으로 활용하여,
문제해결 상황에 처한 개발자가 직접 사고하는 과정이 꼭 필요합니다.
오히려 이런 원칙들이 독이되는 상황이 발생할 수 있고, 주된 목표는 항상 코드의 유지보수성과 확장성을 향상시키는 데에 있어야 합니다 👍 

그리고 원작자의 의도와 다르게 사용되는것도 경계해야 하는 방향 중 하나인데요,
배우고자 하는 개념에 대한 역사를 타고 올라가서 학습하는 방법은 이를 경계하는데에 도움이 되었던 것 같습니다.

이런 부분들을 인지하고 학습하신다면, 두분이 더 단단한 프로그래밍적 사고를 기르시는데에 도움이 되실것 같아 참고차 말씀드려요 :)

이번STEP 수고하셨고, 이번 스텝은 여기서 마무리하겠습니다 👍

2023-11-13 00:57 UTC, merged