은행창구 관리 앱 [STEP4] 뉴준성, Howard
tasty-code/ios-bank-manager pull request #51
Opened 2023-11-15 01:25 UTC by JEON-Sungsu

리뷰어 : @zdodev

## Step4 명세서

- Step 3의 은행을 UI 앱으로 전환합니다.
- 이번 프로젝트의 UI구성은 ‘코드'만 사용하여 구현합니다.
- 고객 정보를 표현할 커스텀뷰를 구현합니다.
    - 뷰에 포함될 정보 : 고객번호, 업무종류
- 대기열은 스택뷰를 활용합니다.
    - 화면 전체를 여러개의 중첩된 스택뷰로 구성하는게 편리할 수 있습니다.
- 화면 구성
    - 업무중인 고객 리스트, 대기중인 고객 리스트업무시간 타이머, 고객 10명 추가 버튼, 초기화 버튼
- 고객 10명 추가 버튼을 통해 임의의 10명의 고객이 추가됩니다.
- 초기화 버튼을 누르면 대기중인 고객과 타이머 모두 초기화됩니다.
- 모든 업무가 끝나고 대기중인 고객이 없으면 업무시간 타이머는 멈춥니다.
- 고객이 추가되어 다시 업무를 처리하면 타이머가 동작합니다.
    - 초기화 하기 전까지 업무시간은 초기화하지 않고 누적합니다.

## 프로그램 동작 화면

- Gif라서 끊키는것 처럼 보이는데, 실제로는 안끊킵니다…!!!

![step4](https://github.com/tasty-code/ios-bank-manager/assets/63297236/cd60c638-fabd-4ab3-99b4-8f7cf1329678)

## 코드 설명

- UI Extension
    - 자주 사용하는 UI들, label, button, stackView 등은 Extension을 활용하여, ViewController 에서 최대한 코드길이를 줄이고 가독성을 높일 수 있도록 만들어 보았습니다.
    
    ```swift
    //ViewController
    
    private let contentStackView = UIStackView(.vertical, 15, .fill)
        
    private let topButtonWrap = UIStackView(.horizontal, 0, .fillEqually)
    
    private let stateIndiCatorWrap = UIStackView(.horizontal, 0, .fillEqually)
    
    private lazy var timeLabel = TimerLabel(prefix: "업무시간", fontSize: 24)
    
    private let waitingLabel = UILabel("대기중", 35, .white, .center, .systemGreen)
    
    private let taskingLabel = UILabel("업무중", 35, .white, .center, .systemIndigo)
    
    private let waitingListWrap = UIStackView(.vertical, 0, .fillEqually)
    
    private let taskingListWrap = UIStackView(.vertical, 0, .fillEqually)
    
    ```
    

- UILabel을 상속받아서 커스텀 UI를 제작해 보았습니다.
    
    ```swift
    final class CustomerLabel: UILabel {
        var customer: Customer
        
        init(customer: Customer) {
            let color: UIColor = customer.task.name == "예금" ? .black : .systemPurple
            self.customer = customer
            
            super.init(frame: .zero)
            
            self.text = "\(customer.id) - \(customer.task.name)"
            self.textColor = color
            self.font = UIFont.systemFont(ofSize: 25)
            self.textAlignment = .center
        }
        
        required init?(coder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
        
    }
    
    final class TimerLabel: UILabel {
        private var prefix: String
        private var startTime: Date?
        private var pauseTime: TimeInterval?
        private var subscription: AnyCancellable?
        
        init(prefix: String, fontSize: CGFloat) {
            self.prefix = prefix
            super.init(frame: .zero)
            
            textAlignment = .center
            text = "\(prefix)-00:00:000"
            textColor = .black
            translatesAutoresizingMaskIntoConstraints = false
            font = UIFont.monospacedSystemFont(ofSize: fontSize, weight: .medium)
        }
        
        deinit {
            resetTimer()
        }
        
        required init?(coder: NSCoder) {
            fatalError("")
        }
        
        func startTimer() {
            if startTime == nil {
                startTime = Date()
            }
            
            if subscription == nil {
                subscription = Timer.publish(every: 0.001, on: .current, in: .common)
                    .autoconnect()
                    .sink { updatedTime in
                        if let pauseTime = self.pauseTime {
                            let formattedTime = (pauseTime + updatedTime.timeIntervalSince(self.startTime!)).formatTimer()
                            self.text = "\(self.prefix)-\(formattedTime)"
                        } else {
                            self.text = "\(self.prefix)-\(updatedTime.timeIntervalSince(self.startTime!).formatTimer())"
                        }
                    }
            }
        }
        
        func pauseTimer() {
            subscription?.cancel()
            subscription = nil
            startTime = nil
            guard let formatTime = text!.formatTimer() else {
                return
            }
            pauseTime = TimeInterval(formatTime)
        }
        
        func resetTimer() {
            subscription?.cancel()
            subscription = nil
            startTime = nil
            pauseTime = nil
            text = "업무시간-00:00:000"
        }
    }
    ```
    

- DispatchQueue completionHandler 사용
    - 비동기 함수를 실행하는 Bank모델에서, completionHandler를 매개변수로 받아서, 비동기 작업이 끝나면 UIView를 업데이트 해 줄 수 있도록 만들어보았습니다.
    - UI관련 작업은 main 쓰레드에서 진행되도록 main 디스패치 큐를 사용하였습니다.
    
    ```swift
    func beginTask(completionHandler: @escaping () -> Void) {
            addRandomCustomers(handledCustomer, taskTypes: LoanTask.self, DepositTask.self)
            
            while !customerQueue.isEmpty {
                if let customer = customerQueue.dequeue() {
                    DispatchQueue.main.async(group: group) {
                        let label = CustomerLabel(customer: customer)
                        self.waitingHandler(label)
                        self.assignTask(label)
                    }
                }
            }
            
            handledCustomer += 10
            group.notify(queue: .main) {
                completionHandler()
            }
        }
        
        func assignTask(_ customer: CustomerLabel) {
            let task = customer.customer.task
            let semaphore = type(of: task).semaphore
            let queue = type(of: task).dispatchQueue
            
            queue.async(group: group) {
                semaphore.wait()
                if !customer.customer.workable {
                    semaphore.signal()
                    return
                }
                DispatchQueue.main.async {
                    self.changingHandler(customer)
                }
                Thread.sleep(forTimeInterval: task.processingTime)
                DispatchQueue.main.async {
                    self.processingHandler(customer)
                }
                semaphore.signal()
            }
        }
    ```

2023-11-15 15:05 UTC, zdodev requested changes
안녕하세요. @JEON-Sungsu , @newJunsung !

이번 Step 4도 잘 구현해주셨네요!
요구사항도 잘 만족하고, 고객과 은행원이 잘 동작합니다.😁
동시성 문제와 은행 로직도 잘 구현해보셨네요!

몇 가지 궁금증 위주로 코멘트를 남겨보았습니다.
같이 고민해보면 좋을 것 같습니다!

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/DepositTask.swift
> +    let name: String = "예금"
예금, 대출 업무를 문자열 대신 `enum` 으로 정의해보는 것은 어떨까요?
의견이 궁금합니다!

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
메인 스토리보드를 제거하고 코드로 `Window` 를 만들어보셨네요👍

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
>      override func viewDidLoad() {
코드의 위치도 의미와 작성한 의도를 가지고 있다고 생각이 듭니다.🙂
메서드(`viewDidLoad`)를 최상단에 위치한 이유를 알 수 있을까요?

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private let taskingListWrap = UIStackView(.vertical, 0, .fillEqually)
UI 요소를 한 줄로, 그리고 간결하게 작성한 것은 좋은 것 같습니다!
다만, UI 요소에 어떤 설정을 한 것인지, 파라미터가 무엇을 의미하는지 알기가 어려워 보입니다.
이후에 코드를 수정하게 된다면, 정의 부분을 하나씩 다 확인하면서 수정해야 하지 않을까 싶습니다.
개인적으로 UI 요소의 선언과 프로퍼티 설정을 분리하지 않고 한군데에서 작성하는 편입니다.🙂
이에 대한 의견이 궁금합니다! 개선을 해주셔도 좋고, 의견을 달아주셔도 좋습니다!

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    }()
클로저를 사용해서 프로퍼티 기본값을 설정해보셨네요.👍

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private func setConstraint(){
공백 오타가 있는 것 같습니다.

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +extension ViewController: BankUIDelegate {
Delegate 패턴을 활용해보셨네요.👍

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +import Foundation
`Foundation` 프레임워크를 추가한 이유가 있을까요?

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +    var customer: Customer
고객 정보를 가지는 커스텀 UILabel을 구현해보셨네요!
고객 정보를 주입받는 형태로 커스텀하신 이유가 궁금합니다!
다른 구현 형태도 선택지에 있었는지 궁금합니다!

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +        self.textAlignment = .center
코드마다 프로퍼티에 접근할 때, `self`를 사용하는 경우와 사용하지 않은 경우가 있습니다.
각각 어떤 이유에서 작성하는지 궁금합니다! 일관성있게 작성해보는 것은 어떨까요?

2023-11-15 15:05 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/TimerLabel.swift
> +                        let formattedTime = (pauseTime + updatedTime.timeIntervalSince(self.startTime!)).formatTimer()
위에서 `startTime` 값을 할당하는 구문이 있어서 현재는 괜찮을 수 있지만,
이후에 코드의 수정, 변경, 위치 이동이 발생했을 때, 강제 언래핑 구문이 아주 위험하게 동작할 수도 있지 않을까 싶습니다.
옵셔널 언래핑을 통해 안전하게 처리해보는 것은 어떨까요?

2023-11-16 01:11 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
>      override func viewDidLoad() {
`ViewController` 안에 UI 요소들이 너무 많아 viewDidLoad를 기존의 방식대로 프로퍼티 밑에 두면, 찾기 어려울 수 있다는 생각이 들었습니다. 나중에 코드를 수정하게 되면, UI프로퍼티를 수정하는 것보다 viewDidLoad를 수정할 일이 많을 것으로 예상되어 viewDidLoad를 최상단에 위치시켰습니다.

2023-11-16 01:13 UTC, JEON-Sungsu commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private func setConstraint(){
수정하였습니다!

2023-11-16 01:14 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +import Foundation
Foundation 프레임워크를 잘못 추가한 것 같습니다. 수정했습니다.😅

2023-11-16 01:22 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/TimerLabel.swift
> +                        let formattedTime = (pauseTime + updatedTime.timeIntervalSince(self.startTime!)).formatTimer()
언래핑을 실패하면 에러를 발생시키게끔 수정했습니다.

2023-11-16 01:24 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +        self.textAlignment = .center
init의 경우에는 self를 붙이게 끔 했습니다.
함수에서 자기 자신의 프로퍼티를 접근할 때는 self를 붙이지 않게 했습니다.
이렇게 한 이유는, Init의 경우에는 매개변수가 클래스의 프로퍼티와 동일한 이름을 가져가는 경우가 빈번하기 때문에,
구분하고자 self 붙이도록 했습니다.

2023-11-16 01:24 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private func setConstraint(){
수정했습니다.

2023-11-16 01:31 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private let taskingListWrap = UIStackView(.vertical, 0, .fillEqually)
분리해서 작성한 이유는 ViewController의 코드를 더 간결하게 해보고자 시도했던 방법입니다.
코드를 다시 확인해보니, 생성자에 매개변수에 이름이 없는 것은 각 매개변수가 무엇을 의미하는지 알아내기 어려울것 같다는 생각이 들었습니다.
```swift
private let taskingLabel = UILabel("업무중", 35, .white, .center, .systemIndigo)
```
위 코드의 경우, `.white`와 `. systemIndigo` 중에 무엇이 배경색이고, 글씨 색인지 알 방도가 없었습니다.
따라서 생성자에 매개변수명을 적도록 수정했습니다.

UI 요소의 작성 방법은 사실 팀 단위의 코드 합의를 통해 이루어지는 것이라고 생각하기 때문에, 어떤 방식이 더 적합한지는 팀마다 다를 것 같습니다.

2023-11-16 01:48 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +    var customer: Customer
프로젝트 초기에는 CustomerLabel을 굳이 만들 필요가 없다는 생각을 했었습니다.
왜냐하면 UILabel에 convenience init(customer: Customer)을 활용하면 될 것 같았기 때문입니다.

초기화 버튼을 눌렀을 때, 대기중 스택뷰에 있던 고객을 없애는 과정에서 예상치 못한 난관이 있었습니다.
대기중 스택뷰에 있는 고객들을 다 없애도 각 고객들을 스레드로 만든 상태라 자신의 차례가 되면,
명령를 그대로 따라 업무중 스택뷰에 보이게 됐습니다.

이 문제를 해결하기 위해, Customer에 workable: Bool 프로퍼티를 만들었고, CustomerLabel에 Customer를 주입받도록 했습니다.
이를 통해서 대기중 스택뷰에서 업무중 스택뷰로 넘어가는 과정에서 CutomerLabel의 Customer의 workable프로퍼티의 참/거짓 여부를 따라서 이후 스레드의 명령을 실행여부를 결정하게끔 했습니다.

물론 CustomerLabel에 workable프로퍼티만 따로 둘 수도 있지만, workable 프로퍼티는 Customer에 있는게 맞다는 생각이 들어, 이 방법을 택하게 됐습니다.

2023-11-16 01:52 UTC, newJunsung commented on BankManagerUIApp/BankManagerUIApp/DepositTask.swift
> +    let name: String = "예금"
이번 프로젝트에서는 최대한 OCP를 지켜보려고 name을 String으로 지정했습니다.

왜나하면 enum타입으로 업무를 지정하게 되면, 새로운 업무를 추가하더라도, enum타입을 또 추가해야 된다고 생각합니다.
물론 사소하게 여겨질 수 있지만, 이 또한 OCP를 위반한 것이라고 생각하여 name을 문자열로 정의했습니다.

2023-11-16 15:28 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/DepositTask.swift
> +    let name: String = "예금"
업무 종류를 문자열로 지정하면 오타, 누락으로 인한 에러와 업무 종류를 파악하기 쉽지 않을 것 같은 생각이 들었습니다!
지금과 같은 의견도 좋습니다!👍

2023-11-16 15:29 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
>      override func viewDidLoad() {
프로퍼티가 복잡하게 있으면 찾기 어려울 수도 있을 것 같습니다! 좋은 의견입니다.👍

2023-11-16 15:30 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private let taskingListWrap = UIStackView(.vertical, 0, .fillEqually)
좋습니다👍

2023-11-16 15:36 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +    var customer: Customer
그런 문제가 발생하셨네요😲
해당 문제를 해결하기 위한 방법과 지금처럼 일련의 설명을 잘 풀어서 설명해주신 점이 좋았습니다!👍
코멘트에 대한 좋은 답변이라 생각합니다😁

2023-11-16 15:37 UTC, zdodev commented on BankManagerUIApp/BankManagerUIApp/CustomeUIs/CustomerLabel.swift
> +        self.textAlignment = .center
좋은 기준이라고 생각합니다👍

2023-11-16 15:42 UTC, zdodev approved these changes
안녕하세요. @JEON-Sungsu , @newJunsung !

Step 4 코멘트에 대한 답변을 잘 달아주셨습니다!
코드를 작성한 의도와 생각을 더 명확하게 알 수 있었던 시간이었습니다.😁
이번 프로젝트를 끝까지 진행하면서 얻을 수 있는 것은 최대한 얻어가시지 않았을까 생각이 듭니다.
지금까지 은행창구 관리 앱 프로젝트를 진행하시느라 고생하셨습니다!
프로젝트를 끝까지 진행하고 마무리하신 점 축하합니다~🍾🎉

2023-11-16 15:43 UTC, merged