은행창구 관리 앱 [STEP4] Roks, Janine
tasty-code/ios-bank-manager pull request #52
Opened 2023-11-15 10:18 UTC by janine-kang

리뷰어: @jungseungyeo
버드: @janine-kang, @KimRoks

린생, 안녕하세요!
아래와 같이 STEP4의 PR 요청드립니다! 🙌🏻

## Summary
STEP4 코드를 통해 은행 창구 앱 UI 구현

<table>
<tr>
<th>최초로 고객 추가 버튼 눌림</th>
<th>초기화 버튼 눌림</th>
<th>고객 10명 추가 버튼 눌림</th>
</tr>
<tr>
<td>
<img src="https://github.com/tasty-code/ios-bank-manager/assets/76927263/f3dacbdb-58d8-4dcf-81d0-893521e423b2" width="auto" height="400" />
</td>
<td>
  <img src="https://github.com/tasty-code/ios-bank-manager/assets/76927263/a6de3394-7d89-472f-a542-2a5a27401f71" width="auto" height="400" />
</td>
<td>
  <img src="https://github.com/tasty-code/ios-bank-manager/assets/76927263/df345b9d-002a-46bc-b45a-ae2431e8b050" width="auto" height="400" />
</td>
</tr>
</table>

### 구현 사항
- [x]  동시성 프로그래밍 중 UI 요소 업데이트의 주의점 이해
- [x]  커스텀 뷰 구현
- [x]  스택 뷰 활용
- [x]  XCode 프로젝트 관리 구조와 이해와 응용

### 주요 고려 사항
- code UI를 구현하고 반복되는 작업을 extension하여 재사용성 확보
- 뷰 스크롤 중 `Timer`가 멈추는 문제를 해결하기 위해 `Timer`의 `run Loop` 조정
- closure를 이용하여 작업이 끝난 후 진행될 메서드 전달
- 기존 BankConsoleApp 프로젝트의 파일을 reference로 추가하여 작업

### 궁금한 점
1. 구조에 관하여
<img width="1476" alt="image" src="https://github.com/tasty-code/ios-bank-manager/assets/76927263/9d3c6b59-2c57-4950-90a5-2b513a3338f1">
이번 STEP 진행하면서 가장 어려웠던 점은 기존의 BankConsoleApp 추상화를 깨고 다시 추상화를 진행했던 부분입니다. 

애초에 Bank 객체에게 부여했던 역할과 이번 스텝의 Bank가 진행할 역할이 다르다는 것을 인지했고, 이에 기존의 추상화를 끌고가기 어렵다고 판단하게 되었는데요. 그러면서 나타난 문제점이, 위의 이미지처럼 어떻게 구조를 잡을 것인가에 대한 것이었습니다.

현재는 두번째 박스쳐진 부분처럼, BankManager라는 객체를 없애고 Bank라는 모델 자체를 직접적으로 불러서 모든 작업들을 처리하게 되었습니다. 그 배경에는 closure()와 Operation 객체가 있는데요. 
Completion handler가 두 개로 나눠진 OperationQueue의 addBarrierBlock에 정확한 타이밍에 닿아 처리되야 했고, 그러다보니 클로저가 여러번 중첩되기 시작하면서 이슈가 발생했던 것 같습니다.

좀 두서없이(?) 작성하게 되었지만, 결론적으로 Model인 Bank를 직접적으로 VC에서 불러 이벤트들에 사용하는 것이 린생이 보시기에 어떤지 궁금합니다!

2. UI Update와 main.sync에 관하여
Dispatch Queue 활용 하여 UI Update시 반드시 main Queue에서 진행하는것으로 알고있는데,
main.sync는 Block-Wait으로 인한 정상적인 작동이 불가한것으로 알고있습니다(특별한 상황을 제외하고)

그렇다면 UI Update는 전부 main.async에서 작성하게 되는것일까요?

이때 main큐의 serial한 환경에서 비동기작업을 하게 되는것이 어떤 큰 의미가 있을지도 궁금합니다.

이번 STEP이 저희에겐 좀 버거웠습니다 😭
코드가 확실히 정리되지 않은 상태로 올리게 된 PR이라, 복잡하더라도 양해해주시면 감사하겠습니다 🫠

2023-11-15 14:17 UTC, jungseungyeo requested changes
질문
1. 결론적으로 Model인 Bank를 직접적으로 VC에서 불러 이벤트들에 사용하는 것이 린생이 보시기에 어떤지 궁금합니다!

`Bank를 모델이라고 표현이 되어 있지만 모델의 역할은 아닌같아요. 모델이 되기 위해서는 기능의 역할이 아닌 데이터만 가지고 있는 형태입니다. 웹에서 spring에서 말하는 model에서는 비지니스 로직을 가지게 설계가 되고 있으나 iOS에서는 그렇게 사용되지는 않습니다. 간혹 이런 부분을 싫어하는 개발자가를 많이 접해서 면접이나, 과제에서 모델이라고 표현이 된다면 안좋은 인상을 줄수 있을거같아요. 그러면 Bank는 무엇이지 파악해보면 저는 Bank가 여전히 Manger의 역할을 하고 있다고 보고 있습니다. 네이밍이 달라졌지만 역할을 보면 은행 업무를 관리하는 역할을 하고 있는것으로 보이고 이벤트를 View단으로 전달하고 있습니다. 따라서 설계를 변경 되었다고 표현이 되고 있지만 어쩐히 동일한 구조를 가지고 있다고 판단이 됩니다. `

2. UI Update와 main.sync에 관하여

`넵 당연히 UI를 업데이트하는 경우 메인스레드로 UI를 업데이트해야합니다. 하지만 업데이트를 할때마다 사용하면 코드마다 main.async 가 되겠죠? 지금같이 비동기로 작성되어 이벤트가 전달 되는 경우 당연히 main.async 로 감싸서 표현해야 UI가 안전하게 업데이트가 됩니다. 그래서 UI를 업데이트 하는 함수를 하나로 만들어서 해당 함수는 내부적으로 main.async 가 돌아가게 보장을 해준다면 UI를 업데이트하는 곳마다 main.async 를 작성하지 않아도 되겠죠? 중요한것은 updateUI()라는 함수로 업데이트 하는 곳을 하나로 만들고 해당 부분에서 보장을 해주면 됩니다.`

Janine, Roks 고생하셨습니다.

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Extensions/UIButton.swift
> +    convenience init(title: String, titleColor: UIColor, align: NSTextAlignment = .center) {
convenience를 사용해서 확장해서 사용하는부분이 좋네요 ㅎㅎ

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +    @objc func addCustomerButtonTapped() {
```suggestion
    @objc private func addCustomerButtonTapped() {
```

은닉화를 잊지말아주세요

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        mainView.workTimeLabel.text = "업무시간 - \(formattedString)"
이 부분도 int를 확장해서 만들면 더욱 효율이 좋을거같아요. 

``` swift
extension Int {
 func formatTimeInterval(_ interval: Double) -> String {
  ....
  } 
}
```

위와 같이 확장해서 사용하는 방식은 어떤가요?

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        bank.UIUpdater = self
UIUpdater를 소문자로 해주세요 프로퍼티는 소문자로 작성하는편입니다.

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Models/Bank.swift
> +    weak var UIUpdater: UIUpdatable?
```suggestion
    weak var uiUPdate: UIUpdatable?
```

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Models/Bank.swift
> +protocol UIUpdatable: AnyObject {
프로포콜 네이밍이 역할을 나타내면 좋을거같아요.
UIUpdateable이라는 네이밍은 UI를 업데이트를 하는 표현인건 알겠지만 무슨 UI를 업데이트를 할때 필요한 protocol인지 알기 어려운거 같아요.

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Models/Bank.swift
> +protocol UIUpdatable: AnyObject {
또 위 네이밍의 able은 역할을 나타내기 때문에 기능을 구현하기 보다는 DIP 의존성 역전의 해당하는 기능인거 같아요.
이런경우 able보다는 delegate라는 위임이라는 표현이 더욱 직관적인거 같아요.

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Views/BankView.swift
> +    private let rootContainer: UIStackView = UIStackView(spacing: 10, axis: .vertical)
View의 역할별로 // MARK: - 표시하여 구분지어주면 좋을거같아요. 

코드로 보기에 정리가 안된 느낌이 드는거같아요.

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Views/BankView.swift
> +    let workingListView: ListView = ListView()
```suggestion
   private let workingListView: ListView = ListView()
```
를 통해서 은닉화를 해주세요. 

은닉화가 되어 있지 않아 외부에서 .text로 변경이 됩니다. 

이 부분은 private으로 은닉화를 하고 updateUI를 함수를 만들어서 진행해주세요.

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Views/BankView.swift
> +    func configureAttribute() {
```suggestion
    private func configureAttribute() {
```

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Views/BankView.swift
> +    func configureLayout() {
```suggestion
    private func configureLayout() {
```

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        mainView.waitingListView.itemListStackView.arrangedSubviews.forEach {
mainView의 resetUI함수를 만들어서 은닉화를 지켜주세요.

2023-11-15 14:17 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        mainView.waitingListView.itemListStackView.arrangedSubviews.forEach {
디미터 법칙을 위반하는 코드가 작성되었어요. 
a.b.c()와 같은 코드를 작성하게되면 a -> b -> c 로 의존성이 생성되게 됩니다. 
이렇게 되면 점차 코드 수정이 힘들어지는 현상이 발생해요.
하나의 기능을 하는 함수를 호출하는 방식으로 수정이 필요할거같아요.

https://prohannah.tistory.com/204 <- 디미터 법칙

2023-11-17 04:28 UTC, janine-kang commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +    @objc func addCustomerButtonTapped() {
넵 해당 부분 변경했습니다

2023-11-17 04:28 UTC, janine-kang commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        bank.UIUpdater = self
넵 반영했습니다

2023-11-17 04:28 UTC, janine-kang commented on BankManagerUIApp/BankManagerUIApp/Views/BankView.swift
> +    let workingListView: ListView = ListView()
넵 해당 부분 반영했습니다!

2023-11-17 04:37 UTC, KimRoks commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        mainView.workTimeLabel.text = "업무시간 - \(formattedString)"
Double을 확장하는 방식을 채택하여 적용하였습니다

2023-11-17 04:40 UTC, janine-kang commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        mainView.waitingListView.itemListStackView.arrangedSubviews.forEach {
그렇군요! 고려하여 반영하겠습니다.

+) 린생께서 말씀해주신대로 디미터 법칙을 최대한 지키고자 노력했는데, 몇몇 구간에서는 위반하게 되었습니다 🫠 
이 부분들은 구조와 연관이 있는 부분들이라 좀 더 고려해보도록 하겠습니다!

2023-11-17 04:41 UTC, janine-kang commented on BankManagerUIApp/BankManagerUIApp/Models/Bank.swift
> +protocol UIUpdatable: AnyObject {
넵 확인했습니다! UIUpdateDelegate로 변경했습니다

2023-11-17 04:43 UTC, KimRoks commented on BankManagerUIApp/BankManagerUIApp/Controllers/ViewController.swift
> +        mainView.waitingListView.itemListStackView.arrangedSubviews.forEach {
메서드들을 추가하여 수정하였습니다

2023-11-17 04:56 UTC, janine-kang commented
> 질문
> 
> 1. 결론적으로 Model인 Bank를 직접적으로 VC에서 불러 이벤트들에 사용하는 것이 린생이 보시기에 어떤지 궁금합니다!
> 
> `Bank를 모델이라고 표현이 되어 있지만 모델의 역할은 아닌같아요. 모델이 되기 위해서는 기능의 역할이 아닌 데이터만 가지고 있는 형태입니다. 웹에서 spring에서 말하는 model에서는 비지니스 로직을 가지게 설계가 되고 있으나 iOS에서는 그렇게 사용되지는 않습니다. 간혹 이런 부분을 싫어하는 개발자가를 많이 접해서 면접이나, 과제에서 모델이라고 표현이 된다면 안좋은 인상을 줄수 있을거같아요. 그러면 Bank는 무엇이지 파악해보면 저는 Bank가 여전히 Manger의 역할을 하고 있다고 보고 있습니다. 네이밍이 달라졌지만 역할을 보면 은행 업무를 관리하는 역할을 하고 있는것으로 보이고 이벤트를 View단으로 전달하고 있습니다. 따라서 설계를 변경 되었다고 표현이 되고 있지만 어쩐히 동일한 구조를 가지고 있다고 판단이 됩니다. `
> 
> 2. UI Update와 main.sync에 관하여
> 
> `넵 당연히 UI를 업데이트하는 경우 메인스레드로 UI를 업데이트해야합니다. 하지만 업데이트를 할때마다 사용하면 코드마다 main.async 가 되겠죠? 지금같이 비동기로 작성되어 이벤트가 전달 되는 경우 당연히 main.async 로 감싸서 표현해야 UI가 안전하게 업데이트가 됩니다. 그래서 UI를 업데이트 하는 함수를 하나로 만들어서 해당 함수는 내부적으로 main.async 가 돌아가게 보장을 해준다면 UI를 업데이트하는 곳마다 main.async 를 작성하지 않아도 되겠죠? 중요한것은 updateUI()라는 함수로 업데이트 하는 곳을 하나로 만들고 해당 부분에서 보장을 해주면 됩니다.`
> 
> Janine, Roks 고생하셨습니다.

린생 안녕하세요! 😁
위에 답변 주신 내용을 토대로 리팩토링을 진행해보았는데요, 다시 보니 잘 나눠진게 맞을까 하는 의구심이 샘솟네요 😭

결론적으로 보면, 
- View는 자기자신의 View를 변경 (`BankView`, `ListView`)
- ViewController는 데이터와 View의 매개체 (`ViewController`)
- Model은 데이터 관리 및 GCD를 이용하여 흐름 관리 ( `Bank`, `Timer` 등)
- UIUpdateDelegate를 이용하여 Model이 View Update 시점을 알림

이렇게 역할이 나눠졌습니다.

우선, 기존과 동일하게 Bank가 관리의 업무까지 관할하고 있는 것은 변함이 없는 것 같습니다.

다만, 린생께서 주신 `updateUI` 힌트를 참고하여, 
Bank에서 직접적으로 View의 이벤트를 변경하기보단 `Delegate패턴으로 VC에게 신호를 보내고,
그 신호에 따라 VC가 View를 변경하는 구조`로 바꿔보았습니다.

처음 리팩토링을 할 땐 BankManager라는 객체를 심어주고, BankManager가 GCD를 이용하여 은행의 업무와 Timer의 흐름을 관할하는게 어떨까 생각하고 구조를 변경해보았는데요. 하다보니 디미터의 법칙을 너무 많이 위반하게 되고, 그를 다시 처리하기 위해서는 BankManager의 역할이 모호해져서 날려버렸습니다. 그럼에도 불구하고, Bank가 GCD 관리 역할을 한다는 것이 불만족(?)스럽습니다. 해결법이 있을까요?

또한, BankView 내에 가지고 있는 모든 View에 대한 캡슐화를 진행하며, 각각의 뷰를 업데이트 하는 함수들을 BankView 안에 만들었는데요. 이 처럼 View가 자기자신의 View 데이터를 변경하는게 과연 괜찮을까요? 

리팩토링 된 구조에 대해 전반적인 린생의 의견 또한 궁금합니다.

2023-11-17 09:38 UTC, jungseungyeo approved these changes
질문 주신것에서 Bank가 GCD를 관리하는 것이 불만이라고 하셨는데, 저도 그렇습니다. 코멘트에서도 이야기 하였지만, updateUI는 UIUpdateDelegate의 역할이라고 말하기는 어려워보여요.

UIUpdateDelegate 네이밍이 이러서 그렇지만 직관적인 네이밍으로 수정을 해보자면 BankDelegate가 맞겠죠? 

그럼 관점에서 GCD를 관리 하니 더욱 이상한 모양이 되는거같아요.

updateUI는 View단의 역할이니 View의 기능을 확장해주면 좋습니다.

``` swift 

protocol UIViewControllerable { 
  func updateUI() 
}

extension UIViewControllerable {
 // 작성해주신 코드
}
extension UIViewController: UIViewControllerable {}
```

위와 같이 했다면 좀 더 괜찮은 설계가 되었을거같습니다 ㅎㅎ 

두분 다 고생하셨습니다.

2023-11-17 09:38 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Views/UIText.swift
> +    static let workingStationTitleLabel = "업무중"
위와 같은 형태를 많이 사용을 하는 편이긴 한데. 별도의 파일로 관리하면 코드 점핑이 발생해서 복잡도가 올라갈수있어요.
사용하는 View 안에서 private enum Const {} 형태로 사용하면 더욱 좋을거같아ㅛ.

2023-11-17 09:38 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/BankServiceExecutor.swift
> +final class BankServiceExecutor {
좋습니다 ㅎㅎ

2023-11-17 09:38 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Models/UIUpdateDelegate.swift
> +extension UIUpdateDelegate {
protocol을 확장해서 사용하셨네요 ㅎㅎ 공통된 기능을 제공하기 위해서 사용하여 의도적으로는 좋은거같아요. 
고생하셨습니다. ㅎㅎ

제 의도는 updateUI함수를 viewController에서 만드는 것을 의도하였던것인데 (UI를 업데이트 하는 곳은 하나만 존재하게) main thread로 전달하는 함수를 공통화 하였네요 ㅎㅎ 
그래도 두분이 의도한 대로는 잘 된거같아요. 

설계적으로는 근데 문제가 있어요. 예를 들어 removeCustomerLabel -> 하고 updateUI함수로 다시 호출하고 있죠? 그러면 protocol에서 한번에 처리하고 올려주는것이 좋을거같은데 이부분은 실수할수가 있어요.

차라리 updateUI함수는 UIUpdateDelegate 프로토콜의 역할이 아닌 UIViewController를 extension하여 구현을 하여 가져갔다면 View를 업데이트하는 ViewController의 기능이 확장이 되어서 더 좋은 설계가 될 수 있었던거같아요. ㅎㅎ

2023-11-17 09:38 UTC, jungseungyeo commented on BankManagerUIApp/BankManagerUIApp/Views/BankView.swift
> +    private let rootContainer: UIStackView = UIStackView(spacing: 10, axis: .vertical)
주석으로 어느 부분인지 달아서 휴먼 리소스를 줄일수있을거같네요 ㅎㅎ 좋습니다.

2023-11-17 09:38 UTC, merged