은행창구 관리 앱 [STEP 4] bello, dora
tasty-code/ios-bank-manager pull request #54
Opened 2023-11-16 06:01 UTC by JinUng41

리뷰어: @forestjae

버드: @JinUng41, @KSK9820

안녕하세요, 숲재!! 마지막 PR입니다. 😄

[STEP 4]에서 비동기 작업과 UI 업데이트가 가능하도록 구현해 보았습니다.

읽어보시고 코멘트 남겨주시면 감사하겠습니다!! 🙏🙏

## 프로젝트 요구사항

Step 3의 은행을 UI 앱으로 전환합니다.

- [x]  이번 프로젝트의 UI구성은 ‘코드'만 사용하여 구현합니다.
- [x]  고객 정보를 표현할 커스텀뷰를 구현합니다.
    - 뷰에 포함될 정보 : 고객번호, 업무종류
- [x]  대기열은 스택뷰를 활용합니다.
    - 화면 전체를 여러개의 중첩된 스택뷰로 구성하는게 편리할 수 있습니다.
- [x]  화면 구성
    - 업무중인 고객 리스트, 대기중인 고객 리스트업무시간 타이머, 고객 10명 추가 버튼, 초기화 버튼
- [x]  고객 10명 추가 버튼을 통해 임의의 10명의 고객이 추가됩니다.
- [x]  초기화 버튼을 누르면 대기중인 고객과 타이머 모두 초기화됩니다.
- [x]  모든 업무가 끝나고 대기중인 고객이 없으면 업무시간 타이머는 멈춥니다.
- [x]  고객이 추가되어 다시 업무를 처리하면 타이머가 동작합니다.
    - 초기화 하기 전까지 업무시간은 초기화하지 않고 누적합니다.

## 구현 내용

### 객체간 역할

이름 | 타입 | 역할
-- | -- | --
ViewController | final class | 각 버튼에 대한 메서드를 정의함, 타이머를 동작시킴과 동시에 비동기 작업을 실행시킴, 화면에서 label(고객 id, taskType)에 따른 레이블을 추가, 삭제하는 프로토콜을 구현함.
BankView | final class | Code로 구현된 커스텀 뷰로써, 뷰에 필요한 UI 요소와 오토레이아웃을 구현
ClientLabel | final class | 고객에 대한 레이블 생성을 위해, 커스텀 레이블을 구현
Bank | final class | 전반적인 은행 업무를 담당함, ViewController에서 이벤트가 발생하면, 해당 이벤트를 처리하는 로직을 구현함, 은행원이 업무를 비동기적으로 처리하는 작업이 실제로 실행됨, 또한 ViewController에 구현된 Label 프로토콜을 채택하여, UI 업데이트가 되도록 하였음.
Client | struct | 손님 객체로, id와 taskType(업무타입: 대출, 예금)을 프로퍼티로 가짐.
TaskType | enum | 업무의 종류(대출, 예금)과 그에 맞는 소요 시간과 description을 가짐.
Prompt | enum | 은행 메세지, 입력에 대한 메세지, 업무 상태에 대한 메세지 출력을 위함.

### 동작화면
실행하고 멈추었다가 실행하기 | 실행중에 인원추가하기 | 실행중에 초기화 누르고 다시 실행하기
------------------|---------------------|--------------------------
![멈췄다 실행하기](https://github.com/tasty-code/ios-bank-manager/assets/91656206/0743f376-470e-44d8-8602-495ea23a9799) | ![실행중에 인원추가](https://github.com/tasty-code/ios-bank-manager/assets/91656206/7d8063f5-55e7-4490-a299-429cb51b60da) | ![실행중에 초기화 누르고 다시 실행](https://github.com/tasty-code/ios-bank-manager/assets/91656206/58005b7a-4746-46bf-8f4c-b77f51fc5f69)

<br>

## 🙋 질문 있습니다!

### `lazy var` VS `let`

- `lazy var`는 지연 저장 속성으로 해당 저장 속성의 초기화를 지연시키는 것으로 이해했습니다.
- BankView 코드에서 주로 stackView는 `lazy var`로, 기타 다른 UI 요소는 `let`으로 선언한 이유로도
    - stackView 안에는 다른 UI 요소를 subViews로서 넣어줘야 하기 때문에 `lazy var`로 선언하였습니다.
        - 다른 저장 속성에 의존하기 때문입니다.
        - ‘먼저 스택뷰에 담을 UI 요소가 초기화 된 다음에, 스택뷰가 해당 요소를 subViews로 가진다’라고 이해하였습니다.
- 저희는 button에 대한 addTarget 메서드를 뷰컨트롤러에서 지정하고 있습니다.
- 이 과정에서 target에 들어가는 `self`는 뷰컨트롤러의 인스턴스이며 button을 누르는 이벤트를 뷰컨트롤러가 처리하는 것으로 이해하였는데 저희가 이해한 부분이 맞는지 궁금합니다!!
    - responder chain을 따라 내부적으로 다른 객체가 이벤트를 담당하는지
    - 뷰컨트롤러 자체가 이벤트를 담당하는지

### 동작 상황과 초기화 문제

- 타이머의 종료
    - 고객의 업무는 Bank에서 처리하는데, 모든 고객의 업무가 끝나면 ViewController에 있는 타이머를 멈춰야합니다.
    - Bank에서 모든 고객의 업무를 끝났음을 ViewController에게 알려주어야 타이머를 중지시키고, 레이블 업데이트를 중지시킬 수 있습니다.
    - 이를 위해 ViewController에서 Bank의 open()함수를 호출 할 때, ViewController의 전역변수 DispatchGroup을 매개변수로 전달합니다.
    - DispatchGroup이 종료되면 타이머와 UI를 업데이트하는 main 스레드에게 notify를 해줍니다.
- 문제 상황은 해당 과정 중에서, 비동기 작업이 실행 중에 초기화 버튼을 눌렀을 때 발생하게 됩니다.
    - 초기화 버튼을 누르게 되면, Bank 내부적으로 전역변수인 isCancelled의 값을 변경합니다.
    - 비동기 작업들이 해당 전역 변수의 값을 읽고, early exit하도록 현재 구현하였습니다.
    - 그러한 방식으로 동작하는 초기화 버튼을 누르고 난 뒤에 0.5초 이내에 다시 고객 추가 버튼을 누르게 되면
    - 비동기에서 early exit을 하기 전에 다시 값이 바뀌어 UI업데이트를 진행하는 문제가 있습니다.
- 해당 과정을 해결할 수 있는 방법이 있는지 궁금합니다!!
    - 저희가 판단하기로는 비동기로 동작하는 스레드 자체를 죽일 수 있는 방법은 찾지 못하였고,
    - Thread.exit()을 실행시켰을 때는 앱이 종료되어서
    - Bool 변수를 두어 early exit이 되도록 하였습니다.

<details>
  <summary>문제 상황에서의 동작 화면</summary>
  <img src="https://github.com/tasty-code/ios-bank-manager/assets/91656206/a575b239-fcbd-4c0e-bce7-bb7a51f8d968" width = 500 height = 1000>
</details>

- 초기화를 누르자마자 고객 추가를 누르게 되면 미처 early exit 하지 못한 작업들이 다시 UI 업데이트를 수행하고 있습니다.

2023-11-17 11:18 UTC, forestjae commented
스텝4까지 잘 마무리해주셨네요 👍 👍 👍 
취소가 즉시 반영이 안되는 것 외에는 잘 동작하는 것 같습니다. 관련해선 밑에 말씀드릴게요.

> ## 🙋 질문 있습니다!
> ### `lazy var` VS `let`
> * `lazy var`는 지연 저장 속성으로 해당 저장 속성의 초기화를 지연시키는 것으로 이해했습니다.
> * BankView 코드에서 주로 stackView는 `lazy var`로, 기타 다른 UI 요소는 `let`으로 선언한 이유로도
>   
>   * stackView 안에는 다른 UI 요소를 subViews로서 넣어줘야 하기 때문에 `lazy var`로 선언하였습니다.
>     
>     * 다른 저장 속성에 의존하기 때문입니다.
>     * ‘먼저 스택뷰에 담을 UI 요소가 초기화 된 다음에, 스택뷰가 해당 요소를 subViews로 가진다’라고 이해하였습니다.
> * 저희는 button에 대한 addTarget 메서드를 뷰컨트롤러에서 지정하고 있습니다.
> * 이 과정에서 target에 들어가는 `self`는 뷰컨트롤러의 인스턴스이며 button을 누르는 이벤트를 뷰컨트롤러가 처리하는 것으로 이해하였는데 저희가 이해한 부분이 맞는지 궁금합니다!!
>   
>   * responder chain을 따라 내부적으로 다른 객체가 이벤트를 담당하는지
>   * 뷰컨트롤러 자체가 이벤트를 담당하는지
> 
1. 그렇다면 lazy를 사용한 프로퍼티는 정확히 어느 시점에 초기화가 될까요? lazy를 사용했을 때 단점이 있을까요? 이 점을 공부해보시길 추천드립니다. 면접에 자주 나오는 질문이에요.
2. 네 target은 그 액션을 받아서 처리하는 역할을 담당하게 되고, 만약 nil을 넣는다면 responder chain을 통해서 담당하는 객체를 찾게됩니다.


> ### 동작 상황과 초기화 문제
> * 타이머의 종료
>   
>   * 고객의 업무는 Bank에서 처리하는데, 모든 고객의 업무가 끝나면 ViewController에 있는 타이머를 멈춰야합니다.
>   * Bank에서 모든 고객의 업무를 끝났음을 ViewController에게 알려주어야 타이머를 중지시키고, 레이블 업데이트를 중지시킬 수 있습니다.
>   * 이를 위해 ViewController에서 Bank의 open()함수를 호출 할 때, ViewController의 전역변수 DispatchGroup을 매개변수로 전달합니다.
>   * DispatchGroup이 종료되면 타이머와 UI를 업데이트하는 main 스레드에게 notify를 해줍니다.
> * 문제 상황은 해당 과정 중에서, 비동기 작업이 실행 중에 초기화 버튼을 눌렀을 때 발생하게 됩니다.
>   
>   * 초기화 버튼을 누르게 되면, Bank 내부적으로 전역변수인 isCancelled의 값을 변경합니다.
>   * 비동기 작업들이 해당 전역 변수의 값을 읽고, early exit하도록 현재 구현하였습니다.
>   * 그러한 방식으로 동작하는 초기화 버튼을 누르고 난 뒤에 0.5초 이내에 다시 고객 추가 버튼을 누르게 되면
>   * 비동기에서 early exit을 하기 전에 다시 값이 바뀌어 UI업데이트를 진행하는 문제가 있습니다.
> * 해당 과정을 해결할 수 있는 방법이 있는지 궁금합니다!!
>   
>   * 저희가 판단하기로는 비동기로 동작하는 스레드 자체를 죽일 수 있는 방법은 찾지 못하였고,
>   * Thread.exit()을 실행시켰을 때는 앱이 종료되어서
>   * Bool 변수를 두어 early exit이 되도록 하였습니다.
> 
> 문제 상황에서의 동작 화면
> * 초기화를 누르자마자 고객 추가를 누르게 되면 미처 early exit 하지 못한 작업들이 다시 UI 업데이트를 수행하고 있습니다.

네 이미 큐에 대기중인 작업을 현재 방법으로는 취소할 수가 없습니다. DispatchWorkItem의 cancel 메서드를 활용하는 방법으로 큐에 대기중인 작업이 실행되지 않게 할 수 있습니다.

2023-11-17 11:18 UTC, forestjae requested changes

2023-11-17 11:18 UTC, forestjae commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private let bankView: BankView = BankView()
뷰 컴포넌트와 다른 프로퍼티들은 개행으로 구분해 주시는게 좋을것 같아요

2023-11-17 11:18 UTC, forestjae commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    @objc private func addClientButtonTapped() {
```swift
@objc
func someFunction()
```
이런식으로 개행하시면 가독성을 좀 더 챙길 수 있어요

2023-11-17 11:18 UTC, forestjae commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +        RunLoop.main.add(timer!, forMode: .tracking)
강제 언래핑은 어떤 경우에도 유의해주세요! 
이 상황에서는 절대 크래시가 날 일이 없겠지만 습관을 미리 들여두는게 좋습니다.
협업시에 여러 사람이 같은 코드를 작업하게 되는데, 이 때 예상치 못한 크래시가 발생할 수 있어요.

2023-11-17 11:18 UTC, forestjae commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +        dispatchGroup.notify(queue: DispatchQueue.main) { [unowned self] in
weak 대신 unowned를 사용하신 이유는 무엇인가요? 차이점을 알고 계신가요?

2023-11-17 11:18 UTC, forestjae commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +}
좋은 딜리게이트 사용이네요

2023-11-17 11:18 UTC, forestjae commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +            }
원하는 레이블을 찾은 뒤에 더이상 forEach문이 돌지않아도 되지 않을까요?

2023-11-20 00:26 UTC, KSK9820 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    private let bankView: BankView = BankView()
custom view 변수 개행했습니다.

2023-11-20 00:27 UTC, KSK9820 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    @objc private func addClientButtonTapped() {
수정했습니다.

2023-11-20 00:29 UTC, KSK9820 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +        RunLoop.main.add(timer!, forMode: .tracking)
한 번도확인했어야 했는데, 유의하겠습니다.
수정하였습니다 :)

2023-11-20 00:29 UTC, KSK9820 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +}
감사합니다 😊

2023-11-20 00:50 UTC, KSK9820 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +            }
forEach문 대신 first 요소를 뽑아서 사용하는 방법을 사용하였습니다.

2023-11-20 00:53 UTC, KSK9820 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +        dispatchGroup.notify(queue: DispatchQueue.main) { [unowned self] in
weak는 참조하던 인스턴스가 사라졌을 때 자동으로 nil을 해주고, unowned는 사라졌다면 저희가 직접 nil을 해줘야하는 차이로 알고 있습니다. 

코드에서 unowned를 사용한 이유는, self는 view controller인데, 해당 인스턴스가 사라질 일이 없다고 판단해서 unowned를 사용하였습니다.

2023-11-20 00:55 UTC, JinUng41 commented
`lazy`로 선언된 프로퍼티는, 먼저 상위 뷰가 메모리에 적재되고 난 다음 (혹은 다른 뷰 프로퍼티에 의존할 때) 상위 뷰가 내부의 요소를 그리려고 할 때의 `lazy` 프로퍼티가 메모리에 적재되어 뷰에 그려진다고 이해하고 있습니다!!

2023-11-21 10:13 UTC, merged