은행창구 관리 앱 [Step 4] Comdori, SwainYun
tasty-code/ios-bank-manager pull request #55
Opened 2023-11-16 06:41 UTC by comdori-wj

# 은행창구 관리 앱 [Step 4] Comdori, SwainYun

리뷰어: @protocorn93
리뷰이: @Remaked-Swain & @comdori-wj

🙋🏻‍♂️ 안녕하세요, 콘!
Step4 프로젝트 요구사항에 맞춰 다음 내용 진행하였습니다.
이번 단계에서는 코드로 UI를 작성하고, 타이머의 활용과 GCD를 더 깊게 파고들어 봤습니다.
비동기처리와 메인스레드 내 UI드로잉이 핵심경험인 프로젝트였던 만큼 그 부분에서 많은 버그와 마주했었습니다...
※ 스크린샷이 살짝 끊겨서 보이지만, 실제로는 전혀 끊김없는 점을 양해바랍니다.

-----------------------------------------------

## 🍀 구현사항
|항목|내용|
|:--:|:--|
|ViewController|뷰 요소들과 뷰 요소를 다루는 기능들을 구현했습니다.|
|CustomerLabel|대기중과 업무중에 표시되는 1명의 고객입니다.|
|BankTimer|고객이 추가되면 타이머가 작동되는 부분입니다.|
|Bank|ViewController가 다룰 뷰 요소를 위한 데이터들을 관리하고 적절하게 통신합니다.|
|ViewComponentsExtensions|뷰 요소를 편하게 생성하기 위해 익스텐션으로 미리 정의하여 사용할 수 있습니다.|

## 📸 스크린샷
![Simulator Screen Recording - iPhone 15 Pro - 2023-11-16 at 13.48.17](https://hackmd.io/_uploads/HyfukXmVT.gif)

## 🤔 궁금한 점

### SwainYun
1. **StackView의 컴포넌트 재사용**
CustomerLabel이 스택뷰에 많이 쌓이면 타이머와 스크롤이 버벅거리는 현상이 발견되었습니다. 테이블 뷰의 경우 메모리를 절약하기 위해 셀을 재사용하는 것과 같이 스택뷰도 그러한 작업을 해줄 수 있다면 이런 현상을 해결할 수 있을 것 같다고 생각했습니다.
CustomerLabel을 생성하고 지우는 것도 맞지만 Label에 전달할 Customer객체만 바꿔치기 해서 Label을 지웠다가 다시 만들지 않고도 사용할 수 있을 것 같습니다.
이것이 적절한 판단인지 궁금하고, 혹시 더 좋은 방법이 있다면 소개해주세요!
2. **StackView의 arrangedSubview 동적 관리**
```swift
func removeArrangedSubviews(_ views: [UIView]) {
    views.forEach {
        self.removeArrangedSubview($0)
        $0.removeFromSuperview()
    }
}
```
`removeArrangedSubview()` 메서드는 스택 뷰 배열에서 제거할 뿐이지 뷰 계층 구조 상에서도 삭제해주는 것은 아니기 때문에 `removeFromSuperView()` 메서드도 같이 호출해서 상위 뷰 계층 구조와의 링크를 해제해야 한다. 라는 것이 공식문서와 스택오버플로우 등에서 다루는 내용인 것으로 학습했습니다. 이 과정에서 메모리 누수가 발생할만한 가능성이 있을까요?

3. **Bank는 모델인가?**
저희는 Bank는 MVC 구조에서 온전히 모델이라고 부를 수는 없다는 이야기를 나눴습니다. Bank가 데이터만을 다루지 않고 다른 기능들을 가지고 있다는 것이 그 이유였습니다. 이후에 '그렇다면 BankTimer는 온전히 유틸성을 가진 객체인가?'' 에 대해서 논의하기 시작했을 때는 많이 혼란스러웠습니다. 이 부분에 대한 콘의 생각은 어떠하신지 듣고 싶습니다.

4. **객체 협력관계 설계**
이번 프로젝트에서는 프로토콜을 사용한 추상화, 일반화와 더 나아가 SOLID 원칙을 적용해보는 시도를 많이 해보려고 했습니다.
Delegate Pattern 적용, 의존성 주입 등등 다양한 시도를 해보았는데 각 객체의 역할과 책임 분리가 적절하게 이루어졌는지, ViewController가 과한 프로퍼티를 갖는 것이 아닌지 등의 걱정도 많이 들었습니다.
개인적으로 객체 간에 메세징이 많이 어지러운 듯하게 느껴지는 것이 협력관계 설계가 제대로 이루어지지 않았기 때문이라고 생각합니다.
이와 관련한 코멘트를 달아주시면 좋겠습니다 :)

2023-11-17 00:48 UTC, Remaked-Swain commented
### 추가 질문
* **Thread explosion?**
Actor, async-await와 같은 Swift Concurrency 사용 없이 GCD로는 Thread explosion 문제가 발생할 수 있다는 구절을 어디선가 읽었던 기억이 납니다.

<img width="917" alt="multiThreading" src="https://github.com/tasty-code/ios-bank-manager/assets/99116619/b5b26f06-32b7-4289-98f2-89aa40fc64e9">

저희도 그렇고 다른 팀들도 공통적으로 고민 중인 부분인데, 은행원 수 보다 더 많은 Thread를 만드는 것은 오히려 Context Switching의 비용 측면에서 더 비효율적일 것이라 생각해 은행원 수 만큼의 Thread를 만드는 방법을 찾아보려 했습니다.
우리 코드로는 고객 10명 추가가 이루어지면 3개를 넘는 수의 Thread가 생성되고 있음을 확인했습니다.

저는 GCD에 근본적으로 뿌리내리고 있는 개념이 `작업만 대기열에 던져두면 어떤 Thread, 얼마만한 Thread로 이것을 처리할 것인지는 GCD 내지는 CPU가 판단하여 조절해주기에 개발자는 신경쓸 필요도, 억지스러운 개입도 없다.`라고 이해했습니다.

그러나 DispatchSemaphore의 wait(), signal() 사인과 DispatchQueue로 보낼 작업을 묶을 중괄호 블럭의 적절한 위치 변경으로 이를 해결한 팀이 존재합니다.
우리 코드에서는 어떻게 해야 Thread explosion을 예방하게 고칠 수 있을지 궁금해졌습니다.

2023-11-17 06:26 UTC, protocorn93 requested changes
많이 어려운 프로젝트였지만, 이렇게 열심히 최선을 다해 구현해주신 두 분 모두 고생하셨어요. 앞으로 개발을 하는데 있어 동시성에 대한 이슈는 끝까지 챙겨야 하는 부분이기에 앞으로도 다른 프로젝트를 하는데 있어 많은 고민을 해보시면 좋을 것 같아요. 


## 질문 사항

SwainYun

> StackView의 컴포넌트 재사용
CustomerLabel이 스택뷰에 많이 쌓이면 타이머와 스크롤이 버벅거리는 현상이 발견되었습니다. 테이블 뷰의 경우 메모리를 절약하기 위해 셀을 재사용하는 것과 같이 스택뷰도 그러한 작업을 해줄 수 있다면 이런 현상을 해결할 수 있을 것 같다고 생각했습니다.
CustomerLabel을 생성하고 지우는 것도 맞지만 Label에 전달할 Customer객체만 바꿔치기 해서 Label을 지웠다가 다시 만들지 않고도 사용할 수 있을 것 같습니다.
이것이 적절한 판단인지 궁금하고, 혹시 더 좋은 방법이 있다면 소개해주세요!

네 애초에 이런 화면이었으면 스택뷰를 사용하지 않는 것이 맞아요. 다만 프로젝트 명세이기에 여러분이 선택한 방법도 현재 구조에선 괜찮은 대안이 될 수 있을 것 같아요. 저 역시 뷰의 생성/삭제가 가장 많은 리소스를 잡아먹기 때문에 데이터만 갈아치우는 것이 최선이지 않을까 싶네요.  

> removeArrangedSubview() 메서드는 스택 뷰 배열에서 제거할 뿐이지 뷰 계층 구조 상에서도 삭제해주는 것은 아니기 때문에 removeFromSuperView() 메서드도 같이 호출해서 상위 뷰 계층 구조와의 링크를 해제해야 한다. 라는 것이 공식문서와 스택오버플로우 등에서 다루는 내용인 것으로 학습했습니다. 이 과정에서 메모리 누수가 발생할만한 가능성이 있을까요?

네  `removeFromSuperview`가 함께 호출된다면 이 과정에선 메모리 누수가 발생할만한 가능성은 없네요.

> Bank는 모델인가?
저희는 Bank는 MVC 구조에서 온전히 모델이라고 부를 수는 없다는 이야기를 나눴습니다. Bank가 데이터만을 다루지 않고 다른 기능들을 가지고 있다는 것이 그 이유였습니다. 이후에 '그렇다면 BankTimer는 온전히 유틸성을 가진 객체인가?'' 에 대해서 논의하기 시작했을 때는 많이 혼란스러웠습니다. 이 부분에 대한 콘의 생각은 어떠하신지 듣고 싶습니다.

여러분들이 생각하는 모델의 정의는 무엇일까요? 순수히 데이터만을 표현한다면 저는 모델이라고 생각하는데요. `Bank`도 저는 하나의 객체로 보여져요. `BankTimer`도 마찬가지이구요. 여러분이 어떤 부분에서 혼란을 느끼고 계신지는 잘 모르겠지만, 자신의 역할을 수행하는 것 자체로 모두가 객체라고 전 생각해요. `Bank`는 사용자의 입력을 받고, 이 입력을 상호협력하는 객체에 전파시켜주는 역할을 하는 객체죠. Bank와 상호협력 하는 객체 중 시간 관리를 담당하는 객체가 `BankTimer`가 될 것이구요.

`온전한 유틸성 객체`라는 것이 정확히 이해가 되진 않네요. 다만 객체는 모두가 각자만의 역할을 수행해요. 자신의 역할을 수행하면서 자신의 역할 범위의 일은 다른 객체에게 위임할 수 있구요. 이것이 객체간의 상호협력이라고 생각해요. 

> 객체 협력관계 설계
이번 프로젝트에서는 프로토콜을 사용한 추상화, 일반화와 더 나아가 SOLID 원칙을 적용해보는 시도를 많이 해보려고 했습니다.
Delegate Pattern 적용, 의존성 주입 등등 다양한 시도를 해보았는데 각 객체의 역할과 책임 분리가 적절하게 이루어졌는지, ViewController가 과한 프로퍼티를 갖는 것이 아닌지 등의 걱정도 많이 들었습니다.
개인적으로 객체 간에 메세징이 많이 어지러운 듯하게 느껴지는 것이 협력관계 설계가 제대로 이루어지지 않았기 때문이라고 생각합니다.
이와 관련한 코멘트를 달아주시면 좋겠습니다 :)

네네 전 그런 고민이 매우 건전하고 당연한 고민이라고 생각해요. 어쩌면 이제는 객체를 적절히 나누고 협력하는 방법에 대한 고민이 필요한 것이겠지요! 협력관계 설계가 제대로 이루어지지 않았다고 느끼는 것도 당연하다고 생각해요. 

그런 여러 관계 설정의 고민들의 결과 나온 패턴이 전 아키텍처라고 생각해요. 정말 다양한 아키텍처가 있죠. Clean architecture, MVVM, MVP, VIPER 등등 

각자가 모두 저마다의 장단점을 갖는 아키텍처 패턴이에요. 이러한 패턴들을 공부해보시면 여러분들의 고민을 다른 사람들은 어떻게 해결했는지 힌트를 얻을 수 있을거에요.

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Teller.swift
> +        }
`DispatcQueue.main.async`로 감싼 이유가 궁금해요.

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/Extensions/UIViewComponentsConvenienceInitializers.swift
convenience init으로 생산성을 높이려는 시도 좋네요👍

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
스토리보드를 사용하지 않고, 코드로만 UI를 작성하기 위해 이 3줄이 추가가 되었는데, 각각의 줄은 어떤 것을 의미할까요?

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +protocol BankDelegate: TellerWorkingStateNotifiable, AnyObject {
`TellerWorkingStateNotificable`이 AnyObject를 이미 따르고 있기 때문에 여기선 제거가 가능하지 않을까요?

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +    init(_ bankManager: BankDelegate) {
argument label을 활용해주시면 좋을 것 같아요. 사용하는 곳에선 `Bank(self)` 이렇게 작성될텐데, 읽는 입장에선 왜 self를 넘기는지 이해하기 어려울 것 같아요.

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +            DispatchQueue.global().async(group: dispatchGroup, qos: .userInitiated) { [self] in
이전에 남기지 못한 코멘트인데, `[self]`를 통해 캡처 해주셨는데, 필요한 이유가 있을까요?

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/Utilities/BankTimer.swift
> +    private var dateFormatter: DateFormatter = {
`dateFormatter`를 `var`로 선언한 이유가 있으신가요?

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Teller.swift
> +}
`Teller` 동작의 일부를 외부에 위임하는 delegate 성격의 프로토콜은 왠만하면 `-Delegate` 라는 네이밍을 사용해주시는게 좋아요. `TellerDelegate`로 네이밍 되어도 무방해보이는 액션이네요.

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    }()
```swift 
private let headerVerticalStackView: UIStackView = {
  let stackView = UIStackView(axis: .vertical, spacing: Constants.defaultSpacing)
  return stackView
}()
```

self로 접근하는게 아니라면 선언되어도 무방하지 않나요?

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    }
이런 상수는 타입 정의 상단부에 위치하는 것이 읽기 좋은 것 같아요. 제가 근무 중인 곳에서도 내부에서 사용하는 상수는 모두 최상단에 위치시키는 컨벤션을 사용하고 있어요.

2023-11-17 06:26 UTC, protocorn93 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +        timer.fire { [self] timeText in
마찬가지로 `[self]` 캡처가 필요한가요?

2023-11-17 07:47 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Teller.swift
> +        }
`DispatchQueue.main.async { ... }` 블럭으로 감싸주지 않으면 `notifyCustomerDidMatch()` 메서드 호출 결과가 UI 업데이트 작업이기 때문에 에러가 발생했습니다.

UI 업데이트 작업은 메인스레드에서 이루어져야 합니다.
저희가 토론한 후 결정한 그 이유는 다음과 같습니다.
- UI요소는 Thread-safety하지 않습니다. UI요소는 렌더링 사이클에 따라 해당 런루프에서 확인된 이후 그리게 되는데 메인스레드가 아닌 다른 스레드가 UI를 업데이트 하려고 한다면 UI업데이트 동작에 대한 결과가 어떻게 될지 보장할 수 없을 것 같다는 이야기를 나누었습니다. 그래서 Serial한 메인스레드에서 UI업데이트 작업을 하게 된다면 이러한 문제들을 해결하는 효과가 나타난다고 생각합니다.

[참고자료](https://developer.apple.com/videos/play/tech-talks/10855/)

2023-11-17 07:50 UTC, comdori-wj commented on BankManagerUIApp/BankManagerUIApp/Extensions/UIViewComponentsConvenienceInitializers.swift
같은 내용이 계속 반복되어 코드가 길어져서 가독성도 높일겸 적용해보았습니다 👍🏻

2023-11-17 08:01 UTC, comdori-wj commented on BankManagerUIApp/BankManagerUIApp/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
` window?.rootViewController = ViewController()`
- 스토리보드를 사용시 윈도우 객체를 자동으로 만들어주기 때문에 생성할 필요가 없지만 스토리보드를 사용하지 않으면 윈도우 객체를 따로 만들어줘야 합니다. 그렇기에 처음 앱이 시작되면 띄울 화면을 ViewController()로 해준 것 입니다. 물론 첫 화면은 변경 할 수 있습니다.

2023-11-17 08:11 UTC, comdori-wj commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +protocol BankDelegate: TellerWorkingStateNotifiable, AnyObject {
네 이미 상속을 받았기 때문에 지워도 됩니다. 🙂

2023-11-17 08:12 UTC, Remaked-Swain commented on BankManagerUIApp/BankManagerUIApp/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
각 코드라인에 담긴 의미를 생각해보았습니다.

우리는 스토리보드 없이 UI를 작성해야 했으므로 UISceneDelegate의 scene() 메서드를 통해 UI인스턴스를 생성하여 앱에 연결시켜주어야 했습니다.

* `window = UIWindow(windowScene: windowScene)`
    Scene객체의 정보를 가지고 새로운 Window객체를 생성합니다. Window객체는 컨트롤러의 도움을 받아 화면에 나타낼 컨텐츠를 담을 수 있습니다.
* `window?.rootViewController = ViewController()`
    이 window를 다룰 최상위의 컨트롤러를 `ViewController` 객체를 새로 생성하여 대입해줍니다.
* `window?.makeKeyAndVisible()`
    하나의 Scene에는 여러 window가 존재할 수 있는데 어떠한 이벤트를 받을 수 있는 Key Window는 하나만 존재합니다. Window객체의 초기 상태는 isHidden = true이고 Key Window가 아닌 상태입니다. 따라서 `makeKeyAndVisible()` 메서드를 호출해 숨긴 상태에서 벗어나고 Key Window로 만들어줍니다.

2023-11-17 08:17 UTC, Remaked-Swain commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +    init(_ bankManager: BankDelegate) {
해당 부분까지는 미처 신경쓰지 못했습니다.
살펴보니 저 스스로도 나중에 이 코드를 다시 읽었을 때 오해의 여지가 발생할 수도 있겠다는 생각이 들었습니다.
다음과 같이 수정할 수 있었습니다!

```swift
// Bank
init(bankDelegate bankManager: BankDelegate) {
    self.tellers = [Teller(tellerCount: 2, bankManager: bankManager), Teller(tellerCount: 1, bankManager: bankManager)]
    self.bankManager = bankManager
}

// ViewController
private lazy var bank: Bank = Bank(bankDelegate: self)
```

2023-11-17 08:22 UTC, comdori-wj commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +            DispatchQueue.global().async(group: dispatchGroup, qos: .userInitiated) { [self] in
```swift
DispatchQueue.global().async(group: dispatchGroup, qos: .userInitiated) {
    while self.customerQueue.isEmpty == false {
        guard let customer = self.customerQueue.dequeue() else { return }
        self.matchUpService(with: customer, on: teller)
    }
}
```
각 줄마다 self를 붙여줘야 하기 때문에 반복이 되어 [self] 붙이므로써 반복작업을 줄였습니다.

2023-11-17 08:41 UTC, Remaked-Swain commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +            DispatchQueue.global().async(group: dispatchGroup, qos: .userInitiated) { [self] in
DispatchQueue.global()이라는 다른 대기열 큐로 작업을 넘김, 그리고 그 작업이 있던 메모리의 참조를 유지하여야 한다? 라고 이해하고 있었습니다. 그래서 self를 캡처함으로써 참조를 유지할 수 있습니다.

```swift
tellers.forEach { teller in
    DispatchQueue.global().async(group: dispatchGroup, qos: .background) { [weak self] in
        guard let self = self else { return }
        while customerQueue.isEmpty == false {
                guard let customer = customerQueue.dequeue() else { return }
                    
                matchUpService(with: customer, on: teller)
        }
    }
}
```

이렇게 작성하는 경우에는 [self] 캡처로 참조 카운트를 올리든, [weak self]로 했으나 `guard let self = self else { return }`을 해버리면서 참조 카운트를 올리나 똑같은데 그렇다면 결국 weak 키워드를 붙이는 이유가 있느냐는 의견도 있었습니다.

해결의 실마리를 주실 수 있을까요?

2023-11-17 08:44 UTC, comdori-wj commented on BankManagerUIApp/BankManagerUIApp/Utilities/BankTimer.swift
> +    private var dateFormatter: DateFormatter = {
상수로 수정하겠습니다.

2023-11-17 08:57 UTC, Remaked-Swain commented on BankManagerUIApp/BankManagerUIApp/Utilities/BankTimer.swift
> +    private var dateFormatter: DateFormatter = {
`private let dateFormatter: DateFormatter = { }()`
이런 클로저선언문은 무조건 변수로 선언되어야 하는줄 알았는데 제가 잘못알고있었습니다.
아마도 lazy var로 선언된 뷰 요소들 때문에 그렇게 흘러간 것 같습니다..
이외에 별다른 이유는 없습니다.

2023-11-17 09:04 UTC, Remaked-Swain commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Teller.swift
> +}
-able로 네이밍할 경우 어떠한 역할을 나타내는 것 같은 느낌이 듭니다.
그래서 이 경우 TellerDelegate라는 네이밍이 더 적절하다는 것으로 이해했습니다!
감사합니다!

2023-11-17 09:12 UTC, Remaked-Swain commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    }()
self.headerVerticalStackView 해서 접근할 일이 없기 떄문에 lazy var를 떼고 let으로 아예 선언해버리는 것이 무방할 것 같습니다.
그럼에도 지연저장프로퍼티를 써서 무엇을 얻을 수 있는지 더욱 알아봐야 판단이 설 것 같습니다..

2023-11-17 09:17 UTC, Remaked-Swain commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +    }
아 코드 전반에서 사용되는 상수라서 맨 위에 위치하면 가독성 측면에 좋다는 점을 확실히 인지했습니다.
그리고 현업의 바이브도 알려주셔서 감사합니다!

2023-11-17 09:20 UTC, Remaked-Swain commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +        timer.fire { [self] timeText in
클로저의 캡처리스트에 대해서 더욱 정진하고 돌아오겠습니다........

2023-11-17 09:21 UTC, comdori-wj commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +        timer.fire { [self] timeText in
마찬가지로 `self` 캡처 안해주면 일일이 self 키워드를 붙여줘야 되기 때문에 `self`가 필요하다고 생각되어 캡처하였습니다.

2023-11-18 23:18 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Teller.swift
> +        }
네네 좋네요!

2023-11-18 23:19 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Teller.swift
> +}
네네 저도 특정 역할을 추상화할 떈 `-able`, `-Logic`을 많이 사용하고 위임시엔 `-Delegate`를 많이 사용해요!

2023-11-19 04:40 UTC, merged

2023-11-29 05:44 UTC, comdori-wj commented on BankManagerUIApp/BankManagerUIApp/Utilities/Bank.swift
> +            DispatchQueue.global().async(group: dispatchGroup, qos: .userInitiated) { [self] in
> DispatchQueue.global()이라는 다른 대기열 큐로 작업을 넘김, 그리고 그 작업이 있던 메모리의 참조를 유지하여야 한다? 라고 이해하고 있었습니다. 그래서 self를 캡처함으로써 참조를 유지할 수 있습니다.
> 
> ```swift
> tellers.forEach { teller in
>     DispatchQueue.global().async(group: dispatchGroup, qos: .background) { [weak self] in
>         guard let self = self else { return }
>         while customerQueue.isEmpty == false {
>                 guard let customer = customerQueue.dequeue() else { return }
>                     
>                 matchUpService(with: customer, on: teller)
>         }
>     }
> }
> ```
> 
> weak 키워드를 붙여줌으로써 메모리 누수 상황을 예방할 수 있음을 이해하고 있습니다. 그런데 `guard let self = self else { return }` 구문때문에 결국 참조 카운팅 1이 올라가서 weak 키워드를 붙여준 효과가 사라지는 것 아니냐는 의견도 있었습니다. 이 부분에 대해 실마리를 주실 수 있으신지요?

@newJunsung 한테 의견을 구했습니다.
가드문에서 새로운 `self`를 만들기 때문에 참조 카운팅이 되지 않는다고 합니다.