은행창구 관리 앱 [Step 1] Jane, Sajae
tasty-code/ios-bank-manager pull request #57
Opened 2024-01-23 07:51 UTC by suojae3

**리뷰어:** 
@July911

**버드:** 
@jane1choi
@suojae3

안녕하세요 July!
첫번째 PR 잘부탁드립니다 ☺️

<br/>

## 🔍  What is this PR?

은행창구 관리앱 STEP1 기능을 구현했습니다
- Queue 구현을 위한 LinkedList 구현
- 제너릭 타입의 Queue 구현
- UnitTest 작성

<br/>

## ✏️ PR Point

### BaseTestCase 클래스를 활용한 유닛테스트 구현
뱅크샐러드 테크 블로그의 테스트코드 관련 포스트를 참고하여 유닛테스트를 진행하였습니다.
참고자료: [뱅크샐러드 iOS팀이 숨쉬듯이 테스트코드 짜는 방식 3편 - 스펙별 단위 테스트](https://blog.banksalad.com/tech/test-in-banksalad-ios-3/)

1. `given/when/then` 형식으로 테스트 진행. (테스트 방식 정형화 및 테스트코드 가독성을 높이기 위해)
2. `BaseTestCase` 클래스 정의 후 서브클래싱을 통한 테스트 방식 템플릿화.

```swift
// MARK: 기존 테스트 케이스 메서드
func test_sample() {
    //given
    ...
    //when
    ...
    //then
    XCTAssertTrue(Expectation)
}

// MARK: BaseTestCase를 상속받은 테스트 케이스 메서드
func test_sample() {
    given { ... }
    when { ... }
    then { ... }
}
```

<br/>

## 📮  질문

### Queue 테스트 메서드 구현에 있어 분리(separation) 문제
1.  `enqueue()` 테스트 코드 작성에서 들어간 값을 `XCTAssert`를 통해 확인.
2. 노드에 접근하면 링크드리스트와 큐간 테스트 결과 영향이 서로 간섭받는 문제발생.
4. 들어간 값을 확인해주기 위해 `dequeue()` 를 사용하면 테스트 메서드간 분리가 안되는 문제발생.
5. 독립적인 테스트를 위해 `MockClass`를 만들어주기에는 오버엔지니어링인 상황.
6. 링크드리스트에 영향을 받지 않는 큐 유닛테스트 작성에 있어 어떤 방법이 좋은 방법인지 리뷰어님의 생각이 궁금합니다!

2024-01-23 08:11 UTC, July911 requested changes

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        return head == nil ? true : false
? true : false 이 부분이 필요한가요 ?

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +extension LinkedList {
스타일이긴 하지만 extension으로 분리하는게 더 보기 불편할 수 있습니다.

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +
Node는 다른 파일로 분리하는게 좋아보입니다.

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    /// Add
의미있는 주석인가요 ?

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        if head == nil {
만들어두신 isEmpty를 사용하지 않으신 이유가 무엇인가요 ?

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +struct LinkedList<T> {
구조체를 선택하신 이유는 무엇인가요 ? 
final class Node<T>  Node가 class여야만 하는 이유와 이점 역시도 설명해주세요.

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = nil
어떤 동작때문에  head = nil 하면 모두 사라지는걸까요 ?

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func removeFirst() -> T? {
mutating 이 의미하는바는 무엇인가요 ?

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/LinkedListUnitTests.swift
> +        sut = nil
override func setUpWithError() throws {
    override func tearDownWithError() throws {
무엇을 해주는 함수인가요 ?

2024-01-23 08:11 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/LinkedListUnitTests.swift
> +    func test_비어있지_않는_링크드리스트의_첫번째_헤드의_데이터를_가져오면_1이_나옴() {
test_비어있지_않는_링크드리스트의_첫번째_헤드의_데이터를_가져오면_1이_나옴() 

비어있지 않다고 하기보다는 1을 넣어줬다는게 조금 더 맞는 표현같습니다.

2024-01-23 08:18 UTC, July911 commented
커밋단위 잘 나눠주신점과 외부 테스트 코드 적용사례를 보고 바르게 적용하신점 정말 훌륭합니다. 
단, String과 Int타입을 굳이 나눠서 테스트해야헀나라는 생각은 조금 들더라구요. 

### 질문
Queue 테스트 메서드 구현에 있어 분리(separation) 문제
저라면 미리 
override func setUpWithError() throws 
override func tearDownWithError() throws 
를 통해 초기화작업을 끝낸 후 각 테스트 메서드 별로 해줄 것 같습니다. 
그렇다면 
- 노드에 접근하면 링크드리스트와 큐간 테스트 결과 영향이 서로 간섭받는 문제발생.
- 들어간 값을 확인해주기 위해 dequeue() 를 사용하면 테스트 메서드간 분리가 안되는 문제발생. 
를 해결할 수 있을 것 같습니다.

2024-01-24 01:26 UTC, jane1choi commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/LinkedListUnitTests.swift
> +        sut = nil
- setUpWithError(): 테스트 메서드를 실행하기 전 모든 상태를 초기화하는 메서드
- tearDownWithError(): 테스트 메서드 동작 후에 모든 상태를 해제하는 메서드
모든 테스트 함수가 실행되기 전 `setUpWithError()` 가, 실행 후 `tearDownWithError()` 가 실행됩니다.

2024-01-24 01:33 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +
감사합니다! Node 파일 따로 분리했습니다!

2024-01-24 01:37 UTC, jane1choi commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        return head == nil ? true : false
꼼꼼한 리뷰 감사합니다 :)
반영 커밋: [8858fb9](https://github.com/tasty-code/ios-bank-manager/pull/57/commits/8858fb934bf031f257f411f3b9496e0ca9ddd1f0)

2024-01-24 01:38 UTC, jane1choi commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        if head == nil {
반영했습니다!!!
반영 커밋: [8858fb9](https://github.com/tasty-code/ios-bank-manager/pull/57/commits/8858fb934bf031f257f411f3b9496e0ca9ddd1f0)

2024-01-24 01:51 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func removeFirst() -> T? {
1. 구조체는 값타입이기 때문에 기본적으로 메서드를 통해 내부 값을 수정할 수 없습니다. (스택메모리에서 실행되기 때문에 값을 변경해도 저장되지 않고 날라가버림)
2. 이때 `mutating` 키워드를 붙이면 원본 구조체 인스턴스를 인스턴스 프로퍼티가 변경된 구조체 인스턴스로 대체합니다.

2024-01-24 01:55 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +struct LinkedList<T> {
1. Node는 참조를 통해서 메모리에서 데이터를 유지합니다.
2. 이렇게 스택에서 실행되고 힙메모리를 참조하는 다이나믹 디스패치 방식으로 구현하기 위해서는 클래스로 선언해야합니다.

2024-01-24 01:56 UTC, jane1choi commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = nil
연결리스트라는 자료구조는 연속적인 메모리 위치에 저장되지 않는 선형 데이터 구조입니다. 
포인터를 이용해 다음 노드를 연결하는(양방향 연결리스트는 이전노드도 연결) 방식으로 리스트 형태를 만들기 때문에 각 노드는 연결될 노드의 포인터 위치를 가리키고 있습니다.
만약 `head` 노드에 `nil`을 할당해 노드의 데이터를 삭제해주고, 다음으로 연결될 노드에 대한 참조를 해제해준다면 그 다음 노드도 메모리에서 해제되고, 그 다음 노드도 해제.. 이렇게 도미노처럼 다 참조가 끊어져 메모리에서 해제되기 때문에 연결리스트의 모든 노드가 삭제된다고 할 수 있습니다.

2024-01-24 02:12 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    /// Add
반영했습니다!
반영커밋: [1b169a1](https://github.com/tasty-code/ios-bank-manager/pull/57/commits/1b169a11a6dc9a502e0e9bbadf6e14a9732c8874)

2024-01-24 08:10 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTest/LinkedListUnitTests.swift
> +    func test_비어있지_않는_링크드리스트의_첫번째_헤드의_데이터를_가져오면_1이_나옴() {
메서드명 수정했습니다!
반영 커밋: [e5e0bba](https://github.com/tasty-code/ios-bank-manager/pull/57/commits/e5e0bbabdc7105ba69ace85a8ca7698c07254f4a)

2024-01-26 01:57 UTC, merged