은행 창구 관리 앱 [STEP 1] 노움, 토미
tasty-code/ios-bank-manager pull request #59
Opened 2024-01-24 07:47 UTC by angryeon7

> 리뷰어 : @keeplo
버드 : @angryeon7 (토미) @Gnoam-R (노움)
> 

안녕하세요. 말꼬 이번에 은행창구 프로젝트를 같이 진행하게 된 노움과 토미입니다!

읽어보시고 편하게 피드백해 주세요!! 잘 부탁드립니다 :)

---

## Step1 요구사항

은행에 도착한 고객이 임시로 대기할 대기열(큐, Queue) 타입을 직접 구현합니다.

- Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다.
- Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용합니다.
- Queue 타입이 예상한대로 동작하는지 Unit Test를 통해 동작을 검증합니다.
    - Queue에 구현해야 할 필수 기능
        - Enqueue, Dequeue, Clear, Peek, isEmpty

## 고민한 부분 & 해결한 부분 🤔

`removeAll()` 메서드가 리스트를 비우기 위해 `head`, `tail`, `count`를 `nil` 또는 0으로 설정하여 리스트를 비우고 있습니다. 하지만, 이 코드는 리스트의 각 노드를 직접적으로 해제하지 않는다는 점이 걱정되어 노드가 해제될 때 메모리에서 정확히 해제되는지 확인하기 위해 `deinit` 메서드를 활용하였습니다.

→ `head`와 `tail`을 `nil`로 설정하면서 리스트의 모든 노드가 더 이상 참조되지 않게 되고 Swift의 ARC 가 더 이상 참조되지 않는 노드들을 자동으로 메모리에서 해제할 거라고 생각합니다.

`private(set)` 사용
- 테스트 코드에서 내부 상태나 동작을 검증하려면 클래스나 구조체의 내부에 접근할 수 있어야 합니다.
- `private`으로 속성을 선언하면 외부에서의 접근이 완전히 차단되어, 테스트 코드에서 해당 속성을 검증하기 어려웠음

→ `private(set)` 을 사용하여 내부에서는 읽고 쓰기가 가능하지만, 외부에서는 읽기만 가능하게끔 하는 것으로, 테스트에서는 읽기 가능한 선에서 상태를 확인할 수 있게 하였습니다.

## 질문 사항

- Node가 잘 생성되고 해제되었는지 유닛테스트를 해야할까요..?
- 큐, 스택, 트리 등 여러 자료 구조 및 알고리즘이 이미 구현되어 있고 라이브러리로 나와있다고 생각하는데 이러한 것들을 사용 방법만 습득하면 되지않을까? 라는 의문이 있어요.
- 저희가 모든 라이브러리에 대한 구현 방식을 공부할 필요 없다고 생각되는데 위와 같은 자료구조를 원리부터 이해해야 되는 이유가 있을까요? 현업에서 자료구조와 알고리즘을 이해해서 개발해야 되는 상황이 있는지가 궁금해요.

2024-01-24 12:00 UTC, keeplo requested changes
안녕하세요 토미 노움!
반갑습니다 이번 프로젝트 함께 진행할 말꼬입니다!!
잘 부탁드립니다 ~~ 🙌

---

## 질문사항 답변
너무너무너무 좋은 질문을 해주셨어요!!!
다들 쉬쉬하면서 그냥 하라고 하니까 해야지 하다 안하고 마는 영역이라고 생각하는데
지금 같이 과감히 질문해주시는거 너무 좋습니다!!

### Node가 잘 생성되고 해제되었는지 유닛테스트를 해야할까요..?
저는 하면 좋다고 생각합니다. 애초에 저희 접근이 ARC를 활용해서 잘 해제되는지 확인하셨을까? 인데
회사에서 팀원에 코드를 PR로 접근해도 동일할것 같아요 
그런데 테스트코드로 할당 해제에 대한 명시적인 테스트가 있다면 너무 신뢰도가 올라갈것 같아요!

### 큐, 스택, 트리 등 여러 자료 구조 및 알고리즘이 이미 구현되어 있고 라이브러리로 나와있다고 생각하는데 이러한 것들을 사용 방법만 습득하면 되지않을까? 라는 의문이 있어요.
제 기준에서는 그렇지 않다고 확신합니다.
첫번째로 사용 방법만 습득하면 절대 구현할 수 없다고 생각해요. 연습이 필요합니다!
두번째로 자료구조의 활용과 알고리즘의 활용은 기능 동작 그 이상의 영역을 다루는 중요한 키가 됩니다.
`단순 배열을 removeFirst만 사용한다고 해서 Queue가 아닙니다.`

배열의 메모리 주소 사용방법을 이해해야합니다. 
`popLast`와 `removeFirst`는 분명다른 동작이 발생합니다.
앞선 데이터가 remove 되면 그 다음 인덱스 데이터는 모두 한칸씩 이동하는데 O(n) 만큼 
주소이동 리소스가 발생합니다.

하지만 링크드리스트는 중간 데이터가 사라지거나 맨앞 데이터가 사라지면 직전 node 포인터만 
제거 노드에서 제거노드 next 노드로 연결만 해주면되고 그건 O(1) 리소스 발생합니다.

만약 지금 Step처럼 Queue 구조를 미리 구현하지 않고 단순 배열을 이용해서 
Queue 동작처럼 메서드 구성을 한다고 하면 동작에는 문제가 없을수 있지만 
성능차이가 발생합니다.

저는 비전공자와 전공자를 떠나서 고급 개발자로 넘어가는 길목에 중요한 부분이라고 생각합니다
원리 이해같고 기초소양처럼 느끼는 많은 CS 과목들은 별개의 영역이 아닙니다
어떠한 고급 언어도 결국 CPU 입장에서는 0과 1의 나열일 뿐이고 
아무리 하드웨어 성능이 좋아져도 효율성의 차이는 분명 존재합니다!

그리고 개발자의 능력을 좌우하는 부분은 이런 디테일이라고 생각해요
기능 구현에 급급한 개발이상에 무언가가 연봉의 차이를 만들게 된다고 생각해요!

### 저희가 모든 라이브러리에 대한 구현 방식을 공부할 필요 없다고 생각되는데 위와 같은 자료구조를 원리부터 이해해야 되는 이유가 있을까요? 현업에서 자료구조와 알고리즘을 이해해서 개발해야 되는 상황이 있는지가 궁금해요.
Native 개발자와 멀티플랫폼 개발자 또는 앱 출시하는 프론트엔드 개발자 와의 차이점이 여기에서 온다고 생각합니다. 단순히 UI 동작이 표면적으로 보여지는데만 초점을 잡는다면 사실 Native로 구현할 필요가 딱히 없습니다. 종 더 구체적인 디바이스 기능 사용이나 그런부분도 결국 말씀하신 것처럼 구글링만 하면 누구나 라이브러리를 사용할 수 있죠...

그런면에서 Native 개발자는 iOS 디바이스 특성과 swift 언어의 특성을 깊게 파악하고
성능적인 부분을 개선할 수 있어야 합니다.

그런면에서 자료구조 원리나 알고리즘를 이해하는 점은 너무나 중요합니다.
사실 두번째 질문의 유사한 답변이긴 합니다. 하지만 두번 언급해도 부족하지 않습니다.
고급개발자와 단순 코더와 차이점은 디테일에서 옵니다.

마지막에 말씀하신 현업 부분에서도 차이가 분명 존재합니다
팀원 간에도 차이가 발생하기도 하죠... 
1순위는 기능 동작이지만 리펙토링이라거나 최소한 인지하고 효율성을 개선할 수 있는 개발자
또는 기능 설계부터 성능을 고려하는 개발자는 어디에 가도 인정 받습니다.

아는 사람눈엔 보이고 모르는 사람은 평생 모르는 거죠..

--- 

- LinkedList 의 동작에 대해 좀더 고민이 필요합니다
   - 단순 Queue 만을 위한 구현인데 그러면 확장가능성을 닫는 구현이라고 생각해요 
   - 중간 노드가 삭제되는 부분까지 고려해서 ARC 원리와 해제를 고민해보면 좋을것 같아요!
- `private(set)` 적절히 잘 사용해 주셨다고 생각해요!

---

전체적으로 짧은 시간에 잘 구현해주신 것 같아요
테스트 작성이 처음이시라면 쉽지 않으실텐데 아주 잘해주셨어요!!
리뷰를 통해 언급한 부분들 다시 고민해보고 수정해보면 좋을것 같습니다!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +            count += 1
이런 상황은 `count = 1` 로 명시하는게 좋지 않을까요?

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        count = isEmpty ? count : count - 1
매번 삼항연산자를 2번씩 동작할 필요가 있을까요?

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func remove() -> Element? {
메서드의 구현방식이 Queue 동작만을 위한 구현인 것 같습니다.
`LinkedList`는 Queue 뿐만아니라 `Stack`또는 `Deque` 같은 다른 자료구조에도 활용될 수 있을것 같은데요.

어떠한 자료구조에도 활용될 수 있도록 
`LinkedList`를 구성하는 방향을 고민해보면 좋을것 같습니다.

어떤 형태로 구성되면 다른 자료구조도 대응될 수 있는지 또는 현재 구현에서 문제점은 없는지 답변으로 주시거나
가능하다면 수정해보면 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Queue.swift
> +        linkedList.append(item: item)
인수명을 추가해보거나 생략하면 어떨까요?

Line 13 처럼 중복되는 네이밍이 발생할 것같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTellerQueue.swift
> +struct BankTellerQueue<Element> {
구조체로 타입을 변경한 의도가 있으실까요?

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +final class QueueTest: XCTestCase {
QueueTest 라고 명명하시면 특정 개체보다 Queue 로 대변되는것 같아요

BankTellerQueueTest  로 명명하면 좋을것 같아요!

SUT 또는 `Test Double`이라는 키워드를 알고 계신가요?
만약 모르신다면 학습해보시고 UnitTest에 적용해보시면 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +    func test_dequeue호출시_빈배열일시_nil을반환하는지() {
`빈 배열`이라는 용어는 어색한거 같아요! 
 다른 용어로 정제해서 혼동을 줄이면 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +        XCTAssertEqual(sut.peek(), result)
불가피하게 검증 도구로 다른 메서드를 사용해야한다면
동작의 테스트가 완료된 후에 사용되면 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +        XCTAssertEqual(sut.peek(), 1)
1을 하드코딩 하는것보다 Line 47 의 result를 Equal 체크 하면 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +        XCTAssertEqual(sut.dequeue(), nil)
코드만 보면 dequeue 테스트 처럼 보일 수도 있을것 같아요
그리고 반대로 얘기하면 dequeue 테스트의 실패(옵셔널반환) 테스트도 따로 구현되어 있으면 좋을 것 같아요!

그래서 디테일을 적어주신것처럼 인지하기 좋게 테스트를 작성해보는것도 좋을것 같아요!
~~~swift
let result = 1

sut.enqueue(item: result)

XCTAssertEqual(sut.dequeue(), result)
XCTAssertEqual(sut.dequeue(), nil)
~~~

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
>          }
테스트코드도 코드에 일부이며 다양한 개발서적에서 공통적으로 
`테스트는 메서드 또는 개체의 설명서 역할`을 할 수 있다고 소개합니다.

그런 면에서 테스트코드는 구현자가 혼자 확인을 위한 작성이라기 보다
반대로 기능 구현자 외의 모든 사람을 위한 코드라고 볼 수도 있습니다.
테스트는 보시는것처럼 이번 프로젝트에서 UI 가 없는 상태에서 구현된 코드에 대하여 검증할 수 있는 좋은 도구입니다.

테스트코드라도 API Design Guidelines 를 반영하는 네이밍스타일 을 유지하면 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +        XCTAssertEqual(sut.isEmpty(), true)
이 부분을 통해서 전달 드리고 싶은 메시지는 
`실패 케이스` 또는 `검증 케이스` 입니다

이 메서드를 기준으로 말씀드리자면 `isEmpty`메서드에서 
`false` 가 나오는 추가 검증케이스가 있는것도 좋을것 같아요!

메서드의 테스트라고 하기 엔 단편적인 검증만 하는것 같아요!
Bool 타입처럼 명확하거나 옵셔널 타입처럼 구분 가능하면 나눠서 테스트를 명시해주면 더 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
>      }
이 메서드 뿐만 아니라 전체적으로 BDD 를 적용하시면서 

give - when - then 구분을 줄바꿈을 해주어 가독성을 높혀주는것도 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +        XCTAssertEqual(sut.peek(), nil)
테스트 내용에 peek 로 확인한다고 명시해도 괜찮을것 같고 

저였다면 (정답은 절대아닙니다)
~~~swift
fileprivate BankTellerQueue<Element> {
    var last?: Element { self.peek() }
}
~~~
같은 구현을 추가해서 peek 검증 이후에는 이 연산프로퍼티로 peek 의 사용을 표면적으로 가릴것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +    }
`List` 또는 `리스트`로 용어는 통일하면 좋을것같아요!

~해서 ~시 ~후 같은 경우에도 한가지로 통일하면 좋을거 같아요

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +        XCTAssertEqual(sut.count, 0)
여러 테스트를 모두 해주시는군요 아주 좋습니다👍👍

상태값이 모두 체크되니까 네이밍에 그런걸 담아도 좋을것 같아요!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func removeFirst() -> Element? {
네이밍이 좀 더 명료해지네요! 아주 좋습니다  😻

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +    }
이 경우가 `LinkedList`의 구현이 Queue 만을 위한 상태라는걸 대변하는 것 같아요
만약 자체 구성이 다르게 되었다면 
`처음 아이템을 추가할 때`같은 기준점이 생겨서 좋을것 같아요!
두번째 아이템부터는 head 값은 변하지 않겠죠?!

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +final class Node<Element> {
`final` 키워드를 추가해주셨군요!

이 키워드를 추가하신 의도를 설명해주실 수 있을까요?

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
>      var next: Node?
이 프로퍼티는 다음 노드를 가리키는 포인터의 역할을 하게되는데요

강한참조로 연결된다면 문제가 발생하지 않을까요?
그렇다면 어떻게 하면 좋을지, 그렇지 않다면 어떤 원리로 그런지 설명해주실 수 있을끼요?

2024-01-24 12:00 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +final class Node<Element> {
Generic 타입구현으로 다양한 타입에 대응되도록 구현해주셨군요 너무 좋습니다!! 🙌

2024-01-25 11:47 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +final class Node<Element> {
**Final을 추가한 이유**
Final은 서브클래스에서 특정 method, property, subscript 가 오버라이드 되지 않도록 하기위해서 final 키워드를 사용합니다. final을 사용한 클래스는 가장 하위의 클래스로 상속을 할 수 없습니다.

**Final을 사용하게 되면 생기는 이점**
클래스의 경우 원래 Dynamic Dispatch가 사용되지만 final을 사용하게되면 class도 static dispatch 할 수 있습니다.
따라서 메모리 성능이 좋아집니다!

2024-01-25 22:26 UTC, Gnoam-R commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTellerQueue.swift
> +struct BankTellerQueue<Element> {
클래스가 아닌 구조체로 구현이 가능하기 때문입니다. swift에서는 클래스보다 구조체로 개발하는것을 지향하는데요 
구조체는 값 타입으로 객체 생성후 값에 의한 변경이 다른 객체에 영향을 주지 않습니다. 또한 메모리의 할당에서의 성능상 장점이 있어 클래스와 구조체 모두로 구현이 가능하다면 구조체를 사용하는것이 좋은것 같습니다

2024-01-26 01:36 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
>      var next: Node?
현재 `next` 프로퍼티가 강한 참조로 선언되어 있기 때문에 각 노드 사이에 강한 참조 순환이 발생할 수 있습니다. 이는 강한 참조 순환 또는 순환 참조를 발생시킵니다 → 메모리 누수의 원인

예를 들어, 노드 A가 노드 B를 참조하고, 노드 B의 `next`가 다시 노드 A를 참조한다면, 이는 강한 참조 순환이 발생한 것입니다. 이런 경우에는 두 노드 모두 메모리에서 해제되지 않습니다!
이때에는 약한 참조(weak reference)를 사용하여 순환 참조를 피할 수 있습니다

약한 참조는 참조하고 있는 객체를 강하게 유지하지 않고, 참조 대상이 메모리에서 해제되면 자동으로 `nil`로 설정됩니다.

2024-01-26 01:48 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        count = isEmpty ? count : count - 1
if 문을 사용하여 불필요한 동작을 줄일 수 있도록 수정하였습니다!

2024-01-26 01:49 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +            count += 1
`count = 1 `로 명시하는 코드로 수정하였습니다~

2024-01-26 07:00 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func remove() -> Element? {
`Stack,` `Deque ` 같은 다른 자료구조에서도 활용할 수 있도록 삽입, 삭제, 조회 메서드를 추가하여 대응할 수 있도록 코드를 변경하였습니다.

2024-01-26 12:28 UTC, angryeon7 commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +final class QueueTest: XCTestCase {
**SUT (System Under Test)**
"SUT" 또는 "System Under Test"은 테스트 중인 시스템 또는 코드 조각을 나타내는 용어입니다. 
즉, 테스트를 수행하고자 하는 대상이 됩니다..

**Test Double**
테스팅을 목적으로 실제 객체 대신에 사용하는 가짜 객체를 의미하며 Dummy, Fake Object, Stub, Mock들이 있습니다. Test Double은 테스트를 단순화하고 테스트 케이스를 더 쉽게 작성할 수 있도록 도와줍니다.
이러한 Test Double들은 테스트를 더 쉽게 작성하고 의존성을 효과적으로 관리하도록 도와줍니다. 코드의 일부분을 분리하여 테스트하거나, 외부 리소스에 대한 의존성을 제어하기 위해 사용됩니다.

2024-01-26 12:52 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTellerQueue.swift
> +struct BankTellerQueue<Element> {
클래스보다 구조체로 구현하시는 기준이 있으신것 같군요.

제가 궁금했던 출발점은 첫째는 `BankTellerQueue` 개체가 변경된 이유도 있지만 `LinkedList`는 클래스로 설계하셔서
다르게 구조체로 바꾸신 의도가 궁금했습니다.
말씀해주신 기준들에서 두 타입이 다른 이유도 설명해주실 수 있을까요?

추가적으로 추가 설명을 부탁드리고 싶은부분이 있어요!
**swift에서는 클래스보다 구조체로 개발하는것을 지향하는데요** 
혹시 어떤 레퍼런스를 참고하신건지 어떤이유로 지향하는지 설명을 해주실 수 있을까요?

**구조체는 값 타입으로 객체 생성후 값에 의한 변경이 다른 객체에 영향을 주지 않습니다.** 
말씀해주신 이 부분을 조금 더 설명해주실 수 있을까요? 영향을  주지 않는 기준이 궁금합니다!

2024-01-26 15:07 UTC, merged

2024-01-29 11:28 UTC, Gnoam-R commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTellerQueue.swift
> +struct BankTellerQueue<Element> {
마지막 질문에 대해서 먼저 답변 드리자면 구조체는 값 타입이기 때문에 클래스와 달리 하나의 인스턴스를 생성후 다른 변수에 복사하여 사용하는 경우 같은 인스턴스를 전달 받은 2개의 변수는 서로의 값에 영향을 끼치지 않습니다. 
그 이유는 말그대로 클래스는 주소를 참조하여 주소값을 복사해서 2개의 변수는 하나의 메모리를 사용하는 반면 구조체는 복사되어 각각의 메모리가 스텍 영역에 저장되기 때문입니다.

`Node`의 경우 생성되는 인스턴스에 대한 참조 방식으로 `LinkedList`를 구현하여 각각의 노드가 다음 노드에 대한 참조를 구현 방식을 위해서 클래스로 설계했습니다

`Node`와 같이 특정 조건을 제외한다면 클래스가 아니라 기본적으로 구조체로 먼저 생성하는 방식을 선호합니다.
그 이유로 스위프트 공식문서에서 `구조체와 클래스 중 선택`이라는 항목을 살펴보았습니다

위 레퍼런스에서 개요 부분을 요약하자면 
스위프트 프로그래밍은 기본적으로 구조체를 사용한다. 구조체를 사용하면 앱의 전체 상태를 고려할 필요 없이 코드의 일부를 더 쉽게 추론이 가능하며, 클래스와 달리 값 타입이므로 구조체에 대한 앱 흐름에 의도적으로 전달하지 않는한 영향을 끼치지 않는다 라는 내용이 명시되어 있습니다.

https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes

그럼 왜 `BankTellerQueue`는 클래스이고 `LinkedList`는 구조체 이냐? 둘 다 구조체로 만들어야 하는게 아닌가? 
이는 WWDC에서 메모리 관리와 관련하여 비슷한 내용이 있습니다. 

![image](https://github.com/tasty-code/ios-bank-manager/assets/67363759/850adaa5-362e-41ac-8994-e4330fbb0674)

구조체는 클래스에 비해 메모리의 할당 / 할당 해제가 빠르지만 값 타입인 `Queue` 안에 참조 타입인 `Node` 가 들어있는 구조인 경우 구조체를 선택하는 것이 더 느려질 수 있습니다.  따라서 `LinkedList`는 클래스로 선언했으며 클래스는 값 복사를 하지 않기 때문에 다수의 `Node`를 생성하는 경우에 대해서 적합하다고 생각했습니다. 
반면에 큐의 경우 현재 하나의 인스턴스 만을 생성하고 있으며 위의 LinkedList와 같이 클래스로 생성해야 하는 이유가 없기 때문에 구조체로 구현하게 되었습니다

2024-01-31 12:16 UTC, Gnoam-R commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTellerQueue.swift
> +struct BankTellerQueue<Element> {
1. “구조체는 값 타입으로 객체 생성후 값에 의한 변경이 다른 객체에 영향을 주지 않습니다.” 의 의미
- 구조체는 값 타입이기 때문에 클래스와 달리 하나의 인스턴스를 생성후 다른 변수에 복사하여 사용하는 경우 같은 인스턴스를 전달 받은 2개의 변수는 서로의 값에 영향을 끼치지 않습니다.

그 이유는 말그대로 클래스는 주소를 참조하여 주소값을 복사해서 2개의 변수는 하나의 메모리를 사용하는 반면 구조체는 복사되어 각각의 메모리가 스텍 영역에 저장되기 때문입니다.

- Node의 경우 생성되는 인스턴스에 대한 참조 방식으로 LinkedList를 구현하여 각각의 노드가 다음 노드에 대한 참조를 구현 방식을 위해서 클래스로 설계했습니다

2. 클래스보다 구조체로 구현하는 기준
Node와 같이 특정 조건을 제외한다면 클래스가 아니라 기본적으로 구조체로 먼저 생성하는 방식을 선호합니다.

 그 이유로 스위프트 공식문서에서 구조체와 클래스 중 선택이라는 항목을 살펴보았습니다
 
 https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes
 
 위 레퍼런스에서 개요 부분을 요약하자면  
 - 스위프트 프로그래밍은 기본적으로 구조체를 사용한다. 
 - Objective-C로 짜인 무언가와 연관되어있다면 Class를 사용한다. 
 - 데이터의 identity 를 다뤄야 할 필요(동일성 제어가 필요할때)가 있다면 클래스를 사용한다라고 명시되어있습니다.
 
 - 그럼 왜 BankTellerQueue는 구조체이고 LinkedList는 클래스 이냐? 둘 다 구조체로 만들어야 하는게 아닌가?
 이는 WWDC에서 메모리 관리와 관련하여 비슷한 내용이 있습니다.
 
 구조체는 클래스에 비해 메모리의 할당 / 할당 해제가 빠르지만 값 타입인 Queue 안에 참조 타입인 Node 가 들어있는 구조인 경우 구조체를 선택하는 것이 더 느려질 수 있습니다.
  
 따라서 클래스는 값 복사를 하지 않기 때문에 다수의 Node를 생성하는 경우에 대해서 적합하다고 생각하여LinkedList는 클래스로 선언했습니다. 반면에 큐의 경우 현재 하나의 인스턴스 만을 생성하고 있으며 위의 LinkedList와 같이 클래스로 생성해야 하는 이유가 없기 때문에 구조체로 구현하게 되었습니다

2024-02-01 02:20 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        count -= 1
제가 리뷰드렸던 의도는 isEmpty 일 경우는 
메서드 초반에 `guard` 로 이후 로직이 동작할 필요가 없지 않나 싶었습니다!

지금 동작에도 큰 문제는 없을것같아요!

2024-02-01 02:20 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func prepend(item: Element) {
외부에 노출되는 인수명에 관해서는 모두 동일한 기준으로 고민하면 좋을것 같아요!

2024-02-01 02:20 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func removeAt(index: Int) -> Element? {
`API Design Guidelines` 는 완전 습관이 될 정도로 자꾸봐서 외워질 정도로
봐도 부족하지 않습니다! ㅎㅎ

가이드 라인에 따르면 `remove(at index: Int)` 형태로 작성하는 쪽이 좋을것 같아요!

2024-02-01 02:20 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    }
메서드는 0을 넣으면 에러가 나는 구조입니다.
메서드 자체에 대한 에러 경우까지 모두 감당할 수 있도록 로직을 신경써주시면 좋을것 같아요!

구현자는 index 가 0인 경우면 head를 사용할거라고 생각하는데,
미래의 구현자나 다른 개발자는 그 점을 인지하지 못한다면 에러를 유발할 수 있습니다!

2024-02-01 02:20 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
>      var next: Node?
말씀해주신 위험성을 감안해서 `weak` 으로 수정하는 건 어떻게 생각하시나요?

`LinkedList` 에서 head와 tail도 고민해보시면 좋을것 같습니다.

2024-02-01 02:20 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func remove() -> Element? {
요구사항에 없는 부분까지 구현할 필요는 없지만 
`LinkedList` 사용에 필요한 영역은 `Queue` 동작이 연상되지 않는 독립적으로 구현되면 충분할것 같아요!

지금 구현도 아주 좋습니다.

2024-02-01 02:20 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTellerQueue.swift
> +struct BankTellerQueue<Element> {
음 제가 무언가를 놓친것 같은데..

> 구조체는 클래스에 비해 메모리의 할당 / 할당 해제가 빠르지만 값 타입인 Queue 안에 참조 타입인 Node 가 들어있는 구조인 경우 구조체를 선택하는 것이 더 느려질 수 있습니다. 

이 문장을 조금 더 쉬운말 풀이해주실 수 없을까요??;; 이해하기가 어려운것 같아요 ㅠㅠ

"Queue (구조체) 안에 `Node`가 들어가 있는 구조"라는 기준은 `front` 와 `rear` 프로퍼티를 말씀하시는 걸까요?
`front` 프로퍼티는 타입이 참조타입인 Node 인데 구조체 안에 있어도 참조타입의 주소값을 저장하는 형태이지 않나요?

값 복사 같은 경우는 mutating으로 변경점이 생겨도 발생하는 걸로 알고 있거든요.
enqueue가 동작할때 프로퍼티 값이 바뀐다면 Queue (구조체) 개체는 내부 프로퍼티만 바뀌는게 아니라 
인스턴스 전체가 값 복사 될 수 도 있는걸로 알고 있습니다. 
(제가 혹시 잘 못 알고 있는걸까요?;; `inout` 동작 원리 같은 아티클을 봤는데 레퍼런스 주소는 못찾겠네요 ㅠㅠ)

---

추가적으로 
> LinkedList는 클래스로 선언했으며 클래스는 값 복사를 하지 않기 때문에 다수의 Node를 생성하는 경우에 대해서 적합하다고 생각했습니다.

이 부분도 다수의 `Node` 가 생성되는건 struct 나 class 내부에서 동일한걸로 예상되는데
혹시 제가 놓치는 부분이 있는건지 ㅠㅠ 이해가 안되는데 설명을 조금 더 해주실 수 있을까요?

2024-02-01 02:38 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTellerQueue.swift
> +struct BankTellerQueue<Element> {
뭔가 오해가 있는것 같습니다.

> 따라서 클래스는 값 복사를 하지 않기 때문에 다수의 Node를 생성하는 경우에 대해서 적합하다고 생각하여LinkedList는 클래스로 선언했습니다. 반면에 큐의 경우 현재 하나의 인스턴스 만을 생성하고 있으며 위의 LinkedList와 같이 클래스로 생성해야 하는 이유가 없기 때문에 구조체로 구현하게 되었습니다

"class로 선언된 Node 가 다수 할당(인스턴스화)되는 부분이 
`LinkedList` 내부에서 벌어지기 때문에 `LinkedList`을 클래스로 만들었다",
"`Queue` 내부에서는 다수의 할당이 없고 내부에 `LinkedList`만 인스턴스화 한번만 하기때문에 구조체로 만들었다."

이렇게 의미하시는게 맞을까요??

인스턴스화의 속도 차이라거나 주소에 관한 부분들 말씀해주신 부분들은 저도 동일하게 이해하고 있습니다.
하지만 구조체 인스턴스와 클래스 인스턴스는 할당된 후 인스턴스가 동작하는데서 분명 다른 특성을 가지고 있는데

제가 말씀드릴 mutating 부분이 구조체의 특성중 하나입니다.
내부 프로퍼티 변경 -> 곧 인스턴스 자체의 변경 -> A > A' 인스턴스 복사후 치환 (제가 알고있는 구조체 특성)
이런 형태의 특성도 있구요..

제가 인지한 의미가 맞으시면 뭔가 방향이 살짝 틀어진것 같아요!

구조체 인스턴스라고 해서 내부 클래스 인스턴스가 서로에게 참조하는 게 불가능하지 않거든요
클래스 내부에서 인스턴스 생성이 10번 할당되는것과 구조체 내부에서 인스턴스 생성이 10번 할당되는것에 시간 차이는 없습니다.
내부에서 10번 생성될 인스턴스 타입이 구조체인지 클래스인지에 차이는 발생할 수는 있습니다.
하지만 같은 타입인데 구조체 내부 또는 클래스 내부에서 인스턴스화 되는데서 시간차이는 없습니다.