은행 창구 관리 앱[STEP 1] Sidi, Hoi
tasty-code/ios-bank-manager pull request #60
Opened 2024-01-24 07:55 UTC by happykwon

@minsson

안녕하세요, 민쏜
Hoi(@happykwon), Sidi(@jus1234)입니다!
은행 창구 관리 앱[STEP 1] PR입니다.
바쁘신 와중에 리뷰를 해주셔서 감사합니다. ☺️

## 🔍 What is this PR?

STEP 1 기능 구현
- Linked - List 자료구조 구현 
- 은행에 도착한 고객이 임시로 대기할 대기열(Queue) 타입 구현
- Unit Test 

## 📝 PR Point

### 1. Linked - List 자료구조 구현
[ data, next] 가 한 쌍을 노드로 구현된 linked -list 자료 구조 구현 

### 2. Linked - List 자료구조를 채택한 Queue 타입 구현 
Queue라는 FIFO ADT를 프로토콜로 만들고  그것을 채택한 LinkedListQueue 구현  

### 3. Unit Test Code 작성 
각 메스드별 Unit Test Code 작성 

## 질문

### 1. 유닛테스에 관한여 
현재 작성한 코드에서는 ed1476cdb6f3065e4324240009392692265d8c0a 와 같이 인큐와 디큐를 한거번에 테스트하고 있습니다. 인큐와 디큐를 각각 테스트 하는 것이 맞다고 생각은 드는데 인큐된 요소를 확인하는 방법이 디큐 밖에 없어 테스트 코드에서 인큐와 디큐를 둘 다 사용해 작성 했습니다. 이런 경우 메서드 별 독립적인 테스트 코드를 작성하려면 어떻게 할 수 있을 지 궁금합니다.

2024-01-25 15:00 UTC, minsson requested changes
안녕하세요, Sidi, Hoi!
반갑습니다! 3주 동안 잘 부탁드려요! 

자료구조도 잘 구현해주셨고, Generics도 잘 사용해주셨군요!
전반적으로 코드가 너무너무 깔끔해서 가독성이 무척 좋았습니다! 
테스트도 잘 작성해주셨고요!

## 질문 답변

> 1. 유닛테스에 관한여
> 현재 작성한 코드에서는 https://github.com/tasty-code/ios-bank-manager/commit/ed1476cdb6f3065e4324240009392692265d8c0a 와 같이 인큐와 디큐를 한거번에 테스트하고 있습니다. 인큐와 디큐를 각각 테스트 하는 것이 맞다고 생각은 드는데 인큐된 요소를 확인하는 방법이 디큐 밖에 없어 테스트 코드에서 인큐와 디큐를 둘 다 사용해 작성 했습니다. 이런 경우 메서드 별 독립적인 테스트 코드를 작성하려면 어떻게 할 수 있을 지 궁금합니다.

제 개인적인 생각으로는 LinkedListQueue의 queue 프로퍼티가 은닉화 되어 있기 때문에 enqueue와 dequeue를 완전히 분리해서 테스트하는 건 어려울 것 같아요. enqueue의 경우 dequeue를 쓰지 않고 peek을 쓰는 방법이 있기는 하지만, 그것도 결국 다른 메서드에 의존하는 건 마찬가지일 거고요.

다만 enqueue와 dequeue의 테스트를 나눠볼 수는 있겠다는 생각은 들어요. 즉, dequeue만을 위한 테스트 케이스를 하나 더 만들 수 있어요. 이 경우 enqueue의 정상 작동 여부는 다른 테스트에서 검증했다고 가정하고, 이 테스트 케이스에서는 dequeue의 정상 작동 여부에만 초점을 맞출 수 있을 것 같아요.

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +class Node<T> {
Node를 포함해, 구현해주신 모든 `class` 객체에 `final` 키워드를 붙여도 좋을 것 같아요. 혹시 `final` 키워드에 대해 공부해보신 적이 있나요?

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var next: Node?
접근제어에 대해 고민해봐도 좋을 것 같아요! 예를 들어, 현재 기준에서 봤을 때 외부에서 `data`에 접근해, 값을 수정하는 코드가 있거나, 나중에 그렇게 할 계획이 있나요?

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
[if let shrthand](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md)을 사용해보면 어떨까요?

`if let tailNode = tail { }`을 `if let tail { }`로 쓸 수 있어요. 불필요한 네이밍을 생각하지 않아도 되고, 가독성도 좋아진다는 장점이 있어요.

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            }
`removeFirst()` 메서드를 다시 한번 되짚어보며 이 코드의 실행시점에 대해 고민해보면 좋을 것 같아요! 실행될까요?

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
`if head == nil { return nil }`
`if node?.next?.next == nil { break }`

두 줄의 컨벤션이 눈에 들어오네요! 저는 최근까지 거의 무조건 개행을 했었는데, 요즘은 저도 이런 컨벤션을 써볼까 고민 중이에요. 두 분께서 어떤 기준으로 컨벤션을 정하셨는지 궁금해요.

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +import Foundation
불필요해보이는 코드인데, 제거하는 게 어떨까요?

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedListQueue.swift
> +    }
`return self.count == 0 ? true : false` 대신 `return self.count == 0`라고 써도 될 것 같은데 반환값을 따로 명시해주신 이유가 궁금해요.

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedListQueue.swift
> +        }
위에서 정의한 연산프로퍼티인 `isEmpty`를 활용해보면 어떨까요?

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedListQueue.swift
> +    }
- 메서드명이 clear인데 `queue.head.next`와 `queue.head.next.next`.... 등에는 `nil`을 할당하지 않은 이유가 무엇인가요?

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +}
이 코드를 제거하고, LinkedListQueue에서 Queue 프로토콜을 채택하지 않아도 코드가 잘 돌아가네요! 어떤 목적과 의도로 추상화하신 건지 궁금합니다!

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTests/BankManagerConsoleAppUnitTests.swift
> +    }
혹시 이 메서드가 주로 어떤 용도로 사용되는지 설명해주실 수 있나요?

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTests/BankManagerConsoleAppUnitTests.swift
> +    }
에러를 throw하지 않는다면 아래의 메서드들을 사용해도 돼요. 바꿔야 한다는 게 아니고, 이런 것도 있다는 정도만 알아둬도 충분할 것 같아요.

```swift
override func setUp() {
    
}
  
override func tearDown() {
  
}
```

2024-01-25 15:00 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTests/BankManagerConsoleAppUnitTests.swift
> +    func test_큐에_두개의_요소를_인큐했다가_peek을_하면_천번째로_인큐한_요소가_나온다() {
```suggestion
    func test_큐에_두개의_요소를_인큐했다가_peek을_하면_첫번째로_인큐한_요소가_나온다() {
```

2024-01-26 01:20 UTC, jus1234 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +class Node<T> {
더이상 상속되지 않는 클래스의 경우 `final` 키워드를 추가해 `statuc dispatch`가 되도록 수정했습니다!
 `statuc dispatch`는 컴파일 시점에 메서드가 결정되기 때문에 성능 상 이점이 있습니다.

2024-01-26 01:24 UTC, jus1234 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var next: Node?
`data`에 접근해 수정하는 코드가 없고 앞으로도 직접 접근해 수정할 계획은 없어 은닉화와 캡슐화를 적용한 코드로 수정했습니다!

2024-01-26 01:32 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
{ } 안에 들어가는 코드의 양이 간단하다면(로직적인 부분이 들어가지 않는다면)
개행을 하지 않고, 이어서 써주기로 컨벤션을 정했습니다. 이렇게 하면 개행을 해주는 것보다.
같은 줄에서 처리되는 결과에 값을 한눈에 파악할 수 있어 가독성이 더 좋을 것 같다고 판단했습니다.

2024-01-26 01:39 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTests/BankManagerConsoleAppUnitTests.swift
> +    }
오류를 던질 수 있는 메서드로 주로 테스트 중 생성된 데이터나 상태를 정리하는 데 사용됩니다. 
보통 목데이터를 활용한 네트워크 통신 테스트에서 네트워크 세션을 종료하거나, 임시 파일 삭제를 하는 등의 정리 작업을 할 때 자주 사용된다고 알고 있습니다.

2024-01-26 01:48 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedListQueue.swift
> +    }
구조를 생각해보면 head -> node -> node -> tail  형식의 구조로 이루어져있고 각 node(head / tail을 제외한)의 RC값이 1입니다. 이때 head와 tail에 nil값을 할당하면 참조가 연쇄적으로  끊어져 각각의 node에 전부 nil을 할당하지 않더라도 deinit이 됩니다.

2024-01-26 01:49 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +import Foundation
삭제 완료했습니다

2024-01-26 01:50 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedListQueue.swift
> +    }
수정했습니다 :)

2024-01-26 02:04 UTC, jus1234 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
`if let tail { }`으로 수정했습니다! 코드가 간결해지고 가독성이 올라간거 같습니다!

2024-01-26 02:10 UTC, jus1234 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedListQueue.swift
> +        }
수정했습니다! 정의한 계산 속성을 사용해 비어있지 않다는 것을 더 명확히 표현할 수 있게 된거 같습니다!

2024-01-26 02:20 UTC, jus1234 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            }
```
private func removeFirst() -> T? {
        if  head != nil {
            let value: T? = head?.value()
            head = nil
            tail = nil
            return value
        } else {
            return nil
        }
    }
```
로 수정 했습니다!

2024-01-26 02:23 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTests/BankManagerConsoleAppUnitTests.swift
> +    }
앞으로 에러처리가 필요한 경우와 아닌 경우에 맞춰 Unit Test의 사용할 메서드를 한번 더 생각해보겠습니다. 👍

2024-01-26 02:23 UTC, jus1234 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +}
`Queue`는 프로토콜에서 작성된 메서드(enqueue, dequeue 등)를 수행하면서 `FIFO`가 지켜지면 되는 추상적인 개념이라고 생각해 프로토콜로 설계했습니다. `Queue`가 프로토콜이 됨으로써 `LinkedList`를 제외한 다른 자료구조로도 구현될 수 있도록 설계하고 싶었습니다.

2024-01-26 12:15 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var next: Node?
음... 객체지향 프로그래밍에 대해서는 저도 말씀드리기가 특히 조심스러워요. 저도 아직 잘 모른다고 생각하고, 괜히 제 말로 인해서 오해가 생길 수도 있다고 생각하기 때문이에요. 그래도 개인적인 생각을 말씀 드리자면 아래와 같아요.

어떤 커스텀 타입의 프로퍼티가 있고, 그 안의 특정 프로퍼티의 값만 읽어야 하는 경우라면 그 특정 프로퍼티에만 접근할 수 있게 해주는 메서드를 만들고 나머지에 대해서는 접근을 완전히 차단하는 건 좋다고 생각해요. 개인적으로는 그게 제대로 된 은닉화와 캡슐화라고 생각하고요. (제 개인적인 생각일 뿐이에요)

그런데 가끔 보면 모든 프로퍼티에 대한 접근을 차단하고, 메서드를 통해서만 접근할 수 있게 하는 코드도 많이 보는데, 저로서는 아직 그 효용이 무엇인지 모르겠어요. 이와 관련해서 메서드로 만들어놓으면 return하기 전에 뭔가 다른 작업을 할 수도 있다... 그래서 유지보수하기 좋다..는 식의 글을 본 적도 있는데 그런 경우도 별로 없을 것 같고, 만약 필요하다면 필요해지는 순간에 만들면 된다고 생각하고요.

그래서 여기서도 제가 의도했던 건 `private`이 아니라 `private(set)`이었어요. 현재 상황에서는 밖에서 읽을 수만 있으면 되는 상황이고, `data`라는 값 자체에 접근할 거기 때문에 굳이 `private`으로 해놓을 필요는 없다고 생각해요.

제 개인적인 생각일 뿐이므로 이런 생각을 하는 사람도 있다고 생각해주시면 됩니다 ☺️

2024-01-26 12:22 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +class Node<T> {
그 부분도 중요한 것 같고, 또 한 가지로, 저는 final 키워드가 붙어있지 않으면 상속의 가능성을 생각하게 되더라고요. 그래서 혹시 상속 받는 클래스가 있는지 찾아보곤 해요. 그런 오해의 여지를 줄여줄 수도 있다는 점에서도 좋을 것 같아요.

2024-01-26 12:25 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedListQueue.swift
> +    }
저는 처음 LinkedList를 구현할 때 이게 가장 어려웠어요. 그래서 여쭤봤습니다 😅

2024-01-26 12:53 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleAppUnitTests/BankManagerConsoleAppUnitTests.swift
> +    }
넵, 여기에 `sut = nil`이 들어가도 좋을 것 같아요.

2024-01-26 12:59 UTC, merged