은행 창구 관리 앱 [Step1] L, Harry
tasty-code/ios-bank-manager pull request #61
Opened 2024-01-24 12:56 UTC by LeeSe0ngYe0n

안녕하세요, 코든! @ictechgy

은행 창구 관리 앱 STEP1 PR 송부 드립니다.
바쁘신 와중에 리뷰를 해주셔서 감사합니다. ☺️

링크드리스트, 큐 개념을 학습하면서 예제를 참고하여 구현을 하였습니다. 
이해를 최대한 하려고 노력하였는데, 
기본 질문이나, 미흡한 부분 조언 주시면 추가로 더 열심히 고민해보고 코드 수정을 하겠습니다! 

감사합니다!🔥

🔍 What is this PR?

STEP1 큐 타입 구현
- STEP1-1 Queue 타입 구현을 위한 Linked-list 타입을 직접 구현
- STEP1-2 Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics  기능을 활용
- STEP1-3 타입이 예상한대로 동작하는지 Unit Test를 통해 동작을 검증합니다.
- Queue에 구현해야 할 필수 기능
Enqueue, Dequeue, Clear, Peek, isEmpty

📝 PR Point
1. Lineked List 타입 구현
    - Node 클래스를 구현하여 data와 next를 구현, next는 노드가 추가되면 연결되는 다음 노드
    - Head는 첫노드이며, Tail은 마지막에 연결되 노드입니다.
    - push(): 첫 노드를 생성
    - append(): 첫 노드 생성 및 이후 Tail에 노드 추가 및 연결
    - pop(): Head를 꺼내옴
    - clean(): 모든 링크드 리스트 노드를 삭제
    - peek(): 첫 번째 Head 정보를 가져옴
    
2. Queue 타입 구현
    - enqueue() : 큐의 데이터를 추가한다.
    - dequeue() : 가장 최근의 추가한 데이터를 꺼낸다.
    - clean() : 큐의 데이터를 전부 삭제한다.
    - peek() : 큐의 데이터를 꺼내지는 않지만 이제 곧 꺼내게 될 데이터를 알려준다.
    - isEmpty() : 큐의 데이터가 존재하는지 확인한다.
3. Generic 구현
    -  타입에 제한을 두지 않기 위해서 Generic을 사용하였습니다.
4. UnitTest 구현
    - Queue의 메서드들이 잘 작동하는지 Unit Test를 통해 검증하였습니다.

📸 Screenshot
main 콘솔 확인 화면

고민한 부분
1. LinekedList구현 개념을 학습하여 예제 없이 구현을 시도하였으나, 뜻대로 잘 되질 않아 예제를 참고하여 과제를 수행했습니다. 개념을 학습하다보니 LinekedList와 큐는 다른 것이고, 큐를 여러 방식으로 구현할 수 있다는 것을 알게되었습니다. LinekedList 역시 양방향 방식이 있고, Head를 삭제하거나, tail을 삭제할 수 있고, 중간에 연결도 해줄 수 있다는 것을 알았습니다. 다만 현재 과제에서는 은행 창구 구현을 목표로 하므로 연결은 구현하지 않았고, tail에 노드를 추가하며, Head를 삭제해주는 방식으로 구현되어 있습니다. 

2. Generic에서 Equatable한 타입만 활용할 수 있도록 해야하는지 궁금합니다. 현재는 딱히 에러가 없어서 반영해주진 않았습니다. 

질문
- 현재 저희는 `단방향 연결리스트`로 구현하였습니다. 허나 `양방향 연결리스트`를 현재 프로젝트에 적용하는 것에 대해 이점이 있는지 궁금합니다!

- 현재 저희는 `LinkedList`와 `Queue`를 `class 타입`으로 구현하였습니다. 현재 프로젝트에서는 `class`와 `struct` 중 무엇으로 구현하던 저의 생각으로는 크게 상관이 없어보이는데 어떤 것이 더 이번 프로젝트에 적합한지 코든의 의견이 궁금합니다!

- 전반적으로 예제를 참고하긴 했지만 이해는 하면서 진행 중입니다. 미흡한 부분이나 추가로 해보면 좋을 것이 있다면 언제든 말씀해주세요!

2024-01-25 19:40 UTC, ictechgy requested changes
안녕하세요 @LeeSe0ngYe0n , @hemil0102 !
STEP1 진행하느라 고생하셨습니다. 😊

<br>

코드에 대해 궁금한 사항들은 라인별 코멘트로 남겨두었습니다. 여기에서는 질문주신 사항들에 대해 답변드리도록 할게요!   
<br>

## 고민했다고 적어주신 부분
1. LinkedList 개념 학습 과정에 대해 말씀해주신 부분
➡️ 여기에서 '중간에 연결도 해줄 수 있다'라고 말씀하신건 어떤걸 의미하는건가요?? 양방향을 말씀하신걸까요?   
2. Equatable
➡️ 원하는 데이터가 있는지 확인하는 함수가 있어야 한다면 어떨까요?!

<br>

## 질문주신 내용
1. 양방향 연결리스트
➡️ 이건 연결리스트에 기능이 더 존재하는 경우 유용할 수 있는데요! 중간에 있는 노드를 삭제해야 한다면 단방향 연결리스트와 양방향 연결리스트의 구현 차이는 어떻게 될까요?? (현재 프로젝트에 적용하는 것이 이점이 있을지는 이 이후에 생각해봐도 좋을 것 같아요~)    
2. struct / queue
➡️ 개인적으로 저는 둘 다 struct로 구현할 것 같습니다. Node는 참조형태를 띄어야 하지만 두 자료구조는 그럴 필요까지는 없어보여서요!      
혹시나 struct와 class 중 어떤 것을 선택해야 할지 고민이 되신다면 아래 아티클을 읽어보시는게 도움이 될 것 같습니다.   
    - [Swift Programming Language Guide - Structures and Classes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures/)
    - [Apple Documentation - Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)   
3. 추가로 해보면 좋을 것 같은 부분
➡️ 나중에 시간이 나신다면 `LinkedList`에 [노드 중간 삽입, 삭제 / 특정 항목이 있는지 체크] 기능도 넣어보시면 좋을 것 같습니다~!   

<br>

## 추가로 말씀드리고 싶은 부분
1. given when then
➡️ 테스트코드에는 given when then이라는 형식이 많이 쓰이는데요! 한번 공부해보시고 적용해보시면 좋을 것 같습니다.   
2. target dependency / target membership
➡️ `@testable import`에서 컴파일 오류가 발생하고 있었는데요! 다음의 과정을 통해 해결 가능합니다.
프로젝트 설정 > `BankManagerConsolAppTests` Target선택 > Build Phases > Target Dependencies > + 아이콘을 눌러 콘솔 앱 타겟을 추가해주세요.    
(BankManagerConsolApp 파일들에서는 UnitTest Target Membership 제거해주셔도 됩니다)

<br>

## 마지막으로..
LinkedList의 몇가지 함수가 의도했던 바와 다르게 동작할 수 있어서 한번정도 잡고 갈게요! 수정 후에 노티 부탁드리겠습니다~!

<br>

P.S
PR 메시지에 스크린샷이라고 올려주신게 있는데 아무것도 안보여요! 뭔가 안올라간걸까요??

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +import Foundation
import Foundation은 꼭 필요할까요? 🤔

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var count: Int = 0
접근제한을 두어 외부에서 값을 직접적으로 참조하거나 변경하지 못하도록 하는건 어떨까요?

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func push(with data: T) {
인자레이블을 잘쓰셨네요! 👍😆 자연스럽게 읽힙니다!

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = Node(data: data, next: head)
만약에 head 프로퍼티가 이미 특정 노드를 가리키고 있었다면 이 구문은 어떻게 동작하게 될까요?

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
설명에서는 push를 '첫 노드 생성', append를 '그 이후의 노드 생성 및 연결'이라고 해주셨는데요!   
사용하는 입장(외부)에서는 두 함수 이름이 전달하는 바가 비슷해서 오용할 수 있을 것 같아요. 하나의 함수로 합쳐보는건 어떨까요?   
외부에서는 내부의 노드가 몇개가 있든 신경쓰지 않고 하나의 함수만 사용하는 방식으로요!    

이렇게 하면 조금 더 캡슐화가 이루어질 수 있을 것 같습니다 😆

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func pop() -> T? {
pop이라는 이름은 스택자료구조의 pop과 이름이 같아서 최근에 넣은 데이터를 돌려준다는 것처럼 인식이 되는데요!   
여기서는 가장 오래전에 넣은 옛날 데이터를 돌려주고 있으니 다른 이름이 좋을 것 같아요!       

스택 자료구조에 대한 내용은 [이곳](https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%83%9D)을 참고해보시면 좋을 것 같습니다.

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        let returnValue = head?.data
returnValue보다 조금 더 구체적인 네이밍은 어떨까요?

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            return nil
데이터(노드)가 하나만 있을 때 이곳이 원하는 동작을 하는지 한번 살펴보시면 좋을 것 같습니다!

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head?.data
잘 만들어주셨습니다! 😄

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +import Foundation
여기도 꼭 Foundation import가 필요할까요?? 🤔   
프로젝트 전체적으로 한번 확인해보시면 좋을 것 같습니다~

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    var data: T
data는 꼭 var이어야 할까요??

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var queue: LinkedList<T> = LinkedList()
이 프로퍼티도 접근제한자가 없네요! 👀 그리고 꼭 var이어야 할까요?

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var queue: LinkedList<T> = LinkedList()
더불어 큐 안에 큐가 있는 느낌이라 다른 네이밍을 가져가는게 좋을 것 같습니다!

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    func isEmpty() -> Bool {
LinkedList에서는 연산프로퍼티로 만드셨는데 여기에서는 함수로 만드셨네요. 다른 이유가 있을까요?

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +print("8️⃣ queue.isEmpty: \(queue.isEmpty())")
콘솔 출력을 봤는데 잘 나오고 있네요 😊👍

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +final class BankManagerConsoleAppTests: XCTestCase {
Node나 Queue, LinkedList에서는 final이 없었는데 여기에는 있네요! 다르게 적용된 이유가 있을까요??

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    var sut: Queue<String>!
엇 sut라고 이름지으셨군요! 😆 혹시 참고하신 자료가 있을까요?

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    }
동작을 잘 정의해주셨네요!!! 👍👍👍👏👏

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertEqual(1, sut.queue.count)
totalLengh 함수를 쓰지 않으신 이유가 있을까요??

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +
테스트도 정말 많이 만들어주셨고 XCT 함수들도 너무 적절히 잘 사용해주셨어요! ✨✨😊👏

2024-01-25 19:40 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertNil(result)
queue 프로퍼티에 접근제한자를 적용하면 이 두 테스트는 사용할 수 없겠군요! 다른 방법은 없을지 같이 한번 고민해봐요!

2024-01-26 01:54 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +import Foundation
리팩토링 과정에서 필요없는 `주석`과 사용하지 않는 `프레임워크`를 삭제하기로 논의를  하였지만 PR전송에 급급해서 미쳐 삭제하지 못했습니다...ㅜ

2024-01-26 02:18 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    var sut: Queue<String>!
[XunitPatterns](http://xunitpatterns.com/SUT.html)의 문서를 확인해보면 `sut`는 `system under test`의 약자로 테스트 중인 시스템을 의미합니다!

2024-01-26 02:23 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +final class BankManagerConsoleAppTests: XCTestCase {
앗  미처 확인하지 못했습니다...!

2024-01-26 02:36 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +import Foundation
꼭 필요하지 않네요. 찾아보니 Swift Standard Library가 컴파일러에 포함되어 있고 Swift Standard Library도 Foundation 처럼 기본적인 데이터 타입을 활용하게 해주기 때문에 Foundation을 import를 해줄 필요가 없다고 합니다. 다만 Foundation이 Swift Standard Library와 겹치는 요소가 있어도 서로 다른 것으로 Foundation에서만 제공하는 기능을 사용하기 위해서 필요할 경우 import를 해주어야 합니다. 

아래 참고한 글이 있는데, 공식 문서에서는 어느 부분에 명시되어있는지 확인을 못했습니다만, 계속 찾아보겠습니다. 
참고한 글: https://velog.io/@dvhuni/Swift-Compiler-1

2024-01-26 02:38 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func push(with data: T) {
감사합니다. 애플 공식 문서에서 Label all other arguments. 라고 되어 있길래 함수를 설계할 때 인자레이블을 넣어주려고 합니다. 

https://www.swift.org/documentation/api-design-guidelines/#argument-labels

2024-01-26 04:36 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +import Foundation
수정사항 반영: 2d982fa67b11287ec6febafa80e8392e40b8a5de

2024-01-26 05:00 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var count: Int = 0
접근제한수준을 private으로 적용하였습니다!
[수정사항](44b26ef9a77623d2bfef81f86cbe17ca9afd4330)

2024-01-26 05:18 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = Node(data: data, next: head)
새 노드가 생성되면 data에는 노드의 값이 할당되고 next에는 기존에 있던 head의 주소가 할당됩니다.
그 후 새롭게 생성된 노드가 head가 됩니다.
요약하면 새로운 head가 추가되면서 예전 head에 연결이 됩니다.

2024-01-26 06:55 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +import Foundation
감사합니다!
수정사항: 2d982fa67b11287ec6febafa80e8392e40b8a5de

2024-01-26 08:29 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
감사합니다. push() 기능은 head를 추가하지만 위에 언급해주신 질문에서 head에 새로운 노드를 추가하는 것이 현재 저희의 tail에서 노드를 추가하는 것과 방향성이 다른 것 같아, 모든 방식을 우선 tail에 추가해주는 것으로 변경하면서 함수를 병합했습니다. 
이와 동시에 노드가 tail에서 추가되므로, appendNodeAtRear()라는 메서드 명으로 만들어주었습니다. 
혹시라도 추가 의견이 있으시면 언제든지 코멘트 부탁드립니다. 👍

수정사항: d2f4cb71e8fd45aa1089c63c62395b768d562668

2024-01-26 09:34 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func pop() -> T? {
해당 함수명인 pop 대신 removeNodeFromFront로 변경했습니다!
수정사항: 9c5f14c275ee7694e45de6338f29ca91e5710c4a

2024-01-26 09:36 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        let returnValue = head?.data
`returnValue`라는 변수명 대신 `removedNode`로 변경했습니다!
수정사항: 9c5f14c275ee7694e45de6338f29ca91e5710c4a

2024-01-26 09:43 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            return nil
수정 전 로직에서 발생한 오류는 `head = head?.next` 코드가 조건문 위에 구현이 되어 있어 노드가 하나일 경우 `head`에 `head?.next`를 할당되면서 nil이 되는데 이 경우 바로 아래 if문에서 isEmpty가 true가 되어서 저희의 의도대로 기능이 동작하지 않았습니다.
저희의 의도는 Node가 없는 상황에서 메서드가 호출 될 경우 삭제할 것이 없는 조건을 설정하는 것이 목표였습니다.
따라서 이부분을 순서를 변경해주면서 수정해줬습니다! 문제를 확인 해주셔서 감사합니다!

수정사항:  9c5f14c275ee7694e45de6338f29ca91e5710c4a

2024-01-26 09:44 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head?.data
감사합니다!

2024-01-26 09:54 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    var data: T
data는 용도에 따라서 꼭 var일 필요는 없을 것 같습니다만, data를 조금 더 안전하게 처리하기 위해서 해당 부분을 T?로 변경하였습니다. 예를 들어서 노드에 접근해서 data를 변경해주고 싶을 경우에는 var로 선언되면 되겠지만, 현재 저희 은행 창구에서는 data에 해당하는 부분을 ticketNumber라는 창구 번호로 활용하고 싶은데 고객이 표를 뽑고 다른 표를 뽑으면 번호가 변경될 수 있는 상황이 있을 수 있으니 var 되어야할 것 같지만, 그런데 번호 변경이 의미하는 것이 새롭게 대기열에 올라가는 것이기에 굳이? var가 될 필요는 없을 것 같습니다.  안전한 처리를 위해 옵셔널로 변경하였지만 추가 의견이 있으시면 언제든 환영합니다! 

수정사항: 7c32ced125288b1eaa3693c387da3e4e8a021d47

2024-01-26 10:09 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var queue: LinkedList<T> = LinkedList()
해당 변수명을 `queue`에서 `linkedList`로 변경했습니다!
또한  변수`linkedList` 자체가 변경될 필요가 없어보여 `let`으로 선언해줬고 은닉화와 캡슐화를 적용하기 위해 접근제어수준도 `private`으로 변경해줬습니다!

수정사항: ebf378c03c958045d625540af0c45f5ad1b2ee5e

2024-01-28 04:25 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    func isEmpty() -> Bool {
해당 부분은 LinkedList 클래스에서는 내부 push()에서 사용하는 용도였고, Queue에서는 뭔가 메서드 호출로 사용자가 상태를 확인할 수 있게 하고 싶어서 그렇게 적용이 되었습니다. 그런데 연산프로퍼티와 메서드가 비슷한 동작은 하여도 블로그 글들을 찾아보니 메서드는 조금 더 복잡하고 에러 처리가 필요한 상황에 적합하고 그 이외 간단한 것은 연산 프로퍼티로 사용하면 좋다고 하여서, 두 클래스의 isEmpty를 모두 연산 프로퍼티로 적용하였습니다. 그리고 사용자는 값을 변경할 수 없고 읽기만 가능하여 private(set)으로 적용해주었습니다. 

수정사항: 791ab0c3c687cdd54a2fd2f8badc3cf37e4ea6e7

2024-01-28 05:16 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertEqual(1, sut.queue.count)
해당 부분은 큐와 링크드 리스트를 조금 분리해서 테스트 해보고 싶어서 링크드 리스트 내의 push()가 잘 동작하는지 보고 싶어서 따로 작성했습니다. 뭔가 조금 더 세분화되게 테스트를 하고 싶었는데, 테스트 항목이 너무 많아지는 것 같아서 tatalLength로 테스트를 작성하고 문제가 생기면 타고타고 들어가도 될 것 같습니다만... 그래도 세분화 되어있다면 에러가 발생했을 때 조금 더 근원를 빠르게 캐치할 수 있지 않을까 싶습니다.

2024-01-28 05:32 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +final class BankManagerConsoleAppTests: XCTestCase {
unit test 파일을 생성시 해당 클래스에는 자동으로 final 키워드가 생성됩니다. 
상속을 하지 않는데 `final` 키워드를 사용하지 않을 경우 런타임 시점에 `Dynamic Dispatch`를 사용하기 때문에 성능적인 부분에서 이점이 떨어집니다.
그래서 더 이상 상속을 하지 않을 경우 `final` 키워드를 통해 컴파일 시점에 `Static Dispatch`로 동작하게 하여 성능적인 부분에서 이점을 높일 수 있습니다!
그렇기 때문에 test 파일에서는 테스트만 하기 때문에 따로 상속하는 부분이 존재하지 않아 자동으로 키워드가 붙여졌지만 다른 파일에서는 저희가 상속하지 않는 클래스에 `final` 키워드를 따로 사용하지 않아 다르게 적용된 것 같습니다.
현재 프로젝트 내에서 `Node` 클래스를 더이상 상속하는 부분이 존재하지 않기 때문에 `final` 키워드를 사용하였습니다.

2024-01-28 05:54 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertNil(result)
접근제한자를 private으로 두면 읽기가 불가능하여서 테스트를 사용할 수 없어, private(set)으로 접근 제어 수준을 변경하였습니다. 이 방법 외에도 프로퍼티에 private을 적용하고 함수를 통해 은닉화를 해줘서 프로퍼티에 접근하면 테스트가 가능할 것 같은데, 어떤 방식이 나을지는 잘 모르겠습니다. 실제 현업에서는 어떤식으로 실제 은닉화된 코드를 테스트하는지 알 수 있을까요? 😁

수정사항: 88855b0042392ec64a9c44e69819c8cac7733b5f

2024-01-28 08:19 UTC, hemil0102 commented
@ictechgy 리뷰 감사드립니다. 검토해주신 사항 코멘트에 수정 및 답변을 드렸습니다. 그리고 이 외의 추가로 남겨주신 글들에 대한 답변을 짝꿍과 논의하여 남겨드립니다. 

 1. LinkedList 개념 학습 과정에 대해 말씀해주신 부분
    ➡️ 여기에서 '중간에 연결도 해줄 수 있다'라고 말씀하신건 어떤걸 의미하는건가요?? 양방향을 말씀하신걸까요?
    ⭐️ 아, 링크드 리스트에 중간 삽입을 얘기하는 것이었습니다. 
       
2. Equatable
    ➡️ 원하는 데이터가 있는지 확인하는 함수가 있어야 한다면 어떨까요?!
    ⭐️ 해당 부분 선택 사항으로 제시해주신 특정 항목 체크 기능을 구현하면서 필요성을 확인했습니다. 감사합니다!!
    
## 질문주신 내용
1. 양방향 연결리스트
    ➡️ 이건 연결리스트에 기능이 더 존재하는 경우 유용할 수 있는데요! 중간에 있는 노드를 삭제해야 한다면 단방향 연결리스트와 양방향 연결리스트의 구현 차이는 어떻게 될까요?? (현재 프로젝트에 적용하는 것이 이점이 있을지는 이 이후에 생각해봐도 좋을 것 같아요~)
    ⭐️ 특정 항목 검색 기능을 구현해보니 원하는 데이터에 접근할 경우 헤드에서 반복분을 통해서 next로 순차적인 접근이 필요했는데, 양방향 리스트로 구현할 경우에는 tail쪽에서도 접근이 가능하게 구현이 가능할 것 같아 데이터의 위치가 tail쪽에 가까이 있다면 조금 더 빠른 접근이 가능하지 않을까란 생각을 했습니다. 
    
2. struct / queue
    ➡️ 개인적으로 저는 둘 다 struct로 구현할 것 같습니다. Node는 참조형태를 띄어야 하지만 두 자료구조는 그럴 필요까지는 없어보여서요!혹시나 struct와 class 중 어떤 것을 선택해야 할지 고민이 되신다면 아래 아티클을 읽어보시는게 도움이 될 것 같습니다.    
* [Swift Programming Language Guide - Structures and Classes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures/)
* [Apple Documentation - Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)

    ⭐️ 감사합니다! struct로 변경해주었습니다. 

3. 추가로 해보면 좋을 것 같은 부분
    ➡️ 나중에 시간이 나신다면 `LinkedList`에 [노드 중간 삽입, 삭제 / 특정 항목이 있는지 체크] 기능도 넣어보시면 좋을 것 같습니다~!
    ⭐️ 감사합니다! 특정 항목이 있는지 체크를 먼저 적용해주었습니다. 향후 시간이 된다면 노드 중간 삽입이나 중간 삭제 기능도 생각해보겠습니다!  

추가로 말씀드리고 싶은 부분
1. given when then
    ➡️ 테스트코드에는 given when then이라는 형식이 많이 쓰이는데요! 한번 공부해보시고 적용해보시면 좋을 것 같습니다.
    ⭐️ 말씀해주신대로 수정하였습니다! 잘 되었는지 모르지만 확인 부탁드리겠습니다! 

2. target dependency / target membership
    ➡️ `@testable import`에서 컴파일 오류가 발생하고 있었는데요! 다음의 과정을 통해 해결 가능합니다.
    프로젝트 설정 > `BankManagerConsolAppTests` Target선택 > Build Phases > Target Dependencies > + 아이콘을 눌러 콘솔 앱 타겟을 추가해주세요.
    (BankManagerConsolApp 파일들에서는 UnitTest Target Membership 제거해주셔도 됩니다)
    ⭐️ 감사합니다! 설정 적용해주었습니다. 
 
## 마지막으로..
LinkedList의 몇가지 함수가 의도했던 바와 다르게 동작할 수 있어서 한번정도 잡고 갈게요! 수정 후에 노티 부탁드리겠습니다~!
     ⭐️ 감사합니다. 작성해주신 코멘트를 기반으로 고민해보고 수정하였는데, 추가 수정할 부분이 있다면 언제든 추가 의견 부탁드리겠습니다. 
  
P.S PR 메시지에 스크린샷이라고 올려주신게 있는데 아무것도 안보여요! 뭔가 안올라간걸까요??
     ⭐️ 착한 사람 눈에만 보이...는 것은 아니고 저희가 그날 10시에 교실을 나가다가 누락된 부분입니다. 콘솔창을 스샷으로 남겨드리려고 했습니다. 다음에는 PR 드릴 때 조금 더 꼼꼼하게 확인하고 보내드릴게요! 감사합니다.

2024-01-29 15:56 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +import Foundation
공식문서는 아래 정도를 봐주시면 될 것 같아요! (이것도 명시적인 것은 아니지만 그냥 어떠어떠한 것들이 있다 정도로 확인해보시면 될 것 같습니다.)   
- [Foundation Framework](https://developer.apple.com/documentation/foundation)
- [Swift Standard Librady](https://developer.apple.com/documentation/swift/swift-standard-library)

2024-01-29 17:05 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    var data: T
타당한 이유같아요!    
제가 보기에도 이후에 충분히 변경될 수 있으니 var로 두어도 괜찮을 것 같네요.   
더불어 옵셔널로 처리해주신 점은 너무 좋습니다! 👍

2024-01-29 17:11 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    func isEmpty() -> Bool {
get set을 정의하면서 연산프로퍼티로 만들어주셨군요! 👍   
다만 set은 없어도 되는데 존재하는 부분같아요!       
이 부분은 [Swift Documentation - Properties](https://github.com/tasty-code/ios-bank-manager/pull/61#discussion_r1469927748) 여기 내용 참고해보시면 좋을 것 같습니다!

2024-01-29 17:13 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +final class BankManagerConsoleAppTests: XCTestCase {
정확하게 알고 계시네요~!!! 😊

2024-01-29 17:16 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertEqual(1, sut.queue.count)
으흠 그런 이유였군요!    
그런 경우에는 XCTestCase 클래스를 하나 더 만들고 sut를 다르게 주는 것도 방법일 것 같아요~!       
급한 부분은 아니니 나중에 한번 시도해보세요~!

2024-01-29 17:47 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertNil(result)
> 이 방법 외에도 프로퍼티에 private을 적용하고 함수를 통해 은닉화를 해줘서 프로퍼티에 접근하면 테스트가 가능할 것 같은데, 어떤 방식이 나을지는 잘 모르겠습니다

테스트를 위해 프로덕션 코드에 무언가를 추가하는 것은 별로 좋지 않은 것 같아요. 그건 오직 테스트용도일 뿐이니까요!
(이를테면 private 프로퍼티나 메소드를 확인하기 위해 타입 내에 다른 Internal 프로퍼티나 메소드를 추가하는 등)    
-> 물론 테스트 앱 타겟에서 extension으로 기존 타입을 확장하는 것은 괜찮습니다.   

<br/>

>  실제 현업에서는 어떤식으로 실제 은닉화된 코드를 테스트하는지 알 수 있을까요? 😁

- 일단은 해당 private 프로퍼티/메소드 등을 검증해서 얻고자 하는 것이 무엇인지 명확히 하는게 좋을 것 같습니다.
  - private은 private으로 둔 이유가 있기에 꼭 테스트 해야하는 항목으로 삼지는 않는 것 같습니다. 
- 이후에 검중해야 한다는 확신이 생긴다면 프로토콜과 `의존성 주입`을 통해 로직 검증을 (약간 우회하여) 수행합니다. 
  - 이 부분이 궁금하시다면 공식문서는 아니지만 [이 글](https://www.avanderlee.com/swift/testing-private-methods-variables/)을 참고해보시면 좋을 것 같습니다!

2024-01-29 18:48 UTC, ictechgy approved these changes
@LeeSe0ngYe0n , @hemil0102 안녕하세요!   
코멘트 드린 사항들 반영하시느라 고생하셨어요!   

다음 스텝 진행에 문제는 없어보여서 머지하려고 합니다! 👍
몇가지 추가 코멘트를 남겼는데 추후에 확인 부탁드릴게요!   
더불어 given-when-then 너무 잘 해주셨는데, 테스트 실행 코드가 어디에 위치해야 할지 조금만 더 고민해봐주시면 좋을 것 같아요~! 

STEP2도 화이팅입니다!! 😊

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        set { }
다 잘 바꿔주셨어요~ 여기만 제가 남겨드린 [코멘트](https://github.com/tasty-code/ios-bank-manager/pull/61#discussion_r1469935920) 확인 부탁드릴게요!

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func isData(with data: T?) -> Int? {
여기서 반환하는 count는 ~번째에 있다 이런 의미인걸까요??

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    }
캡슐화를 잘 해주셨습니다~!!!

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
👍👍 더 깔끔해졌네요!

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/11.swift
> +final class _1: XCTestCase {
이 파일은 어떤 파일인걸까요??

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    var sutLinkedTest: LinkedList<String>!
[이 코멘트](https://github.com/tasty-code/ios-bank-manager/pull/61#discussion_r1469942073)에서도 말씀드렸지만 다른 XCTest 클래스로 분리하는게 더 깔끔할 것 같습니다~!

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    func test_queue에_노드가_없다() {
테스트명도 'test_~일때_~하면_~할것이다' 형태로 짜주시는게 읽기 편할 것 같습니다! (given when then 형태)

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let result = sut.isEmpty
개인적인 생각이지만 `sut.enqueue`는 준비단계보다는 실행의 단계라서 when에 있는게 적절해보입니다!   
`let result = sut.isEmpty`는 검증의 단계여서 then에 있는게 어울릴 것 같구요~!

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let lengthOfQueue = 2
이 테스트에서 `lengthOfQueue`는 안쓰는 것 같네요!

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        // then 그렇다면 이 케이스는 통과하는가?
앗 무언가 다른 주석이 있군요..!

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let result = sut.peek() == "Second"
peek한 데이터를 변수에 넣고 아래 then에서 `XCTAssertEqual`로 검증하는게 적절할 것 같습니다! (검증용 비교 데이터인 "Second는 given에서 준비)

2024-01-29 18:48 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertEqual("C", result)
"C"라는 값은 given에서 미리 준비해주는게 좋을 것 같아요~

2024-01-29 18:48 UTC, merged

2024-01-30 03:36 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +import Foundation
감사합니다!

2024-01-30 03:41 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertNil(result)
감사합니다!

2024-01-30 03:43 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func isData(with data: T?) -> Int? {
넵.. 저희가 찾고자 하는 데이터가 몇번째 노드에 있는지 확인하고 싶어서 저렇게 만들었는데, 같은 데이터가 2개 있다는 가정은 고려를 하지 않아 현재는 조회하면서 첫노드의 위치만 반환하도록 되어있습니다! 음 count라는 이름이 불명확한 것 같아서 향후 과제에서는 조금 더 명확한 이름으로 수정해보겠습니다.

2024-01-30 03:44 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/11.swift
> +final class _1: XCTestCase {
음 뭔지는 잘 모르지만... xcode에서 파일을 생성하고 삭제할 경우 폴더에는 파일이 남는 것 같은데 삭제해주도록 하겠습니다.

2024-01-30 03:44 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    var sutLinkedTest: LinkedList<String>!
감사합니다! 분리하여서 별도의 테스트 케이스를 만들어보겠습니다 ^^

2024-01-30 03:45 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    func test_queue에_노드가_없다() {
감사합니다. 코멘트 주신 사항 참고하여서 반영해보겠습니다!

2024-01-30 03:45 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let result = sut.isEmpty
아하 그렇군요, 코멘트 주신 사항 반영해보겠습니다. 
감사합니다!

2024-01-30 03:47 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let lengthOfQueue = 2
위에 테스트 케이스를 복사하다가 삭제가 안되었던 것 같아요. 수정하겠습니다. 감사합니다!

2024-01-30 03:48 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        // then 그렇다면 이 케이스는 통과하는가?
리...리뷰하시다가 너무 단조로울 것 같아서 특별한 애를 하나 넣어봤습..은 아니었고 맞춰보겠습니다. 감사합니다! :)

2024-01-30 03:48 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let result = sut.peek() == "Second"
감사합니다! 수정해보겠습니다!

2024-01-30 03:49 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertEqual("C", result)
엇 그럴려고 다른 것은 수정했는데, 저 케이스는 마지막에 접근 제어 수준 반영하면서 누락된 것 같습니다. 동일하게 given에서 처리하도록 하겠습니다. 감사합니다.

2024-01-30 05:00 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        set { }
계산 속성에서 set 블럭을 구현하지 않을 시 애초에 해당 속성에 접근해서 값을 변경하지 못하기 때문에 private 키워드 및 set 블럭을 삭제해주는 리팩토링을 진행했습니다!

수정사항:

2024-01-30 05:12 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/11.swift
> +final class _1: XCTestCase {
수정사항: b455f6f31434e244f17265382097797c9742b80b

2024-01-30 05:12 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let lengthOfQueue = 2
수정사항: f42643db0ebedbb9bb0c9838916641e622e73c23

2024-01-30 05:13 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        // then 그렇다면 이 케이스는 통과하는가?
수정사항: f42643db0ebedbb9bb0c9838916641e622e73c23

2024-01-30 05:13 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertEqual("C", result)
수정사항: f42643db0ebedbb9bb0c9838916641e622e73c23

2024-01-30 05:20 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func isData(with data: T?) -> Int? {
수정사항: 5ee7586535acaf2a6f4b2d6bf1691f5843d8c1c1