은행 창구 관리 앱 [STEP 1] Yuni, Paul
tasty-code/ios-bank-manager pull request #64
Opened 2024-01-25 07:05 UTC by earths-voluble

안녕하세요 마이노(@Mino777)! 유니(@Jin0Yun), 폴(@earths-voluble) 조의 은행 창구 관리 앱 프로젝트 Step 1 PR입니다! 잘 부탁드리겠습니다!

## 배운 것
### Linked List, Queue
자료구조에 대해서는 아직 생소한 부분이 많기 때문에, 배우고 써보더라도 근간부터 와닿는 느낌을 받기는 힘들다는 생각이 듭니다. 그런 측면에서, 자료구조를 직접 구현해보는 것은 자료구조의 구조와 기능, 메커니즘을 이해하는 데 있어서 더할 나위 없는 학습방법이라는 생각이 들었습니다. 자료구조의 기능을 하나씩 구현하면서 링크드 리스트와 큐의 개념과 특성에 대한 이해가 깊어졌습니다.
### 유닛 테스트
학습활동을 통해 유닛 테스트 실습은 해보았지만, 실제 프로젝트에 적용해 본 것은 처음이었습니다. 적용하는 데 있어서 조금 헤메긴 했지만, 실제로 TDD에 가까운 개발방식을 도입하면서 많은 것을 느낄 수 있었습니다.
### 접근 제어
커스텀 컬렉션을 통해 또 다른 커스텀 컬렉션을 구현하면서 각 컬렉션 내부의 프로퍼티나 메서드의 접근제어에 대해 생각해보는 기회를 가지게 되었습니다.

- **체계적인 기능 테스트**
주먹구구식의 `print`함수를 사용한 테스트가 아닌, `given, when, then`을 준수한 테스트 케이스들은 라인 하나 하나의 논리적인 흐름을 다시 한 번 생각하게 해주었습니다.
- **느린 속도는 개선할 점, 그러나**
익숙하지 않은 유닛 테스트를 다루는 과정에서 저희 페어 뿐 아니라 다른 버드들과 함께 고민하고 개선하는 과정은 즐거웠습니다. 하지만 꽤 간단한 자료구조를 구현하는 코드임에도 기능구현을 위한 테스트가 아닌, 테스트를 위한 기능구현이 아닌가 하는 우스갯소리가 나올 만큼 유닛테스트 작성을 위한 시행착오가 길어졌습니다. 
하지만 TDD의 실제 적용은 저희 페어 모두 처음이었던 점, 그리고 유닛 테스트를 통한 기능 구현의 결과적인 완성도는, 만약 유닛테스트를 제대로 하지 않았을 경우 겪었을 시행착오와 그 결과물의 예기치 못한 트러블을 생각하면 만족스러운 경험이었습니다. TDD를 더욱 체득하고 적재적소에 사용할 수 있게 된다면 기능 구현 단계에서의 많은 이슈들을 보다 효율적으로 해소할 수 있으리라는 자신감이 생겼습니다.
## 질문
- **값을 반환하는 메서드의 이름으로 return을 앞에 붙이는 것에 대해**
`headValue` 함수는 원래 `returnHeadValue`로 정의하려고 했지만, 함수명 앞에 `return`이 붙는다는 것이 어쩐지 어색해서 일단 빼고 PR했습니다. 값을 리턴하는 함수명 앞에 `return`이 들어가는 것에 대해 어떻게 생각하시나요?
- **큐의 필요성?**
링크드 리스트의 메서드를 이용한 큐의 구현 시, 사실상 링크드 리스트가 큐의 모든 기능을 가지고 있는데, 별도로 큐가 존재하는 이유가 뭘까요?
- **접근제어에 대해**
타입을 정의하며 메서드 및 프로퍼티의 접근 제어를 다양하게 시도해 보았습니다. 접근제어를 다루게 되면서 의문이 하나 떠올랐는데요,
접근 제어는 항상 최대한 타이트하게 설정해 두는 게 바람직할까요? 은닉화를 생각한다면 필요 한도까지는 최대한 접근을 제한하는 것이 옳은 방향 같기도 한데, 추후 확장을 하다 보면 과도한 제약이 될 수도 있지 않을까 하는 생각도 들었습니다. 마이노는 어떻게 생각하시나요?

2024-01-26 16:05 UTC, Mino777 requested changes
안녕하세요!! 유니, 폴!

STEP 1 진행하시느라 정말 수고 많으셨습니다!!🥳

리뷰를 진행하기전에 제가 드리는 말들이 모두 정답이 아니라는걸 꼭 인지하시면 좋을 것 같아요!

학습을 하시면서 많은분들이 말씀하시겠지만, 코드에는 정답이 없답니다!

만약 제가 코멘트를 달았던 부분에 대해서 여러분들의 코드에 근거가 있고, 이게 더 나은 방향인 것 같은데 라는 생각이 드신다면 저를 설득시키고, 토론하는 과정 또한 저와 여러분 모두에게 정말 좋은 경험이 되실 것 같아요!

언제든지 궁금하신 점이 생기시면 바로바로 말씀해주세요😁

## 코멘트

### 칭찬 드리고 싶은 점
- Linked-list 자료구조를 구현해보신 점👏
- Queue 자료구조를 구현해보신 점👏
- Generics 기능을 활용해보신 점👏
- Unit Test를 진행해보신 점👏

전반적으로 코드는 물론이고, 고민하신 점이나 학습에 대한 목표나 태도들이 너무너무 좋으신 것 같습니다😊
앞으로도 이렇게 배운것을 정리하는 습관을 계속해서 이어나가셨으면 좋겠습니다👍👍

---------------------------

### 질문사항
> 값을 반환하는 메서드의 이름으로 return을 앞에 붙이는 것에 대해

맞습니다.  headValue 라는 네이밍 만으로도 충분한 의미전달이 되기도 하고, Swift의 API Design Guidelines 에서도 메서드의 이름에 return을 명시적으로 포함하는 것은 명확성이나 간결성을 헤치는 케이스 입니다. 
저도 이런 경우 리턴하는 타입만으로 네이밍을 하는편입니다. 이런 고민 너무 좋습니다👍

> 큐의 필요성?

음 많은 이유가 있을 것 같은데, 제가 지금 딱 떠오르는 이유로는 특정한 케이스에 해당하는, 즉 UseCase 관점에서 봤을 때 링크드 리스트가 아닌, 큐를 사용하면 개발자 입장에서는 큐를 사용하는 이유인 FIFO 기능에 대해서만 집중할 수 있을 것 같아요!
또, 큐라는 자료구조가 제공하는 명확한 인터페이스 (enqueue, dequeue) 등이 있기 때문에 협업에 관점에서도 해당 인터페이스의 내부 구현에 대한 걱정 없이 바로바로 해당 자료구조를 사용할 수 있을 것 같네요.
결론적으로는 각각의 자료구조마다 사용하는 목적이나 인터페이스들이 명확하게 제공되기 때문에 결국엔 유지보수적인 측면에서 해당 요구사항에 딱 맞는 자료구조를 사용하는 것이 많은 부분들에서 더 좋기 때문에 라고 생각해보시면 좋을 것 같습니다ㅎㅎ
물론 제 개인적인 의견이기에 이런 고민들은 계속 해나가시면서 자신만의 생각을 정립해보시면 좋을 것 같네용! 이런 고민 너무 좋습니다👍👍

> 접근제어에 대해

고민하시는 내용들이 너무 좋네요ㅎㅎ 저도 해당 부분에 대해서 많은 생각을 했었는데, 마법의 단어를 만나고 나서 고민이 사라졌었습니다ㅎㅎ
영문으로 된 개발 아티클들을 보다보면 sillver bullet, trade-off 라는 단어들을 많이 보시게 될텐데 결론적으로는 개발에는 확실한 정답이 없고 맞닥뜨린 상황에 유연하게 맞춰서 사용해야 된다! 입니다. 
제가 추천드리는 방법으로는, 일단 학습하실 땐 무조건 최대한 제한적인 접근제어를 사용하려고 노력하시는게 좋습니다. 일단 캡슐화에 대한 이해도가 확실하게 생기고 설계력이 생기실때까지 정석적인 방법에 대해 학습되고 익숙해져야 어떤 상황이 왔을 때 어떤 트레이드오프를 하는것이 좋은지에 대한 자신만의 기준이 생기게 되는 것 같아요. 근데 사실 쓰면서 생각해보니 접근제어는 트레이드오프 라기 보다는, 그냥 각 상황에 맞는 접근제어를 사용할 수 있는 설계력을 키워서 접근제어를 유연하게 사용해야하는 것이 맞겠네요ㅎㅎ

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/.swiftlint.yml
> +disabled_rules:
와우..! SwiftLint를 사용해보셨네요! 너무 좋습니다👍👍
시간 나시면 SwiftFormat도 알아보시면 재밌을 것 같습니다😊

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    private(set) var head: Node<T>?
final 키워드를 사용하셨네요! final 키워드를 사용해야할 상황과 얻을 수 있는 이점으로는 무엇이 있을까요?!

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    private(set) var head: Node<T>?
Generics 를 활용하셨네요! 좋습니다👍👍
Generics에 대해서 간략하게 설명해주세요!

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
tail = newNode 로직을 if 문 밖으로 빼줘도 되겠네요!
```swift
func appendNode(value: T) {
    let newNode = Node(value: value)
    if isEmpty {
        head = newNode
    } else {
        tail?.next = newNode
    }
    tail = newNode
}
```

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
일반적으로나 앞으로의 요구사항을 생각해보면, removeFirst 메서드는 노드 제거 뿐만 아니라 queue 자료구조의 dequeue 기능을 위해 제거된 노드의 value 값을 반환하도록 정의해주는 것이 좋아보입니다! 
또, 만약 해당 노드의 head가 nil인 경우(isEmpty) tail도 nil 값으로 업데이트를 해주는 것이 데이터 정확성을 높여줄 수 있을 것 같아요!
그리고 print 보단 옵셔널 반환 방식으로 처리를 해보시면 좋을 것 같습니다.
한번 수정해봅시다💪

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    var value: T?
노드를 사용하는 목적을 생각해보면 value 프로퍼티가 옵셔널일 이유가 있을까요?

어떤 이유로 옵셔널로 작성하셨는지 궁금합니다!

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
해당 메서드도 반환값이 있도록 수정해봅시다!

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +    }
해당 메서드들에 대해서 간략하게 설명해주세요!

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +        XCTAssertEqual(sut.head?.value, "폴")
give-when-then 패턴 너무 좋습니다👍👍👍

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +        XCTAssertEqual(sut.head?.value, "폴")
비어있는 리스트에서 removeFirst 하는 케이스도 추가해보시면 좋을 것 같아요!

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +        // given
테스트케이스 네이밍도 저랑 똑같이 하시네요!
when ~ should ~, 한글 사용 좋습니다!

2024-01-26 16:05 UTC, Mino777 commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +
dequeue에 반환 값이 생기면 해당 메서드에 대한 테스트케이스도 추가해보면 좋겠네요!

2024-01-29 02:35 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    private(set) var head: Node<T>?
여러 가지 이유로 인해 클래스를 더 이상 확장하거나 상속되지 않게 만들고 싶을 때 **`final`** 키워드를 사용하면 컴파일러는 정적 디스패치를 통해 성능 최적화를 수행할 수 있습니다.
정적 디스패치를 사용하면 컴파일 타임에 어떤 메소드가 호출될 지 미리 알 수 있기 때문에 런타임 오버헤드가 없어지고 성능이 향상됩니다. 특히 클래스가 더 이상 서브클래싱되지 않을 것이 분명한 경우에는 **`final`** 키워드를 사용하여 불필요한 동적 디스패치를 방지하고 성능을 향상시킬 수 있습니다.

2024-01-29 02:38 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    private(set) var head: Node<T>?
제네릭을 사용하면 특정 데이터 타입을 미리 지정하지 않고 다양한 타입에 대해 작동하는 코드를 작성할 수 있어 코드의 재사용성을 높일 수 있습니다.

2024-01-29 02:40 UTC, earths-voluble commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +    }
`setUpWithError`는 테스트 실행 전 초기화를 실행해주는 메서드이고, `tearDownWithError`는 테스트 후 정리를 해주는 메서드입니다. 저희 코드를 예시로 들자면, 테스트가 실행되기 전 `setUpWithError`가 `sut`를 LinkedList로 초기화해주고, 테스트가 끝날 때마다 `tearDownWithError`가 `sut`를 다시 `nil`로 정리해줍니다.

2024-01-29 02:45 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    var value: T?
노드를 먼저 생성할때 value의 값이 없을 수 도 있다라고 생각해서 옵셔널로 구현을 했었는데 현재 코드를 보면 값이 항상들어오는게 명확하기 때문에 옵셔널이 없는게 더 좋을 거 같아보여서 수정하였습니다.

2024-01-29 05:59 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
꼼꼼한 리뷰 감사합니다 😁😁

2024-01-29 06:00 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
removeFirst, dequeue 메서드 반환타입 추가하였습니다.

수정사항: 00f00b2

2024-01-29 06:04 UTC, Jin0Yun commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +        XCTAssertEqual(sut.head?.value, "폴")
removeFirst, dequeue 메서드 반환타입 추가 후 test 케이스 추가하였습니다.

2024-01-29 06:05 UTC, Jin0Yun commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +
dequeue 메서드 반환타입 추가 후 test 케이스 추가하였습니다!

2024-01-29 07:44 UTC, Mino777 approved these changes
Step1 진행하시느라 고생하셨습니다💪💪

요청드린 부분들 잘 수정해주셔서 머지하도록 하겠습니다!
앞으로의 스텝들에서도 고민거리, 학습한 부분들 계속해서 정리해주시면 아주 아주 좋을 것 같습니다!

Step2도 빠이팅입니다!!💪💪

2024-01-29 08:20 UTC, merged