은행 창구 관리 앱 [STEP 1] Andy, Sam
tasty-code/ios-bank-manager pull request #65
Opened 2024-01-25 07:45 UTC by andyanappdev

> 리뷰어 : @cherrishRed
> 
> 
> 버드 : @andyanappdev (Andy) @ParkChanH (Sam)
> 

안녕하세요, 레드~!

첫 PR 부터 늦어서 죄송합니다 ㅜㅜ

저희 둘다 자료구조에 대한 기본 지식이 전혀 없어서 Node와 Linked List를 이해하고 학습하는데 시간이 좀 걸렸습니다.

서로 토의도 많이 하고 나름 유익한 시간을 가졌지만 부족한 부분이 많은 점 이해 부탁드려요.

우선 각자가 공부한 내용을 바탕으로 각자의 아이디어 대로 구현 하여 서로의 코드를 설명하는 시간을 가져 보았습니다.

Andy : Doubly linked list (양방향), Sam : Linked list (단방향)으로 구현 하였고 논의를 거쳐 Sam의 코드를 기본 베이스로 하여 이번 프로젝트를 진행하기로 결정 하였습니다.

---

### Step1 요구사항

**Step 1 : 큐 타입 구현**

은행에 도착한 고객이 임시로 대기할 대기열(큐, Queue) 타입을 직접 구현합니다.

- Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다.
- Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용합니다.
- Queue 타입이 예상한대로 동작하는지 Unit Test를 통해 동작을 검증합니다.
    - Queue에 구현해야 할 필수 기능
        - Enqueue, Dequeue, Clear, Peek, isEmpty

**스텝 핵심 경험**

- Linked-list 자료구조의 이해 및 구현
- Queue 자료구조의 이해 및 구현
- Generics 개념이해 및 적용

## 파일트리

```swift
📦BankManagerConsoleApp
 ┣ 📂BankManagerConsoleApp
 ┃ ┣ 📂Model
 ┃ ┃ ┣ 📜LinkedListQueue.swift
 ┃ ┃ ┗ 📜QueueProtocol.swift
 ┃ ┗ 📜main.swift
 ┗ 📂LinkedListQueueTest
	  ┗ 📜LinkedListQueueTest.swift
```

## **설계 및 구현 설명**

### LinkedListQueue

- `Linked List`의 핵심인 `Node`를 단방향으로 설계
- `Node`를 이용하여 `Queue`에서 사용될 필수 기능들을 `Linked List`를 구현했습니다.
- `Queue`에서는 `Linked List` 객체를 생성자 주입을 통해 인스턴스 화하여 `Linked List`에서 구현해 둔 `Queue`의 특성(Enqueue, Dequeue, Clear, Peek, isEmpty)에 접근하여 구현했습니다.
- 이후 각 클래스 간의 `캡슐화`, `은닉화`를 통해 더욱더 클래스 안에 서로 연관된 속성과 기능을 하나의 캡슐로 만들어 데이터를 외부로부터 보호하는 작업을 처리했습니다.
- Class를 선택한 이유: 우선 `Node`는 서로를 참조해야 하므로 클래스로 정의하였습니다. 또한, 참조를 통해 객체가 공유되어야 하는 상황에서는 클래스로 구현하고, 참조를 사용하지 않고 값의 복사만 이루어지는 경우에는 구조체로 구현해야 한다고 생각합니다. 따라서 `Linked List`와 `Queue`도 클래스로 구현되어야 한다고 생각했습니다.

### QueueProtocol

- `Queue`가 필수적으로 수행해야 하는 행위들을 `Protocol`로 정의 하였습니다.
- `ListedListQueue`는 해당 `Protocol`을 채택하여 필수 method 들의 구체적인 내용을 구현 합니다.

### LinkedListQueueTest

- `ListedListQueue` class의 method 들이 의도한 대로 작동 하는지 아래 테스트를 진행하여 검증 했습니다.
    - 빈 큐를 생성하고 비어 있는지 확인하는 테스트
    - 큐에 요소를 추가하고 큐가 비어있지 않은지 확인하는 테스트
    - 큐에서 요소를 제거하고 큐가 비어 있는지 확인하는 테스트
    - 큐에 여러 요소를 추가하고 모두 제거하는 테스트
    - 큐를 비우는 테스트

---

## 질문

- Queue class 를 캡슐화, 은닉화을 위해서 우리는 Node, LinkedList 를 subClass 로 정의하였습니다. 이런식으로 구현하는 것이 올바른 방법인지 의문점이 생겨 올바른 방향은 무엇인지 궁금합니다.
- LinkedList 의 장점은 일반 리스트 사용보다 중간에 데이터를 추가하고 삭제할때 유리하다고 알고있습니다. 하지만 이 Step1 명세서상 중간에 추가 또는 삭제를 고려하지않아도 판단 했습니다, 그래서 저는 단방향 LinkedList 로 구현을 했습니다. 구현을 할 때 추후에 경우를 미리 대응하기 위해 양방향 LinkedList 로 구현하는 것이 올바른 방식인지 궁금합니다.

2024-01-25 18:50 UTC, cherrishRed requested changes
안녕하세요 앤디! 샘!
이번 프로젝트 잘 부탁드립니다!

## 👏 칭찬 드리고 싶은점 
* 깊은 공부
    코드에서 부터 자료구조에 대해서 많은 공부를 하신게 느껴지는 코드 였습니다. 
    또 판단을 하시기 위해 다양한 방법으로 큐를 만들어 보신 것도 좋았습니다!
* Generic 활용
    제네릭을 활용하셔서, 큐 자체가 가진 요소들이 무엇이 있는지 코드에 잘 드러나서 좋았습니다!
* 테스트 코드 구현
    큐가 잘 작동하는지에 대한 테스트를 작성하신 점이 좋았습니다!

## 🤔 질문에 대한 답변

> Queue class 를 캡슐화, 은닉화을 위해서 우리는 Node, LinkedList 를 subClass 로 정의하였습니다. 이런식으로 구현하는 것이 올바른 방법인지 의문점이 생겨 올바른 방향은 무엇인지 궁금합니다.

좋은 방법이라고 생각합니다.
Node는 당연히 존재해야 하고, 밖에서는 Node의 존재를 몰라야 하니 당연한 선택이었을 것 같구요. 

아마도 LinkedList의 구현과 Queue 의 구현이 거의 동일해서, 이런 고민을 하셨을 거라 생각이 되는데요.

선택하기 나름이라고 생각합니다.
LinkedList 와 Queue 는 구분되어야 한다. 인터페이스와 구현은 구분되야 한다. 라고 생각하시면, 분리하시면 됩니다.

지금 코드에서의 분리는, 개인적인 생각으로는 미래를 봐서도 LinkedList와 큐의 구현이 별로 바뀌지 않을 것 같기 때문에 코드의 분량으로 불필요하다고 생각됩니다. 

하지만, 모두가 큐와 링크드리스트가 어떻게 작동하는지 알고 있기 때문에 메서드 명만 달라지더라도 의미가 있다고 생각합니다. 즉, 분리를 했기 때문에 가독성이 올라 간 것 같습니다. 

이 부분이 이해가 잘 안되시면 이야기 해주세요.

> LinkedList 의 장점은 일반 리스트 사용보다 중간에 데이터를 추가하고 삭제할때 유리하다고 알고있습니다. 하지만 이 Step1 명세서상 중간에 추가 또는 삭제를 고려하지않아도 판단 했습니다, 그래서 저는 단방향 LinkedList 로 구현을 했습니다. 구현을 할 때 추후에 경우를 미리 대응하기 위해 양방향 LinkedList 로 구현하는 것이 올바른 방식인지 궁금합니다.

이 부분을 정말 선택의 영역입니다.
앞으로 어떤 구현사항이 오게 될 지 실제로는 정말 알 수 가 없기 때문이죠. 

그래서 interface가 존재합니다.

지금 두분이 단방향리스트와 양방향리스트를 구현하셨고, 다른 프로토콜을 채택하고 있지만,
`enqueue`, `dequeue`, `clear`, `peek`, `isEmpty` 
를 가지고 있는 것이 같네요.

두 개의 다른 큐를 같은 프로토콜을 채택해서 만들면, 나중에 쉽게 교체할 수 있습니다. 
```swift
var queue: QueueProtocol = LinkedListQueue()
var queue: QueueProtocol = DoublyLinkedListQueue()
```

queue를 나중에 사용하게 되는 사람 입장에서는 QueueProtocol이라는 interface를 통해서 사용하는 것이기 때문에, 내부 구현이 바뀌게 되어도 전혀 문제가 되지 않습니다.
이 2개 뿐만 아니라, CircularLinkedListQueue 라던가 다른 자료 구조도 QueueProtocol을 준수하기만 한다면, 만들 수 있을 것 같네요.

## 🟡 예쁜 파일 트리
파일트리는 두분이 직접 손으로 타이핑 하신 건가요?
만들어 주는 프로그램이 있나요? 
이모티콘이 있는게 제 취향이라 여쭤 봅니다 😆

2024-01-25 18:57 UTC, cherrishRed requested changes

2024-01-25 18:57 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/DoublyLinkedList.swift
> +            return
이 부분이 동일 조건이 두번 들어있네요.

2024-01-25 18:57 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/DoublyLinkedList.swift
> +            let isForward = (index <= half)
사이즈를 나눠서 어디서 부터 찾을지 나누신 부분 좋습니다!

2024-01-25 18:57 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedListQueue.swift
> +    private var bankQueue: LinkedList<T>
bankQueue 라는 네이밍을 LinkedListQueue 에 사용하는 것은 어색한 것 같아요.
나중에 LinkedListQueue를 변수나 상수로 만들때 사용하면 좋은 이름일 것 같습니다.
네이밍을 바꿔주세요

2024-01-25 18:57 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedListQueue.swift
> +    }
이 메서드들에 public 을 붙이신 이유는 무엇일까요?

2024-01-25 18:57 UTC, cherrishRed commented on BankManagerConsoleApp/LinkedListQueueTest/LinkedListQueueTest.swift
[7가지 유명한 유닛 테스트 네이밍](https://dzone.com/articles/7-popular-unit-test-naming)
을 참고하여 이름을 작성해 보세요!

다언어 사용자가 개발하는 앱이 아니라면, 테스트 메서드 명은 한글로 작성하셔도 됩니다!

2024-01-26 09:55 UTC, andyanappdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/DoublyLinkedList.swift
> +            return
앗~ 어제 밤에 method 들 수정 하다가 실수를 했내요 ㅜㅜ 감사합니다.
동일 조건 제거하여 commit 하였습니다.

2024-01-26 10:09 UTC, andyanappdev commented on BankManagerConsoleApp/LinkedListQueueTest/LinkedListQueueTest.swift
오 이런 좋은 자료를 알려 주셔서 감사합니다.
주로 class 단위로 테스트 코드를 작성하는 편인데 
flutter 에서 테스트 코드 작성시 "해당 class 이름(== 파일 이름)_test" 형태로 작성하던 습관이 있어서
LinkedListQueue 클래스를 테스트 하는 것이라 LinkedListQueueTest 라고 네이밍을 했습니다.
알려 주신 자료 잘 읽어 보다 참고하여 다음 테스트 코드 작성시에는 반영해보도록 하겠습니다.
감사합니다.

2024-01-29 02:04 UTC, ParkChanH commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedListQueue.swift
> +    }
클래스의 메서드들이 다른 모듈에서도 접근 가능하도록 하고 또한 코드의 의도를 명확히 전달하여 코드의 가독성을 높이기 위한 목적으로 적용했습니다!!

2024-01-29 02:21 UTC, ParkChanH commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedListQueue.swift
> +    private var bankQueue: LinkedList<T>
해당 리뷰 해주신 부분 수정 후 커밋 했습니다.

bankQueue -> elements

2024-01-29 04:55 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedListQueue.swift
> +    }
`public` 을 사용하는 경우는, 모듈 간의 접근이 필요할 때 사용하는 것인데, `LinkedListQueue` 는 또 `public` 이 아니기 때문에, 이 메서드들에 다른 모듈에서 접근 하는 경우는 없을 것 같네요...?
지금은 internal 레벨로도 충분한 것 같습니다.

아래, flutter를 사용하셨다고 해서 말씀드리면, 
swift에서의 접근 제어자와 Dart에서의 접근제어자가 조금 다릅니다. 기본값도 다르고 받는 영향의 범위도요.
Dart는 라이브러리가 기준이고, Swift는 모듈이 기준이죠. (제가 Dart를 찍먹만 해봐서 이부분은 틀릴 수도 있습니다.) 

결론은 swift를 기준으로 접근제어자에 대해서 조금더 공부를 해보시면 좋을 것 같습니다!

2024-01-29 04:58 UTC, cherrishRed approved these changes
앤디, 샘 수고하셨습니다! 👏👏👏

리펙토링 내용과, 남겨두신 코멘트 잘 보았습니다!

접근 제어자 관련 코멘트 하나 남겨 두었으니 확인해 보시고, 다음 STEP 진행하실 때 같이 반영해서 작업하시면 될 것 같습니다!

2024-01-29 05:15 UTC, andyanappdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedListQueue.swift
> +    }
Flutter는 저만 다루고 있습니다. ^^
접근 제어 수준이 Swift가 좀더 세분화 되어 있습니다.
1. `open` : 다른 모듈에서도 접근가능 / 상속 및 재정의도 가능 **(제한 낮음)**
2. `public` : 다른 모듈에서도 접근가능 (상속 / 재정의불가)
3. `internal` : 같은 모듈 내에서만 접근가능 (디폴트)
4. `fileprivate` : 같은 파일 내에서만 접근가능
5. `private` : 같은 scope내에서만 접근가능 **(제한 높음)**

- 따로 명시하지 않으면 internal 설정임(디폴트)
- **모듈(module)** : 프레임워크, 라이브러리, 앱 등 import해서 사용할 수 있는 외부의 코드
    - 모듈(프레임워크나 라이브러리)을 만들어서 배포하려면, public 이상으로 선언 해야함
- class 접근 수준을 가장 넓히면 `open` (상속, 재정의와 관계)
- struct 접근 수준을 가장 넓히면 `public` (구조체는 어짜피 상속이 없기 때문)

### **접근 제어를 가질 수 있는 요소** (접근 제어 수준을 설정할 수 있는 것들)

- Swift 공식 문서 - entities(엔터티) 또는 독립된 개체
1. 타입 (클래스 / 구조체 / 열거형 / 스위프트 기본타입 등)
2. 변수 / 속성
3. 함수 / 메서드 (생성자 및 서브스크립트 포함)
4. protocol도 특정영역으로 제한될 수 있음

### private 와 fileprivate의 차이점 (같은 파일 내부에서의)

- `fileprivate` 접근수준으로 지정한 요소는 같은 파일 어떤 코드에도 접근 가능
- `private` 접근수준으로 지정한 요소는 같은 파일 내부에 다른 타입의 코드가 있더라도 접근 불가능
    
    단, 자신을 확장하는 (`extension`) 코드가 같은 파일에 존재하는 경우에는 접근 가능
---
Sam이 이번 프로젝트에 본인이 적용해 보고자 하는 아이디어에 대해서 저는 적극적으로 권장 하고 있습니다.
저의 생각과 다른 부분이 있더라고, 구현해 보고 그 코드에 대한 본인만의 근거만 있다면 시도해 보자고 하고 있습니다.
이부분에 대해서 Red가 질문 할 것이라고 예상하고 있었습니다.
이번 기회를 통해 Sam이 다시 한번 더 access control에 대해서 고민하고 생각해 볼수 있는 좋은 기회가 되고 저 또한 다시 한번 더 공부할수 있는 기회가 된다고 생각합니다.

2024-01-29 07:33 UTC, merged