은행 창구 관리 앱 [STEP1 ] Jin, Loffy
tasty-code/ios-bank-manager pull request #66
Opened 2024-01-25 08:16 UTC by kimdj1102

리뷰어: 다나 @songda515
버드: Jin @wlsdud-dev, Loffy @kimdj1102

안녕하세요 다나~!
Jin, Loffy 입니다! 은행 창구 관리 앱 STEP1 PR 보냅니다!
잘 부탁드립니다~😀

## 프로젝트 구현 요구사항
### Step 1 : 큐 타입 구현
#### 은행에 도착한 고객이 임시로 대기할 대기열(큐, Queue) 타입을 직접 구현합니다.

- Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다.
- Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용합니다.
- Queue 타입이 예상한대로 동작하는지 Unit Test를 통해 동작을 검증합니다.
    - Queue에 구현해야 할 필수 기능
    - Enqueue, Dequeue, Clear, Peek, isEmpty

## 🤔고민이 되었던 점
#### Queue를 구현하기 위해 LinkedList와 Node를 구현하였습니다.
Queue의 필수기능(Enqueue, Dequeue, Clear, Peek, isEmpty)를 구현하기 위해 각각 다음과 같은 기능을 구현했습니다. 
- Node
    - `var value: T` 
    - `var next: Node?`
- LinkedList
    - `isEmpty()` 
    - `isNotEmpty()` : 조금 더 명확하게 상태를 확인할 수 있도록 isEmpty()의 반대 메서드를 따로 생성해주었습니다.
    - `count()`
    - `append(value: T)`
    - `first() -> Node<T>?`
    - `last() -> Node<T>?`
    - `insert(value: T, at: Int)` : 원하는 위치에 vaule를 삽입해주는 함수입니다. 아직은 해당함수를 사용할 일이 없지만, 추후에 사용할 상황이 있을 경우를 대비해 구현해 두었습니다. 
    - `remove(at index: UInt) -> Node<T>?` : 원하는 위치(index)의 Node를 삭제하는 함수입니다. index값은 음수가 되지 않도록 UInt로 선언해주었습니다. 
    - `removeLast() -> Node<T>?` : 마지막 Node를 삭제해줍니다. insert()와 마찬가지로 추후에 사용할 상황이 있을 경우를 대비해 구현해 두었습니다.
    - `removeAll()`
    - `search(value: T?) -> [(Node<T>?, Int)]?` : value값과 일치하는 모든 노드와, 해당 노드 몇번째 위치하는지를 배열로 반환해주는 함수입니다. 마찬가지로 추후에 사용할 상황이 있을 경우를 대비해 구현해 두었습니다.

- Queue
    - `enqueue(value: T)`
    - `dequeue() -> T?`
    - `peek() -> T?`
    - `clear()`
    - `isEmpty()`

#### Unit Test를 위해 LinkedList Node를 출력하는 테스트 코드를 구현해주었습니다. 
```swift
extension LinkedList: CustomStringConvertible {
    public var description: String {
        var result = ""
        var node = head
        while node != nil {
            guard let unNode = node else {
                break
            }
            result += String(describing: unNode.value) + (unNode.next == nil ? "" : " -> ")
            node = unNode.next
        }
        
        return result
    }
}
```
CustomStringConvertible 프로토콜을 채택해서 LinkedList의 Node를 조금더 가시적으로 확인할 수 있도록 구현해주었습니다. 
![image](https://hackmd.io/_uploads/ry-4OqJ9p.png)

    
## 조언을 구하고 싶은 부분

- LinkedList에서 노드를 반환값으로 넘겨줄때 노드의 값만을 주어야 하는지, 노드 자체를 넘겨주어 처리하도록 하는게 맞는지 고민을 하였습니다. 현재 우리의 프로젝트에서는 링크드리스트에서 큐로 만들어주는 구조로 하위 단계인 큐에서 값을 반환하는게 맞다고 판단 하였습니다. 다나의 의견이 궁금합니다.

2024-01-25 15:51 UTC, songda515 requested changes
안녕하세요 Jin, Loffy! STEP1 진행하느라 고생많으셨습니다 😊
Linked-list, Queue, Unit Test 전반적으로 전부 잘 작성해주신것 같아요!
제가 코멘트 드린 부분은 사소한 영역이라서 참고해주시면 될것 같습니다 🙏

- LinkedList 를 Queue 에서 활용하기에, 제가 생각할때에도 Queue 에서는 Node 자체를 활용하기보다는 Node 의 값만 활용해도 될것 같다고 생각드네요!
- 전반적으로 메소드에 `mutating` 키워드를 붙여주신 것 같은데, 필요한지 여부를 체크해서 작성해주는게 좋을것 같습니다.

혹시 더 궁금하신 점 있으면 코멘트로 남겨주세요 😊

2024-01-25 15:51 UTC, songda515 commented on BankManager.swift
> -import Foundation
요 파일은 일부러 남겨두신건가요? 👀

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +    var list = LinkedList<T>()
오오 링크드리스트로 Queue 를 구현해주셨네요 🙌

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +    mutating func peek() -> T? {
해당 메서드도 `mutating` 이 필요한가요? 👀

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/CustomerQueueUnitTest/CustomerQueueUnitTest.swift
> +        XCTAssertNil(customerQueue.dequeue())
비어있는 배열의 경우의 동작이 궁금했는데 테스트 코드가 있으니 확인하기 좋네요! 🙌

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    static let nodeInterpolation: UInt = 1
여기서 타입을 `UInt` 로 하신 이유가 있으신가요?

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +struct LinkedList<T: Equatable> {
Generics 을 잘 활용해주셨네요! 사용하는데 어려우셨던 점은 없으셨나요? 👀

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        if isNotEmpty() {
사소한 부분인데, 여기서는 바로 `else` 구문을 작성해줘도 되지 않을까 싶네요~!
`if isNotEmpty()` 로 보니까 또 다른 조건이 있는건가 싶기도 해서요! 
추가적으로 필요하다고 생각하시면 그대로 두셔도됩니다~!

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        var node = head
옵셔널값으로 계속해서 사용되는것 같은데, `guard let` 으로 언래핑해주는것도 좋을것 같아요 😌

2024-01-25 15:51 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        if isEmpty() { return nil }
요것도 어느정도 선호의 영향이긴 하지만,
early return 하는 케이스에는 guard 구문을 써주면 더 이해하기 쉬울것 같아요!

2024-01-26 05:50 UTC, kimdj1102 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        if isEmpty() { return nil }
[해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/66/commits/3bbfbb40c080fa3760b6a3b7f3ae2dc595551215) 에서 수정하였습니다.

2024-01-26 05:54 UTC, kimdj1102 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        if isNotEmpty() {
저번에 피드백을 받았었는데 가독성을 위해서 else를 사용하는 대신 isEmpty()에 추가로 isNotEmpty()도 만들어서 사용한다고 들어서 이렇게 해보았는데요...! 혹시 다나의 의견은 어떤지 여쭤보고 싶습니다!

```swift
if isEmpty() {
    head = newNode
    tail = newNode
    return 
}

if isNotEmpty() {
    tail?.next = newNode
    tail = newNode
}
```
대신 두 경우의 if를 사용하게 되면 첫번쨰 if문에서 return을 추가해주어야 하는 번거로움이 있는 것 같습니다.

2024-01-26 05:59 UTC, kimdj1102 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +struct LinkedList<T: Equatable> {
Generics자체를 사용하는데 큰 어려움은 없었던 것 같은데, Equatable을 어떤 상황에서 추가해주어야 하는건지에 대해 공부를 좀 해보았습니다. 

Equatable은 구조체 인스턴스끼리 비교를 가능하게 해주기 위해 채택을 하는데, 저희는 search함수에서 같은 제네릭타입의 value값을 비교해주기 위해 Equatabled을 채택해서 사용하였습니다.

2024-01-26 06:29 UTC, kimdj1102 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        var node = head
[해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/66/commits/4edfb581a9547b37c9c9a31734ceed4b4c8c41fb)에서 수정하였습니다. 

head가 Node<T>?이기 때문에 guard let으로 옵셔널을 벗겨주고 node 변수에 할당을 해주었습니다. 혹시 이렇게 요구하신게 맞을까요?

2024-01-26 06:45 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +    mutating func peek() -> T? {
`stuct`는 값 타입으로 stack에 저장 되고 값이 변경되기 전까지 주소값만을 가지고 있습니다. 그리고 값이 변경 되었을때 Copy on Write 방식으로 실제 메모리에 할당되기 때문에 프로퍼티가 언제 변경 되어서 복사해야 하는지 알 수 없기 때문에 메서드에 `mutating` 키워드를 붙여 메모리에 복사하라고 알려주어야 합니다.
`struct`가 이렇게 작동하는 이유는 애플이 메모리 접근의 안정성과 메모리 효율을 높이기 위해서 이러한 방식을 쓰는거 아닐까 합니다.

`struct`가 값 타입이라 값이 복사한다는건 알았지만 복사동작이 어떻게 이루어 지는지는 알지 못했습니다. 그래서 단순히 구조체에서는 메서드에 `mutating`을 붙여 써야 한다고 생각 하였는데 지적해주신 부분에 대해 다시 공부하면서 `mutating`을 선택적으로 사용해야 하는 이유를 알게 됐습니다.

2024-01-26 06:46 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    static let nodeInterpolation: UInt = 1
`linkedlist` 메서드중 `remove(at index: UInt) -> Node<T>?`, `insert(value: T, at index: UInt)` 에서 `index`를 `UInt` 타입으로 선언 해 주어 매직넘버도 같은 타입으로 지정 해주었습니다.

메서드 파라미터인 `index`를 `Uint`로 선언 해 준 이유는 노드는 음수로 가지 않기 때문에 음수값이 메모리를 차지하는것이 불필요 하다 생각해 `Int`가 아닌 `Uint`롤 선언 해 주었습니다. `Uint8`, `Uint16` 등 메모리를 더 적게 사용 하는 방법으로도 고민 하였는데 일단은 값의 제한(?)이 없는 Uint로 선언 해 주었습니다.

`nodeInterpolation` 를 -1로 선언 하여 index값과 + 하여 계산을 하고 싶었지만 `Int`와 `Uint`는  타입이 달라 계산이 불가능 하여 `Uint` 타입으로 지정하여 구현 하였습니다.

2024-01-26 07:24 UTC, wlsdud-dev commented on BankManager.swift
> -import Foundation
포크 받을때 포함되어 있어서 지우지 않았고 지우면 혹시 프로젝트에 문제가 생길까봐 지우지 않았습니다.

2024-01-26 07:28 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +    var list = LinkedList<T>()
네, 혹시나 링크드리스트를  다른 곳에서 사용할 수도 있을거라 생각해 하위 객체로 큐를 만들었습니다.

2024-01-26 12:31 UTC, wlsdud-dev commented
LinkedList를 의존하고 있는 Queue를 의존성 역전 원칙으로 의존성 주입을 해 보았습니다.
실제 프로젝트에서는 반영이 안되어 있고 학습한 내용을 활용해보기 위해 따로 구현을 했습니다.
```swift
protocol LinkedListProtocol<element> {
    associatedtype element
    var description: String { get }
    func isEmpty() -> Bool
    mutating func append(value: element)
    mutating func remove(at index: UInt) -> Node<element>?
    mutating func removeAll()
    func first() -> Node<element>?
}

struct LinkedList<T: Equatable>: LinkedListProtocol {
    typealias element = T
    
    private var head: Node<T>?
    private var tail: Node<T>?
    
    init(head: Node<T>? = nil, tail: Node<T>? = nil) {
        self.head = head
        self.tail = tail
    }

struct CustomerQueue<T: Equatable> {
    var list: any LinkedListProtocol<T>
    
    init(list: any LinkedListProtocol<T> = LinkedList()) {
        self.list = list
    }
```
일단 테스트는 해봤는데, 의도한 대로 동작은 하지만 혹시 잘못 구현이 된 건지  조언을 얻고 싶습니다.
그리고 링크드리스트와 큐를 의존성 주입 하는건 의미가 없는 행동 일까요?

2024-01-29 09:48 UTC, songda515 approved these changes
수정해주신부분 확인했습니다~!
STEP1 머지하도록 할게요🙇‍♀️

의존성 구분지어보는걸 연습해보시면 의존성을 끊어내는 법을 배우실 수 있을것 같습니다!
추후 스텝에서 반영되어있으시다면 참고해서 리뷰할게요 🙏

2024-01-29 09:48 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        if isNotEmpty() {
음..! 🤔 true / false 로 명확히 나뉘는 케이스는 if - else 를 쓰는게 더 나을것 같아요~ 
이 케이스에서는 아래같은 스타일을 선호하긴 합니다. 
다른 리뷰어분들의 의견을 고려해서 두분의 선호에 맞게 개발하시면 될것 같아요!

```swift
let newNode = Node(value: value)

guard isNotEmpty() else {
    head = newNode
    tail = newNode
    return
}

tail?.next = newNode 
tail = newNode
```

2024-01-29 09:48 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        var node = head
`guard var head` 도 가능하다는점 참고해주시면 좋을것같아요!!

2024-01-29 09:48 UTC, merged