은행 창구 관리 앱 [Step1] 댄, 네로
tasty-code/ios-bank-manager pull request #67
Opened 2024-01-25 08:38 UTC by ODDNERO

Step 1
멤버 : @eensungkim, @ODDNERO
리뷰어 : @yim2627

은행 창구 관리 앱 프로젝트의 첫 번째 스텝입니다!
정리하여 PR 드립니다. 잘 부탁드립니다! :bow: 

# PR 상세
- LinkedList 구현
- LinkedList 를 활용한 Queue 구현
- Unit Test 작성

# 이번 스텝을 통해서 배운 점
- Linked-list 자료구조의 이해 및 구현
- Queue 자료구조의 이해 및 구현
- Generics 개념이해 및 적용
- getter 의 활용
- Unit Test 의 활용
- Equatable 프로토콜 활용

# 구성
## Model
- main.swft, BankManager.swift 는 기존에 이미 작성되어있던 파일이며, 이후 스텝에서 활용하게 될 수도 있어 일단 그대로 두었습니다.

### Node.swift
- 자체 데이터인 _value 와 다음 노드를 가리키는 포인터 역할의 next 프로퍼티를 가지고 있습니다.
- getter 의 역할만 필요한 경우에는 연산 프로퍼티로, getter/setter 모두가 필요한 경우 메서드로 구분했습니다.

### LinkedList.swift
- 리스트의 시작점이 될 head 와 리스트 전체의 길이를 나타내는 _count 프로퍼티를 가지고 있습니다.
- 마찬가지로 getter 의 역할만 필요한 경우에는 연산 프로퍼티로, getter/setter 모두가 필요한 경우 메서드로 구분했습니다.

### Queue.swift
- LinkedList 를 활용하고 있으며, 프로젝트 요구사항인 필수 기능들을 Queue 의 메서드로 구현했습니다.

## Unit Test
### BankManagerConsoleAppTests.swift
- Queue 가 제공하고 있는 5개 메서드, isEmpty(), enqueue(), dequeue(), peek(), clear() 에 대한 Unit Test 를 구현했습니다.

# 질문
댄: 이번 스텝에서 가장 고민되었던 지점이 getter 의 사용 및 구현 방법에 관한 부분이었습니다. Node 의 value 같은 경우 연산 프로퍼티를 활용해 getter 를 구현했고, next 의 경우 private(set) 접근제어자를 통해 외부에서 next 로 접근은 가능하지만 set 은 불가능한 방향으로 구현을 했습니다.

스텝 도중에 진행되었던 객체지향 프로그래밍을 위한 객체 생활 체조(?) 문항을 보면, "getter/setter 를 구현하지 않습니다" 라는 항목이 있었습니다. 찾아보니 무조건적인 금지라기보다는, 무분별하게 사용하지 말라는 의미로 이해가 되었습니다.

위에서 언급한 Node 의 next 프로퍼티는 다음 노드를 가리키는 포인터 역할을 하고 있는데요. LinkedList 가 노드의 포인터에 대한 정보를 모른 채로 자신의 책임을 다하는 것이 어렵지 않나 하는 생각이 들었습니다. 노드의 추가 또는 삭제가 진행될 때마다 노드들을 서로 연결해주거나 연결을 지워주려면 노드의 정보는 필수적으로 요구되는 내용이라는 생각이 들었기 때문입니다. 그래서 이 경우에는 getter 를 완전히 제거하는 것이 어렵다는 생각이 드는데요.

getter 를 완전히 제거하는 것이 어렵다면, 필수불가결한 getter 를 파악할 때 리뷰어님은 어떤 전제들을 가지고 계신지 궁금합니다!

2024-01-26 03:39 UTC, yim2627 requested changes
안녕하세요 댄, 네로!

구현사항을 모두 잘 구현해주셨네요! 고생많으셨습니다.

질문 사항에 대한 답변과 커멘트를 남겨놨으니 확인 부탁드립니다!

이번 스텝 고생 많으셨습니다. 질문 사항이 있으시다면 언제든지 DM주세요!

### 질문 사항
댄

>이번 스텝에서 가장 고민되었던 지점이 getter 의 사용 및 구현 방법에 관한 부분이었습니다. Node 의 value 같은 경우 연산 프로퍼티를 활용해 getter 를 구현했고, next 의 경우 private(set) 접근제어자를 통해 외부에서 next 로 접근은 가능하지만 set 은 불가능한 방향으로 구현을 했습니다.
스텝 도중에 진행되었던 객체지향 프로그래밍을 위한 객체 생활 체조(?) 문항을 보면, "getter/setter 를 구현하지 않습니다" 라는 항목이 있었습니다. 찾아보니 무조건적인 금지라기보다는, 무분별하게 사용하지 말라는 의미로 이해가 되었습니다.
위에서 언급한 Node 의 next 프로퍼티는 다음 노드를 가리키는 포인터 역할을 하고 있는데요. LinkedList 가 노드의 포인터에 대한 정보를 모른 채로 자신의 책임을 다하는 것이 어렵지 않나 하는 생각이 들었습니다. 노드의 추가 또는 삭제가 진행될 때마다 노드들을 서로 연결해주거나 연결을 지워주려면 노드의 정보는 필수적으로 요구되는 내용이라는 생각이 들었기 때문입니다. 그래서 이 경우에는 getter 를 완전히 제거하는 것이 어렵다는 생각이 드는데요.
getter 를 완전히 제거하는 것이 어렵다면, 필수불가결한 getter 를 파악할 때 리뷰어님은 어떤 전제들을 가지고 계신지 궁금합니다!

우선 책은 정답이 아닙니다. 제가 해당 문구를 보고 이해한 바로는 "getter, setter를 동시에 사용하지 말아라" = "접근 제한을 잘 걸어라" 로 이해했습니다.

말씀해주신 상황에서 node에 대한 정보 등을 얻기위해선 당연히 get에 대한 접근제한을 걸지 않아야 얻을 수 있게되지만, 마음대로 value나 다음 포인터를 바꿀 수 있게하는 set은 잠궈버리는 게 맞다고 생각합니다.

저는 내가 특정 프로퍼티에 접근하여 값을 꺼내와야한다 = 접근제한자 X, 내가 값을 가져와야되는데 특정 프로퍼티 값을 어디선가 바꾸면 안된다 라고 한다면 private(set)이나 상수로 만들고, 어디서도 접근할 필요가 없고 내부에서 사용하거나 변경할 것이다 한다면 private으로 제한하고 있습니다.  
--
네로

>어떤 함수의 일을 새로운 함수로 나눌 수 있다면 조금 굳이? 싶더라도 되도록 다 나누는 것이 좋을까요?
자잘하게 다 세분화하는 것이 좋은 것인지 기준이 헷갈립니다.
ex) 함수 내에서 특정 노드가 nil인지 != nil로 파악하는 부분이 있을 때,
노드가 nil인지 판단한 후 Bool값을 return하는 새로운 함수를 만들어 주는 것이 의미가 있을까요?

함수가 많은 기능을 포함하고 있거나, 복잡한 검증 절차(예외처리)가 필요할 땐 함수를 세분화해주는 것이 좋겠지만, 저의 경우엔 너무 파편화되는 것은 오히려 코드 리딩에 방해가 된다고 생각하여 하나의 함수에 하나의 예외처리 이상이 존재한다면 해당 함수가 단일 책임을 갖고 있는지 의심을 하고 분리가 필요하다 생각되면 분리하는 편입니다.

그리고 isEmpty 등등 많이 쓰이는 함수들의 경우엔 분리를 해놓고 사용하는 것이 좋아보입니다.

> Unit Test 할 때 import 부분에서 모듈을 못 찾는 경우가 계속 발생했는데, 혹시 이런 문제가 gitignore setting과 관련이 있을까요?
해당 오류에 대해 경험한 적이 있으시다면 어떤 방법을 사용해 해결하셨는지 알려 주시면 감사하겠습니다!

gitIgnore는 Remote환경에 업로드할 때 포함시키지 않을 것들을 정의하는 것이라 상관없어보입니다.
테스트 타겟을 찾지 못하는 것은 타겟간의 디펜던시를 갖지 않아 생기는 문제이니 아래화면에서 디펜던시를 추가해준다면 해결 가능하니 참고해주세요!
<img width="868" alt="image" src="https://github.com/tasty-code/ios-bank-manager/assets/70251136/c710b6a0-ea72-4ddd-a390-29da3aeecdf0">

2024-01-26 03:39 UTC, yim2627 commented on .gitignore
> +Pods/
이번 스텝에선 Pod이 포함되어있지 않은데 ignore에 포함시키신 이유가 있나요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    public func getNode(index: Int) -> Node<T>? {
public 접근제한자를 붙이신 이유가 궁금합니다.

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +class LinkedList<T: Equatable> {
제네릭을 사용하셨는데, 제네릭에 대해서 설명부탁드립니다!

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
subscript를 생성해주셨네요! 👍 
옵셔널을 반환하는데, 예외처리가 아닌 fatalError를 내게하신 이유가 있나요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +struct Queue<T: Equatable> {
Node나 LinkedList는 클래스인데, Queue만 구조체인 이유가 궁금합니다.

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    }
해당 함수들은 어떤 역할을 하는 함수일까요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertTrue(result, "예상되는 값은 true")
BDD를 사용하여 테스트해주셨네요 👍
BDD란 무엇이고, TDD와 다른 점이 무엇일까요? 그리고 given, when, then을 나누는 기준은 어떻게 정의하셨나요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +final class BankManagerConsoleAppTests: XCTestCase {
다른 클래스들은 final이 적용되어있지 않은데 테스트 타입에만 적용해주신 이유가 있으실까요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var linkedList: LinkedList<T>
Queue를 통해 enqueue, dequeue를 진행하는데 linkedList가 외부에서 접근가능 할 필요가 있을까요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    }
같은 값을 반환할 것 같은데, 접근제한자를 달리해서 변수를 2개 정의하신 이유가 있으실까요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        result = sut.linkedList.count
Queue의 isEmpty로도 테스트가 가능할 것 같습니다!

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let lastNode = sut.linkedList[2]?.value
linkedList에 직접 접근하여 value를 확인하고 계신데, 다른 방법은 없을까요? Test를 위해서 오픈해놓으신건지 궁금합니다!

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
dequeue된 값을 알아야되는 상황은 없을까요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    var sut: Queue<String>!
sut라는 용어를 사용해주셨네요! 해당 용어의 의미는 무엇인가요?

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    }
테스트가 아주 잘 읽히네요! 👍👍

2024-01-26 03:39 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertEqual(1, result, "예상되는 값은 1")
메세지까지 작성해주셔서 더 잘 읽히네요!

2024-01-26 04:35 UTC, eensungkim commented on .gitignore
> +Pods/
널리 사용되는 .gitignore 를 통째로 붙여넣고 그 외에 필요한 부분을 추가해 주었었는데요.
Pods/ 는 코코아팟으로 관리되는 라이브러리 폴더이다보니 일반적으로 .gitignore 에 포함이 되어있고,
특별히 이 부분을 제거해 주지는 않았었습니다!

2024-01-26 04:39 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    public func getNode(index: Int) -> Node<T>? {
링크드 리스트를 구현하면서, 꼭 큐에서만 활용하지 않더라도 그 자체로 다른 곳에서도 활용될 수 있는 링크드 리스트로 만들어보자고 생각했었습니다.
그래서 외부에서 링크드리스트를 활용할 때 필요한 함수들에 public 을 붙여주었었구요.
마찬가지 이유로 실제 활용되지 않는 메소드들도 추가로 구현을 해봤었습니다.

2024-01-26 05:04 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
학습을 위해서 subscript 를 구현해 보면 좋겠다고 생각했고, 기준을 스위프트의 배열에 적용된 subscript 로 잡았었는데요.
배열에서 음수 값 또는 count 를 넘어가는 값을 입력했을 때 fatalError 를 내고 있어서 똑같이 적용해 보았습니다.

충분히 해당하는 에러 처리를 해주었으니 언급해 주신대로 옵셔널을 반환하지 않아도 될 것 같아보이네요.
옵셔널을 제거해 보겠습니다! 🙇

2024-01-26 05:06 UTC, ODDNERO commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    }
`setUpWithError()`: 각각의 테스트 케이스가 실행되기 전마다 특정한 초기 상태로 reset해 주는 함수
`tearDownWithError()`: 테스트 동작이 마무리된 후에 모든 상태를 해체하는 함수

```swift
override func setUpWithError() throws {
    sut = Queue(linkedList: LinkedList())
}

override func tearDownWithError() throws {
    sut = nil
}
```
사실 저희 코드에서 `tearDownWithError()`는 없더라도 같은 동작을 하지만, 한번 활용해 보고자 하는 차원에서 사용하였습니다!

2024-01-26 05:11 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    }
_value 로 실제 프로퍼티를 감춰두고 연산프로퍼티를 활용한 getter 를 만들어 두면,
외부에서 접근이 불가능할 뿐 아니라 ide 등에서 제공하는 추천 영역에도 노출되지 않기 때문에
'은닉화/캡슐화가 조금 더 잘 되지 않나?' 라고 생각했습니다.
(

다소 통일성이 떨어지더라도 여러 방법들을 사용해보고 고민하려던 이유가 제일 크다고 봐주시면 될 것 같습니다!

2024-01-26 05:35 UTC, ODDNERO commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +final class BankManagerConsoleAppTests: XCTestCase {
해당 final class~ 줄은 Test 파일을 생성하면서 기본적으로 구성된 부분이라 따로 수정하지 않았습니다.
다른 클래스들에도 final 키워드를 적용해 보겠습니다!

2024-01-26 05:44 UTC, ODDNERO commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
당장 Queue를 구현할 때는 dequeue의 값을 알아야 할 필요가 없었어서 생각해 보지 않은 부분인데, Step 2의 요구 사항을 확인해 보니 바로 알아야 할 상황이 생기네요! `firstNode`의 값을 return하도록 수정하겠습니다. 🫡

2024-01-26 05:50 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +struct Queue<T: Equatable> {
각 타입을 구조체 또는 클래스 중 무엇으로 구현해야 할지에 대해서 미리 고민해 보지는 않았었습니다. 😅 
다만 swift 는 [기본적으로는 구조체를 활용할 것을 권장하고, 특수한 경우에 class 를 활용하라고 안내](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)하고 있더라구요.
그래서 일단은 struct 로 시작하고, 문제가 생기거나 이 과정에서 class 를 활용하는 편이 나은 경우에만 class 로 변경하는 편인데요.
Node 와 LinkedList 를 구현하는 시점과 Queue 를 구현하는 시점이 조금 차이가 있었어서 Queue 는 구조체로 자연스럽게 만들게 되었습니다.

Node의 경우에는 struct 로 구현하면 내부의 프로퍼티가 다시 재귀적으로 자신과 같은 타입을 가질 수 없어 에러가 떴었고,
레퍼런스 타입으로 구현되어야 조금 덜 복잡하게 바로 LinkedList 로 활용이 가능하다고 판단해서 class 로 구현했구요.
LinkedList 는 그 과정에서 크게 고민하지 않고 class 로 변경을 해주었었습니다.

주신 질문을 가지고 다시 고민해 볼 때, Queue 가 굳이 레퍼런스 타입이어야 할 이유가 없다고 생각하구요. 사실 그런 관점에서 LinkedList 도 struct 로 변경하는 편이 낫지 않을까 생각합니다.

2024-01-26 06:03 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        XCTAssertTrue(result, "예상되는 값은 true")
BDD 는 TDD 에서 파생된 것으로, 사용자의 행위에 기반하여 '사용자가 어떠어떠하게 행동할 것이다' 라는 예측 시나리오를 짜고 이를 바탕으로 테스트를 한다고 알고 있습니다.
기능 그 자체보다는 사용자가 하는 행위에 따른 결과를 고민한다는 점에서 TDD 와 차이가 있다고 생각합니다.

given, when, then 의 경우, 현재 Queue 를 사람들이 실제로 활용할 때 제대로 동작하는지를 확인하는 과정으로 이해하고,
given : 조건을 세팅
when : 실제 행위의 발생(queue 의 메서드 호출)
then : 결과가 알맞게 도출되는가

라는 기준으로 설정했습니다.

2024-01-26 06:15 UTC, ODDNERO commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    var sut: Queue<String>!
`sut` = System Under Test의 약자로 테스트하고자 하는 대상(시스템)을 의미합니다! ([xunitpatterns 사이트](http://xunitpatterns.com/SUT.html))

`AUT`(Application Under Test), `MUT`(Method Under Test), `CUT`(Class Under Test), `OUT`(Object Under Test) 등으로도 지칭 가능하지만, 조금 더 포괄적인 의미의 sut를 사용하였습니다.

2024-01-26 06:28 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var linkedList: LinkedList<T>
test 를 위해서 열어둔 부분도 있었는데요.
private let 으로 변경하고, 별도의 메서드로 테스트 실행이 가능하도록 변경했습니다!

2024-01-26 06:28 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +        let lastNode = sut.linkedList[2]?.value
위에서와 마찬가지로 메서드를 새로 구현했고, private let 으로 접근제어 했습니다.

2024-01-26 06:37 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
잘못된 내용을 적었어서 수정하고 추가 댓글 남깁니다!

빈 LinkedList 를 만들수 있도록 하기 위해서 첫 번째 노드인 head 를 옵셔널로 관리하고 있는데요.
이 값이 제대로 반환될 수 있도록 옵셔널 반환을 넣어둔 부분입니다.

2024-01-26 06:53 UTC, ODDNERO commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +class LinkedList<T: Equatable> {
`Generic` = 일반적인, 포괄적인이라는 뜻으로, **타입에 의존하지 않는 범용 코드**를 작성할 때 사용합니다!
제네릭을 사용하면 특정한 타입만 받을 수 있는 것이 아닌, 어떤 타입이든 받을 수 있는 상태의 class를 생성할 수 있습니다.

특정 타입을 미리 지정하지 않고 파라미터화한 후, 구체적인 타입은 사용자에 의해 외부에서 결정되도록 합니다.

2024-01-26 09:23 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    public func getNode(index: Int) -> Node<T>? {
현재 구현에서 모듈이 나눠져있거나 외부 의존이 필요하지 않으므로 해당 부분은 제거해주는 것이 좋아보입니다. 
public 접근제한자에 대해서 더 공부해보시면 도움이 될 것 같아요.
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol/#Access-Levels

2024-01-26 09:26 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
fatalError는 앱을 강제로 죽이는 메서드입니다. 그래서 배열도 out of index로 인해 앱이 죽는 일을 방지하기 위해 subscript를 통해 예외처리를 하기도합니다. 앱이 반드시 죽어야하는 케이스(결제가 무한대로 된다던지 등등)엔 fatalError도 괜찮지만, 예외처리가 가능한 것들은 앱을 죽이지 않고 처리하는 것이 좋아보이는데 어떻게 생각하시나요?
https://stackoverflow.com/questions/25329186/safe-bounds-checked-array-lookup-in-swift-through-optional-bindings

2024-01-26 11:04 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +struct Queue<T: Equatable> {
뭐든지 이유만 있다면 괜찮다고 생각합니다!
구조체, 클래스 고민은 많이 어렵다고 생각해요.. 저도 매번 고민입니다..  
링크 영상보시면 더 도움이 되실겁니다! 
https://developer.apple.com/videos/play/wwdc2016/416/

2024-01-26 11:05 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var linkedList: LinkedList<T>
테스트를 위해서 본 코드의 변경이 일어나는 것은 좋지않다고 생각합니다! 예를 들면 본 코드에선 타입 내부 프로퍼티가 외부에선 알 필요가 없는건데, 테스트를 위해 열어놓는 것 처럼요!
사람마다 차이가 있지만, 저는 테스트를 위한 Equtable 채택도 테스트 타겟에서 Extension으로 해주는 편입니다.

2024-01-29 02:24 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
예외처리를 하는 방식이 더 나을 것 같습니다!
반드시 fatalError 여야만 하는 이유는 없어서요. 변경했습니다! 🙇

2024-01-29 02:24 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    public func getNode(index: Int) -> Node<T>? {
public 제어자를 모두 제외했습니다! 🙇

2024-01-29 02:36 UTC, yim2627 approved these changes

2024-01-29 02:36 UTC, merged