은행 창구 관리 앱[STEP 2] Sidi, Hoi
tasty-code/ios-bank-manager pull request #71
Opened 2024-01-29 06:42 UTC by jus1234

@minsson

안녕하세요, 민쏜
Hoi(@happykwon), Sidi(@jus1234)입니다!
은행 창구 관리 앱[STEP 2] PR입니다.
바쁘신 와중에 리뷰를 해주셔서 감사합니다. ☺️

## 🔍 What is this PR?

STEP 2 기능 구현

- 은행, 고객, 은행원 타입 구현
- Queue 활용
- 간접 재귀를 사용한 반복 프로그램 구현

## 📝 PR Point

### 1. 고객, 은행원 Queue를 활용한 순차 업무 처리

LinkedListQueue<Customer>, LinkedListQueue<BankManager>가 dequeue될 때 마다 로직 처리

### 2. 하드코딩 방지를 위한 Enum 타입 활용

하드코딩을 없애기 위한 Message, Menu Enum 타입 구현

## 질문

### 1. 저희는 반복 프로세스를 재귀를 통해 구현했습니다. 가독성과 코드의 흐름이 반복문보다는 재귀를 통해 연결 시키는 것이 더 잘어울린다고 생각해 재귀를 사용해 구현했습니다. 이정도의 크기의 프로그램은 재귀를 해도 된다고 판단했지만 반복 로직을 엄청나게 많이 돌 경우 스택오버 플로우가 생길 가능성이 있긴 합니다. 민쏜은 어떤 방법이 더 좋다고 생각하시는지 궁금합니다!

2024-01-30 15:02 UTC, minsson requested changes
안녕하세요, 시디, 호이!
Step 2 수행도 고생하셨습니다!

코드가 너무 깔끔해서 놀랐어요! 전반적으로 무척 가독성이 좋은 코드였다고 생각해요.
또, enum 타입을 여러모로 무척 잘 활용해주셔서 저도 코드리뷰를 하며 다방면으로 생각도 많이하고, 많이 배울 수도 있어 감사했어요.

자세한 코멘트는 코드 코멘트 참고 바랍니다!

### 질문에 대한 답변
> 저희는 반복 프로세스를 재귀를 통해 구현했습니다. 가독성과 코드의 흐름이 반복문보다는 재귀를 통해 연결 시키는 것이 더 잘어울린다고 생각해 재귀를 사용해 구현했습니다. 이정도의 크기의 프로그램은 재귀를 해도 된다고 판단했지만 반복 로직을 엄청나게 많이 돌 경우 스택오버 플로우가 생길 가능성이 있긴 합니다. 민쏜은 어떤 방법이 더 좋다고 생각하시는지 궁금합니다!

현재 프로젝트에서는 재귀로 해도 전혀 문제가 없다고 생각해요. 가독성과 간결함 측면에서 이점이 많아보여요. 말씀해주신 것처럼 재귀는 함수 호출에 따른 오버헤드가 있고, 재귀 호출이 깊어지면 스택오버플로우의 위험성도 있는 건 사실이에요. 그런데 저로서는 현재 프로젝트 단계에서는 그럴 여지가 보이지 않아요.

다만 정말 은행 시스템이라면 이야기가 달라질 것 같은데요. 하지만 이 부분은 어차피 서버에서 처리할 영역이므로 저희가 재귀로 뭔가를 처리할 건 없어보여요. 그러고보면 iOS 개발자로서 뭔가를 재귀로 구현해 스택오버플로우를 발생시키는 게 가능한 요구사항이 있을지 저도 궁금해지네요..!

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +}
`customerCount`는 좀 더 구체적으로 네이밍하면 더 좋아질 것 같아요. 네이밍만으로는 정확히 어떤 역할인지 파악하기 어려워보여요.

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +}
`init` 내부의 코드는 별개의 메서드로 분리하고, 그 메서드를 `init` 내부에서 호출하면 가독성이 좀 더 좋아질 것 같아요.

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
위 두 메서드와, 다른 파일에서 작성해주신 아래의 코드를 함께 보면 좋을 것 같아요.

```swift
enum Menu {
    case open
    case exit
}

extension Menu {
    var value: Int {
        switch self {
        case .open:
            return 1
        case .exit:
            return 2
        }
    }
}
```

- `selectMenu()`가 `Menu` 타입을 반환하고, 반환 받은 곳에서 switch문을 쓰면 어떨까요?
- Menu의 case로 `invalidInput`을 추가하면 어떨까요?
- enum의 rawValue를 활용해보면 어떨까요?

이렇게 하면, 제 생각에는 아래 코드의 가독성을 좀 더 높일 수 있을 것 같아요. (제 생각일 뿐이니, 두 분이 한번 해보시고, 더 좋다고 생각하시는 방향을 선택하시면 돼요.)

```swift
guard let selectedMenu = selectMenu() else {
    Message.wrongInput.printMessage()
    process()
    return
}

if selectedMenu == Menu.exit.value {
    return
}
```
```swift
guard let input = readLine(),
      let selectedMenu = Int(input),
      (Menu.open.value...Menu.exit.value) ~= selectedMenu else {
    return nil
}
```

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
enqueue(element:)의 호출부에서 보니, enqueue(_:)로 바꾸는 게 좀 더 가독성이 좋을 것 같네요!

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
- 메서드명에 오타가 있어요.
- 코드의 의도가 저로서는 잘 이해되지 않는 부분이 있어서 질문 드리고 싶어요. 
  - bankManagerQueue가 있어야 하는 이유가 무엇인가요?
  - 어떤 이유로 bankManager가 bankManager에 dequeue되었다, enqueue되는 건가요?

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
위 코멘트와는 별개로 while let 문법 활용이 너무 멋지네요 👍👍👍

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Menu.swift
> +}
다른 코멘트에 이 객체와 관련된 내용을 남겼는데, 여기서는 이 방식으로 구현하신 이유에 대해 여쭤보고 싶어요.

- rawValue를 활용하는 방법도 있을 것 같은데, value라는 별도의 연산프로퍼티를 만든 이유는 무엇인가요? 어떤 기준으로 선택하신 건가요?
- value를 Int 타입으로 만드신 이유는 무엇인가요?

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Message.swift
> +}
연관값을 아주 잘 활용하셨네요! Message라는 별도의 객체를 만들어주신 것도 좋고요. `.input` 케이스에서 terminator를 사용하지 않아도 되는 상황이었다면 아래처럼 작성하는 방법도 있을 것 같아요.

```swift
private var message: String {
  switch self { ... }
}

func printMessage() {
  print(self.message)
}
```

물론 printMessage에서 input 케이스에 대해서만 따로 분기를 하는 방법도 있을 것 같은데, 굳이 그렇게 하는 것도 애매하게 느껴지네요 😅

2024-01-30 15:02 UTC, minsson commented on BankManager.swift
> +}
- `bank manager deal(s) with customer`라는 문장이 너무 자연스럽게 읽혀 좋네요! 👍
- completionHandler로 self를 넘기는 것과 관련해서는 다른 코멘트에서 질문한 내용이 있으니 참고 부탁드려요~!

2024-01-30 15:02 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
>  		};
객체가 많아지니 슬슬 폴더를 사용해서 파일들을 정리해보면 좋을 것 같네요!

2024-01-31 05:16 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +}
수정완료했습니다 가독성이 더 좋아진 것 같습니다 감사합니다 .

2024-01-31 06:59 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
수정완료했습니다. 로직이 하나 더 추가되지만, 분기점을 확실하게 알 수 있는 장점이 있는것같습니다.

2024-01-31 07:00 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
수정완료했습니다 가독성이 더 좋아진것같습니다 :)

2024-01-31 07:02 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
bankManager가 한명이아닌 여러명일 경우를 생각해서  bankManagerQueue를 만들어놓았습니다. 
그래서, 작업이 끝난 후 completionHandler통해 스스로를 bankManagerQueue에 enqeue합니다.

2024-01-31 07:02 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Menu.swift
> +}
빼는것으로 수정했습니다, 유저인풋값이 int라서 value를 Int타입으로 했습니다.

2024-01-31 07:03 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Message.swift
> +}
저희도 생각을 해봤는데 애매한것 같아서 그냥 두는것으로 하겠습니다 🤣

2024-01-31 07:03 UTC, happykwon commented on BankManager.swift
> +}
감사합니다 😃

2024-01-31 07:06 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
>  		};
Modles / DataStricts / Enums로 파일분류 완료했습니다 :)

2024-01-31 14:30 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
이 부분은 좀 더 자세히 설명해주시면 좋을 것 같은데, 우선 STEP 3에서 바뀌는 걸 보고 다시 대화를 나누어도 좋을 것 같아요.

2024-01-31 14:31 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Menu.swift
> +}
유저 인풋값은 "1"이라는 문자열이고, 그걸로 어떤 연산을 할 것이 아니므로 Int로 취급할 이유는 없어보여요.

2024-01-31 14:32 UTC, merged