은행 창구 관리 앱 [STEP 2] Jane, Sajae
tasty-code/ios-bank-manager pull request #72
Opened 2024-01-29 07:38 UTC by jane1choi

리뷰어:
@July911

버드:
@jane1choi
@suojae3

안녕하세요 July!
STEP 2 PR 올립니다!! 이번 PR도 잘 부탁드립니다 ☺️

## 🔍 What is this PR?
은행창구 관리 앱 STEP 2 기능을 구현했습니다.

<구현 사항>
- 콘솔 앱 구현
    - 10~30명의 고객 방문을 한 명의 은행원이 순서대로 처리하도록 하는 프로그램 구현 

## ✏️ PR Point
### 1. Bank, BankManager 역할 분리
`Bank` 클래스는 입출력 담당, `BankManager`는 로직 담당을 통한 객체의 역할을 분리하였습니다.
`Bank`는 `BankManager`를 소유하고 클로저를 통해 연산결과를 전달함으로써 객체 간의 단방향 의존성을 설정했습니다.

### 2. `DispatchQueue.global().sync`, `Thread.sleep(forTimeInterval: )`
`작업을 처리하는 은행원의 수 == 스레드의 수` 라고 생각해 `DispatchQueue.global().sync` 를 이용하여 작업이 처리되도록 했습니다.
한 명의 은행원이 작업을 처리할 경우, 작업을 순차적으로 처리하기 때문에 `sync` 한 방식으로 처리되도록 하였습니다.
또한, 구현 요구 사항에 각 고객의 업무를 처리하는 데 걸리는 시간은 0.7초로 제시되어있어
작업 간 0.7초의 delay를 주기 위해 `Thread.sleep(forTimeInterval: )` 메서드를 사용했습니다.

**`sleep()`이 아닌 `Thread.sleep(forTimeInterval: )`을 사용한 이유?**
delay를 주는 메서드로 `sleep()`또한 사용할 수 있지만, `sleep()` 은 delay 시간을 `UInt32` 타입으로 지정해야 되는데, 0.7의 경우 `UInt32` 타입으로 변환 시 0으로 변환되기 때문에 delay를 줄 수 없었고, 해당 메서드는 프로그램 전체를 중단 시키기 때문에 해당 스레드의 작업만 중단 시키는 `Thread.sleep(forTimeInterval: )`이 더 적합하다고 판단했습니다. 

### 3. 부동소수점 처리
총 작업 시간 계산을 위한 `totalDuration` 프로퍼티를 `Double` 타입으로 선언해두었는데, 
`Double`은 부동소수점 자료형이기 때문에 부동 소수점 오차 해결을 위해 소수점 셋째 자리에서 반올림 후 항상 소수점 둘째자리까지 표시될 수 있도록 포맷을 지정해주었습니다.
```Swift
 let duration: Double = round(totalDuration * 100) / 100
```
```Swift
 return "업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(count)명이며, 총 업무시간은 \(String(format: "%.2f", duration))초입니다."
```

### 4. `Queue`, `LinkedList` UML 작성
STEP 1에서 July가 조언해주신대로 자료구조의 `Queue`, `LinkedList`의 작성해보았습니다!
<img src="https://github.com/tasty-code/ios-bank-manager/assets/63277563/36c3da2e-e7f3-4a14-ab82-819e119e0dc5" width="400">

## 📮 질문
### 1. 매직 넘버의 사용
객체 지향 프로그래밍에 대해 활동학습을 통해 학습하며 
`모든 원시 값과 문자열을 포장합니다.` - 매직 넘버의 사용을 지양하는 것이 좋습니다.
라고 학습했는데요! 이러한 학습을 토대로 최대한 객체 지향적인 코드를 구성하고자 아래의 코드와 같이 전역 상수로 숫자 값을 선언해두고 해당 상수를 이용해 로직을 짜거나, 계산해주는 방식을 사용했는데요!
```Swift
private let startNumber: Int = 1
private let customerCountRange: ClosedRange<Int> = 10...30
private let duration = 0.7
```
이렇게 각 클래스 내에서 선언해두고 사용할 경우, 코드가 분산되고 재사용이 어렵다는 문제가 있을 수 있을 것 같다는 생각이 들었습니다. 이러한 문제를 해결할 수 있는 방법으로 매직넘버를 선언해두는 `enum`이나 `struct` 를 만들어두고 `enum`의 경우 케이스의 `rawValue`, `struct` 는 `static let` 으로 값을 선언해두고 사용해줄 수 있을 것 같은데 이러한 방법에 대한 July의 생각이 궁금합니다! 평소에 어떤 방법을 지향하시는지, 현업에서 자주 사용되는 방식이 있는지 의견 주시면 감사하겠습니다😊😊 

### 2. 대기열 구성과 작업의 처리방식에 대한 고민
저희가 STEP 2의 로직을 구현한 방식은, 오늘 올 손님을 먼저 줄 세워두고(`makeCustomerQueue`) 이 작업이 완료되면 대기열의 손님의 업무를 순차적으로 처리(`handleTask`)하는 방식입니다. 이는 실제 은행 업무 처리 방식과 거리가 있다는 생각이 들었는데요, 왜냐하면 실제 은행에서는 오늘 올 손님이 몇명인지 미리 알지 못하고 대기열에 손님이 들어오면 업무를 바로 시작하기 때문입니다! 그래서 손님을 줄세우는 `enqueue` 작업과 업무를 처리하는 `handleTask` 를  동시에 수행할 수 있도록 두 작업을 비동기적으로 처리해야 하는 것이 맞지 않을까? 라는 생각에 async 하게 두 작업이 처리될 수 있도록 여러 시도를 해보았는데, 다음과 같은 문제가 있었습니다.
```
1) enqueue, dequeue 작업을 비동기적으로 처리하니 순서가 보장되지 않아 enqueue되기 전에 dequeue가 호출되는 경우, 프로그램이 바로 종료됨
2) 대기열의 작업 내에서도 순서가 보장되지 않음 (번호 순서대로 작업이 처리되지 않아 원하지 않은 동작)
3) 비동기적으로 처리하는 것 == 스레드를 여러 개 사용하는 것이니 은행원이 한 명이라는 요구 사항에 맞지 않는 것 같음
```
이러한 이유로 현상태를 유지하게 되었는데요,, 이 부분에 대한 July의 의견이 궁금합니다!

2024-01-29 09:54 UTC, July911 requested changes

2024-01-29 09:54 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func openBank() {
다른곳에서 호출되는 메서드는 이름에 신경써주세요 ~! 
뱅크라는 클래스안에 또 bank 가 들어가는건 중복되어 보이네요 !

2024-01-29 09:54 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +              userChoice > 0 && userChoice < 3
userChoice > 0 && userChoice < 3 하나의 상수로 빼줘도 좋겠네요.

2024-01-29 09:54 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        bankManager.updateTaskState = { result in
클로저를 사용해주셨네요. 
1. 클로저가 무엇인지
2. 순환참조가 발생하는지, 발생한다면 어떻게 해결할건지 
3. 아니라면 그 이유는 무엇인지 
에 대해서 답변주세요.

2024-01-29 09:54 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func makeCustomerQueue(with customer: Int) {
customer: Int 가 맞나요 ? 
또한 이름과 같은 행동을 하고 있나요 ?

2024-01-29 09:54 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func handleTask(completion: @escaping (Double) -> Void) {
모호한 이름같습니다. 
@escaping 는 무엇인지, 어떤 경우에 주로 사용되는지 적어주세요.

2024-01-29 09:54 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        while !customerQueue.isEmpty {
while let 으로는 커버가 안되는 경우였나요 ?

2024-01-30 01:24 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        bankManager.updateTaskState = { result in
1. 클로저란 실행가능한 코드블럭입니다. 일급객체로서  변수형태로 저장할 수도 있고 함수의 파라미터로도 넘길 수 있습니다.

2.  만약 순환참조가 발생한다면 캡쳐리스트 안에서 `weak self`나 `unowned self` 를 통해 해결할 수 있습니다. 약한 참조를 통해 Reference Count 를 올리지 않음으로써 메모리가 해제되고 있지 않는 순환참조 현상을 해결합니다.

3. 하지만 `showProcessState()`에서는 순환참조가 발생하고 있지않습니다. 그 이유는 클로저 내에서 자기자신의 메서드나 프로퍼티를 참조하고 있지 않기 때문이고, 사용하고 있는 외부객체인 Message 도 값타입인 enum이기 때문에 참조순환이 발생하지 않고 있습니다.

2024-01-30 01:33 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        while !customerQueue.isEmpty {
<img width="560" alt="image" src="https://github.com/tasty-code/ios-bank-manager/assets/126137760/712b4fca-71be-4c9a-ac71-a7d45e7dba24">

이럴수가 중복된 로직이 있었군요
`dequeue`했을 때 값이 안나오면 비어있는 큐인데 중복체크할 필요가 없는 것 같습니다,

while let 을 통해 좀 더 간결하게 수정했습니다!

2024-01-30 01:38 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func openBank() {
메서드 이름 `openBank()` 에서 `open()`으로 수정 했습니다!

2024-01-30 01:42 UTC, jane1choi commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func handleTask(completion: @escaping (Double) -> Void) {
escaping 클로저는 클로저가 함수의 인자로 전달됐을 때, 함수의 실행이 종료된 후 실행되는 클로저 입니다.
함수 종료 시, 내부의 클로저도 같이 메모리에서 해제되지만, `@escaping`을 이용해 탈출 클로저로 선언할 경우, 해당 클로저만을 위해 메모리 공간을 만들게 됩니다. 그렇기 때문에 함수 외부에서 사용이 가능하게 됩니다. 
```
1. 클로저를 외부 변수/상수에 저장 가능합니다.
2. 함수가 반환되어 종료된 이후에도 클로저 실행이 가능합니다.
```
탈출 클로저의 경우 위의 두 가지가 가능해지기 때문에 서버 통신 시 비동기 처리가 필요한 경우(서버 통신 결과물을 이용해 어떤 작업을 해주어야 할 때)나 함수 종료 직후의 이벤트 처리를 위해 많이 사용됩니다.

2024-01-30 02:08 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func handleTask(completion: @escaping (Double) -> Void) {
리뷰어님께 질문이 있습니다! 메서드 명을 고려하던 중 handleTask메서드가

1. 디큐를 통한 손님업무처리
2. 작업시간 계산 

두 역할을 하고 있다 생각해서 역할 분리를 위해 아래와 같이 고쳐보았습니다! 

<img width="641" alt="image" src="https://github.com/tasty-code/ios-bank-manager/assets/126137760/ac4836f0-99b4-4806-b8a6-c59cc8639bc9">

만약 리뷰어님이라면 어떻게 handleTask메서드를 리팩토링하실지 궁금합니다!

2024-01-30 02:18 UTC, jane1choi commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +              userChoice > 0 && userChoice < 3
조언 감사합니다! 
반영커밋: [b7817e0](https://github.com/tasty-code/ios-bank-manager/pull/72/commits/b7817e03333acdb7b04ae1df0f616b2e5a544dd5)

2024-01-30 02:25 UTC, suojae3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func makeCustomerQueue(with customer: Int) {
customer라는 파라미터명은 대기인원수를 나타내는 네이밍에 있어서 너무 광범위하다고 생각했습니다. 나타내고자 하는바를 명확히하기 위해 customerCount로 파라미터명 수정했습니다!

2024-01-30 02:29 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        bankManager.updateTaskState = { result in
weak self 와 unowned self 의 차이는 무엇인가요 ?

2024-01-31 06:01 UTC, merged

2024-01-31 07:53 UTC, jane1choi commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        bankManager.updateTaskState = { result in
## weak vs. unowned
**weak reference**
    - 참조하는 인스턴스의 reference count를 증가시키지 않습니다.
    - 참조하는 인스턴스가 메모리에서 할당 해제될 경우 **nil** 이 할당됩니다.
**unowned reference**
    - 참조하는 인스턴스의 reference count를 증가시키지 않습니다.
    - 참조하는 인스턴스가 메모리에서 할당 해제될 경우 별다른 조치를 취하지 않는다.

**공통점:** 참조 카운트를 증가시키지 않아 순환 참조를 해결할 수 있는 방법이 될 수 있습니다.

**차이점:**
`weak` 와 다르게 `unowned` 프로퍼티는 옵셔널 타입으로 선언하지 않아도 됩니다.

왜냐하면 unowned 참조는 weak와 다르게 자신이 참조하는 인스턴스가 항상 메모리에 존재할 것이라는 전제를 기반으로 동작하기 때문입니다. (참조하는 인스턴스가 메모리에서 해제되어도 스스로 nil 할당해주지 않음)

그렇기 때문에, 잘못된 메모리 접근으로 런타임 오류가 발생해 프로세스가 강제로 종료될 가능성이 있습니다.
따라서 참조하는 인스턴스가 먼저 메모리에서 해제될 가능성이 없는 경우, 즉 참조하고 있는 객체의 생명주기가 현재 scope의 객체보다 생명주기가 더 길거나 같을 경우에만 사용해야 합니다. (수명이 더 짧은쪽에서 선언)

**`weak`와 `unowned`를 사용하여 순환 참조를 방지할 때 주의 사항**

- weak 를 사용하는 경우 : 옵셔널 타입으로 선언해야 함
- unowned 를 사용하는 경우 : 인스턴스간 life time을 고려해야 함

## [weak self] vs. [unowned self]
클로저의 캡처리스트 내에서의 사용도 마찬가지 입니다.

클로저가 self를 캡처하면 강한 참조 순환을 발생시킬 수 있기 때문에 이를 해결하기 위해 클로저 캡처리스트 내에서 `[weak self]` 또는 `[unowned self]` 로 self가 클로저 내에서 약하게 캡처되거나 소유되지 않은 상태로 캡처될 수 있도록 해줄 수 있습니다. 

- `[weak self]` 선언 후 self 접근: VC를 약하게 참조하겠다
- `[unowned self]` 선언 후 self 접근: VC를 소유하지 않고 참조하겠다

주의 사항도 그대로 적용시켜보면, 

`unowned self`는 self(== vc)의 생명주기가 클로저의 생명주기와 같거나 긴 것이 보장이 될 때만 사용해야합니다.