은행 창구 관리앱 [STEP2] 미르, 희동
tasty-code/ios-bank-manager pull request #73
Opened 2024-01-29 08:37 UTC by MyNB1

@GREENOVER 안녕하세요 그린!
STEP2 PR보내드립니다! 확인부탁드립니다!🙇

### 🤔 고민했던점
#### 각 모델을 역할분리시키려고 하였습니다.
`BankManager`는 고객을 순서에 맞게 대기시키고, 은행원에게 순서에 맞게 배정시키는 역할입니다.
`BankClerk` 0.7초동안 업무(시작과 끝)를 하는 역할입니다. 
`Bank`는 위의 모델들을 인스턴스화하여 고객수에 맞게 BankManager에게 전달합니다. open메서드를 통해 bankManager와 bankClerk프로퍼티가 일을하고, close메서드를 통해 print를 호출하고 업무를 종료합니다.
`Customer` number를 가지고 있는 고객입니다.
`ConsoleManager` 콘솔창에 무엇을 입력할지와 원하는 숫자를 입력하면 업무를 시작하고 프로그램을 종료시키는 역할입니다.

#### 총업무시간 생성하는 방법에 대해 고민했습니다.
코드에서 실제로 작동하는 시간을 구현하였는데 데 연산으로 만든 시간을 출력하는 것은 연산하는 코드를 추가해야 하기 때문에 불필요한 코드 작성이라고 생각하여 연산으로 만든 시간을 적용하는 것이 적절하지 않다고 판단하였고 실제 작동시간을 그대로 출력하도록 구현 하였습니다. ([CFAbsoluteTimeGetCurrent()](https://developer.apple.com/documentation/corefoundation/1543542-cfabsolutetimegetcurrent)사용)
### 🧐 조언을 얻고 싶은 부분
- `각 고객의 업무를 처리하는 데 걸리는 시간은 0.7초입니다`를 나타내기 위해 usleep을 사용하고 있습니다. 해당 부분 작동원리를 찾기가 어려웠습니다만, 어렴풋이 찾아본바로는 UInt32를 매개변수로 받기에 0.7초를 변형하여 사용할 수 있는 usleep()을 사용하였습니다. 해당부분이 적절한 방법인지 궁금합니다.

- 얼핏 듣기로는 while true문을 사용하는 것을 지양한다고 들었습니다. create 메서드를 구현할 때 while true문을 적용했는데 구현은 잘 되었으나 true상황이 정확히 어떤 상태인지에 대한 이해가 부족한 것 같습니다. 적절한 방법으로 구현된 것인지 의견 여쭙습니다!

2024-01-29 09:52 UTC, GREENOVER requested changes
@MyNB1 @mireu930 
스텝2도 너무 고생 많으셨습니다~!!
전체적으로 요구사항은 아주 잘 만족하고 동작도 잘합니다ㅎㅎ
그렇기에 이번 스텝에서 리뷰도 요구사항보다는 조금 더 객체지향과 의존성에 포커싱을 맞춰 리뷰 드렸습니다 🙋🏻
***
### 칭찬드리고 싶은 부분
- 네이밍 작명을 잘하시는것 같아요 💯
- 커밋 히스토리를 아주아주 잘 관리하시네요 💯
- 적절하게 객체들을 분리시켜 사용하시는점 💯
***
### 궁금하신 부분에 대한 저의 의견
- 각 고객의 업무를 처리하는 데 걸리는 시간은 0.7초입니다를 나타내기 위해 usleep을 사용하고 있습니다. 해당 부분 작동원리를 찾기가 어려웠습니다만, 어렴풋이 찾아본바로는 UInt32를 매개변수로 받기에 0.7초를 변형하여 사용할 수 있는 usleep()을 사용하였습니다. 해당부분이 적절한 방법인지 궁금합니다.
  - 네 충분히 적절해보입니다ㅎㅎ
  다양한 방법이 있겠지만, 예를들어 Thread의 sleep을 이용한다면 0.7초를 그대로 넣어줘야되서 가독성의 향상을 가져올 수는 있어 보여요.
  그렇지만 어떻게보면 지금 구현하신것처럼 마이크로초 단위로 컨트롤하는것이 100% 보장되는것은 아니지만 조금 더 정확한 시간을 지연시켜줄거라고는 보입니다.
  아니면 더 세밀하게 보장하고싶다면 Timer 클래스나 GCD를 이용해봐도 좋을것 같구요..!
- 얼핏 듣기로는 while true문을 사용하는 것을 지양한다고 들었습니다. create 메서드를 구현할 때 while true문을 적용했는데 구현은 잘 되었으나 true상황이 정확히 어떤 상태인지에 대한 이해가 부족한 것 같습니다. 적절한 방법으로 구현된 것인지 의견 여쭙습니다!
  - 지양한다는 이유가 무한 루프가 돌 수 있을 수 있는 상황이 발생하여서 그럴것이고 현재로써는 저는 적절해보이긴합니다!
  말씀처럼 ConsoleManager에서 while 반복문 로직을 보면 항상 true로 들어가겠지만, 예를들어 해당 콘솔매니저 인스턴스를 main에서 만들고 동작시켜줄때 어떠한 에러가 있어서 동작시키지 말아야한다면, while문에 들어간 bool값을 이용할 수도 있을것 같구요 🤔
  true로 동작시켜줄때 잘된건 항상 특별한 조건이 없으면 true이기에 무조건 보장되어 while문을 돈다고 보면 좋을것 같습니다~!
***
다시 한번 고생 많으셨습니다ㅎㅎ
전체적으로 은닉화와 접근레벨 그리고 의존성 주입에 대해 고민해보면 좋을 포인트들을 남겨봤습니다~!
언제든 재리뷰 요청 혹은 머지 요청해주세요 😃

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    let bankClerk = BankClerk()
private으로 은닉화하고 이니셜라이저를 통해 받아오는 방법은 어떤가요~?
현재 외부에서 Bank의 해당 프로퍼티들을 직접 접근할 수 있을것 같은데, 은닉화와 의존성 주입을 활용해보면 좋을것 같아요 🙋🏻

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    let bankClerk = BankClerk()
현재 인스턴스를 그냥 내부에서 생성할 수도 있겠지만, 추후에 BankManager 타입에서 여러 인자들이 존재하고 그에 맞는 BankManager를 넣어줘야한다면 확장성에서 조금 고려되어야할것 같아 보입니다 🤔

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func closeBank(time: String) {
외부에서 직접 호출할 일이 없다면 private해도 되지 않을까요~?

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func setCustomerCount(customer: Int) {
외부에서 직접 호출할 일이 없다면 private해도 되지 않을까요~?

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        let workTime = String(format: "%.2f", endOfWorkTime - startWorkTime)
시간을 계산하고 반환하는 로직 처리를 객체지향 원칙인 SOLID의 SRP에 적용하여 별도 메서드로 분리해보면 어떨까요?
적절히 클로저 파라미터를 이용해도 될것 같아서요~!
```swift
func calculateWorkTime(work: () -> Void) -> String { }
```
요런 시그니쳐를 가진 메서드로 분리하여 구현한다면 조금 더 메서드의 할일이 분리되지 않을까 싶습니다!

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +    var pace: Double = 0.7
의존성 주입을 활용해보면 어떨까요 🙋🏻

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +    var pace: Double = 0.7
마찬가지로 pace를 외부에서 수정할 수 없도록 은닉화해봐도 좋을것 같아요!
실수로 변경할 여지가 있어보여서요ㅠ

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +        print("\(customer.numOfPerson)번 고객 업무 완료")
스타일이기는 하지만..! SRP를 따라 한 메서드에서 하나의 역할만 할 수 있도록 분리해봐도 좋을것 같아요~!

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +            BankClerk().recieve(customer: list as? Customer ?? Customer(numOfPerson: 0) )
해당 BankClerk 인스턴스를 직접 여기서 다루는것이 아닌 BankManager내에서 전역적으로 생성하는것은 어떨까요~?
왜냐하면 현재 코드로는 매번 해당 인스턴스를 새로 생성하고 있기에 재사용성과 성능에서 떨어질것 같습니다ㅠ

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        while let list = try? queue.dequeue() {
에러를 던지는 코드가 없어보이는데 괜찮을까요..!?

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +            BankClerk().recieve(customer: list as? Customer ?? Customer(numOfPerson: 0) )
초기값을 활용하는것도 방법일 수 있겠지만, 가독성과 보다 정확한 에러처리를 위해서는 요런 사용도 있을것 같아 의견 드립니다 🙋🏻

```swift
while let number = try? queue.dequeue() {
  guard let customer = number as? Customer else {
    throw 에러!
  }
  bankClerk.recieve(customer: customer)
}
```

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +
한줄 개행은 의도일까요..!?

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +protocol Number {
뭔가 공통적인 프로토콜의 네이밍이 아닌 느낌이 살짝 듭니다 🥲
해당 프로토콜이 뭔가 전체적으로 숫자를 아우르는 Number라는 이름의 프로토콜인데 Customer말고 다른곳에서도 채택한다면 numOfPerson 프로퍼티를 꼭 구현해줘야 해서 적절할까 생각이 들었어요ㅎㅎ

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +            print("입력 :", terminator:" ")
혹시나 실수나 코드가 많아졌을때 유지보수를 편하게 하기 위해서 네임스페이스도 적절히 상황에 맞다면 활용해봐도 좋을것 같습니다 🙋🏻

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
get 프로퍼티로 선언해주신 이유가 궁금합니다 🙋🏻
요 프로토콜을 따른다면 실제 만들어진 인스턴스에서 새 값으로 set할 수 없나요~?

2024-01-29 09:52 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +    let randomNumber: Int = Int.random(in: 10...30)
외부에서 의존성 주입을 통해 받아오면 어떨까요~?

2024-01-30 02:26 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    let bankClerk = BankClerk()
말씀주신바와 같이 확장성을 고려한다면 의존성주입을 활용해보는 것도 좋다고 생각혀 [해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/3224badb408868d7fb74b57f412580d8dae1dc23)에서 수정해봤습니다!

2024-01-30 02:27 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func closeBank(time: String) {
[해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/cea8086c50761bb2170ac75804199c6e93225198)에서 수정했습니다!

2024-01-30 02:27 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func setCustomerCount(customer: Int) {
[해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/cea8086c50761bb2170ac75804199c6e93225198)에서 수정했습니다!

2024-01-30 02:29 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        let workTime = String(format: "%.2f", endOfWorkTime - startWorkTime)
[해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/9b45479fd64e9c277bbbc10617be1853e4cd5163)에서 수정했습니다!

2024-01-30 02:30 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +        print("\(customer.numOfPerson)번 고객 업무 완료")
[해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/5fad5d66b89a1c0794b6cedbe050012d21c7894f)에서 수정했습니다!

2024-01-30 02:32 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +
앗.. 아닙니다..ㅎ (신중하지 못했습니다..)
다시 수정하였습니다!

2024-01-30 02:35 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +protocol Number {
고객의 수를 아우르는 네이밍이 적절하다고 생각하여 `CustomerNumbering`이라고 수정해봤습니다!

2024-01-30 02:40 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +            print("입력 :", terminator:" ")
추후 유지보수를 위해 네임스페이스를 [해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/853efeaa057a9a3211cd901de47bc6b7a8cd3ad4)에서 분류해줬습니다. 원래는 네임스페이스 파일을 따로 분리해줬지만, 현재 프로젝트에선 네임이 많지않다고 생각해 타입안에 네임스페이스를 분류해뒀습니다.

2024-01-30 02:40 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +    let randomNumber: Int = Int.random(in: 10...30)
[해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/1a6b315e860081668a0ddc91e54487f26eab0d04)에서 수정했습니다!

2024-01-30 02:46 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +            BankClerk().recieve(customer: list as? Customer ?? Customer(numOfPerson: 0) )
매번 해당 인스턴스를 생성하면 재사용성이 떨어진다고 생각해 BankManager내에서 전역상수로 지정해줬고, 말씀주신대로 가독성과 정확한 에러처리를 위해 수정해봤고, 에러를 던져서 do-catch문으로 받아서 메서드가 좀더 안전하게 실행될수 있도록 [해당커밋](https://github.com/tasty-code/ios-bank-manager/pull/73/commits/8ea762312f03acd3cacdb2c75bb5b5bbd404cca8)에서 수정해줬습니다!

2024-01-30 03:25 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
프로토콜을 채택한 프로퍼티는 최소한 요구사항을 위해 읽기전용인 get을 선언해줬고, 
해당 프로토콜을 따르면 새값인 set을 할 수 없는것으로 알고 있습니다!

2024-01-30 03:43 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
오호 그렇다면 실제로도 Number 프로토콜을 따르는 Customer 인스턴스를 생성한 후 numOfPerson의 값을 업데이트 시킬 수 없는건가요~?

2024-01-30 05:32 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
넵! get프로퍼티가 프로퍼티를 읽을 수만 있고 새로운 값을 설정할 수 없고, 업데이트를 하려면 get set을 선언해줘야합니다!

2024-01-30 06:34 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
그런데 이 상황에서 수정이 되지 않나요~? 🤔
```swift
protocol Number
  var numOfPerson: Int { get }

struct Customer: Number {
  var numOfPerson: Int
}

var customer = Customer(numOfPerson: 5)
customer.numOfPerson = 6
```
이 코드가 get으로 읽기만 의도하셨다면 해당 numOfPerson값이 update되지 않아야 할텐데 되지 않나요~?

2024-01-30 09:13 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
아.. 헷갈려서 잘못알고 있었던거 같습니다.. 
get프로퍼티를 선언하게되면 읽기와 읽기,쓰기를 모두 구현할수 있습니다. 
따라서  만들어진 인스턴스에서 새 값으로 set할 수 있습니다!

2024-01-30 09:45 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
그럼 의도하신것처럼 해당 numOfPerson이 get만 되도록 하려면 어떻게 수정해보는것이 좋을까요!?

2024-01-30 09:52 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
프로토콜을 채택하고 있는 타입의 프로퍼티에 private(set)으로 읽기만 가능하도록 하는 방법이 있습니다! 
```swift
protocol Number {
  var numOfPerson: Int { get }
}
struct Customer: Number {
  private(set) var numOfPerson: Int
}
```

2024-01-30 10:24 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
👍👍👍👍
그럼 프로토콜에서는 get 프로퍼티로의 지정이 왜 필요할까요~?

2024-01-31 01:56 UTC, mireu930 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
get을 쓴 이유는 get set을 쓰게되면 read-only를 사용하지 못하기 때문에 프로토콜을 채택한 타입에 프로퍼티에 read-only를 사용하기 위해 get프로퍼티로 지정해줬습니다. 이런의도로 get을 지정해주긴했는데 다른이유가 있는지 궁금합니다.

2024-01-31 02:29 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var numOfPerson: Int { get }
아하 큰 의도보다는 여러분들이 의도하는것이 정답이긴하지만, 구현에서는 그 의도가 잘 반영될 수 없어서 말씀드렸어요..!
프로토콜로 get하게 정의해두어도 결국 채택하는쪽에서 설정하지 않으면 read-only가 되지 않으니까요ㅠ
그렇다고 프로토콜에서 그럼 get 프로퍼티로 정의할 필요가 없지않냐!?는 아닙니다.
말그대로 프로토콜은 어떠한 요구사항의 청사진이기에, 해당 프로토콜을 채택하여 청사진으로 볼때 "아 이 프로퍼티는 read-only해야 하구나"라고 생각하고 현재처럼 private(set)등을 이용해 read-only하게 구현하는것을 놓치지 않을 수 있을것 같습니다!

2024-01-31 02:39 UTC, GREENOVER approved these changes
리팩토링 하시느라 수고 많으셨습니다!! 👍👍👍
다음 스텝도 화이팅입니다ㅎㅎ

2024-01-31 02:39 UTC, merged