은행 창구 관리앱 [STEP2] 노움, 토미
tasty-code/ios-bank-manager pull request #74
Opened 2024-01-29 12:25 UTC by angryeon7

> 리뷰어 : @keeplo
버드 : @angryeon7 (토미) @Gnoam-R (노움)
> 

안녕하세요-!-! 말꼬
항상 꼼꼼한 피드백 너무 감사드려요-! 
이번 STEP2도 피드백 마구마구 부탁드립니다! 즐거운 하루 보내세요🍀

---

## Step1 구현사항

### 1. `Bank` 구조체

- `bankWatingQueue` : 은행에 방문하여 접수한 고객들의 대기열
- `clerk` : 은행에서 근무중인 은행원
- `handledCustomerCount` : 처리된 고객 수를 추적하는 변수
- `open()`: 대기열을 설정하고 은행 작업을 실행
- `executeBankWork()`: 은행의 작업을 수행
- `setWaitingLine()`: 은행의 대기열에 10~30 사이의 랜덤한 수의 고객들을 저장해주는 메서드
- `serveCustomer()`: 은행의 대기열이 비어있을때까지 고객을 순서대로 은행원에게 보내는 메서드

### 2. `BankManager` 구조체

- 은행의 전반적인 운영을 관리합니다.
- `Menu` : 메뉴 옵션 (개점 및 종료)을 나타내기 위해 열거형
- `run` :  메뉴를 반복적으로 표시하고 사용자 입력을 받아 선택한 메뉴 옵션을 처리합니다.
- `processMenu` : 선택한 메뉴 옵션을 처리합니다. 예를 들어 은행 개점 또는 프로그램 종료.
- `showMenu` 및 `inputMenu` 메서드는 메뉴 옵션을 표시하고 사용자 입력을 가져오는 데 사용합니다.

### 3. `BankWork` 프로토콜

- 일반적인 은행 작업을 위한 공통 인터페이스를 정의하는 프로토콜.
- `work(for:)` 메서드 하나를 포함하며 주어진 고객에 대한 작업을 수행

### 4. `BankClerk` 구조체

- `BankWork` 프로토콜을 준수하며 은행 직원을 나타냅니다.
- `work(for:)` 메서드를 구현하며 고객에 대한 작업을 시작 및 완료하는 메시지를 출력

### 5. `BankMessage` 열거형

- 은행 운영과 관련된 다양한 메시지를 출력한다.
- `show` 속성은 각 case에 대한 형식화된 문자열을 제공합니다.

### 6. `Customer` 구조체

- `var number` : 은행의 대기번호

## **🧐 조언을 얻고 싶은 부분**

- BankMessage가 지금은 메시지의 양이 적어 하나의 enum으로 관리가 가능하지만, 하나의 enum으로 묶기에는 통일감이 부족하다고 생각합니다..
- 이 부분에 대해 어떻게 생각하시는지 궁금합니다.

```swift
enum BankMessage {
    case open
    case exit
    case start(Int)
    case done(Int)
    case result(Int, String)
    
    var show: String {
        switch self {
        case .open:
            return "1 : 은행 개점"
        case .exit:
            return "2 : 종료"
        case .start(let number):
            return "\(number)번 고객 업무 시작"
        case .done(let number):
            return "\(number)번 고객 업무 완료"
        case .result(let customerCount, let intervalTime):
            return "업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(customerCount)명이며, 총 업무시간은 \(intervalTime)입니다."
        }
    }
}
```

2024-01-30 11:10 UTC, keeplo requested changes
두 분 Step 2 진행하시느라 고생하셨습니다! 🙌🏼🙌🏼🙌🏼
제가 괜찮다고 하곤 본의 아니게 만 하루가 다되는 늦은 리뷰를 드려버렸네요 ㅠㅠ
> 평소에 4-5시에 일어나고 9-10시에 자가지고 ㅠㅠ 놓쳤어요 죄송합니다😰

---
구현사항의 설명이 있어서 분명 도움은 될거라고 생각하는데
이렇게 매번 설명을 적는게, 주석을 달지 말자는 교육 의도의 모순점이 될 수도 있고
두 분도 일일이 모든 메서드를 설명하시기가 쉽지 않았을거라고 생각되요! 

팀바팀이긴 하지만 분명 많은 개발서적에서 주석과 테스트의 수정 비용과
구현 수정 했음에서도 내용 수정을 실수로 놓치는 등의 위험성을 공통적으로 얘기하는 부분이니 
문서화에서 적어주신 구현사항이나 설명을 위한 주석은 최소화하면 좋을 것 같아요!
리뷰나 Step 3 진행중 메서드가 수정 또는 제거되면 이 PR - Conversation은 레거시가 됩니다!

저는 개인적으로 UML을 연습하시는게 더 좋을 수도 있을것 같아요!

---
조언을 구하셨는데
좀 애매한 답변을 드릴 것 같습니다.

우선 구현해주신 방향은 너무 좋습니다.
꼭 메시지를 위한  String이 아니더라도 그리고 enum 의 case가 늘어나는 방향이더라도
`무조건 적으로 늘어나면 구조체로 해야한다` 같은 부분은 저는 반대하는 편이에요!

제 경험을 말씀드리면 `Alert`에 보여줄 메시지를 switch 케이스로 담은 
`Factory` 개체의 메서드로 구현해본적도 있습니다.
```swift
struct / enum AlertMessage {
   
   // if struct
   // private init() {}
 
   enum Alert {
       case decodingFailure
       case userConfirm
       // ...
   }
   
   static func make(by alert: Alert) -> AlertItem {
       switch alert {
          case decodingFailure: 
                return .init (
                     // ...
                )
          // ...
       }
    }
}
```

그리고 String에 초점을 잡아보자면
저는 String 데이터도 View로써 명시하는 편입니다
`Localization`도 대비하기 좋고

지금 구조에서 모든 String 데이터를 한번에 관리 가능한 장점과 반대로 
화면을 그려주는 데이터를 View에서 직접 접근하는 장점도 있습니다

```swift
// Aview.swift

let label = UILabel()

// ...

label.text = "\(item.number) 번째 데이터"

```

다양한 레퍼런스들을 경험하시고 결정하시되 팀원과 상의후 결정하는
트레이드 오프 적인 성향이 강한 부분 같아요!

--- 

이번 Step2 설계는 많이 고민하셨을거라고 생각됩니다.
저는 다음스텝을 바라보는 구현은 안하는걸 추천드리는 편이라서
현 스텝에 요구사항 중심으로 확인했고 잘 구현해주셨어요! 👍🏼

로직 자체에 대한 문제점은 전혀 없었고
눈의 띄는 부분들 중심으로 코멘트를 달았습니다 
코멘트가 적은 만큼 반대로 좀 더 고민하고 구조를 수정해야할 수도 있는
묵직한 코멘트 들이 있네요..

제가 두 분의 개인적인 개발 학습 히스토리는 모두 파악하지 못했기 때문에
혹시나 OOP 개념이나 의존성 등의 디테일한 영역이 설명이 부족하거나, 
아직 어려운 부분이 있으시다면 언제든 디엠주세요! 
혹시 필요하시면 모두 가능한 시간이면 디코 `코드먹방`에서 구두로 설명드릴게요!

---

Step 1 에 코멘트가 추가적으로 있는데 
확인을 못하신건지 확인은 하셨는데 반영을 안하신건지 알 수 없더라구요!

답글 달아주시지 않은 코멘트 확인한 부분이 있다면 이모지 달아주세요!
그리고 수정을 하면 좋을것 같다는 부분에는 어떤 의도와 이유로 반영하지 않는지
설명을 해주시면 좋을것 같아요!

2024-01-30 11:10 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            clerk.work(for: customer)
사용자가 2를 입력해서 종료하는 시점은 정말 예측할 수 없기 때문에
한줄의 코드 수준이더라도 명료하면 좋을것 같아요!

고객에 대한 처리 (`clerk.work(_:)`) 가 끝나지 않은 상태이니 
`handledCustomerCount += 1`
코드의 위치가 아래로 내려가는 쪽이 좋을것 같아요.

하지만 제 예상으로는 업무 완료 메시지가 종료 후에 나올 수도 있는데
이런 점도 고민해보면 좋을것같아요.

전체적인 흐름을 보았을때 `print()`  라는 콘솔에 바로 표시할 수 있는
강력한 전역 메서드를 사용하는게 아니라

UI 처럼 View Layer로 전달을 해야한다면 지금처럼 모든 개체가 print를 사용하는 
방향에 대해서도 출력 책임을 어떻게 하면 좋을지 고민하면 좋을것 같아요!

2024-01-30 11:10 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +                  let menu = Menu(rawValue: value)
사용자 입력을 enum의 rawValue 까지 연결 하셨군요!
아주 좋은 아이디어 같습니다! 👍🏼👍🏼

추후에 서버통신이나 DB 접근에서도 이 rawValue-enum을 잘 활용하시면
유용할거에요!

2024-01-30 11:10 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    }
모르거나 의식하고 넘어가기 보단 어렵더라도 언급하는 쪽을 택하겠습니다.. ㅎ

OOP 구현에서 SOLID 원칙이나 다양한 개발 권장사항들이 있는데요
다양한 개발서적에서 공통적으로 언급하는 부분중 하나가 응집도/결합도 입니다.
각 개체간의 의존관계로 인해서 발생하는 부분인데

구현 로직에는 전혀 문제가 없지만 개발규모가 커질 수록 이 미세한 부분들이
큰 비용으로 발생하는걸 대비하는 일종의 습관처럼 의식해야하는 부분이 있습니다.

예를들어 `BankManager` 입장에서는 특정개체A의 메서드의 파라미터 타입을 몰라도
됩니다 (정확히는 그걸 감안해서 A는 접근제어를 관리해야합니다)
하지만 지금같은 구현은 `private func showPromt(message: BankMessage)`
에서 명시된 `BankMessage` 타입이 작성되었기 때문에 

`BankManager`와 `BankMessage`는 의존관계가 형성됩니다.
그 의미는 UML을 그릴때 선으로 이어진다는걸 의미합니다.

제가 다른 부분에서 `print` 메서드가 전역이라는 점과 UI로 치환해본다면
현재 구조에는 수정이 불가피 할거로 답변을 드렸는데

설계를 좀더 개선하실때 위에서 언급한 의존관계도 함께 고민해주시면 좋을것 같아요!

2024-01-30 11:10 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    }
혹시 `break`는 `run()` 메서드의 while 문에서 동작되는 걸까요?

음.. 물론 들여쓰기 2번 규칙이 있어서 
이런 구현이 나올 수는 있는데
`processMenu(_:)` 메서드는 개체 내에 어디서든 사용될 수 있다는 걸 의미하는데
외부의 구현을 함수 내부에서 인지하고 사용되는건 조심스러울것 같아요!

팀마다 사람마다 다르겠지만 메서드가 수십개가 되면 
각 매서드가 독립적으로 한가지 일을 할때 추적이 가능합니다.
지금처럼 로직의 분리되거나 `processMenu(_:)` 메서드를 독립적으로 의도를 이해할 수 없으면 좋은 방향은 아닌것 같아요!

처음엔 switch 문으로써 break를 명시하신줄 알았습니다 

반환값을 이용하는 방향을 추천드려요!

2024-01-30 11:10 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +        print(BankMessage.done(customer.number).show)
다른 코멘트에서 언급한 `print()`를 여기서도 고민해보면 좋을것 같아요

OOP 개념을 대입해보면 `BankClerk` 
개체의 책임은 어디까지이면 좋을지 고민해보면 좋을 것 같아요!

2024-01-31 12:33 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +        print(BankMessage.done(customer.number).show)
`BankClerk`가 메시지 출력 및 대기 기능을 직접 수행하지 않고, 별도의 함수로 분리하여 처리하였습니다.

2024-01-31 12:33 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    }
반환값을 이용하여 수정하였습니다!

2024-01-31 12:37 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    }
출력 관련 로직이 `Bank`에 캡슐화되고, 향후 UI 레이어로의 전환에 용이해지도록했습니다.
출력은 `Bank`에서 담당하고, `BankManager`는 결과만 받아서 표시하도록 변경할 수 있게 수정하였습니다.

2024-02-01 01:49 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            clerk.work(for: customer)
BankView를 생성하여 출력 관련 로직에 책임을 갖게 수정하였습니다. 출력 로직이 별도의 구조체로 이동함으로써, 출력 방식을 변경하거나 다른 UI 프레임워크로 전환하기가 용이해졌습니다!

2024-02-01 03:20 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
> +        print(BankMessage.done(customer.number).show)
음... 단순히 함수에서 분리되는건 큰 의미가 없습니다;;
`BankClerk` 개체에 책임으로써 `print()` 를 사용하는 부분이 존재하는 것에 대한 부분이었어요!

2024-02-01 03:33 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            clerk.work(for: customer)
제가 언급했던 책임을 전달한 구현으로 static 메서드로 구현되는 부분은 충분히 나쁘지 않아보입니다.
그런데 말씀하신 것처럼 UI프레임워크 전환이라면 BankManager가 ViewController로 치환될 것 같은데..
`Bank`에서 ConsoleView에 접근하는 부분은 없는게 좋을것 같아요!

`print()` 메서드가 존재하는데서 문제가 발생하기 보다
`ConsoleView` 개체를 `print()` 호출 위치에서 호출하게 된다면 결과적으로 Bank의 책임 속에는 `ConsoleView.showResult(_:_:)` 메서드 호출이 포함되게 됩니다.

저는 앞서 말한것 처럼 BankManager에서만 `ConsoleView`에 접근하는 형태로 구현하는게 좀더 
각 개체간의 책임과 역할 그리고 관계를 가져가는데 좋을것 같아요!

2024-02-01 03:35 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    }
음... 반환값을 이용하셨다고 했는데.. 어떤 부분인지 알려주실 수 있을까요?;;

2024-02-01 05:43 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    }
죄송해요. 착각했습니다ㅜㅜ processMenu라는 메소드의 분리가 좋지 않다고 생각하여 run()에 추가하였습니다.

2024-02-01 13:00 UTC, merged

2024-02-01 13:06 UTC, keeplo commented
변경점도 확인 했습니다!

구두로 말씀드렸던 것처럼 현시점에서는 보이지 않는 설계 수정이 필요한 부분들이 앞으로 생길 수 있어요!
잘 해결해 나가실거라고 생각합니다

Step 2에서는 동작에 큰 이슈도 없고 전반적으로 소통도 되었기때문에 머지 했습니다!

Step 3 진행하시면서 언급한 코멘트들도 상기해주시면서 진행하면 좋을것 같아요!

--- 

weak 참조에 관해서는 확인해보았는데 
retain count가 0이라서 인스턴스가 끊어지는게 맞습니다.
리뷰에서는 눈으로만 보고 `이렇게 될 것 같은데?` 하는 부분도 있는데

delegate 패턴 적용하시는걸 보면서 다시 떠올랐어요 
제가 weak 프로퍼티 했던건 강한참조로 이어진 개체간에 추가 참조가 발생하면 weak 으로 했었습니다;;
저도 다시 리마인드 할 수 있었습니다 ㅎㅎㅎ;;

> 그런점에서 delegate를 weak var 로 선언하면 좋을것 같아요 ㅎㅎ

현시점에서는 말씀해주신 것처럼 단방향 링크드리스트이기도 하고 설계상 강한참조로 존재하는게 맞습니다.

2024-02-05 02:04 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +
이런 단순 공백은 커밋에 포함되지 않도록 확인해주세요!

Xcode 에서 변경점 확인하시거나
GUI Git 툴을 사용해보시는것도 추천드려요

저는 주로 fork 쓰는데 이것도 좋고 Gitkraken 이나 source tree 도 있습니다!

2024-02-05 02:04 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +
이런 줄바꿈도 포함되지않도록 유의해주세요!

커밋 단위를 고민하시는 것처럼 동료가 리뷰 해주는 이유라거나
에러 추적을 위해 커밋 단위로 변경점을 봐야하기 마련인데 
가독성을 방해하는 요소가 되기도 해요!
이런 불필요한 변경점은 0에 수렴할 수록 좋습니다!