은행 창구 관리 앱 [STEP2] 댄, 네로
tasty-code/ios-bank-manager pull request #76
Opened 2024-01-30 06:22 UTC by ODDNERO

Step 2
멤버 : @eensungkim, @ODDNERO
리뷰어 : @yim2627

은행 창구 관리 앱 프로젝트의 두 번째 STEP입니다!
이번 PR도 잘 부탁드립니다! 🙇🏻‍♀️🙇🏻‍♀️

# PR 상세
- Queue 활용
- 콘솔 앱 구현
<br/>

# 구성
### main.swift
- BankManager 콘솔 앱 실행

### BankManager.swift
- 메뉴를 출력하고 사용자의 입력을 받아 해당 기능 실행
- 랜덤하게 10~30명의 고객을 생성하여 Queue에 고객을 추가
- Queue 대기열에서 순서대로 dequeue하여 Banker에게 고객을 전달

### Banker.swift
- 고객을 전달받아 업무를 시작~완료하는 메시지를 출력
- 소요된 시간을 return

### Customer.swift
- 소요 시간, 대기 번호를 갖는 고객 구조체
<br>

# 질문
1. `캡슐화`
현재 BankManager에서 Banker를 가지고 있고, Banker가 외부로 노출하는 메서드인 provideService를 호출하여 업무를 시작하는 구조인데요. Banker에서 외부로 노출하는 메서드가 하나밖에 없다 보니, 별도의 **프로토콜**을 구현하지는 않은 상황입니다!
하지만 추후 Banker를 확장할 가능성을 염두에 둔다면, 프로토콜을 통해 BankManager에서 **접근 가능한 메서드를 조절**해 줄 필요도 있다고 생각됩니다. 초기 단계에서부터 이러한 부분들을 고려하여 구현해 두는 것이 좋을까요?
만약 그렇다면 어떤 기준을 가져야 할까요?

2. `의존성`
Banker 의 경우 현재 Customer 만을 전달받을 수 있기 때문에 Customer에 의존적이라고 생각합니다.
이 문제 역시 프로토콜을 활용해 해결할 수 있을 거라고 생각하는데요. 
소요 시간과 대기 번호를 갖는 프로토콜을 구현해 Customer 에 채택해주고, 
Banker 가 전달받는 객체의 타입을 해당 프로토콜로 지정해주면 추후에 다른 객체에게도 확장이 열려있을 것 같아요.
이런 구현이 당장에는 몇 줄의 코드가 추가되는 형태이지만 추후 확장에 열려있어 더 바람직한 방향일지 궁금합니다.

<br>

2024-01-30 08:20 UTC, yim2627 requested changes
안녕하세요! 댄 네로!

이번 스텝도 고생 많으셨습니다. 

구현이 안된 부분도 있어 커멘트로 남겨놨으니 확인 부탁드립니다.

> **캡슐화**
현재 BankManager에서 Banker를 가지고 있고, Banker가 외부로 노출하는 메서드인 provideService를 호출하여 업무를 시작하는 구조인데요. Banker에서 외부로 노출하는 메서드가 하나밖에 없다 보니, 별도의 프로토콜을 구현하지는 않은 상황입니다!
하지만 추후 Banker를 확장할 가능성을 염두에 둔다면, 프로토콜을 통해 BankManager에서 접근 가능한 메서드를 조절해 줄 필요도 있다고 생각됩니다. 초기 단계에서부터 이러한 부분들을 고려하여 구현해 두는 것이 좋을까요?
만약 그렇다면 어떤 기준을 가져야 할까요?

추후 확장이 될지 안될지는 기획자도 모르기 때문에 개발자가 생각하기엔 무리가 있을 것 같습니다. 단, 테스터블한 구조를 위해선 가짜 Banker를 만들기 위한 프로토콜을 통하든, 구조체를 통하든 어떤 방법으로든 추상화가 필요할 수 도 있겠네요.
게다가 테스터블한 구조를 위해 진행한 추상화가 확장 가능한 구조까지 이뤄질 수 있으므로, 이런 방향을 생각하여 개발하시면 도움이 될 것 같습니다. 

ex) 과수원에서 사과만 키우진 않으니, 재배 목록에 "사과"가 아닌 "과일"로 추상화하여 어떤 과일(확장성)이든 판매할 수 있게 만든다.

> **의존성**
Banker 의 경우 현재 Customer 만을 전달받을 수 있기 때문에 Customer에 의존적이라고 생각합니다.
이 문제 역시 프로토콜을 활용해 해결할 수 있을 거라고 생각하는데요.
소요 시간과 대기 번호를 갖는 프로토콜을 구현해 Customer 에 채택해주고,
Banker 가 전달받는 객체의 타입을 해당 프로토콜로 지정해주면 추후에 다른 객체에게도 확장이 열려있을 것 같아요.
이런 구현이 당장에는 몇 줄의 코드가 추가되는 형태이지만 추후 확장에 열려있어 더 바람직한 방향일지 궁금합니다.

위에서 말씀드린 것과 의견 같습니다.

궁금하신 점이 있다면 언제든지 DM 주세요!

2024-01-30 08:20 UTC, yim2627 commented on BankManager.swift
> +            print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomers)명이며, 총 업무시간은 \(String(format: "%.2f", totalTime))초입니다.")
`start()` 메서드의 "은행 개점" 케이스에 업무 마감이라고 프린트가 찍혀있으니, 조금 어색해보이는데, 어떻게 생각하시나요?

2024-01-30 08:20 UTC, yim2627 commented on BankManager.swift
> +    mutating func startBankingProcess() {
구조체가 가진 값을 변경하려다보니 `mutating`을 붙여야되는 일이 발생했는데, mutating은 무엇이고, 어떻게 동작할까요?

2024-01-30 08:20 UTC, yim2627 commented on BankManager.swift
> +    private let banker: Banker = Banker()
만일 테스트를 진행할 때 가짜 은행원들을 넣어주고 싶다면 타입을 어떻게 정의하는 것이 좋을까요?

2024-01-30 08:20 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +}
현재 은행원이 업무를 처리하는 시간은 0.7초로 되어있는데, 실제로 반영되지 않고, 출력만 되고있는 것 같습니다.
하나의 업무를 처리하는 데 1.2초가 소요되는데, 업무가 10개가 있다하면, 실제 콘솔에 전부 출력이 되려면 12초가 걸려야 합니다.
구현 사항 한번 확인 부탁드리고, 이때 어떤 방식으로 진행하실 지 말씀해주세요!

2024-01-30 08:20 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    private(set) var waitingNumber: Int
👍👍

2024-01-30 08:20 UTC, yim2627 commented on BankManager.swift
> +    mutating func startBankingProcess() {
외부에서 사용하나요?

2024-01-30 08:20 UTC, yim2627 commented on BankManager.swift
> +        }
잘못된 입력에 따른 예외처리도 있다면 좋을 것 같습니다! 현재는 문자열 입력시 그냥 종료되고 있습니다.

2024-01-30 08:25 UTC, yim2627 commented on BankManager.swift
> +        while !queue.isEmpty() {
👍👍

2024-01-30 08:42 UTC, eensungkim commented on BankManager.swift
> +            print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomers)명이며, 총 업무시간은 \(String(format: "%.2f", totalTime))초입니다.")
그렇게 보일 수 있을 것 같아요!
print 문을 startBankingProcess() 메서드 내부로 옮겨서 뱅킹 프로세스가 종료되는 시점에 호출되도록 변경하고,
기존에 재귀로 호출하던 start 메서드를 main 으로 이름을 변경했습니다!

2024-01-30 10:09 UTC, eensungkim commented on BankManager.swift
> +    private let banker: Banker = Banker()
가짜 은행원들이라면 복수의 은행원이 되는 셈이니, [Banker] 로 만들어주어야 할 것 같습니다.
그렇게 된다면 기본값도 [Banker()] 가 되겠고, setter 를 별도로 구현하여 외부에서 주입도 가능하게 만들어줘야 할 것 같습니다!
질문에서 의도하신 답변일까요?

2024-01-30 10:35 UTC, eensungkim commented on BankManager.swift
> +        }
잘못된 입력이 있는 경우 print 출력 후 다시 메뉴를 선택하도록 로직을 수정했습니다!

2024-01-31 01:57 UTC, eensungkim commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +}
DispatchQueue.global().sync 를 통해 메인이 아닌 별도의 스레드에서 Banker의 업무가 처리되도록 하고,
Banker 가 출력하는 2개의 메시지 사이에 Thread.sleep(forTimeInterval:) 을 넣어 해당 스레드가 소요 시간만큼 멈출 수 있도록 구현했습니다!

2024-01-31 01:58 UTC, eensungkim commented on BankManager.swift
> +    mutating func startBankingProcess() {
외부에서 사용하지 않기 때문에 private 제어자 추가하겠습니다.

2024-01-31 02:10 UTC, eensungkim commented on BankManager.swift
> +    mutating func startBankingProcess() {
댓글에 말씀해주신 것처럼 `mutating` 키워드는 구조체가 가진 내부 프로퍼티를 메서드가 변경하는 경우에 붙여주어야 하는 키워드입니다.
구조체는 값 타입이기 때문에 구조체의 내부 프로퍼티는 기본적으로 인스턴스 메서드로 변경이 불가능 하지만, 특별히 변경이 필요한 메서드를 구현하는 경우에 `mutating` 키워드를 통해 프로퍼티의 변경 기능을 구현할 수 있습니다. 또한 이러한 변경 가능한 메서드는 변수 타입으로 선언된 구조체에만 적용이 가능합니다. 상수(`let`)으로 선언하는 경우 해당 구조체 자체가 바뀔 수 없기 때문에 아무리 해당 프로퍼티가 변수(`var`)로 선언되어 있다 하더라도 변경이 되지 않습니다.

`mutating` 메서드를 구현하는 경우 메서드가 끝날 때 변경사항을 원래의 프로퍼티에 덮어씌우게 됩니다. 공식문서에서는 메서드가, 프로퍼티 뿐 아니라, 완전히 새로운 인스턴스를 암시적인 `self` 프로퍼티에 할당하여 기존의 인스턴스를 아예 새로운 인스턴스로 바꿀 수도 있다고 안내하고 있습니다.

2024-01-31 11:49 UTC, yim2627 commented on BankManager.swift
> +    private let banker: Banker = Banker()
추상화를 활용하여 어떤 은행원이든(물론 제한을 걸 수 있습니다) 올 수 있도록 해야 확장 및 테스트에 용이한 구조가 될 것 같다고 말씀드린 것이였습니다. 다만 이번 스텝이 구현 요건이 아니므로 참고만 해주시면 될 것 같아요.

2024-01-31 11:51 UTC, yim2627 commented on BankManager.swift
> +    mutating func main() {
start 라는 메서드 이름을 main으로 바꾸는 것보단 업무 마감 프린트를 분리하거나, startBankingProcess 메서드가 완료되었을 실행되는 핸들러로 넣어준다면 더 단일 책임적이고, 가독성 좋은 코드가 될 것 같은데, 어떻게 생각하시나요?

2024-01-31 11:53 UTC, yim2627 commented on BankManager.swift
> +            DispatchQueue.global().sync {
👍👍 
async와 sync의 차이, global과 main 스레드의 차이는 다음 스텝에서 질문드리겠습니다. 이전까지 공부해보심 좋을 것 같아요!

2024-02-01 00:22 UTC, eensungkim commented on BankManager.swift
> +    private let banker: Banker = Banker()
아하 이해했습니다.
프로토콜을 활용해서 해당 프로토콜을 준수하는 타입이라면 다 받을 수 있도록 만들어야 한다는 부분이 아닐까 같이 고민했었거든요.
아마 구현을 하게 된다면 프로토콜을 활용할 것 같습니다!

2024-02-01 00:24 UTC, eensungkim commented on BankManager.swift
> +    mutating func main() {
completionHandler 로 넣어주면 더 깔끔할 것 같습니다!

2024-02-01 06:47 UTC, yim2627 approved these changes
lgtm 🤩

2024-02-01 06:47 UTC, merged