은행 창구 관리 앱 [STEP 2] Yuni, Paul
tasty-code/ios-bank-manager pull request #77
Opened 2024-01-30 07:13 UTC by earths-voluble

안녕하세요 마이노(@Mino777)! 유니(@Jin0Yun), 폴(@earths-voluble) 조의 은행 창구 관리 앱 프로젝트 Step 2 PR입니다! 잘 부탁드리겠습니다!
***
📦BankManagerConsoleApp  
 ┣ 📂Bank  
 ┃ ┣ 📜BankManager.swift  
 ┃ ┣ 📜BankMessage.swift  
 ┃ ┣ 📜Banker.swift  
 ┃ ┗ 📜Customer.swift  
 ┣ 📂DataStructure  
 ┃ ┣ 📜LinkedList.swift  
 ┃ ┣ 📜Node.swift  
 ┃ ┗ 📜Queue.swift  
 ┗ 📜main.swift

## 고민한 부분
- **Switch문에 대해**
`main`에서 `bankManager`객체의 `openBank`메서드를 통해 초기 입력을 받을 때, Switch문을 사용했습니다만, 객체지향 원칙을 위반할 소지가 많은 문법이라고 들었습니다. 그래서 대안으로 딕셔너리를 활용하는 방법을 찾았지만 현재 시점에서 Switch문에 비해 정말로 크게 이점이 있는지 와닿지가 않아서 사용하지 못했습니다.
- **Banker와 BankManager 클래스의 기능 나누기**
`Banker`와 `BankerManager`의 영역을 어떻게 나눠줄지 고민이 많았습니다. Step2의 명세만이라면 크게 고민하지 않았겠지만, Step3의 구현사항으로 은행원을 여럿 두어야 한다는 것을 알게 되면서, enqueue및 dequeue기능을 다루는 클래스와 그렇지 않은 클래스로 나눠야 하는지도 고민했습니다. 하지만 소요 시간을 측정한다거나 count를 하는 데 있어서 다른 메서드와도 엮여 있는 부분이 있어서 쉽사리 분리할 수 없었습니다.
- **더 개선할 부분?**
Step2의 명세를 구현하는데는 오랜 시간이 걸리지 않았지만, 왜인지 모르게 부족하다는 느낌이 들었습니다. 너무 추상적이지만, 전체적인 구조라거나 의존성 혹은 프로토콜 등을 활용해서 앱의 구조를 더 명쾌하게 만들 방법이 있을까요?

2024-01-31 14:08 UTC, Mino777 requested changes
안녕하세요!! 유니, 폴!

STEP 2 진행하시느라 정말 수고 많으셨습니다!!🥳

역할과 책임을 나누려고 고민하신 부분들이 보이네요💪
코멘트들 및 남겨주신 고민들에 대해 답변 남겨드립니다!

---------------------------------------------------------------------------------------

## 코멘트

### 고민했던점

> Switch문에 대해

넵 저도 지금 케이스같은 경우엔 굳이 딕셔너리를 활용해야될 이유는 모르겠습니다ㅎㅎ
그리고 Switch문의 경우 case가 변할일이 정말 많거나, 해당 enum 타입 하나를 정말 많은 곳에서 사용하지 않는 이상 개인적으로 객체지향 원칙을 위반하니까 Switch 문은 쓰면 안좋아! 라는 부분은 크게 동의하지 못하는 편입니다ㅎㅎ 애초에 저런 상황에 Switch 문을 사용한다는거 자체가 설계단 부터 잘못됐다고 생각하기도 하구요! (물론 팀에서 Switch문 대신 Strategy패턴 + 딕셔너리 등으로 다 대체해서 사용하자! 라고 결정된다면 당연히 팀에 맞추는것이 맞습니다!)
결론적으로는 정답은 없습니다ㅎㅎ 본인, 본인 팀과 의사결정만 잘해서 적재적소에 알맞은 방법을 정하고 지키기만 하면 아무 문제 없습니다!

> Banker와 BankManager 클래스의 기능 나누기

코드단에서도 코멘트를 남겨놓았습니다!
일단 저라면 Bank 객체를 하나더 만들어서
BankManager -> 프로그램적으로 필요한 의존성들을 외부로부터 주입받고, 입력을 받고, 시작하는 루트 역할
Bank -> Banker 객체를 가지고 전반적인 은행 운영 역할(오픈, 고객생성, 은행원에게 고객할당, 클로즈)
Banker -> 오로지 Task에만 집중해서 전달받은 Task 수행, Task 종료 후 걸린 시간 전달
이정도로 나눠보면 좋을 것 같습니다!

> 더 개선할 부분?

음 해당 고민이 들땐 말씀해주신 의존성, 프로토콜을 통해서 각 객체들, 타입들에 역할과 책임을 정말 극한으로 나눠보시는 경험을 해보시면 어느정도 해소가 될 것 같습니다.
정말 현실세계에 입각해서 자기가 생각하는 역할과 책임들을 최대한 세세하게 쭉 만들어보고, 그걸 코드로 옮기려고 해보시면 비록 그게 명쾌하지 않더라도, 명쾌하지 않는 부분들을 본인이 제일 잘알기 때문에 질문하기도 정말 쉬워집니다ㅎㅎ
그리고 저런 부분들을 하려다보면 자연스럽게 의존성주입, 프로토콜을 활용에 대한 고민도 덤으로 얻으실 수 있습니다💪

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +let bankManager = BankManager(banker: banker)
오우 의존성 주입 좋습니다👍👍

의존성 주입을 왜 해야하는지에 대해 설명해주세요!

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    var banker: Banker
지금 banker 프로퍼티가 public, 변수일 이유가 있을까요?! 

어떤 이유로 이렇게 정의하셨을까요?!

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +            BankMessage.menu.message()
print를 위한 타입을 정의해서 사용하시는 부분 좋습니다👍👍

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +            guard let choice = readLine() else { return }
이 부분도 따로 user의 input을 받는 메서드로 분리해서 에러 핸들링 까지 진행하면 좋겠네요!

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankMessage.swift
> +}
print문이 계속 중복되고있네요!
보통 이러한 메세지를 정의하고 전달하기 위한 enum 타입의 경우
enum 타입에선 print를 하고싶은 string 값만 정의해서 리턴해주는 책임을 가지고,
print를 하는 부분은 따로 정의해주는게 일반적입니다.

enum 타입에선 메시지만 반환해주고, 프로토콜의 기본구현을 활용해서 필요한 class에만 채택해서 print 하는 책임을 나눠봅시다!

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +
현재 Banker class의 역할이 많은 것 같아요!
객체지향적으로, 실생활에서 봤을 때 Banker는 오직 task 처리와 해당 task가 얼마나 걸렸는지 알려주는 역할만 하면 좋지 않을까요?
실질적으로 고객은 Bank에서 번호표를 뽑고 기다리기도 하구요!

Bank -> 오픈, 고객 생성, 클로즈
Banker -> task, task 시간 측정해서 은행에 알려주기
요정도로 나눠보면 좋을 것 같습니다💪

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +    }
재귀는 왠만하면 사용하지 않으시는게 좋습니다!

반복문으로 바꿔봅시다!💪

2024-01-31 14:08 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Queue.swift
> +
자료구조는 최대한 해당 자료구조에만 집중해서 순수하게 사용하는것이 좋습니다.

고객 수를 위한 프로퍼티인 것 같은데, 해당 프로퍼티는 Bank가 가지면 좋지 않을까요?

2024-02-01 05:03 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +
감사합니다!
Bank와 Banker로 역할분리 하였습니다 :) c804bd3

2024-02-01 05:04 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Queue.swift
> +
Bank가 customersCount를 가지고 있는게 좋을 것 같아 수정하였습니다!
수정사항: 8a6dd7b

2024-02-01 05:09 UTC, earths-voluble commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +    }
재귀를 추천하지 않으시는 이유가 궁금해서 찾아보았습니다!
재귀는 함수 안에서 함수의 호출이 반복되면서, 스택 메모리가 커지고, 스택을 구성하고 해제하는 과정의 오버헤드도 들어가면서 결과적으로 반복문에 비해서 성능적인 약점이 있다고 하네요. 앞으로는 이런 부분도 고려해서 사용해 보도록 하겠습니다!
반복문으로 변경하였습니다! ed17cdc

2024-02-01 05:18 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +let bankManager = BankManager(banker: banker)
클래스 내에서 다른 클래스를 인스턴스로 직접 생성할 경우 강한 의존성을 갖게됩니다. 이 경우 의존 클래스의 변경이 의존하는 클래스에 영향을 미치거나, 특정 클래스의 인스턴스 생성 방법이 변경될 경우 모든 의존 클래스가 영향을 받게됨으로 유지보수가 어려워집니다.
하지만 의존성 주입을 하면 객체간의 결합도를 낮춰주면서 의존 클래스가 변경 되더라도 주입되는 인스턴스를 생성하는 코드만 수정하면 되므로 유지보수에 용이하며 단일 책임원칙을 준수할 수 있습니다.

2024-02-01 05:26 UTC, earths-voluble commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +            guard let choice = readLine() else { return }
b0c2a73 에서 에러 핸들링 구현하였습니다! 감사합니다!

2024-02-01 05:28 UTC, Jin0Yun commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankMessage.swift
> +}
프로토콜로 필요한 class에서만 채택해서 사용할 수 있게 구현해보았습니다! 
수정사항: cd8424f

2024-02-01 05:29 UTC, earths-voluble commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    var banker: Banker
변수, 상수 여부와 접근제어! 신경썼어야 하는데, 처음에 별 생각 없이 변수로 정의해놓고 다시 안 본 것 같습니다 ㅜㅜ 조금 더 신경쓰면서 작성해보도록 하겠습니다!
a3f1768 에서 수정하였습니다😅

2024-02-01 13:31 UTC, Mino777 approved these changes
요청드린 부분들 모두 빠르게 수정해주셨네요!
잘 수정해주셔서 크게 드릴 코멘트는 없어보입니다👍

Step2 진행하시느라 고생많으셨습니다! 
Step3도 빠이팅입니다💪💪

2024-02-01 13:31 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +            let choice = getUserInput()
보통 호출 당하는 메서드가 아래 있는것이 코드 읽기가 더 편합니다ㅎㅎ
openBank() -> getUserInput() 순으로 호출 하는 메서드가 먼저 있으면 눈을 위에서 아래로 쭉쭉 읽을 수 있습니다👍

2024-02-01 13:31 UTC, merged