Step2
tasty-code/ios-bank-manager pull request #79
Opened 2024-01-30 12:45 UTC by hemil0102

# 안녕하세요, 코든! @ictechgy

L(@), Harry(@hemil0102)입니다. 
은행 창구 관리 앱 STEP2 PR 송부 드립니다.

바쁘신 와중에 리뷰를 해주셔서 감사드리며,
새벽 늦게 리뷰해주시는데 너무 무리하지 마시고, 
건강 잘 챙기시길 바랍니다. 🔥🔥🔥💪🏻

# 🔍 What is this PR?

step2-1 Queue를 활용한 은행 대기열 구현 
step2-2 타입 추상화 및 일반화

# 📝 PR Point
1. 은행 구현에 필요한 각 객체의 역할, 책임 및 협력 구조
![Screenshot 2024-01-30 at 9 36 27 PM](https://github.com/tasty-code/ios-bank-manager/assets/83139316/a87612a5-fc75-4a87-9bad-7adecc42fd73)

2. BankManager struct 타입 구현(위 그림에서 은행)
 - 역할
     - 콘솔창에 메뉴가 띄어지고 해당 메뉴의 해당하는 번호를 입력하면 그에 따른 동작을 진행합니다.
 - 책임
     - `operate()`: 콘솔창에 메뉴를 보여주고 입력값을 받습니다.
     - `executeBankingOperation()`: 입력한 번호에 따라 로직을 처리합니다.
     - `selectBankingOperation()`: 메뉴에 해당하지 않은 번호를 입력시 에러를 던져줍니다. 
     - `printMenuOfBank()`: `executeBankingOperation()`로직에서 메뉴를 출력합니다.
     - `printCloseMenu()`: 모든 고객들의 업무가 끝나면 업무를 처리한 총 고객의 수와 총 업무시간을 출력합니다.
     - `createEmployee()`: 일처리를 할 직원을 생성합니다.
     - `handleCustomerTasks()`: 직원이 업무를 처리를 시작하고 업무를 종료합니다. 
 
3. CustomerManager struct 타입 구현(위 그림에서 고객 매니저)
- 역할
     - 은행에 방문할 `고객을 생성`해주며 방문한 고객을 티켓머신을 통해 `대기열에 등록`합니다.
     - BankManager에 집중된 `책임을 분산하기 위해` 고객 관련 항목을 분리하였습니다. 
- 책임 
    - `createCustomer()`: 고객(Customer)를 10~30명을 생성합니다. 
    - `registerCustomer()`: 생성된 고객을 ticketMachined을 통해 대기열에 등록합니다. 
    - `resetCustomer()`: 은행 개점을 할 때마다 생성된 고객과 대기열을 초기화 합니다. 

4. Customer struct 타입 구현
- 역할
    - 은행에 방문할 고객이며 `티켓 번호`와 `처리할 업무 속성`을 지닙니다.
    - 업무는 STEP2에서 `업무` 한가지 일만 지닙니다. (이후 대출, 예금 분리 예정)

5. Employee struct 타입 구현(위 그림에서 은행원)
- 역할
    - 은행에 방문한 고객의 업무를 처리합니다. STEP2에서는 `업무` 한가지 일만 지닙니다. 
- 책임
    - `handleCustomerTasks()` 고객 업무 처리, 대기열에 등록된 고객의 업무를 `task`에 기반하여 처리합니다. 

6. 에러 핸들링
     - `selectBankingOperation()`에서 메뉴에 해당하지 않는 번호 및 문자가 입력될 시 해당 에러를 던져주고, `operate()`에서 해당 에러를 처리합니다.

# 🤔 고민한 부분
1. 객체의 역할, 책임 및 협력
- 코드를 작성하기 전에 그림을 그리며 리얼월드 은행을 생각하며 객체들의 역할, 책임 및 협력에 관한 아이디어를 먼저 구상하였습니다. 다만 그림은 코드 작성 도중에 변경될 수 있어 러프하게 작성하였고, 실제로 코드를 작성하면서 수정된 아이디어가 많았지만 결과적으로 초기 구상에서 크게 벗어나지 않았습니다. 역할, 책임 및 협력을 기반으로 집중하면서 하다보니 확실히 조금은 더 클린한 코드가 나온 것 같지만 아직 가야할 길이 먼 것 같습니다. 관련하여서 추가로 생각해볼 것이 있다면 언제든 조언 부탁드리겠습니다. 

❓질문
1. BankManager역할 분리, CustomerManger에 대해
BankManger에 모든 것을 구현하다보니 갖게되는 속성이 많아지는 만큼 책임도 많아졌습니다. 그리하여 역할 및 책임을 분리해주었는데... 고객을 대기열에 올리는 역할이 CustomerManager보다는 BankManager에서 해주는게 맞지 않을까 생각은 듭니다. 이 부분에 대해 역할 분리가 현재로 충분할지 아니면 조금 더 다른 관점으로 생각해보면 좋을지 궁금합니다. 

2. struct로 구현된 Queue 타입
현재 Queue가 struct로 구현되어 있기에 나중에 동시성을 구현할 때 다수의 은행원이 같은 곳을 바라보게 하려면 class가 되어서 참조 형식으로 바꿔줘야하지 않을지 고민이 듭니다. 구조체로도 STEP3를 할 수 있는걸까요? 안되는 것은 없을 것 같지만 어떤 타입으로 가져가는게 좋을지 궁금합니다. 

3. 동시성 구현
- 현재 짝꿍과 동시성 기본 개념에 대해 학습을 하고 있습니다. 코드 상에 어떻게 구현해보면 좋을지를 생각해보는데 처음 접하는 개념이라 현재 작성된 코드가 동시성 적용이 가능한 구조인지를 잘 모르겠습니다. STEP3 동시성을 구현해보려고 은행원이 업무를 처리하니, 업무 기준으로 우선 일을 나누고 디스패치에 넣어주면 되지 않을까 하면서 구현을 했는데, 뭔가 은행 업무 종료 문구가 먼저 나온 이후에 고객 업무를 처리하거나, 뒤죽박죽 뒤엉키고 있습니다. 기본 개념을 조금 더 확실히 이해하려고 노력할텐데, 어떤 방향으로 생각해보면 좋을지 조언 부탁드립니다. 

# 🖥️ 콘솔 구동 화면

### **은행개점**
![1](https://github.com/tasty-code/ios-bank-manager/assets/83139316/6456cb5e-4b79-4f2b-8513-8bbc94a41cfa)
### **업무종료**
![2](https://github.com/tasty-code/ios-bank-manager/assets/83139316/a0e88800-3291-4239-9d44-b1776b11619e)
### **오입력시**
![3](https://github.com/tasty-code/ios-bank-manager/assets/83139316/b9218831-70dc-462d-95ab-58460f8c405a)

# 감사합니다.🙏🏻

2024-01-31 19:29 UTC, ictechgy requested changes
안녕하세요 @LeeSe0ngYe0n , @hemil0102 !!!    
STEP2 구현하시느라 고생하셨습니다!!!!  🎉       

PR 메시지 매번 상세하게 써주셔서 너무 감사해요!
상세 코멘트는 라인별로 따로 남겨두었구요! 질문주신 사항들 답변드려볼게요

<br/>

## 고민했다고 해주신 부분
> 1. 객체의 역할, 책임 및 협력

많은 고민을 하신 것이 느껴졌는데요! (그림도  👍👍!!!)  다음의 사항을 말씀드려보고 싶어요
- 사용자 입력을 받는 것이 꼭 은행이어야 할까요? 콘솔 입력을 받고 객체간의 협력을 시작시킬 별도의 타입이 있는건 어떨까요?
  - 지금은 은행 타입이 생성되자마자 open된 상태인데 사용자가 1번을 입력 한 순간 오픈되도록 만들 수도 있을 것 같네요!
- 현재 형태는 Employee가 직접 Queue에서 하나씩 값을 가져와서 처리하는 식인데 상위에서 Queue를 반복하면서 일을 분배시키는 형태도 가능할 것 같아요! (이건 관점의 차이일 뿐인것 같아서 참고만 해주세요!)
- 은행원은 고객과 상호작용해야하는데 그러한 요소가 지금은 없는 것 같아요! Customer가 가질 메소드는 없는걸까요? 

<br/>

## 질문주신 내용들
> 1. BankManager역할 분리, CustomerManger에 대해

제가 봤을 때에는 지금 형태도 좋은 것 같아요! 말씀하신 것처럼 대기열과 대기열에 올리는 것들 등을 BankManager가 가져갈수도 있지만 BankManager가 비대해질 수도 있을 것 같아보이네요!   

<br/>

> 2. struct로 구현된 Queue 타입

class가 고민이시군요! 여기에는 다른 질문을 드려보고 싶어요!
- Manager 타입들은 꼭 Struct여야할까요? Queue는 Struct로 두고 Manager들을 Class로 가져가면 어떻게 될까요? 그리고 이렇게 한다면 메모리 구조는 어떠한 형태가 될까요?

<br/>

> 3. 동시성 구현

은행을 닫기 전 모든 작업을 기다릴 수 있는 방법을 찾아보시면 좋을 것 같은데요! 혹시 DispatchGroup에 대해 학습하셨을까요?    
더불어 은행원이라는 '유한한 자원'을 어떻게 분배하여 니즈가 다른 손님들을 가능한한 한번에 처리할 수 있을지 고민해보시면 좋을 것 같습니다.
-> 은행원 배열이나 큐는 꼭 하나여야 할까요? 은행원을 담는 자료구조는 큐가 되면 안될까요? 등등..    
(도움이 되셨을지 모르겠네요..! 😅)   

혹시나 너무 어렵다 싶으면 다시 한번 말씀 주세요!      

현재 PR은 몇가지 함수명만 수정해주시면 머지하도록 할게요!   
화이팅입니다~!!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +struct BankManager {
BankManager나 다른 타입들을 struct로 만드셨더라구요!   
class가 아닌 struct를 선택하신 이유가 있을까요??

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private var customerManager = CustomerManager()
다른 프로퍼티들은 타입 어노테이션이 있는데 이 프로퍼티는 없네요! 다른 이유가 있을까요??

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private var totalTaskTime: Double { Double(customerManager.customers.count * 700) / 1000 }
이 부분은 나중에 실제 시간을 측정하는 형태로 바꿔봐도 좋을 것 같습니다!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +            customerManager.resetCustomer()
매 반복마다 특정 환경을 리셋해주신 점 좋습니다 ㅎㅎ 👍

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +                let input = try selectBankingOperation()
사용자의 입력을 받는다는 점에서 좀 더 직관적인 함수명을 가져볼 수 있을 것 같은데 어떻게 생각하시나요?   
이를테면 `receive ~ Input` 등과 같이요!   

아니면 `~ selectedByUser` 등과 같이 지어볼 수도 있을 것 같아요.

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +                print(error.localizedDescription)
👍👍 localizedDescription을 쓰셨네요!!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private mutating func executeBankingOperation(of input: String) {
접근제어도 함수명도 인자레이블도 모두 잘 지어주셨어요!! 😆✨👍

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +            break
함수 하나를 깔끔하게 잘 구성해주신 것 같네요!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +        }
두 guard는 하나로 합쳐볼 수도 있을 것 같은데 별도로 분리하신 이유가 있을까요?

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private func selectBankingOperation() throws -> String {
유효하지 않은 상태를 처리하는 방법에는 여러가지가 있을텐데 (이를테면 nil을 반환하고 이를 에러로 인식한다던지) throws 형태를 사용하신 이유가 궁금합니다!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private func printCloseMenu() {
다른 네이밍은 어떨까요? '닫는 메뉴를 출력한다'처럼 읽히는 것 같아서요!    
현재 출력하고자 하는 문구는 메뉴가 아니니 바꿔보면 좋을 것 같습니다~

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private mutating func handleCustomerTasks() {
이 함수는 꼭 mutating이어야 할까요?? 한번 살펴보시면 좋을 것 같습니다!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Controller/CustomerManager.swift
> +    }
접근제어도 잘 설정해주셨고 함수들도 깔끔하게 잘 분리해서 구현해주셨습니다! 😆👍

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Enum/InputError.swift
> +        }
커스텀 에러를 이용해주신 점 좋습니다! 👏😄

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Model/Employee.swift
> +                usleep(700000)
usleep을 쓰셨군요! 👀

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Queue/LinkedList.swift
> +    var isEmpty: Bool { head == nil }
잘 바꿔주셨습니다! 😄

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Queue/LinkedList.swift
> +        var foundLocation = 0
변수명 잘 수정해주셨습니다~!!    
함수명도 '노드의 위치를 돌려받을 수 있다' 라고  기대할만한 네이밍이면 좋을 것 같습니다!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/Queue/Queue.swift
> +    var isEmpty: Bool { linkedList.isEmpty }
잘 수정해주셨습니다~!!  👍

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerLinkedListTests.swift
> +final class BankMangerLinkedListTests: XCTestCase {
별도의 파일로 분리해주셨네요~!! 🙌

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerLinkedListTests.swift
> +        let result = sutLinkedTest.isData(with: nil)
nil을 검색하는 형태인데 동일한 input을 검색하는게 적절하지 않을까 싶어요!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerLinkedListTests.swift
> +        XCTAssertEqual(expectedResult, result)
잘 만들어주셨습니다!!!  👍

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerQueueTests.swift
> +        sut.enqueue(with: input)
잘 옮겨주셨네요!!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerQueueTests.swift
> +        XCTAssertEqual(expectedResult, result)
쭉 보고 있는데 다 잘 바꿔주신것 같아요..!!!!

2024-01-31 19:29 UTC, ictechgy commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerQueueTests.swift
> -    }
테스트 코드 작성하시느라 고생하셨습니다! 😊

2024-02-01 01:34 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +            customerManager.resetCustomer()
감사합니다. 고객의 무한 증식을 막았어야만 했어요. 🤣

2024-02-01 10:18 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +struct BankManager {
이유는 아래와 같습니다. 

1. 애플 공식 문서에서 뭘 사용할지 모르겠으면 default로 struct를 사용하라고 하여서 사용한 것이 있습니다. 
2. 클래스의 상속 기능을 사용하지 않을 것 같습니다. 
3. 과정에서 POP를 배웠는데 구조체에 프로토콜을 채택하여서 기본 구현으로 무언가를 해본게 생각나서, 어떤 일부 기능들을 프로토콜로 구현해서 채택해보는 연습을 해보고 싶었습니다. 
4. 데이터 관점에서 보면 아직 서버 연동은 잘은 모르지만 문서에서 identity 라는 용어가 나오면서 클래스와 구조체 사용을 나누는데, 이게 저희 케이스에 해당되는지는 않는 것 같습니다. 

메모리 관점을 언급해주셔서 남겨보면, 
struct는 값타입, class는 참조타입으로 각각 스택과 힙 영역에 데이터를 할당하게 되는데... 정적과 동적이라는 큰 차이가 있습니다. 
정적은 타입의 크기가 정해져서 접근이 빠른 대신에 항상 일정한 크기를 할당해야해서 메모리 공간 활용이 정적보다는 많이 사용하며, 
동적은 타입의 크기가 가변적이어서 조회를 하면서 공간을 확인하기때문에 속도는 느리나 가변적으로 데이터를 할당하므로 공간을 아껴쓸 수 있다는 이점이 있습니다. 

그리고 성능으로 보면 애플 동영상에서는 참조 카운트를 성능을 위해서 줄이라고 가이드를 하고 있는데, 다만 구조체 내에 클래스가 포함되어 있다면, 구조체를 복사할 시 참조도 같이 복사되므로 참조 카운트가 늘어나 성능이 좋지 않다고 가이드를 하고 있습니다. 

이런 여러가지 경우를 고려해보면 현재 저희의 BankManager나 Queue는 사실상 구조체이긴 하지만 Node가 클래스로 포함되어 있어서, 어쩌면 위에 참조가 복사되는 경우에 해당되지 않을까 싶기도한데요. 또 그렇다고 Class로 BankManger를 만들어줘도 어차피 참조 안에 참조가 있는거라 오히려 구조체 안에 클래스가 더 나은거 아닌가? 이 부분은 아직 제대로된 개념이 잡히지 않아서 쉽게 답변을 드릴 수 없는 것 같습니다. 이렇게 보는 관점이 맞는 것인지 잘 모르겠어서 혹시라도 어떤 공부를 하면 좋을지 알려주시면 감사드리겠습니다! 

현재로써는 프로토콜 기본 구현을 사용해보고 싶고 상속을 사용하지 않으며 참조를 줄여보고 싶어서 구조체를 채택했습니다. 
만약에 잘못 생각하고 있는 것이라면 답변 부탁드리겠습니다.

2024-02-01 12:29 UTC, LeeSe0ngYe0n commented
## 고민했다고 해주신 부분
1. 객체의 역할, 책임 및 협력
 
많은 고민을 하신 것이 느껴졌는데요! (그림도 👍👍!!!) 다음의 사항을 말씀드려보고 싶어요
 
* 사용자 입력을 받는 것이 꼭 은행이어야 할까요? 콘솔 입력을 받고 객체간의 협력을 시작시킬 별도의 타입이 있는건 어떨까요?
>  코든의 말씀대로 새로운 타입을 정의한 후 사용자에게 보일 메뉴와 사용자에게 입력값만 받을 수 있는 타입을 구현하는 것을 STEP3를 하면서 고려해보겠습니다!
 * 지금은 은행 타입이 생성되자마자 open된 상태인데 사용자가 1번을 입력 한 순간 오픈되도록 만들 수도 있을 것 같네요!
 > 위에 말씀드린 새로운 타입 구현하면서 같이 고려해볼 사항이라고 생각합니다!
 * 현재 형태는 Employee가 직접 Queue에서 하나씩 값을 가져와서 처리하는 식인데 상위에서 Queue를 반복하면서 일을 분배시키는 형태도 가능할 것 같아요! (이건 관점의 차이일 뿐인것 같아서 참고만 해주세요!)
 > Employee가 Queue에서 하나씩 값을 가져와 처리하는 방식보다는 코든이 말씀해 주신대로 상위 모듈에서 해당 업무를 미리 분류 후 해당 업무를 처리하는 Employee에게 전달하여 Employee는 전달받은 일만 처리하는 것이 향후 동시성 작업 단위를 분류하는것에 도움이 될거 같습니다!
* 은행원은 고객과 상호작용해야하는데 그러한 요소가 지금은 없는 것 같아요! Customer가 가질 메소드는 없는걸까요?
> STEP3를 진행하면서 고객에 책임추가를 고려해보겠습니다!
> 
> 
## 질문주신 내용들
1. BankManager역할 분리, CustomerManger에 대해
제가 봤을 때에는 지금 형태도 좋은 것 같아요! 말씀하신 것처럼 대기열과 대기열에 올리는 것들 등을 BankManager가 가져갈수도 있지만 BankManager가 비대해질 수도 있을 것 같아보이네요!
>  감사합니다!
> 
2. struct로 구현된 Queue 타입
class가 고민이시군요! 여기에는 다른 질문을 드려보고 싶어요!
* Manager 타입들은 꼭 Struct여야할까요? Queue는 Struct로 두고 Manager들을 Class로 가져가면 어떻게 될까요? 그리고 이렇게 한다면 메모리 구조는 어떠한 형태가 될까요?
> 아래 코멘트에 답변을 드렸는데 클래스가 되었을 때에는 상속이 가능해질거 같습니다! 더 상세한 내용은 아래 코멘트 확인부탁드립니다!
> 
> > 3. 동시성 구현
> 
> 은행을 닫기 전 모든 작업을 기다릴 수 있는 방법을 찾아보시면 좋을 것 같은데요! 혹시 DispatchGroup에 대해 학습하셨을까요? 더불어 은행원이라는 '유한한 자원'을 어떻게 분배하여 니즈가 다른 손님들을 가능한한 한번에 처리할 수 있을지 고민해보시면 좋을 것 같습니다. -> 은행원 배열이나 큐는 꼭 하나여야 할까요? 은행원을 담는 자료구조는 큐가 되면 안될까요? 등등.. (도움이 되셨을지 모르겠네요..! 😅)
> 이 부분은 현재 공부를 하면서 확인했습니다. 은행원을 담는 자료구조가 큐로 구현하는 것은 아직 머릿속에 잘 안그려집니다... 다만 STEP3를 하면서 코드를 작성하면서 고려해보겠습니다!

2024-02-01 12:31 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private var customerManager = CustomerManager()
으엇 죄송합니다. 저는 생략하는 편이고 엘은 남겨주는 편인데 같이 반영하면서 통일이 되지 않아 저희 팀은 타입을 가급적 명시해주는 것으로 컨벤션을 정했습니다. 

수정사항: c890c85fdea5cb0e63dc595161172ed0af48a18b

2024-02-01 12:32 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/Controller/BankManager.swift
> +        }
두 guard문을 하나로 쓸 생각을 하지 못했습니다..ㅠ
코든이 주신 리뷰 후 하나로 합쳤습니다!!

수정사항: c890c85fdea5cb0e63dc595161172ed0af48a18b

2024-02-01 12:32 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private var totalTaskTime: Double { Double(customerManager.customers.count * 700) / 1000 }
감사합니다. `STEP3`에서 동시성이 적용되면 시간 계산을 어떻게 해야할지 아직은 감이 안오는데 말씀해주신 내용 반영해보겠습니다.

2024-02-01 12:33 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +                let input = try selectBankingOperation()
감사합니다. 이 부분은 애플 문서 가이드를 보니 어떤 리턴 값을 가지면서 다른 변수로 값이 할당되는 용도로 사용되는 경우는 동사에 ed 형식으로 네이밍 하는 것을 권장한다고 하여서 수정하였습니다. 

수정사항: c890c85fdea5cb0e63dc595161172ed0af48a18b

2024-02-01 12:35 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private func selectBankingOperation() throws -> String {
처음 해당 코드를 구현 시 조건에 만족하지 않는다면 프린트문을 통해 콘솔에 문구를 바로 출력해주는 코드로 구현 하였지만 에러 핸들링 연습 목적을 위해 사용 해보았습니다!

2024-02-01 12:38 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private mutating func handleCustomerTasks() {
감사합니다. 이 부분은 코드를 작성하다가 mutating이 에러가 발생해서 적용을 해주었는데, 코드 수정 작업을 하다가 남겨진 부분으로 mutating을 삭제하였습니다.

2024-02-01 12:38 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private func printCloseMenu() {
해당 함수는 업무가 마감된 후 업무를 처리한 총 고객의 수와 총 업무시간을 출력해주는 함수이기 때문에 함수명을 `reportDeadlineSummary`로 변경해주었습니다!

2024-02-01 12:40 UTC, hemil0102 commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerLinkedListTests.swift
> +        let result = sutLinkedTest.isData(with: nil)
감사합니다. 해당 부분을 다시 살펴보니 노드가 생성되고 삭제된 이후에 값이 없는 것을 체크하므로 말씀해주신 검증 방식이 타당하다고 생각하여 반영해주었습니다. 

수정사항: c890c85fdea5cb0e63dc595161172ed0af48a18b

2024-02-01 12:43 UTC, LeeSe0ngYe0n commented on BankManagerConsoleApp/Queue/LinkedList.swift
> +        var foundLocation = 0
해당 함수는 검색한 노드의 위치를 알려주고 있는 함수이기 때문에 `searchNodeLocation`으로 함수명을 변경하였습니다!

2024-02-01 18:23 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +struct BankManager {
좋은 답변 감사합니다~!   
제 생각이지만 어떤걸 명확히 써야한다라는 특정한 기준은 없을 것 같아요! (물론 성능적으로 좋은 방향을 항상 선택하면 좋겠지만 그 선택에는 어떤 제한이나 제약이 같이 따라오기도 하는 것 같아요)       

이럴 때 저는 참조관계를 직접 그려보고 어떤게 더 나을지 선택하고는 하는데요!    

현재 상황을 봤을 때 다음의 문제때문에 class를 고려한다고 해주셨었어요   
- 여러 은행원들이 하나의 큐를 참조해야하지 않을까?    
  - (지금 상태에서는) 그러면 은행원(쓰레드)들이 하나의 큐를 쓰게 되는 것이고 그러면 큐 인스턴스 복사가 일어나는데 -> 노드들은 class이므로 reference count가 너무 많이 생기지 않을까?   
➡️ 이런 경우까지 오게 되면 사실 Queue를 class로 두는게 맞을 수도 있어요.    

하지만 다르게 생각해보면 어떨까요? 
- Customer Queue는 꼭 하나여야할까요? 
- 각 업무별로 Customer Queue가 있다면 은행원(쓰레드)들은 자신들만의 개별 Queue를 가질 수 있을 것이고 이 경우에는 reference count 에 대한 overhead가 적지 않을까요?    

이 부분들은 선택하고 구현하기 나름일 것 같습니다..!     
(사실 저는 은행원도 큐에 넣어서 만들 수 있을 것 같다고 생각해요!)

2024-02-01 18:28 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    private func selectBankingOperation() throws -> String {
나중에 Result 타입에 대해서도 공부해보시면 좋을 것 같습니다~!   
doc: https://developer.apple.com/documentation/swift/result

2024-02-01 18:30 UTC, ictechgy commented on BankManagerConsoleApp/Model/Employee.swift
> +                usleep(700000)
사실 저는 Thread.sleep을 쓰는 편이라 말씀드린 거였습니다 ㅎㅎ 😆

2024-02-01 18:37 UTC, ictechgy approved these changes
안녕하세요 @hemil0102 , @LeeSe0ngYe0n    
리뷰 반영하시느라 고생하셨습니다!! 🎉😄    

STEP2에서 요구하는 조건들은 다 만족시켜주신 것 같아서 머지하도록 할게요!       
별도로 제가 위에 추가 코멘트들을 남겨두었는데요. 확인 부탁드리겠습니다~~   

STEP3 화이팅입니다!!!!

2024-02-01 18:38 UTC, merged