[STEP2] 우노, 도도
tasty-code/ios-bank-manager pull request #8
Opened 2022-10-18 07:39 UTC by eunho8713

## 구현 내용
- BankManager 타입 구현 : `workStart` 메서드  -> 업무 처리 

- Bank 타입 구현 : `choiceMenu` 메서드 -> 은행 메뉴 선택 후 그에 따른 동작 처리

- Client 타입 구현 : `randomClientNumber` 메서드 -> 랜덤으로 고색수 생성

## 조언을 얻고 싶은 내용
![스크린샷 2022-10-18 오후 4 38 33](https://user-images.githubusercontent.com/105549066/196366866-1a7e9639-72b0-4dea-9f31-139b3ef8b907.png)
콘솔앱을 구현할때 main.swift 파일에서 이런식으로 사용해도 되는지 궁금합니다!

2022-10-18 08:11 UTC, jaemuYeo requested changes
스텝2도 고생많았습니다 👏
전반적인 구현에는 문제가 없지만 메뉴 입력을 1또는 2 이외의 값을 눌렀을때에
앱이 강제종료되는 이슈가 있었어요!!
다음 PR요청때 한번 수정해보면 좋을 것같습니다 ㅎㅎ

제가 생각하는 이번 타입설계에서의 큰 틀은
손님, 은행, 은행원 입니다.
어떤 타입에 어떤 속성과 행동들이 있으면 좋을지 고민해보며
코멘트를 반영해보면 좋을 것같아요!!
화이팅입니다 💪

2022-10-18 08:11 UTC, jaemuYeo commented on BankManager.swift
> +    func workStart() {
workStart메서드가 너무 많은 역할을 담당하고있네요!!
메서드당 기능을 하나씩 쪼개서 호출해보면 좋을 것 같아요!

2022-10-18 08:11 UTC, jaemuYeo commented on BankManager.swift
> +        let clientList = Queue<Int>()
clientList보다는 clientQueue가 더 적절하다 생각합니다!

2022-10-18 08:11 UTC, jaemuYeo commented on BankManager.swift
> +        for client in 1...clientNumber {
1이라는 매직넘버를 어떻게 처리해보면 좋을까요? 🤔

2022-10-18 08:11 UTC, jaemuYeo commented on BankManager.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(clientNumber)명 이며, 총 업무시간은 \(strTotalWorkTime)초입니다.")
실행예시와 띄어쓰기를 맞춰주세요~

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +class Bank {
은행이라는 객체는 메뉴를 선택하는 역할만 있나요?

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        if let inputMenu = Int(readLine()!) {
오우!! 강제추출은 금지입니다!

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                return
메뉴는 1또는 2인데 그 외의 숫자나 문자를 넣어도 종료가 되고있어요.
1 또는 2가 아닐때 다시 앱을 실행해주어야 할 것같습니다!

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +struct Client {
고객이라는 타입에는 랜덤으로 고객번호를 생성하는 역할만이 있나요?

고객은 웨이팅번호라는 속성을 가지고있고
고객을 받는 주최자는 은행이라고 생각합니다
어떻게 설계해보면 좋을까요?

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    func randomClientNumber() -> Int {
함수의 네이밍은 어떻게 지어야하나요!?

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        let clientNumber = Int.random(in: 10...30)
10과 30이라는 매직넘버는 어떻게 처리해볼 수 있을까요?

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +menu.choiceMenu()
네 됩니다!! 🙂

2022-10-18 08:11 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +
이런 빈 개행들도 커밋할때 기록에 남는답니다!
저는 빈곳은 항상 지워두는 편이예요 ㅎㅎ

2022-10-19 01:00 UTC, dddowon commented on BankManager.swift
> +    func workStart() {
마감처리를 하는 `workLast()` 기능을 만들면 좋을 것 같네여

2022-10-19 01:06 UTC, eunho8713 commented on BankManager.swift
> +        let clientList = Queue<Int>()
큐를 사용하는것이니까 그게 더 적절한것 같네요 반영하겠습니다!

2022-10-19 01:07 UTC, dddowon commented on BankManager.swift
> +        for client in 1...clientNumber {
넵 1은 firstClient clientNumber도 lastClient로 처리해주었습니다

2022-10-19 01:07 UTC, eunho8713 commented on BankManager.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(clientNumber)명 이며, 총 업무시간은 \(strTotalWorkTime)초입니다.")
넵

2022-10-19 01:10 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                return
넵 수정했습니다!

2022-10-19 01:11 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        if let inputMenu = Int(readLine()!) {
if let에 let을 사용해 Int형으로 묶어주는 안전한 방법을 사용해서 해결해봤습니다!

2022-10-19 01:23 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    func randomClientNumber() -> Int {
앞에 generate와 같은 동사를 붙여주는게 좋을것 같네요!

2022-10-19 01:25 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        let clientNumber = Int.random(in: 10...30)
상수로 만들어 처리해줬습니다

2022-10-19 01:26 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +
넵 의미없는 12번 부터의 개행을 말씀하시는건가여??

2022-10-19 01:26 UTC, eunho8713 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +menu.choiceMenu()
넵

2022-10-19 02:55 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +
넵!

2022-10-20 07:29 UTC, jaemuYeo requested changes
현재 Bank타입과 BankManager 타입간에 의존도가 너무 강하다고 생각합니다 🤔
두 타입간의 차이점을 잘 모르겠어요!
Bank를 BankManager라 생각하고 직원 타입을 만들어보면 어떨까요??

2022-10-20 07:29 UTC, jaemuYeo commented on BankManager.swift
> +struct BankManager {
도도와 우노가 생각한 BankManager는 `은행 직원`인가요???

2022-10-20 07:29 UTC, jaemuYeo commented on BankManager.swift
> +    func work() {
해당 메서드를 중첩함수로 작성하신 이유가 궁금합니다!!
중첩함수의 특징은 어떤 것이 있나요??

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    var bankManager: Int = 1
이 변수는 어디에 활용되나요?

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let waitingNumberQueue = Queue<Int>()
아래 두 상수는 한 메서드 안에서 사용되는데 Bank의 프로퍼티로 선언한 이유가 있나요??

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let clientNumber = Client().generateClientRandomNumber()
저는 보통
```swift
private let client = Client()

client. generateClientRandomNumber()
```
이렇게 타입 인스턴스를 만들고 인스턴스메서드를 호출하는 편입니다!

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        print("1 : 은행 개점" )
한번의 print문으로 처리할 수 있는 방법은 어떤것이 있을까요?

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func runApp() {
현재 1, 2 Int타입을 제외한 String 타입을 입력해도 앱이 종료됩니다!

runApp이라는 표현보다 은행과 조금 더 가까운 네이밍은 없을까요?

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        if let inputStringMenu = readLine(),
사용자 입력에 대한 역할도 하나의 기능으로 분리시키면 좋을 것 같아요!
매개변수의 활용을 해보세요!

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +           let inputIntMenu = Int(inputStringMenu) {
Int로 형변환 한 이유는 무엇인가요?

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            if inputIntMenu == 1 {
매직넘버 1과 2를 Menu라는 타입에 담아서 사용해보면 좋을 거같아요!
Hint. 열거형

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        let startNumber: Int = 10
start와 finish라는 네이밍보다 최소, 최대라는 표현이 조금 더 와닿을거같아요!

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +private let menu = Bank()
은행의 인스턴스인데 변수명이 menu여야 할까요??
똑같이 bank로 해도 될 것같아요!!

2022-10-20 07:29 UTC, jaemuYeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    func generateClientRandomNumber() -> Int {
손님을 생성한다는 것은 손님을 받는 은행측에서 하는 일이지 않을까요??

2022-10-21 03:03 UTC, dddowon commented on BankManager.swift
> +struct BankManager {
넵 은행 직원으로 생각했었지만 다시 생각해보니 BankManager라는 뜻은 지점장으로 여기서 하는 일이 Bank에서 하는 일이 되면 좋겠네요

2022-10-21 03:04 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    var bankManager: Int = 1
은행원이라고 생각해서 만들어놨지만 활용할 필요가 없어보여서 지워도 될듯 합니다!

2022-10-21 03:05 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let clientNumber = Client().generateClientRandomNumber()
넵

2022-10-21 03:05 UTC, eunho8713 commented on BankManager.swift
> +    func work() {
전역변수로객체 바로 안에 let waitingNumber = waitingNumberQueue.count 를 사용할려 했었지만 객체안에 바로 사용할 수 없기에 중첩함수를 사용하게 됬습니다. (workStart 메서드와 workFinish 메서드가 waitingNumberQueue.count 를 전역변수로 가지고 있어야하기때문)

2022-10-21 05:04 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func runApp() {
넵 bankOpen이라는 네이밍으로 했습니다!

2022-10-21 05:07 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +           let inputIntMenu = Int(inputStringMenu) {
처음에 1, 2의 값을 받을려고 생각해 형변환을 했지만 그냥 문자열로만 받는다는 것으로 바꿔 변환하지 않았습니다. 그러므로 다른 문자열을 입력받는 것도 앱이 다시 실행되도록 수정이 됐습니다!

2022-10-21 05:07 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        let startNumber: Int = 10
넵

2022-10-21 05:08 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +private let menu = Bank()
넵

2022-10-21 05:08 UTC, dddowon commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    func generateClientRandomNumber() -> Int {
넵 그렇거 같습니다

2022-12-22 07:56 UTC, closed without merging