은행 창구 관리 앱 [STEP 2] Andy, Sam
tasty-code/ios-bank-manager pull request #80
Opened 2024-01-30 14:27 UTC by andyanappdev

> 리뷰어 : @cherrishRed
> 
> 
> 버드 :@andyanappdev (Andy) @ParkChanH (Sam)
> 

안녕하세요, 레드~!

은행 창구 관리 앱 STEP2 입니다.

이번 PR Review도 잘 부탁 드립니다.

---

## STEP 2 : 타입 구현 및 콘솔앱 구현

### 타입 구현 - 은행, 고객

- 은행에는 n명의 은행원이 근무합니다.
- 은행에는 n명의 고객이 업무처리를 위해 대기합니다.
    - 고객의 대기열은 Step 1에서 구현한 Queue 타입을 활용합니다.
- 모든 고객의 업무가 끝나면 은행업무를 마감합니다.
- 업무를 마감할 때 "업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 XX명이며, 총 업무시간은 XX초입니다."라고 출력합니다.
- 은행원은 고객의 업무를 처리합니다.
- 각 고객의 업무를 처리하는 데 걸리는 시간은 0.7초입니다.
- 은행원이 한 번에 처리할 수 있는 고객은 한 명입니다.
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다.
    - "3번 고객 업무 시작"
- 고객의 업무를 처리하면 아래와 같이 출력합니다.
    - "5번 고객 업무 완료"
- 은행/고객 타입 외에 필요한 타입이 있다면 자유롭게 구현합니다

### 콘솔앱 구현

- Step 2의 은행에는 한 명의 은행원이 근무합니다.
- 은행원은 한 번에 한 명의 고객의 업무를 처리할 수 있습니다.
- 앱을 실행하면 두 개의 메뉴를 출력합니다.
    
    ```
    1 : 은행 개점
    2 : 종료
    ```
    
- 사용자가 1을 입력하면 은행을 개점하고 10명~30명의 고객이 방문합니다. 10~30 사이의 임의의 수 만큼의 고객의 업무를 처리하면 은행문이 닫히고 다시 메뉴를 출력합니다.
- 사용자가 2를 입력하면 프로그램을 종료합니다.

### STEP 핵심 경험

- Queue의 활용
- 타입 추상화 및 일반화

---

## Floder Structure

```
📦BankManagerConsoleApp
 ┣ 📂Model
 ┃ ┣ 📂LinkedListQueue
 ┃ ┃ ┣ 📜QueueProtocol.swift
 ┃ ┃ ┣ 📜LinkedListQueue.swift
 ┃ ┃ ┗ 📜DoublyLinkedList.swift
 ┃ ┣ 📜Customer.swift
 ┃ ┗ 📜Bank.swift
 ┣ 📂View
 ┃ ┗ 📜ConsoleMessage.swift
 ┣ 📂Controller
 ┃ ┗ 📜BankController.swift
 ┗ 📜main.swift
```

---

## 설계 및 구현 설명

### 목적

고객의 은행 업무 처리를 허며, MVC(Model-View-Controller) Architecture를 적용하였습니다.

### Architecture 간략 설명

- **Model** : **`Customer` struct,** **`Bank`** class 로 구성
    - STEP 1에서 구현한 LinkedListQueue 포함
- **View** : **`ConsoleMessage`** struct는 console에 나타낼 메시지를 가지고 있습니다.
    - 총 3가지 method로 구성 (taskStartMessage, teskEndMessage, bankClosingMessage)
- **Controller** : **`BankController`** class는 앱을 실행하는 method를 가지고 있으며, 실행시 console에 메뉴를 출력 후 사용자로부터 입력 값을 받아 분기 처리 합니다.
- **main** : App 실행 시 진입점으로, App 실행에 필요한 인스턴스들을 차례대로 생성하여 주입 해주고 최종적으로 **`BankController`** 에 접근하여 앱 실행 method를 호출 합니다.

### 주요 컴포넌트

1. **Customer (Model)**
    - 각 고객은 고유한 번호(`waitingNumber`)를 가집니다.
    - 은행 업무 처리를 위해 대기하는 고객들을 나타냅니다.
2. **Bank (Model)**
    - 은행에 도착한 고객들을 **`Queue<Customer>`** 형태로 관리합니다.
    - 고객의 업무 처리 로직을 담당하며, 모든 고객이 처리되면 업무를 마감합니다.
    - 고객의 업무 처리 시간은 0.7초로 설정되어 있습니다.
3. **ConsoleMessage (View)**:
    - 업무 시작, 업무 완료, 은행 마감 등의 상황에서 콘솔에 출력할 메시지를 정의합니다.
4. **BankController (Controller)**:
    - 사용자 입력에 따라 은행의 개점과 종료를 제어합니다.
    - 사용자가 "1"을 입력하면 은행을 개점하고, "2"를 입력하면 애플리케이션을 종료합니다.

### 작업 흐름:

1. **`BankController`** 인스턴스가 생성되고, **`runBankApp()`** method를 통해 애플리케이션의 메인 루프가 시작됩니다.
2. 사용자가 "1"을 입력하면 **`Bank`** 클래스의 **`open()`** method가 호출되어 고객의 업무 처리가 시작됩니다.
3. 모든 고객이 처리되면, **`Bank`** 클래스의 **`close()`** method가 호출되어 총 처리한 고객의 수와 총 소요된 시간과 함께 업무 마감 메시지를 출력합니다.
4. 사용자가 "2"를 입력하면 App을 종료됩니다.

---

## 질문

### Sam

Class / Struch 의 올바른 사용 에 대해 고민이 있습니다. 제가 생각하기에 class / struch 는

### Struct

- **목적**: 연관된 간단한 값의 집합을 캡슐화하는 것.
- **사용 상황**:
    - 구조체 내의 프로퍼티가 값(Value) 타입일 때.
    - 복사(Copy)가 참조(Reference)보다 합당할 때.

### Class

- **특징**: 참조(Reference) 타입.
- **사용 상황**:
    - 상속(Inheritance)이 필요할 때.
    - 객체의 공유가 필요할 때.

라고 생각하는데.  예를 들어

```swift
/// 고객의 고유 번호 설정
struct Customer {
    let waitingNumber: Int
    
    init(waitingNumber: Int) {
        self.waitingNumber = waitingNumber
    }
}
```

위 코드에서 **`Customer`** 구조체는 간단한 값(여기서는 **`waitingNumber`**)을 캡슐화합니다. 

즉 주요 질문은, 이 구조체의 인스턴스가 복사되는 것이 바람직한지, 아니면 참조되어 공유되는 것이 더 적절한지궁금합니다.

너무 제가 생각하기에 명확하지않아서 레드가 생각할떄는 어떤 상황에 class / struct 를 사용하시는지 궁금합니다.

### Andy

- protocol QueueProtocol 구현 의도
    - QueueProtocol을 정의 하여 interface로 활용함이 목적 이었습니다.
        - DIP + IoC 패턴을 적용하여 Decoupling 및 다형성을 통한 확장의 유연성을 확보함이 주 목적
- 문제점 발생 Point
    
    ```swift
    protocol QueueProtocol {
        associatedtype Element
        var peek: Element? {get}
        var isEmpty: Bool {get}
        func enqueue(_ element: Element)
        func dequeue() -> Element?
        func clear()
    }
    ```
    
    - `associatedtype` 사용으로 즉 제네릭을 사용하여 protocol을 정의하다 보니 코드가 특정 구현체에 의존하게 되어 다형성이 줄어 드는 결과가 발생해 버렸습니다.
        - 위 문제를 해결하기 위한 시도
            1.  `associatedtype` 을 사용하지 않고 `Any`를 사용할 경우에는 Bank class에서 type casting이 필요하게 되는 번거로움이 또 발생하게 되고…
            2. `Customer` 타입을 사용하는 것은 STEP 1의 요구사항인 ‘Queue 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용’ 위배
    - 결국은 Bank class에서 사용하는 `QueueProtocol`을 채택한 구체적인 타입이 `Customer` 타입을 Element로 가지도록 제한
        
        ```swift
        final class Bank<Q: QueueProtocol> where Q.Element == Customer {
            private let customerQueue: Q
            private let consoleMessage: ConsoleMessage
            private var totalCustomers: Int = 0
            
            init(customerQueue: Q, consoleMessage: ConsoleMessage) {
                self.customerQueue = customerQueue
                self.consoleMessage = consoleMessage
            }
        ....
        }
        ```
        
        - 그러다 보니 Bank를 가지고 있게 되는 BankController 에서 Bank타입을 명시적으로 `Bank<LinkedListQueue<Customer>>` 설정해 주어야 됨으로써 최초의 protocol QueueProtocol 구현 의도와 멀어져 버리게됨
            
            ```swift
            final class BankController {
                private let bank: Bank<LinkedListQueue<Customer>>
                
                init(bank: Bank<LinkedListQueue<Customer>>) {
                    self.bank = bank
                }
            ...
            }
            ```
            
- 좀더 고민하고 연구해보면 다른 방법이 있을것만 같은데… PR 시간이 너무 지연되고 있어서 Red에게 조언을 구해 봅니다.
- 과연 이 상황에서 protocol QueueProtocol을 사용해야 할 이유가 있을까요? (의도와 목적에서 멀어져 버린 상황)

2024-01-31 02:15 UTC, cherrishRed requested changes
안녕하세요! 앤디 샘!

이번 스텝도 정말 수고하셨습니다! 👍👍👍

## 🙋질문에 대한 답변 
### ⛄️ class / struct 의 사용 

샘이 직접 작성하진 클래스와 구조체의 특성대로 사용합니다. 
“swift language guide에도 WWDC에도 구조체가 정말 좋으니 구조체를 많이 사용해라” 라는 식의 애플의 조언이 있는데요.
그래서 저는 개인적으로 생각할 때, 특별한 일이 없으면 구조체를 사용하고 참조 되어야 한다거나 하는 특별한 일이 있을 경우에는 클래스를 사용합니다. 
지금 Customer 객체는 구조체여도 괜찮을 것 같습니다. 

실제로 앱을 만들다보면, 이렇게 구조체인지 클래스인지 결정할 수 있는지 자유가 많지는 않은데요, 
UIKit을 사용해보셔서 아시겠지만, UIKit 요소들을 상속받아 사용하는 경우가 많아서, 참조될 일이 없다. 라고 판단해도 클래스로 구현할 수 밖에 없는 일도 있습니다. 

### ⛄️ QueueProtocol 의 사용

QueueProtocol의 자체의 문제는 아니고, 모든 프로토콜이 격는 문제입니다. 
우리가 여기서 생각해봐야 할 것은, customerQueue 를 꼭 외부에서 주입 받아야 하는가? 입니다. 
어떤 값들을 DI 해야 하는 걸까요? 

저번 PR 에서 어떤 조건에서 사용하느냐에 따라서 적절한 Queue 가 달라진다
라는 이야기를 나눴는데요. 
이제 Bank 라는 구현체의 구현이 정해졌기 때문에, 
만약 새로운 bank1, bank 변수를 만든다고 하더라도 새로운 큐가 필요한 경우는 없을 것 같습니다. 

물론, 지금의 코드가 확장성 면에서는 더 좋습니다만,
언급하신 단점들이 있으니, 어떤 단점을 선택할지 선택의 문제입니다.

2024-01-31 02:15 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        let numberOfCustomers = Int.random(in: 10...30)
customer의 수를 랜덤이 아니라 설정할 수 있도록 하면 좋을 것 같아요!
혹시 이게 요구사항이라면, 안 바꾸셔도 됩니다!

2024-01-31 02:15 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
Tread.sleep 은 쓰레드 자체를 중지합니다. 
지금은 메인쓰레드를 계속 멈추면서 가는 건데요, 
지금은 cmd 프로그램이지만, UI 가 있었으면, 0.7초 동안 UI 작업이 멈추는 것이고, 이는 오류로 이어질 가능성이 엄청 높아요!
다른 방법도 생각해보시면 좋을 것 같습니다!😆

2024-01-31 02:22 UTC, ParkChanH commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        let numberOfCustomers = Int.random(in: 10...30)
이부분은 10~30 사이의 임의의 수 만큼의 고객의 업무를 처리 하라는 요구 사항에 따라 처리했습니다!!

2024-02-01 03:30 UTC, andyanappdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
어떻게든 sleep이 메인스레드에서 일어 나지 않도록 해보려고 여러 시도를 해보면서
`if Tread.isMainThread` 를 활용해서 확인 해보았는데 성공을 못했습니다.
계속 이것 저것 해보다 보니 해결 방법이 Concurrency 적인 접근 방법이 아닌 다른 방법으로 해야 할것 같다는 생각이 듭니다.
기존 코드 보다는 조금더 발전시켜 일단 commit을 해두었습니다.
레드의 해결방안 조언을 받아 보고 싶습니다.

2024-02-01 07:19 UTC, cherrishRed approved these changes
앤디 쌤! 수고하셨습니다! 

Thread.sleep 을 DispatchQueue 를 사용하여 처리하도록 변경하신 부분 잘 보았습니다! 

> 메인스레드에서 일어 나지 않도록 해보려고 여러 시도를 해보면서
if Tread.isMainThread 를 활용해서 확인 해보았는데 성공을 못했습니다.


라고 이야기 하셨는데, 만약 다른 쓰레드를 멈추게 한다고 하더라도,
쓰레드를 멈추게 하는 일이 어떤 사이드 이펙트를 일어나게 할지 모르기 때문에, 
Dispatch Queue 를 사용하신 방법 아주 좋았습니다!

Dispatch Queue 가 작업하는 순서가 중요하다면 나중에 DispatchSemaphore 를 사용해 볼 수 도 있을 것 같습니다.  

> Concurrency 적인 접근 방법이 아닌 다른 방법으로 해야 할것 같다는 생각이 듭니다.

Dispatch Queue 의 사용도 Concurrency 적인 사용법인데… 이부분은 어떤 부분을 이렇게 이야기 하시는지 제가 이해를 잘못한 것 같아요. 
만약 Concurrency 를 사용하고 싶지 않으신 거라면, 지금은 은행원이 한명이니, Timer 로도 충분히 처리 가능할 것 같습니다.

approve 드리겠습니다!
나머지 개선사항은 다음 스텝에서 이어서 진행하시면 될 것 같습니다!

2024-02-01 10:28 UTC, merged