은행 창구 관리 앱[STEP 3] Sidi, Hoi
tasty-code/ios-bank-manager pull request #82
Opened 2024-02-01 06:42 UTC by happykwon

@minsson

안녕하세요, 민쏜
Hoi(@happykwon), Sidi(@jus1234)입니다!
은행 창구 관리 앱[STEP 3] PR입니다.
바쁘신 와중에 리뷰를 해주셔서 감사합니다. ☺️

## 🔍 What is this PR?

STEP 3 기능 구현
- 업무별 은행원 / 고객 Queue 
- 비동기 처리 

## 실행화면 
![image](https://github.com/tasty-code/ios-bank-manager/assets/149054154/8d470de0-b306-4f37-b5bd-94d7f8ddf300)
![image](https://github.com/tasty-code/ios-bank-manager/assets/149054154/2c6bb8a9-85ef-4e89-bf16-ce7e65e8effa)

## 프로젝트 구조
```Bash
├── BankManagerConsoleApp
│   ├── BankManagerConsoleApp
│   │   ├── DataStructs
│   │   │   ├── LinkedList.swift
│   │   │   ├── LinkedListQueue.swift
│   │   │   └── Queue.swift
│   │   ├── Enums
│   │   │   ├── Menu.swift
│   │   │   ├── Message.swift
│   │   │   └── Task.swift
│   │   ├── Models
│   │   │   ├── Bank.swift
│   │   │   ├── BankManager.swift
│   │   │   └── Customer.swift
│   │   └── main.swift
│   └── BankManagerConsoleAppUnitTests
```
## 📝 PR Point

### 1. 비동기 처리 
은행원별 업무 비동기 처리(loan 1명, deposit 2명)

### 2. 업무별 Queue분리
은행원이 수행하는 업무별 구분 
고객 용무별 구분

## 질문

### 1. 비동기 처리시 처리 시간을 구하는 방법
저희가 생각한 방법은 두가지가 있었습니다. 
1. 시작할 때 시간을 기록해서 끝날 때 시간과 비교하는 방법 (Dispatch 활용)
```
let teskTime = DispatchTime.now()
let endTaskTime = DispatchTime.now()
self?.totalTeskTime = Double(endTaskTime.uptimeNanoseconds - teskTime.uptimeNanoseconds) / 1e9
```  
2.  Date 타입 활용 
```
 let openTime: Date = Date()
Date().timeIntervalSince(openTime)
```
이거 외에 다른 좋은 방법이 있는지 궁금하고, 현업에서 비동기 처리에 대한 정확한 시간을 알아야한다면 어떤식으로 접근을 하는지 궁금합니다.

### 2. 지난 PR(STEP 2) completionHandler 관련
지난 PR에서 민쏜이 `completionHandler` 부분에서 자세한 설명을 부탁하셨는데 어떤 부분이 궁금하셨는지 궁금합니다!
먼저 저희 코드를 설명을 드리자면 `completionHandler`에서는 은행원이 작업을 끝낸 후 스스로(BankManager)를 은행원큐 대기열에 인큐하는 작업을 처리합니다. 그래서 `completionHandler(self)`라는 코드가 있고 여기서의 `self`는 `Bank`에서 작성한 `completionHandler` 클로져의 `manager`에 해당합니다. 결국 `bankManagerQueue.enqueue(Self(manager))`가 되도록 설계 했습니다.

2024-02-04 17:28 UTC, minsson requested changes
안녕하세요, 시디, 호이!
Step 3도 잘 수행해주셨군요! 고생 많으셨습니다. 

이번 스텝에서는 다른 것보다는 두 분이 질문 2로 남겨주신 내용에 대한 부분에 집중해보면 좋을 것 같아요. 아래 답변을 보시면 제가 DispatchGroup과 DispatchSemaphore를 언급하고 있는데요. 이 개념을 공부해보고 프로젝트에 적용해보면 어떨까 싶어요. 

## 질문에 대한 답변

### 질문 1
비동기 처리시 처리 시간을 구하는 방법

정확한 게 중요하다면 말씀해주신 `DispatchTime`을 쓰거나, `CFAbsoluteTimeGetCurrent`을 쓰는 방법이 있어보여요. 다만 현재 프로젝트에서는 가독성 및 편의성 측면에서 Date를 사용하는 것도 괜찮은 선택이었다는 생각이 들어요. 

### 질문 2
지난 PR(STEP 2) completionHandler 관련

제가 좀 더 자세하게 설명드렸으면 좋았을 것 같아요. completionHandler 내부의 코드 그 자체보다는, 왜 은행원 대기열이 필요한지 잘 이해되지 않아서 질문드렸어요. 은행원 대기열을 만들고, enqueue하고, dequeue하는 이유가 무엇인가요? 

혹시 `DispatchGroup`과 `DispatchSemephore`에 대해서도 공부해보셨나요? 아직 안 해보셨다면, 이번 기회에 공부해보고 적용해보시는 것도 좋을 것 같아요! 코드를 상당부분 개선할 수 있을 것 같아요.

만약 잘 쓰게 되면 현재 Bank 객체에 있는 프로퍼티 중 `depositManagerQueue`, `loanManagerQueue`, `isDepositManagerWorking`, `isLoanManagerWorking`, `isbankWorking`을 없앨 수 있을 것 같아요.

한번 살펴보고 무리라고 생각된다면 너무 많은 시간을 할애하기보다는 다음 스텝을 수행하며 준비해보셔도 좋을 것 같고요!

### 질문 3
출력(실행) 시 CLI에서 공백라인 출력

아, 이 부분은 저도 모르겠네요.. 코드만 봐서는 개행이 생길 이유가 없어 보여서요. 다만 저도 예전에 이와 같은 프로젝트를 수행한 적이 있는데, 그때 코드를 가져와서 실행해보니 마찬가지로 개행이 생기네요. 예전에 실행했을 때는 개행이 없었던 것 같은데 말이죠.. 단순히 버그가 아닐까 싶기도 한데, 저도 잘 모르는 부분이라 답변 드리기가 조심스럽네요..! 🥲

2024-02-04 17:28 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private var loanManagerQueue: LinkedListQueue<BankManager>
- `private var`를 `private let`으로 변경하면 어떻게 되나요?
- 만약 `private let`으로 바꿨는데 동작한다면, 그 이유는 무엇인가요?

2024-02-04 17:28 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private var maxCustomerNumber: Int
네이밍에 오해의 여지가 있어보여요. max라고 하니 은행에서 받을 수 있는 고객 수의 최대치처럼 느껴져요. 좀 더 적절한 네이밍이 있을까요?

2024-02-04 17:28 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Enums/Task.swift
> +    }
korean이라는 네이밍이 좀 어색하게 느껴져요. 뭔가 현지화와 관련이 있는 느낌이에요. title, description 등의 네이밍은 어떨까요?

2024-02-04 17:28 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
- validate라는 네이밍과 이 메서드의 역할이 잘 매치되지 않는다는 생각이 들어요.
- 옵셔널한 `Menu?`를 반환하지 않아도 될 것 같아요. 어차피 "1"과 "2"가 아닌 모든 인풋이 `wrongInput`에 해당하므로, nil을 리턴하지 않고 `Menu.wrongInput`을 반환해도 된다고 생각해요. 그러면 여기서 `Menu` 타입을 반환하고, `process()` 메서드에서는 불필요한 언래핑을 줄일 수 있어요. (사실 nil을 반환하는 방법이나, 제가 지금 말씀드리는 방법보다는 에러처리를 하는 편이 더 좋다고 생각해요)

2024-02-04 17:28 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        isLoanManagerWorking = false
이 코드만 봐서는 isLoanManagerWorking이 왜 false가 되어야하는지 잘 이해되지 않을 수 있어요. switch문을 써서 task가 `.loan`일 때 `isLoanManagerWorking = false`가 실행된다는 걸 명시해주는 편이 좋을 것 같아요.

2024-02-04 17:28 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        self.isLoanManagerWorking = true
지금 코드에서 init()이 필요한 이유는 무엇인가요?

2024-02-04 17:28 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +            customerQueue.enqueue(Customer(number: $0, task: task))
Bank가 고객 객체들을 생성하고, 대기열까지 구성하는 건, Bank의 역할이 과다한 부분이라는 생각이 들어요. 별도의 객체로 분리하고, Bank가 주입 받는 방법은 어떨까요?

2024-02-08 02:47 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Enums/Task.swift
> +    }
description으로 변경완료했습니다 :)

2024-02-08 02:48 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private var maxCustomerNumber: Int
totalcustomer로 변경 완료했습니다 :)

2024-02-08 03:59 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
`process()`안에 서 언래핑을 한번 해주는 방식으로 변경했습니다.

2024-02-08 03:59 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +        isLoanManagerWorking = false
`semaphore`를 사용해 `isLoanManagerWorking` 프로퍼티는 삭제했습니다

2024-02-08 04:14 UTC, happykwon commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +            customerQueue.enqueue(Customer(number: $0, task: task))
은행원 , 고객 , 은행이라는 객체들의 역할을 생각해봤을 때 대기열의 생성은 은행의 책임이 맞다는 생각을 했는데 
민쏜은 어떤 객체가 대기열을 만드는 책임을 갖을 수 있다고 생각하시는지 궁금합니다

2024-02-08 04:17 UTC, jus1234 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    private var loanManagerQueue: LinkedListQueue<BankManager>
`private let`으로 바꿨어도 정상적으로 동작했습니다. 저희가 만든 `LinkedListQueue`는 참조 타입으로 속성의 상태가 변화 하더라도 뮤테이팅이 발생하지 않아 `let`으로 사용해도 정상적으로 동작 했습니다.

2024-02-13 12:31 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +            customerQueue.enqueue(Customer(number: $0, task: task))
은행원, 고객, 은행이라는 객체와 별개로 다른 객체를 만들고, 그 객체의 메서드를 통해 생성한 대기열을 은행에 주입하는 방식을 생각해봤어요. 은행원, 고객, 은행이라는 객체만 사용해야 할 이유는 없다고 생각해요.

2024-02-13 12:31 UTC, merged