은행 창구 관리 앱  [STEP 3] Kyle, Effie
tasty-code/ios-bank-manager pull request #84
Opened 2024-02-01 16:59 UTC by Changhyun-Kyle

두두(@FirstDo) 안녕하세요. 에피(@hyeffie), 카일(@Changhyun-Kyle)입니다!

이번 스텝에서는 지난 스텝에서 구현한 은행원과 은행 고객 대기열을 확장하여 관리하는 기능을 구현했습니다. 지난 리뷰에서 잠깐 언급했던 것처럼 다른 호출 방향을 도입함에 따라 구조를 수정하게 되었고, 이 과정에서 객체 간의 소통을 책임을 기준으로 설계했습니다.

## 요구사항 구현

- 이전 설계 유지
    
    이전 스텝에서 구현했던, 여러 명의 은행원이 고객 업무를 처리할 수 있는 구조를 유지하면서, 은행원들이 자신이 처리할 수 있는 업무 종류에 따라 서로 다른 대기열 관리자(`ClientManager`)를 참조하도록 구현했습니다.
    
- 새로운 설계
    
    추가로 업무 종류에 따라 고객 대기열과 은행원 대기열을 함께 관리할 수 있는 `TaskManager`를 여러 개 두는 새로운 설계로 구현해보았습니다. 새로운 구조는 은행원이 큐로 부터 고객을 직접 요청하는 방식이 아닌, 대기열을 관리하는 `TaskManager` 가 은행원의 업무를 트리거하는 방식입니다.
    

## 폴더 구조

```jsx
.
├── App
│   ├── BankManagerApp.swift
│   └── BankManagerAppMenu.swift
├── Model
│   ├── BankManager.swift
│   ├── Banker.swift
│   ├── TaskManager.swift
│   ├── TicketDispenser.swift
│   └── Value
│       ├── BankTaskType.swift
│       ├── Client.swift
│       └── Order.swift
├── Protocol
│   ├── BankRunnable.swift
│   ├── BankerEnqueuable.swift
│   ├── ClientEnqueuable.swift
│   ├── ClientTaskHandlable.swift
│   ├── TaskManagable.swift
│   ├── TextInputReadable.swift
│   ├── TextOutputDisplayable.swift
│   └── TicketProvidable.swift
├── Utils
│   ├── LinkedList.swift
│   ├── Node.swift
│   └── Queue.swift
├── View
│   ├── ConsoleManager.swift
│   └── IOError.swift
└── main.swift
```

---

## 고민한 점

### 설계 변경

이전 스텝에서도 여러 명의 은행원이 고객 업무를 처리할 수 있는 구조였고, 호출 순서는 다음과 같았습니다.

> `BankManagerApp` > `BankManager` > `Banker` > `ClientManager`
> 
1. `BankManagerApp`은 앱이 실행되는 상태인 동안 메뉴를 입력 받고 실행하는 루프를 돌립니다.
2. `App`은 메뉴가 결정되면 은행원을 생성해서 `BankManager`의 실행을 호출합니다.
3. `BankManager`는 고객을 생성하고 고객 대기열에 추가하고, 은행원의 업무를 시작을 호출합니다.
4. `Banker`는 독립적인 스레드에서 비동기적으로 업무를 실행합니다.
5. `Banker`는 `ClientManager`(`ClientDequeuable`)에게 고객을 대기열에서 `dequeue`해서 돌려주기를 요청하고, 돌려 받은 고객의 업무를 처리합니다.

이 구조는 은행원이 루프 실행의 주체가 되는 구조였는데요. 이 구조에서 은행원이 아닌 다른 주체가 루프 실행을 관리하도록 하는 설계에 대해 고민하게 되었습니다.

![Untitled](https://github.com/tasty-code/ios-bank-manager/assets/101093592/6f8e2f50-3c87-4a07-a59e-5ebc4c99b06d)

두 가지 설계를 변경하면서 느낀 것은 다음과 같았습니다.

- 어떤 설계이든 동시 접근이 일어나는 대기열이 있고 이 경합은 관리되어야 한다.
    - 기존 설계에서는 여러 `Banker` 스레드에서 접근하는 고객 대기열의 경합을 관리해야 했고,
    - 수정된 설계에서는 `Banker`가 업무 수행을 완료 후 다시 은행원 대기열로 들어올 때 은행원 대기열의 경합을 관리해야 한다.
    - 그리고, `dequeue` 와 `enqueue` 이 동시에 발생하며 경합이 생길 수 있으므로 `dequeue`도 `enqueue` 경합과 함께 관리해야 한다.
- 루프 실행의 주체가 되는 객체가 어떤 대기열을, 어떤 속성을 알고 있느냐에 따라 **루프 실행 조건이 까다로워질 수 있다.**
    - 기존 설계에서는 `Banker`가 참조하고 있는 고객 대기열에서 `dequeue` 해서 고객을 리턴받을 수 있으면 실행할 수 있었던 반면,
    - 수정된 설계에서는 `TaskManager`가 두 개의 큐를 관리하다 보니, 루프 실행 조건이 까다로워진다.
- 실행 조건만 제대로 설계하면, 두 가지 방법 모두  프로젝트 명세서에서 요구하는 로직을 문제 없이 수행할 수 있다.
    - 하지만, 그렇지 않다면…아래와 같이…무한한 기다림 속으로…🥲
        
        ![Untitled2](https://github.com/tasty-code/ios-bank-manager/assets/101093592/f9d795f3-79d2-4060-93f6-b5516b2bf7c7)
        

### 책임 주도 설계

[지난 스텝 리뷰](https://github.com/tasty-code/ios-bank-manager/pull/75#discussion_r1470359537)에서 객체마다 추상화 여부가 다르다는 코멘트가 있었는데요. 이 부분을 해결하기 위해 객체의 소통 과정 속에서 각 객체의 책임을 우선적으로 작성한 후 구현을 작성하려 노력했습니다.

객체 간에 의존성을 인터페이스로 제한해, 각 객체의 책임을 위주로 소통할 수 있도록 구현했습니다.

- `BankerEnqueuable` : 은행원 대기열에 업무에 맞는 은행원을 추가합니다.
- `BankRunnable` : 은행 업무에 따라 해당하는 은행원과 고객을 생성하고 은행 업무를 지시합니다.
- `TaskManagerable` : 지시 받은 은행업무 은행원이 수행하게 합니다.
- `ClientTaskHandlable` : 은행원이 업무를 수행합니다.
- `ClientEnqueuable` : 은행 업무에 따라 고객을 대기열에 추가합니다.
- `TicketProvidable` : 고객 대기 번호를 생성하고 분배합니다.

![Untitled3](https://github.com/tasty-code/ios-bank-manager/assets/101093592/30820104-0b44-498e-9c7b-581815f6b0da)

---

## 질문

### 은행 개점 관련 정보의 주입을 어디에서 결정하는 게 좋을까?

`BankManagerApp`의 구현을 보면, 사용자에게 입력 받는 메뉴에 따라 개점을 하거나 하지 않는 로직을 포함하고 있습니다. 이때 은행 개점에 필요한 정보인 고객의 수(`clientCount`), 티켓 발행 객체(`TicketDispenser`), 타입 종류에 따른 은행원 수(`Order`) 등을 생성하게 되는데요. `App`이 이런 정보들을 생성하고 주입, 전달하는 것이 어울리는지 궁금합니다. `App`에서 생성해서 `BankManager`로 주입을 해야 하는 방법, 아니면 `Bankmanager`에서 생성해서 `TaskManager`로 전달하는 방법을 비롯한 여러 선택지 중에 두두는 어느 위치가 현재 요구사항에 가장 어울린다고 생각하시나요?

```swift
// BankManagerApp
func startBank() {
        guard let clientCount = (10...30).randomElement() else { fatalError() }
        let dispenser = TicketDispenser(totalClientCount: clientCount)
        
        let orders = [
            Order(taskType: .loan, bankerCount: 1),
            Order(taskType: .deposit, bankerCount: 2),
        ]
        
        let bankManager = BankManager(
            textOut: self.output,
            dispenser: dispenser
        )
        
        bankManager.runBank(with: orders, numberOfClient: clientCount)
    }
```

2024-02-02 01:15 UTC, FirstDo requested changes
안녕하세요 두분!
밤늦게까지 정말 고생 많으셨습니다..!!!

구조를 전체다 바꿔버리는게 쉬운일이 아니였을텐데 대단하십니다 ㅎㅎ
그와중에 객체들도 다 추상화 하셨네요..!!

## 질문에 대한 답변

#### 은행 개점 관련 정보의 주입을 어디에서 결정하는 게 좋을까?

어디서 주입하든 상관은 없지만, 보통 이런 의존성들은(대표작으로 네트워크나 스토리지 같은 것들?) 여러 객체에서 쓰이는 경우가 많기때문에 저는 최상단에서 주입해주는 편입니다.

iOS App에서는 AppDelegate 여기서는 BankManagerApp이 되겠네요

2024-02-02 01:15 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TicketDispenser.swift
> +    }
이부분이 이해하기가 너무 힘듭니다 ㅠㅠ

제가 이해한게 맞다면 totalIndexCount명만큼의 사람을 받아서
랜덤으로 아래와 같은 딕셔너리를 만드는게 목적인거 같은데 훨씬 쉽게 쓸 수 있을것 같아요..!
[BankTaskType.deposit: [8, 6, 3], BankTaskType.loan: [11, 10, 9, 7, 5, 4, 2, 1]]

저라면 이런식으로 했을것 같아요 (!는 무시해주세요 ㅎㅎ..)

```swift
var result: [BankTaskType: [Int]] = [.deposit: [], .loan: []]

for index in (1...totalIndexCount) {
  let type: BankTaskType = [BankTaskType.loan, BankTaskType.deposit].randomElement()!
  result[type]!.append(index)
}

result[.loan]!.reverse()
result[.deposit]!.reverse()

return result
```

두분도 더 단순하고 명확하게 작성해보실 수 있을것 같네요..!

2024-02-02 01:15 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TicketDispenser.swift
> +    }
이부분도 마찬가지입니다. 훨씬 더 간단하게 쓸 수 있을거에요
`popLast` 라는 친구를 활용해보세요

2024-02-02 01:15 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TicketDispenser.swift
> +    private var indicesByTask: [BankTaskType: [Int]]
이름이 좀 어색한거 같아요 `indicesByTask`
물론 맞는데,
우리가 [Int] 라는 타입을 네이밍할때 무조건 intArray 이런식으로 짓지는 않잖아요??

2024-02-02 01:15 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Value/BankTaskType.swift
> +enum BankTaskType {
enum으로 관리하신 부분이 좋습니다!

또 연산프로퍼티를 쓰신 부분도 좋네요
이거 피치못할사항이 아니라면 `Type`은 굳이 안붙이셔도 될것같아요!

그리고 앞의 로직을 바꾼다면, CaseIterable의 기본 구현인 allCases로도 충분할거 같긴합니다

2024-02-02 01:15 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/App/BankManagerApp.swift
> +        guard let clientCount = (10...30).randomElement() else { fatalError() }
fatalError 쓸꺼면 차라리 !하는게 더 깔끔하지 않나 싶습니다

아래부터는 진짜 개인적인 생각입니다
!나 fatalError나 둘 다 권장하는 방식은 아니지만 진짜 100퍼 확신이 있으면 전 부분적으로는 쓸 수도 있다고봐요

2024-02-02 01:15 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TaskManager.swift
> +            }
아예 구조를 바꾸셨네요!!! 짤은시간에 대단하십나다 ㅎㅎ
결국 핵심은 이부분인것 같은데, 바뀐방식에서 가장 어려울거라고 생각했던건 (제생각) 은행원이 작업이 끝났을때
어떤식으로 알리고 다음 작업을 받아갈 것인지에 대한 문제였던것 같습니다

while문을 사용해서 무한루프를 도는것으로 구현하셨는데,
이번스텝은 결국 여러 동시성 문제들을 겪어보고 해결하는게 목적이기때문에 코드작성도 작성이지만 해당 부분에 대한 공부를 많이 해보시는게 더 도움되실것 같습니다

물론 충분히 많이 하고 계신거 같지만요..!!

이런 `Busy Waiting` 방식의 단점이라던가?

2024-02-02 01:15 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    let taskType: BankTaskType
비슷한 코맨트지만 굳이 Type을 붙일 필요가 없어보입니다..!

2024-02-02 06:05 UTC, Changhyun-Kyle commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TicketDispenser.swift
> +    private var indicesByTask: [BankTaskType: [Int]]
`TicketDispenser` 객체에 더 알맞게 `ticketNumbers`로 수정했습니다!
```swift
private var ticketNumbers: [BankTaskType: [Int]]
```

2024-02-02 06:06 UTC, Changhyun-Kyle commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    let taskType: BankTaskType
반영했습니다!

2024-02-02 06:35 UTC, Changhyun-Kyle commented on BankManagerConsoleApp/BankManagerConsoleApp/App/BankManagerApp.swift
> +        guard let clientCount = (10...30).randomElement() else { fatalError() }
현재 프로젝트에 `swiftlint`를 적용 중 입니다. 사실, 해당 부분에서 `nil`일 때 강제 언래핑을 하는 것과 `fatalError`를 하는 것과 차이는 없지만 `swiftlint rule`에 강제 언래핑을 제한하는 규칙은 있어도 fatalError 자체를 제한하는 규칙은 없더라구요..! 
이럴 때, 강제 언래핑 규칙을 `disable`하는 것이 나을 지 아니면 현재처럼 `fatalError`로 처리하는 것이 나을 지라고 고민하던 와중에 불현듯 저희가 저번 STEP에서 구현한 에러 핸들링이 생각나서 `BankManagerAppError` 타입을 생성 후 `throw`할 수 있게 리팩토링했습니다!
```swift
guard let clientCount = (10...30).randomElement() else { throw  BankManagerAppError.outOfIndex }
```
- [SwiftLint - Fatal_Error_Message](https://realm.github.io/SwiftLint/fatal_error_message.html)
- [SwiftLint - Force Unwrapping](https://realm.github.io/SwiftLint/force_unwrapping.html)

2024-02-02 06:48 UTC, hyeffie commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Value/BankTaskType.swift
> +enum BankTaskType {
중복을 방지하기 위해서 Set을 파라미터로 받았던 건데, 사실 인터페이스가 필요할만한 구현인가 싶더라긴 해요... enum의 allCases를 전달받으면 당연히 문제가 발생하지 않지만, 배열을 전달했을 때 저희 로직으로 구현을 하다 보면 문제가 있었고 그래서 중복을 처리해서 사용하자는 의미로 set으로 전달받고 싶었어요. 의도는 그랬습니다 ㅋㅋ
근데 위에서 추천해준 로직처럼 단순한 로직으로 바꾸면 작은 수정으로 배열로도 중복 제거 없이 충분히 해결할 수 있겠더라고요. 참고해서 반영해두겠습니다 !

2024-02-02 07:15 UTC, Changhyun-Kyle commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TicketDispenser.swift
> +    }
위에서 로직을 수정하니까 훨씬 간결하게 구현 가능해졌습니다!
```swift
    func provideTicket(of taskType: BankTaskType) -> Int? {
        return self.ticketNumbers[taskType]?.popLast()
    }
```

2024-02-02 07:17 UTC, Changhyun-Kyle commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TicketDispenser.swift
> +    }
기존 로직을 구현할 때, 배열을 어떻게 자를 것인가에 대해 몰두하다보니 로직이 너무 복잡해졌네요...ㅠ
리뷰해주신 방법처럼 반영했습니다!
```swift
    private static func componentIndices(
        totalIndexCount: Int,
        taskTypes: [BankTask]
    ) throws -> [BankTask: [Int]] {
        var result: [BankTask: [Int]] = taskTypes.reduce(into: [:]) { partialResult, task in
            partialResult.updateValue([], forKey: task)
        }
        
        for number in 1...totalIndexCount {
            guard let type = taskTypes.randomElement() else { throw BankManagerAppError.outOfIndex }
            result[type]?.append(number)
        }
        
        for type in taskTypes {
            result[type]?.reverse()
        }
        return result
    }
}
```

2024-02-02 08:48 UTC, hyeffie commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/TaskManager.swift
> +            }
오,, 루프를 끊임 없이 도는 걸 자원의 관점으로는 처음 생각해본 것 같아요. 이 설계의 의도가 원래 조건에 맞을 때까지 루프를 반복할 수 밖에 없는 구조였거든요.

말씀해주신 것처럼 Busy Waiting 에 대해서 카일이랑 학습을 좀 해봤는데, 저희의 두번째 설계 같은 Busy Waiting 의 단점은 루프가 헛도는 동안 CPU 자원이 낭비된다는 점이더라고요. 그리고 이 문제를 해결할 수 있는 방법이 헛도는 걸 방지하기 위해 해당 스레드를 sleep 상태로 만들고, 조건이 만족되면 다시 wake up 하는 방식이었어요.

저희 구현의 경우에는 
```swift
               ...
               guard
                    let banker = self.dequeueBanker(),
                    let client = self.clientQueue.dequeue()
                else {
               ...
```
이 부분을 만족하지 않으면 sleep을 하고 banker가 enqueue 되는 시점에 다시 wake up 해주어야 하겠죠?

그런데 이렇게 되면 다시 enqueue하는 banker가 이 루프 실행의 주체가 되므로, 다시 이전과 비슷한 설계가 되지 않을까? 라는 생각이 들었습니다. 물론 다른 점도 있지만요.

또 현재 반복문에서 실행하는 코드의 주기가 짧기 때문에 스레드를 재웠다가 깨우는 과정이 빈번하게 일어나고, 그래서 오히려 이 구조를 유지한다면, busy waiting이 오버헤드가 적지 않을까 라는 생각을 해보았습니다.

확실히 어느 설계를 채택하느냐에 따라 동시적인 실행과 임계 영역 관리, 자원의 관리 측면에서 정말 달라지는 것 같아요. 좋은 주제를 던져주셔서 많이 배워갑니다 ☺️

2024-02-03 00:59 UTC, FirstDo approved these changes
고생하셨습니다..!

2024-02-03 00:59 UTC, merged