은행 창구 관리 앱 [STEP3] 댄, 네로
tasty-code/ios-bank-manager pull request #86
Opened 2024-02-02 08:41 UTC by eensungkim

Step 3
멤버 : @eensungkim, @ODDNERO
리뷰어 : @yim2627

은행 창구 관리 앱 프로젝트의 세 번째 스텝입니다!
정리하여 PR 드립니다. 잘 부탁드립니다! :bow: 
</br>

# PR 상세
- 고객과 은행원을 서로 다른 큐로 관리
    - 고객: 자체 제작한 `큐`
    - 은행원: `OperationQueue`
- 은행원 큐는 다시 예금과 대출으로 나누어 관리
    - 예금: 최대 2개의 `Operation` 동시 실행
    - 대출: 최대 1개의 `Operation` 실행
- `addDependency` 를 통해 예금/대출 큐가 소진된 이후의 작업 연결
</br>

# 이번 스텝을 통해서 배운 점
- `OperationQueue` 의 이해와 활용
- `BlockOperation` 의 이해와 활용
- `DispatchQueue` 의 이해
- `DispatchGroup` 의 이해
- 스레드가 어떻게 생성되고 사라지는지 디버깅으로 확인하기
- `CaseIterable` 채택을 통해 열거형 값 랜덤으로 생성
</br>

# 구성
### BankManager.swift
- 예금과 대출 큐를 분리
- `OperationQueue` 의 `maxConcurrentOperationCount` 활용하여 동시 실행되는 `Operation` 수를 제한하는 것으로 요구사항 구현

### Customer.swift
- `BankingService` 열거형으로 고객이 원하는 서비스의 종류 구현
- 연산 프로퍼티를 활용하여 서비스 종류에 따른 연관 값 getter 구현
</br>

# 질문
1. 요구사항을 보면 2명의 은행원이 예금 업무를 처리한다고 안내하고 있습니다. 이번 스텝에서는 이 내용을 `OperationQueue` 의 `maxConcurrentCount` 와 `isSuspended` 를 활용해 구현했습니다.
요구사항은 만족하고 있지만, 실제 은행에서 일어날 수 있는 상황과 비교하면 지금의 구현 내용에는 보완할 점이 있다고 생각합니다. 현재는 2명이 예금 업무를 처리하기 시작한 뒤에는, 어느 하나의 은행원이 업무를 종료하더라도 다음 손님을 받을 수 없게 구성되어 있는데요. 실제 은행에서는 모든 예금 업무가 동일한 시간을 갖는 것이 아니기 때문에, 예금을 담당하는 직원이 비는 경우에 바로 다음 고객을 받을 수 있어야 한다고 생각합니다.
`OperationQueue` 가 가진 `Operation` 의 개수를 알 수 있다면, 개수가 2 미만인 경우에만 다음 `Operation` 을 추가하는 로직으로 요구사항을 쉽게 해결할 수 있다고 생각합니다. `OperationQueue` 에도 큐가 현재 가지고 있는 `Operation` 의 `count` 를 확인하는 기능이 있을 것으로 생각했으나, [공식문서](https://developer.apple.com/documentation/foundation/operationqueue/1415115-operationcount)를 확인해보니 `OperationQueue.operationCount` 는 `Deprecated` 될 예정이라고 안내하더라구요.  `Deprecated` 될 예정인 `property` 를 사용하는 것은 바람직하지 않다고 판단하여 그대로 마무리를 지은 상황입니다.
이런 경우에 혹시 활용할 만한 아이디어가 있을까요? 또는 `OperationQueue` 의 다른 활용방법이 있을지 궁금합니다.
</br>

2. 코드의 중복을 없애고 싶어서 아래와 같은 함수를 구현했었습니다. 근데 이 함수로 `BlockOperation` 을 만들고 이를 `OperationQueue` 에 추가해주는 경우에 실제 출력이 예상한 것과 다른 결과를 보여주었습니다. (메뉴 선택 출력문이 도중에 출력이 되어버리는 문제)
BlockOperation 은 OperationQueue 에서 실행할 하나의 단위를 만드는 것이기 때문에, 함수에서 이를 제작하여 돌려준다고 해서 내부의 코드가 실행되지는 않는다고 생각했었는데요. 실제 결과가 예상과 달라 조금 혼란스러웠습니다. 혹시 어떤 부분을 잘못 생각했던 것일지 궁금합니다.

```swift
// startBankingProcess 메서드 내에서
// ...
let depositCustomerBlock = createCustomerBlock(of: .deposit)
let loanCustomerBlock = createCustomerBlock(of: .loan)
// ...
```
```swift
private func createCustomerBlock(of type: BankingService) -> BlockOperation {
    let customerQueueDictionary: [BankingService: Queue<Customer>] = [
        .deposit: depositCustomerQueue,
        .loan: loanCustomerQueue
    ]
    let queueDictionary: [BankingService: OperationQueue] = [
        .deposit: depositQueue,
        .loan: loanQueue
    ]
    
    let block = BlockOperation {
        while let customerQueue = customerQueueDictionary[type], !customerQueue.isEmpty() {
            guard let node = customerQueue.dequeue() else {
                return
            }
            let customer = node.value
            let customerBlock = BlockOperation {
                self.banker.provideService(to: customer)
            }
            guard let operationQueue = queueDictionary[type] else {
                return
            }
    
            operationQueue.addOperation(customerBlock)
            if operationQueue.isSuspended {
                operationQueue.waitUntilAllOperationsAreFinished()
            }
        }
    }
    return block
}
```
</br>

3. 현재 구현에서는 main 스레드는 은행원 업무를 처리하는 동안 대기하고 있는 상황입니다. 그동안 global 스레드만 일하고 있는 상황인데요. 이런 구현은 문제가 되는 구현일까요?
</br>

2024-02-03 12:44 UTC, yim2627 requested changes
안녕하세요 댄 네로!

GCD가 아닌 OperationQueue로 구현해주시다니.. 놀랬습니다. 솔직히 저도 잘 몰라서.. 😅

우선 질문 주신 부분은 최대한 답변드리려고 했으나 부족한 부분이 있을 수 있을 것 같습니다. 우선 GCD가 아닌 OperationQueue로 작업하신 이유가 궁금하고, 이는 현재단계에서 구현이 많이 어려운 부분이기 때문에 조심스레 변경을 추천을 드려봅니다.

>요구사항을 보면 2명의 은행원이 예금 업무를 처리한다고 안내하고 있습니다. 이번 스텝에서는 이 내용을 OperationQueue 의 maxConcurrentCount 와 isSuspended 를 활용해 구현했습니다.
요구사항은 만족하고 있지만, 실제 은행에서 일어날 수 있는 상황과 비교하면 지금의 구현 내용에는 보완할 점이 있다고 생각합니다. 현재는 2명이 예금 업무를 처리하기 시작한 뒤에는, 어느 하나의 은행원이 업무를 종료하더라도 다음 손님을 받을 수 없게 구성되어 있는데요. 실제 은행에서는 모든 예금 업무가 동일한 시간을 갖는 것이 아니기 때문에, 예금을 담당하는 직원이 비는 경우에 바로 다음 고객을 받을 수 있어야 한다고 생각합니다.
OperationQueue 가 가진 Operation 의 개수를 알 수 있다면, 개수가 2 미만인 경우에만 다음 Operation 을 추가하는 로직으로 요구사항을 쉽게 해결할 수 있다고 생각합니다. OperationQueue 에도 큐가 현재 가지고 있는 Operation 의 count 를 확인하는 기능이 있을 것으로 생각했으나, [공식문서](https://developer.apple.com/documentation/foundation/operationqueue/1415115-operationcount)를 확인해보니 OperationQueue.operationCount 는 Deprecated 될 예정이라고 안내하더라구요. Deprecated 될 예정인 property 를 사용하는 것은 바람직하지 않다고 판단하여 그대로 마무리를 지은 상황입니다.
이런 경우에 혹시 활용할 만한 아이디어가 있을까요? 또는 OperationQueue 의 다른 활용방법이 있을지 궁금합니다.

우선.. OperationQueue는 작업중 Cancel등의 작업이 필요하거나, GCD에서 진행하지 못하는 복잡한 작업 상태관리를 위해 사용하곤 합니다. 그래서 이번 프로젝트엔 어울리지 않는다는 생각이 먼저 들기도 하네요 🥲operationCount 는 Deprecated가 된 배경은 저도 잘 모르겠고.. 이를 어떻게 해결해야할지는 쉽게 해결될 문제는 아닐 것 같아요. 해서 저는 현재 말씀하시는 상황을 쉽게 보완할 수 있는 GCD 및 semaphore를 사용하도록 변경하는 것이 더 도움이 되지 않을까 생각이 드네요..

>코드의 중복을 없애고 싶어서 아래와 같은 함수를 구현했었습니다. 근데 이 함수로 BlockOperation 을 만들고 이를 OperationQueue 에 추가해주는 경우에 실제 출력이 예상한 것과 다른 결과를 보여주었습니다. (메뉴 선택 출력문이 도중에 출력이 되어버리는 문제)
BlockOperation 은 OperationQueue 에서 실행할 하나의 단위를 만드는 것이기 때문에, 함수에서 이를 제작하여 돌려준다고 해서 내부의 코드가 실행되지는 않는다고 생각했었는데요. 실제 결과가 예상과 달라 조금 혼란스러웠습니다. 혹시 어떤 부분을 잘못 생각했던 것일지 궁금합니다.
// startBankingProcess 메서드 내에서
// ...
let depositCustomerBlock = createCustomerBlock(of: .deposit)
let loanCustomerBlock = createCustomerBlock(of: .loan)
// ...
 private func createCustomerBlock(of type: BankingService) -> BlockOperation {
    let customerQueueDictionary: [BankingService: Queue<Customer>] = [
        .deposit: depositCustomerQueue,
        .loan: loanCustomerQueue
    ]
    let queueDictionary: [BankingService: OperationQueue] = [
        .deposit: depositQueue,
        .loan: loanQueue
    ]
    
    let block = BlockOperation {
        while let customerQueue = customerQueueDictionary[type], !customerQueue.isEmpty() {
            guard let node = customerQueue.dequeue() else {
                return
            }
            let customer = node.value
            let customerBlock = BlockOperation {
                self.banker.provideService(to: customer)
            }
            guard let operationQueue = queueDictionary[type] else {
                return
            }
    
            operationQueue.addOperation(customerBlock)
            if operationQueue.isSuspended {
                operationQueue.waitUntilAllOperationsAreFinished()
            }
        }
    }
    return block
}

이 부분은 BlockOperation의 `addOperation()`을 함수 중간에 호출시켜버리기 때문에 도중에 출력되는 문제가 발생하는 것 같습니다. 해당 메서드의 동작 과정을 좀 더 공부해보신다면 도움이 될 것 같습니다.

>현재 구현에서는 main 스레드는 은행원 업무를 처리하는 동안 대기하고 있는 상황입니다. 그동안 global 스레드만 일하고 있는 상황인데요. 이런 구현은 문제가 되는 구현일까요?

앱내에서 UI를 담당하는 main 스레드가 특정 작업을 완료할때까지 대기상태가 되어 버린다면 앱이 죽어버리는 문제까지 발생합니다. 이는 현재 콘솔앱이여서 문제가 크게 되지 않았던 것 같지만, 실제 앱 환경에선 큰 문제가 될 수 있습니다.

2024-02-03 12:44 UTC, yim2627 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +}
👍👍

2024-02-03 12:44 UTC, yim2627 commented on BankManager.swift
> +    }()
GCD가 아닌 OperationQueue를 사용해주신 이유가 궁금합니다.
둘의 차이는 무엇일까요?

2024-02-03 12:44 UTC, yim2627 commented on BankManager.swift
> +    private func startBankingProcess(completionHandler: @escaping (_ customer: Int, _ time: Double) -> Void) {
escaping closure에 대해서 설명해주세요!

2024-02-03 12:44 UTC, yim2627 commented on BankManager.swift
> +                }
해당 부분은 어떤 동작을 기대하고 작성해주신걸까요?

2024-02-03 12:44 UTC, yim2627 commented on BankManager.swift
> +        let depositCustomerBlock = BlockOperation {
BlockOperation이란 무엇인지 설명 부탁드립니다.

2024-02-03 12:44 UTC, yim2627 commented on BankManager.swift
> +                depositQueue.addOperation(customerBlock)
`start()` 메서드 대신 `addOperation()`을 사용하면 어떤 차이가 있을까요?

2024-02-05 02:17 UTC, eensungkim commented on BankManager.swift
> +    }()
동시성을 공부하면서 참고했던 문서는 공식문서와 야곰닷넷의 [동시성 프로그래밍 강의](https://yagom.net/courses/%eb%8f%99%ec%8b%9c%ec%84%b1-%ed%94%84%eb%a1%9c%ea%b7%b8%eb%9e%98%eb%b0%8d-concurrency-programming/)였는데요. `Operation` 의 경우 `GCD` 위에서 동작하며, `GCD` 를 객체지향적으로 새롭게 재탄생시킨 high-level 의 API 라고 소개하고 있었습니다. 그리고 [(예전의) 공식문서](https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008091-CH1-SW1)를 보면 `Operation Queues` 는 Objective-C 객체를 활용해 tasks 를 캡슐화하고 실행한다고 되어있고, `Dispatch Queues` 는 C 를 기반으로 한 앱에서 tasks 를 동시에 실행하는 것이라고 안내가 되어 있었습니다.

Operation 에는 상태를 추적할 수 있는 다양한 프로퍼티가 구현되어 있기 때문에 이를 바탕으로 조금 더 섬세한 제어가 가능하다고 생각합니다. 다만 이번 Step3 에서 활용이 필요했던 부분은 아니었습니다.

`OperationQueue` 를 활용하는 것이 코드를 조금 덜 작성할 수 있고 더 깔끔하게 작성하면서도, 기능적으로 원하는 바를 구현하기에 더 용이하다고 느꼈습니다. 조언해주신 이후에 `DispatchQueue` 와 `DispatchSemaphore` 를 조합한 방법으로로 구현을 해보았는데요. `wait()`, `signal()` 을 직접 관리를 해주어야 한다는 점에서 조금 더 명령적인 프로그래밍이 된다는 느낌이었습니다. `maxConcurrentOperationCount` 를 통해 활용하게 될 스레드의 갯수 자체를 제한하는 방식이 조금 더 깔끔하다고 느꼈기 때문에 이번 Step3 에서 `OperationQueue` 를 활용하게 되었습니다. 그리고 비동기적인 작업들을 하나의 단위로 묶어내고, 이들 사이에서의 순서(dependency) 를 연결하는 과정이 더 수월했던 점도 `Operation Queue` 를 활용한 이유였습니다.

2024-02-05 02:23 UTC, eensungkim commented on BankManager.swift
> +                }
`OperationQueue.isSuspended` 프로퍼티는 큐가 현재 적극적으로 태스크를 스케쥴링 하고 있는지를 Bool 값으로 나타냅니다. `depositQueue` 는 동시에 2개까지 태스크를 돌리게 되기 때문에, 만약 2개의 작업이 현재 실행중인 상태라면 큐에 새롭게 작업들을 추가해두기 보다는 기존의 작업이 끝난 뒤에 새롭게 큐에 작업을 넣어주도록 했습니다.

해당 동작은 Step3 에서 의미가 있다기보다는, `depositQueue` 로 모든 고객 목록이 넘어가지 않도록 제한하여 Step4 에서 요구하는 업무중 대기열을 보여주기 위해 작성한 부분입니다.

2024-02-05 02:28 UTC, eensungkim commented on BankManager.swift
> +        let depositCustomerBlock = BlockOperation {
`OperationQueue` 에서 실행하는 작업의 단위인 추상화된 `Operation` 클래스를 상속받아, 실행되기를 원하는 일련의 코드들의 목록을 묶음화할 때 활용하는 클래스입니다. `Operation` 을 상속받는 별도의 `Custom Operation` 을 생성할 수도 있고, 기존에 구현된 `BlockOperation` 을 활용할 수도 있습니다.

2024-02-05 02:33 UTC, eensungkim commented on BankManager.swift
> +                depositQueue.addOperation(customerBlock)
`start()` 로 실행하는 경우는 동기냐 비동기냐에 따라 나뉩니다. 동기인 경우 현재 스레드에서, 비동기인 경우 새로운 스레드를 만들어서 `Operation` 을 처리합니다. 다만 `start()` 의 경우 `Operation` 을 수동으로 관리하고 싶을 때 제한적으로 활용할 수 있는 방법이며, 기본적으로는 `OperationQueue` 에 추가하는 것이 올바른 활용법이라고 알고 있습니다.

`addOperation()` 으로 실행하는 경우에는 `Operation` 을 각각 새로운 스레드를 만들어 실행하게 됩니다.

2024-02-05 02:41 UTC, eensungkim commented on BankManager.swift
> +    private func startBankingProcess(completionHandler: @escaping (_ customer: Int, _ time: Double) -> Void) {
클로저가 함수에 인자로써 전달되지만, 해당 함수의 리턴(종료) 이후에 호출되는 경우에 이를 `'함수를 탈출(escape) 한다'` 고 말하며, 클로저가 탈출할 수 있도록 하기 위해 `@escaping` 을 파라미터의 앞에 붙여주어야 합니다.
예를 들어 어떤 함수가 비동기적인 작업을 요청하면서 컴플리션 핸들러를 인자로 전달받아 비동기적인 작업이 완료된 이후에 실행하는 경우에, 함수는 비동기적인 작업이 마무리되기 전에 `return` 될 것이므로 해당 클로저를 탈출 클로저로 받아야 합니다.

2024-02-05 11:03 UTC, merged