은행 창구 관리 앱 [STEP 3] Andy, Sam
tasty-code/ios-bank-manager pull request #88
Opened 2024-02-05 08:54 UTC by andyanappdev

> 리뷰어 : @cherrishRed
> 
> 
> 버드 : @andyanappdev (Andy) @ParkChanH (Sam)
> 

안녕하세요 레드

벌써 STEP 3 PR 까지 진행하게 되었내요.

이번 PR Review도 잘 부탁 드립니다.

---

## Step 3 : 다중처리

- Step 3의 은행에는 3명의 은행원이 근무합니다.
    - 2명의 은행원은 예금업무를, 1명의 은행원은 대출업무를 처리합니다.
    - 고객의 업무 종류는 고객 생성시 임의로 지정합니다.
- 한 명의 은행원은 한 명의 고객을 응대할 수 있습니다.
- 고객이 원하는 업무의 종류와 소요시간은 아래와 같습니다.
    - 대출 : 1.1초
    - 예금 : 0.7초
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다.
    - "3번 고객 대출업무 시작"
- 고객의 업무를 처리하면 아래와 같이 출력합니다.
    - "11번 고객 예금업무 완료"

### STEP 핵심 경험

- 동기(Synchronous)와 비동기(Asynchronous)의 이해
- 동시성 프로그래밍 개념의 이해
- 동시성 프로그래밍을 위한 기반기술(GCD, Operation) 등의 이해
- 스레드(Thread) 개념에 대한 이해
- GCD를 활용한 동시성 프로그래밍 구현
- 동기(Synchronous)와 비동기(Asynchronous) 동작의 구현 및 적용

---

## Floder Structure

```
📦BankManagerConsoleApp
 ┣ 📂Model
 ┃ ┣ 📂LinkedListQueue
 ┃ ┃ ┣ 📜QueueProtocol.swift
 ┃ ┃ ┣ 📜LinkedListQueue.swift
 ┃ ┃ ┗ 📜DoublyLinkedList.swift
 ┃ ┣ 📜Customer.swift
 ┃ ┗ 📜Bank.swift
 ┣ 📂View
 ┃ ┗ 📜ConsoleMessage.swift
 ┣ 📂Controller
 ┃ ┗ 📜BankController.swift
 ┗ 📜main.swift
```

---

## 설계 및 구현 설명

### 주요 컴포넌트

1. **Customer (Model)**
    - 각 고객은 고유한 번호 (`waitingNumber`)를 가집니다.
    - 은행 업무 처리를 위해 대기하는 고객들을 나타냅니다.
    - (STEP 3 추가 사항) 각 고객은 고유한 업무 ( `TaskType`)를 가집니다.
2. **Bank (Model)**
    - 은행에 도착한 고객들을 **`Queue<Customer>`** 형태로 관리합니다.
    - 고객의 업무 처리 로직을 담당하며, 모든 고객이 처리되면 업무를 마감합니다.
    - (STEP 3 추가 사항, `open` method 내) 고객 생성시 교유한 업무의 종류는 임의로 설정 된다.
        - 고객의 업무 처리 시간은 고유한 업무에 따라 적용됩니다.
    - (STEP 3 추가 사항, `processCustomer` method 내)
        - `DispatchSemaphore` 를 적용하며 taskType 처리할 떄 공유 쓰레드에 동시적으로 접근하는것을 제한 하여 한 명의 은행원은 한 명의 고객을 응대할 수 있습니다.
        - `DispatchGroup()` 를 통해 대출, 예금 업무가 하나에 그룹으로 묶어서, 같이 하나의 업무 로 묶어서 처리 하도록 하였습니다.
        - `totalTime` 은 작업의 시작시간 과 끝나는 시간을 측정하여, 두 시간 간에 차이 로 총 업무시간을 구했습니다.
    - (STEP 3 추가) `handleCustomer` method
        
        - 고객의 업무처리를 직접적으로 담당하며 `Customer`에 `Task` 에 따라 맞는 작업이 처리됩니다.
        
3. **ConsoleMessage (View)**
    - 업무 시작, 업무 완료, 은행 마감 등의 상황에서 콘솔에 출력할 메시지를 정의합니다.
4. **BankController (Controller)**
    - 사용자 입력에 따라 은행의 개점과 종료를 제어합니다.
    - 사용자가 "1"을 입력하면 은행을 개점하고, "2"를 입력하면 애플리케이션을 종료합니다.

### 작업 흐름:

1. **`BankController`** 인스턴스가 생성되고, **`runBankApp()`** method를 통해 애플리케이션의 메인 루프가 시작됩니다.
2. 사용자가 "1"을 입력하면 **`Bank`** 클래스의 **`open()`** method가 호출되어 고객의 업무 처리가 시작됩니다.
3. 모든 고객이 처리되면, **`Bank`** 클래스의 **`close()`** method가 호출되어 총 처리한 고객의 수와 총 소요된 시간과 함께 업무 마감 메시지를 출력합니다.
4. 사용자가 "2"를 입력하면 App을 종료됩니다.

---

## 질문

- App 실행시 특정한 규칙이 없이 아래의 스크린샷과 같이 출력물 중간에 빈줄이 생기는 문제가 발생하였습니다.
    
![image](https://github.com/tasty-code/ios-bank-manager/assets/89269326/a8439a5c-bd95-4c25-8726-ad8bad8bce1a)

- 원인을 찾기 위해 여러 가지 시도를 해봤는데 특정한 규칙이 있는 것도 아니고 해서 원인을 정확하게 찾아 내는 것이 쉽지 않내요 ㅜㅜ
- 혹시나 해서 다른 팀들도 동일한 현상이 발생하는지 질문해 보았는데 다른 팀들도 저희와 같은 문제점을 가지고 있었습니다.
- Andy 생각 : 동시에 작업이 끝났을 경우 각 쓰레드에서 print에 접근하여 콘솔에 출력하려고 하다보니 경합상황이 발생해서 그런것이 아닌지 추측해 봅니다.
- 이 문제에 대한 레드의 의견이 궁금합니다.
- PS. Xcode Version 15.0.1 로 실행하면 문제가 발생하지 않지만 Version 15.3 으로 실행하면 발생하는 것도 잘 이해가 되지 않습니다.

2024-02-05 18:30 UTC, cherrishRed requested changes
두분 모두 수고 많으셨습니다!
벌서 STEP3까지 왔네요☺️

## 🥨 질문에 대한 답변

> App 실행시 특정한 규칙이 없이 아래의 스크린샷과 같이 출력물 중간에 빈줄이 생기는 문제가 발생하였습니다.

이 부분에 대해서는 솔직히 저도 잘 모르겠습니다. 😅
제 Xcode 는 아직 14라서 그런지, 제 맥에서는 그런 줄 현상이 나타나지는 않았는데요. 
코드상에서는 엔터가 찍힐 부분이 없고 다른 분들도 이런 현상을 겪고 있다고 하시니
아마도 Xcode 오류 일 것 같습니다. 
가끔씩 각 버전에서 고질적인 버그 같은게 있는데 아마도 그 중 하나이지 않을까… 그냥 추측해봅니다. 

## 🥨 칭찬드리고 싶은 부분 

🍞 **escaping closure의 활용** 
클로저를 적절하게 잘 사용하셔서, 비동기 코드가 잘 작동을 하는 것 같습니다!

🍞 **DispatchSemaphore 의 활용** 
`depositSemaphore` `loanSemaphore` 를 만드셔서 테스크의 종류에 따라 다른 쓰레드에서 작동하게 만드신 부분 정말 좋습니다!

## 🥨 수정하셨으면 하는 부분 
🍞**Thread.sleep**
Thread.sleep 을 다시 사용하셨더라구요. 
저번 PR에서 말씀드린 것과 같은 이유로, 쓰지 않기를 권장드립니다!
DispatchWorkItem asyncAfter Timer 등등 어느 것을 쓰셔도 좋으니, Thread.sleep 을 쓰지 않고 해결 해보세요!

2024-02-05 18:30 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/View/ConsoleMessage.swift
> +        print("\(customerNumber)번 고객 \(task)업무 완료")
`teskEndMessage` → `taskEndMessage` 
오타 있습니다!

2024-02-05 18:30 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +}
TaskType 을 만드시고, 따로 description 을 만드신 부분 좋습니다!

2024-02-06 01:52 UTC, ParkChanH commented on BankManagerConsoleApp/BankManagerConsoleApp/View/ConsoleMessage.swift
> +        print("\(customerNumber)번 고객 \(task)업무 완료")
해당부분 수정하겠습니다!! 🥹

2024-02-06 01:52 UTC, ParkChanH commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +}
감사합니다!!

2024-02-09 15:09 UTC, cherrishRed approved these changes
앤디, 쌤! 
수정하신 부분 잘 보았습니다

DispatchGroup을 사용하여 해결하신 부분 너무 좋습니다!
approve 드립니다!

2024-02-09 15:09 UTC, merged