은행 창구 관리 앱 [STEP3] L, Harry
tasty-code/ios-bank-manager pull request #90
Opened 2024-02-06 08:17 UTC by hemil0102

안녕하세요, 코든! @ictechgy 🦆

L(@LeeSe0ngYe0n), Harry(@hemil0102)입니다.
은행 창구 관리 앱 STEP23 PR 송부 드립니다.

이번 PR은 설날이 있어서 많이 미흡하지만, 모르는 부분도 많아서 기능 구현한 부분까지 보내드립니다.
왜인지 모르겠지만 콘솔에서 출력을 띄어쓰고 있는데... 은행원의 업무 순서는 제시된 요구사항대로 나오는 것 같아요. 
PR 질문란에 질문 확인 부탁드리겠습니다. 

# 🔍 What is this PR?

step2-1 Queue를 활용한 은행 대기열 구현
step2-2 타입 추상화 및 일반화

# 📝 PR Point

**1. 은행 구현에 필요한 각 객체의 역할, 책임 및 협력 구조**
<img width="674" alt="Screenshot 2024-02-06 at 4 39 46 PM" src="https://github.com/tasty-code/ios-bank-manager/assets/83139316/3663b653-332d-475a-87d6-2cc899d7d89b">
<img width="950" alt="Screenshot 2024-02-06 at 5 16 18 PM" src="https://github.com/tasty-code/ios-bank-manager/assets/83139316/b4933117-dea8-4d88-897d-bb449be9144e">

**2. Console Manager struct 타입 구현** 
**역할**
은행, 고객, 손님의 협력을 제어

**책임** 
`operate()` : 콘솔 메뉴 출력 및 입력에 따른 기능 수행
`selectedByUser()` : 콘솔 입력 받기
`triggeredBankDoorStatus()` : 콘솔 입력에 따라서 `isOpen` 은행의 영업 상태를 변경
`executeBankingOperation()` : 은행 업무 수행
`bankManager.assignEmployeeTasks()` :  은행원 업무 배정, 디스패치큐로 쓰레드를 나누는 파트
`customerManager.createCustomers()` : 손님 생성
`customerManager.registerCustomers()` :  손님 대기열 등록
`employees.handleTasks()` : 은행원1, 2 3 이 각각 해당하는 업무를 처리
`bankManager.reportDeadlineSummary()` :  은행 업무 마감 보고
`customerManager.resetCustomer()` : 은행 마감할 때 생성된 고객과 대기열을 초기화
`operate()`: 재수행을 위한 재귀적인 호출 구조 (**이런 구조가 좋은지는 잘 모르겠습니다...)**

**3. BankManager struct 타입 구현**
**역할**
고객의 업무를 맡는 은행원에게 업무(쓰레드)를 할당 및 업무 마감 보고 역할
DispatchQueue 타입의 가상의 은행원 속성을 지닌다. **(이런 구현이 좋은 것인지 잘 모르겠습니다.)**

**책임**
`reportDeadlineSummary()` : 업무 마감 보고, `Date.timeIntervalSinceReferenceDate` 활용

`assignEmployeeTasks()` :  은행원 업무 디스패키 큐를 통한 대기열 생성

**4. CustomerManager()** 
**역할**
고객의 업무를 맡는 은행원에게 업무(쓰레드)를 할당하는 및 업무 마감 보고 역할
손님, 대출 대기열, 예금 대기열 속성을 지닌다

**책임**
`createCustomers()` : 고객을 1~30에서 랜덤하게 생성하며 대출과 예금 업무도 랜덤하게 지정
`dequeueLoanCustomerFromQueue()` :  대출 대기열에 접근하기 위한 캡술화 
`dequeueDepositCustomerFromQueue()` : 예금 대기열에 접근하기 위한 캡슐화
`registerCustomers()` :  업무가 배정된 손님을 대출, 예금 대기열에 등록
`resetCustomer()` : 생성된 고객과 대기열을 초기화

**5. Customer**
**역할**
은행에 방문하는 고객, 표와 업무 속성을 지닌다. 
**책임**
`askEmployeeHandleTasks()` : 은행원이 업무 처리시 표와 처리할 업무를 전달한다. **(약간 억지로 책임을 만든 느낌이 있습니다.)**

**6. Employee**
**역할**
지정된 업무를 처리
**책임**
`handleTasks()` :  대출, 예금1, 예금2 업무를 동시에 처리하는 메서드

# 🤔 고민한 부분
**1. 객체의 역할, 책임 및 협력**
지난 STEP2에 해주신 조언에 따라서 고객에게 책임을 부여하려 했는데 굳이 필요한걸까? 라는 고민을 많이하면서 은행원이 업무를 처리할 때 표와 업무를 말해주는 듯한 책임을 만들어줬습니다. 이 부분은 혹시 생각하고 계신게 다르다면 힌트를 부탁드립니다. 이 밖에 입력을 BankManager 타입에서 분리하여 ConsoleManager 상위 타입에서 객체들간의 협업을 도모하도록 구현했습니다. 다만 콘솔 매니저 내부의 operate()를 재귀적으로 호출하는 것이 좋은 구조인지 조금 잘 모르겠습니다. 왠지 함수 안에 자기 자신을 또 호출한다는게 어색하게 느껴져서요. 

**2. 동시성 구현**
처음으로 동시성을 배워서 개념을 학습하고 구현하는 것에 애를 먹었습니다. 그래도 알려주신 내용과 명세서에 제시된 그림의 패턴을 분석하면서 거꾸로 어떤 것은 비동기이고 어떤 것은 동기일지? race condtion를 어떻게 해줄지 고민을 많이했습니다. 처음 구현할 때는 semaphore을 활용하여 업무 처리 전체를 감싸주었는데 이럴 경우 처음 순서가 정해지면 출력이 순차적으로 되었습니다. 이를 해결하고자 qos barrier나 다른 방법을 찾으려 했는데 모두 다 답은 아닌 것 같아서, 조금 더 고민을 해보았는데, 고객을 데려오는 것만 동기로 처리하고 나머지 일을 처리하는 것은 비동기로 구현한다면, 과제에서 제시된 그림의 모습으로 출력될 것이라고 생각되어 구현을 해주었습니다. 

**3. 리팩토링**
디스패치를 처음 사용해봐서 우선 가능한대로 리팩토링을 하였는데, 썩 마음에 들지 않는 것 같습니다. 어떤 식으로 해주면 깔끔할지 아직도 고민 중이고, 리뷰해주시는 와중에도 계속 생각해보고 수정해볼 생각입니다. 혹시라도 고쳐졌으면 좋은 부분이 있다면 알려주시면 감사드리겠습니다. 

❓질문
**1. 왜 출력에 공백이 생기는가?**
아래 그림 처럼 제 콘솔에서 공백이 생기면서 출력이 되는데, 갑자기 생겼다가 안생겼다가 해서 조금 왜인지 오리무중입니다.
혹시 관련 증상이 똑같이 나타나거나 어떻게 해결 해보면 좋을지 알려주실 수 있을까요? 

![Screenshot 2024-02-06 at 4 32 00 PM](https://github.com/tasty-code/ios-bank-manager/assets/83139316/3af420c7-05bd-449c-b5d2-b56c80184581)

**2. BankManager**
DispatchQueue 타입의 가상의 은행원 속성을 지니게 구현하였는데, 은행원이 DispatchQueue는 아닐 것 같은데, 여기 이 부분 이상한 것 맞겠죠? 기능 구현을 위해 일단 저렇게 해주긴 했습니다만 조금 맥락이 맞지 않는 느낌입니다. 

**3. Customer**
손님은 어떤 책임을 갖고 은행원과 소통하는게 좋아보이는지 추가 조언을 부탁드립니다. 

**4. TimeInterval 을 활용한 업무 처리 시간 구현**
```swift
       let bankingServiceStart = Date.timeIntervalSinceReferenceDate
        employees.handleTasks(with: mutableCustomerManager, bankManager: bankManager, group: group, semaphore: semaphore)
        group.wait()
        let bankingServiceEnd = Date.timeIntervalSinceReferenceDate
```
이 부분 역시 인터넷 예제를 찾아보다가 적용을 하였는데, 뭔가 하드코딩같은 스멜도 납니다. 이렇게 구현한 것에 대해서 어떻게 생각하시나요? 다른 방법으로 구현을 했어야 했을지, 조금 궁금합니다. 

🖥️ 콘솔 구동 화면

은행개점
![Screenshot 2024-02-06 at 5 08 39 PM](https://github.com/tasty-code/ios-bank-manager/assets/83139316/d280e551-bc47-4cde-ad14-23f9b94f4d83)

마감출력
![Screenshot 2024-02-06 at 5 09 17 PM](https://github.com/tasty-code/ios-bank-manager/assets/83139316/3aae8c57-93e5-4306-a78f-6ad6d986bfd5)

업무종료
![Screenshot 2024-02-06 at 5 09 43 PM](https://github.com/tasty-code/ios-bank-manager/assets/83139316/d1554e6f-12a4-4c12-b487-50ed12d3533c)

오입력시
![Screenshot 2024-02-06 at 5 10 05 PM](https://github.com/tasty-code/ios-bank-manager/assets/83139316/c03bf8a5-5c16-41f7-b999-6f4b7b145d0b)

# 감사합니다.🙏🏻

2024-02-07 19:36 UTC, ictechgy requested changes
안녕하세요 @hemil0102 , @LeeSe0ngYe0n !!   
STEP3 고생하셨습니다!     

시간이 별로 없으셨을텐데, 너무 잘 구현해주셨어요!! 👍      
아래에서는 질문주신 사항들에 대해 답변드리도록 하겠습니다. 라인별 코멘트들도 확인 부탁드려요! 😄 
(타겟 브랜치가 main으로 되어있길래 이 부분은 제가 임의 변경했습니다! 올리실 때 타겟 브랜치는 꼭 확인 부탁드릴게요~~)

<br/>

## 📝 PRPoint에서
1. `operate()`를 재귀적으로 쓰셨는데요~! 제 생각을 말씀드리기에 앞서 여쭤보고 싶은 것이 있습니다. 반복문이 아닌 재귀를 선택하신 이유가 무엇인가요?? 그 이유를 알면 제가 좀 더 명확히 답변해드릴 수 있을 것 같아요!
2. DispatchQueue 타입의 가상의 은행원 -> 이 부분은 은행원 타입(Employee)이 되면 좋을 것 같습니다! DispatchQueue는 동시성을 이용하기 위한 애플 프레임워크 타입이다보니 은행원 타입이라고 보기에는 조금 어려울 것 같습니다. Employee가 DispatchQueue를 품고 있다던지 하는 형태는 어떨까요?
3. Customer의 책임 -> 이 부분은 해당 라인 코멘트 참고 부탁드릴게요!

<br/>

## 🤔 고민했다고 해주신 부분
1. 객체의 역할, 책임 및 협력 
    - 제가 떠올렸던 형태는 Customer 내부에 작업 관련 함수가 존재하고 그 안에 `Thread.sleep`이 있는 형태였습니다. 하지만 현재 형태도 좋다고 생각합니다! 
    - 재귀적 호출에 대한 부분은 위 PRPoint쪽 질문 드린 내용 확인 부탁드릴게요!
 
2. 동시성 구현
    - race condition도 고려해주신점 너무 좋습니다!! 👍👍😆🙌
    - 현재 step에 대한 요구사항 구현은 방법이 정말 많아서 어떤게 딱 정답이다 말씀드리기는 어려울 것 같아요!
    - 다만 현재 형태에서 DispatchQueue는 Employee 내부로 이동시켜주고, BankManager에서 손님 Dequeue이후 직접 Employee에게 작업을 할당하는 방식은 어떨까 싶습니다.
    - (또다른 방법으로는) BankManager에서 DispatchQueue와 semaphore를 일종의 도구로 가지고 있고 while 반복문 내에서 queue.async등을 이용하여 employee-customer 매칭을 시키는 방식도 있을 것 같습니다.

3. 리팩토링 
    - 위에서 말씀드렸지만 정답이 딱히 없는 부분이라서요! 제가 말씀드린 내용 포함해서 여러가지 형태 더 고민해보시고 적용해보시면 될 것 같습니다.

<br/>

## ❓질문주신 내용
1. 공백 발생 문제
    - 공백은 저도 처음 보는 문제인데요! 버그가 아닌가 싶습니다. Thread.sleep에 의해 강제 개행이 일어나고 있는 것으로 보이는데 일단은 넘어가주셔도 될 것 같습니다. (usleep은 미발생하네요)
 
2. 은행원 타입
    - Employee가 은행원 타입이 되는 것이 어울릴 것 같습니다~!

3. Customer의 책임
    - 위에서 말씀드린 내용이라 넘어가도록 할게요!

5. TimeInterval 을 활용한 업무 처리 시간 구현
    - 방식이 이상한 것은 아닌데요! `timeIntervalSinceReferenceDate`를 꼭 써야 하는지는 한번 돌이켜봐주시면 좋을 것 같습니다. (잘못됐다는 것은 아닙니다!!!)

<br/>

동시성 구현이 잘못된 것은 아닌데요! Employee 타입에 대해 조금 더 고민해봐주시면 좋을 것 같아서 일단은 Request Changes로 하도록 할게요!    

고생하셨습니다~!

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    var employee_deposit2: DispatchQueue?
각각의 은행원이 DispatchQueue 타입이 되게 하셨군요!     
더불어 외부에서 참조하는 경우도 있어서 접근제어자를 빼신 것 같아요! 맞을까요?

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +        employee_deposit2 = DispatchQueue(label: "예금2", attributes: .concurrent)
attribute를 concurrent로 하셨네요! serial하게 생성하지 않고 concurrent하게 만드신 이유가 궁금합니다!

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    mutating func assignEmployeeTasks() {
은행원들을 만드는 함수인데 Task를 직원들에게 할당한다는 의미로 다가와요! 다른 이름은 어떨까요?

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +            operate()
재귀호출을 이용하셨군요! 😄👍

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +    private func triggeredBankDoorStatus(by input: String) -> Bool {
Bool값을 반환하는 함수인데 is, should, need 등과 같이 '~한가?'로 읽히는 네이밍은 어떨까요?

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +    private mutating func executeBankingOperation() {
접근 제어자들 잘 붙여주셨습니다! 👍😆

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        bankManager.assignEmployeeTasks()
직원들을 준비시키는 부분은 사실 타입 내부 initializer에서 해도 되지 않을까요?

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        customerManager.registerCustomers()
손님을 생성하고 등록하는 이 부분은 조금 더 캡슐화 할 수 있을 것 같아요!   
호출을 2번 직접 하기보다는 한번만 호출하고 customerManager가 준비에 대한 책임을 모두 가져가면 어떨까요?

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        operate()
여기 안에서 operate()를 다시 부르고 있군요!    
이 `executeBankingOperation`함수도 결국 `operate`에서 호출된 함수이기 때문에 재귀 포인트가 2곳이 생긴 것 같아요!    

다른 재실행 방식은 없을까요??!

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        let employees = Employee()
Employee는 BankManager 안에 있어야 할 것 같은데 별도로 나와있는 것이 조금은 어색해보이네요!   
`BankManager`타입 내부로 옮길 수는 없을까요??

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        employees.handleTasks(with: mutableCustomerManager, bankManager: bankManager, group: group, semaphore: semaphore)
mutableCustomerManager를 통해 타입 복사본을 넘기고 내부에서는 해당 복사본을 mutable하게 다시 한번 복사하여 사용하고 있는 것으로 보이는데요!    
이런 부분이 class를 고려해볼만한 부분이 아닌가 생각해봅니다!

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        let bankingServiceEnd = Date.timeIntervalSinceReferenceDate
`timeIntervalSinceReferenceDate`는 어떤 값을 가져오는 프로퍼티인가요?     
꼭 해당 프로퍼티를 써야하는지 한번 살펴보시면 좋을 것 같습니다!      

(그냥 `Date()`를 쓰는 방법은 어떨까요?)

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        bankManager.reportDeadlineSummary(with: customerManager, startTime: bankingServiceStart, endTime: bankingServiceEnd)
bankManager가 직접 시간값을 계산하고 출력하게 책임을 부여하신 점은 좋습니다! 👍    
다만 customerManager 인스턴스 복사본 전체를 넘겨야 하는지는 의문인데요!   

총 손님 수만 넘겨주어도 되지 않을까요?

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(customerManager.customers.count)명이며, 총 업무시간은 \(convertedTotalTime) 입니다.")
시간 계산 로직은 정확하게 잘 짜주셨어요!  😊

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/CustomerManager.swift
> +    mutating func createCustomers() {
복수형에 알맞는 좋은 네이밍 변경이네요! 😄

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/CustomerManager.swift
> +            customers.append(Customer(ticketNumber: ticketNumber, task: Task.allCases.randomElement() ?? .loan))
작업도 랜덤하게 잘 주입해주셨네요!  👏

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/CustomerManager.swift
> +            }
큐를 두개 이용해서 작업별로 분리하셨군요! 👍

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Enum/Task.swift
> +enum Task: CaseIterable {
Task라는 네이밍은 Swift async-await의 Task와 중복되는 네이밍이기 때문에 잘못 사용될 수 있을 것 같아요!   
다른 이름이나 조금 더 구체적인 네이밍은 어떨까요? (은행 업무와 같은..)

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Customer.swift
> +    private(set) var task: Task
let에서 private(set)으로 바꾸신 이유가 궁금합니다!

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Customer.swift
> +        return (ticketNumber, task)
이러한 메소드가 어떻게 보면 불필요해보일수도 있겠지만, 저는 괜찮다고 생각합니다.     
외부에서 직접 Customer에 접근해 번호표와 작업을 읽어갈 수도 있겠지만 그것이 외부에서 지녀야 하는 책임인가? 에 저는 의문이 듭니다. 그것이 자연스럽다면 이 Customer는 하나의 객체가 아니라 단순 데이터 Model에 지나지 않을까요?       

더불어 ticketNumber와 task가 private으로써 완전 은닉화를 해야하는 대상인 경우 이 메소드의 존재이유는 더 명확해질 것 같아요.

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    var employee_deposit2: DispatchQueue?
변수명은 조금 더 고민해봐주시면 좋을 것 같아요!

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Employee.swift
> +                guard let customer = mutableCustomerManager.dequeueLoanCustomerFromQueue() else { return }
이 부분은 while let 형태를 써보면 어떨까요?

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Customer.swift
> +        return (ticketNumber, task)
이와는 별도로, optional을 반환하도록 하신 이유가 있을까요??

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Employee.swift
> +                guard let customerInformation = customer.askEmployeeHandleTasks() else { return }
customer에게서 티켓넘버와 업무를 가져오는 부분은 `tuple unpacking`을 써보시면 좋을 것 같네요!

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Employee.swift
> +                semaphore?.wait()
큐에 대한 접근을 동기적으로 보장해주기 위해 semaphore를 쓰셨군요! 👍👍👍

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Employee.swift
> +                semaphore?.wait()
그런데 semaphore 인자는 왜 옵셔널로 두셨나요??  🤔

2024-02-07 19:36 UTC, ictechgy commented on BankManagerConsoleApp/Model/Employee.swift
> +            while mutableCustomerManager.depositTicketMachine.isEmpty == false {
다 잘 구현해주셨는데요! 여기에는 어떤 동기화 처리가 없어도 괜찮을까요?

2024-02-14 00:42 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    var employee_deposit2: DispatchQueue?
(접근제어) c17f9624a4557462f3f2f6a6eae81bb25886a5b5 
(변수명 변경) c688b6edcce2fa821e8e4252c971261cf571fa79
(변수명 변경2) 0a18a476579b87f299f0ee71992aad5f3dcf59ae

2024-02-14 00:45 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +        employee_deposit2 = DispatchQueue(label: "예금2", attributes: .concurrent)
주어진 명세서를 확인하였을 때 작업들이 순차적으로 처리되기 보다는 누가 먼저 일을 끝내면 일을 바로 받아와서 하는 형태로 생각되었습니다. 이 경우 serial로 업무를 처리하게 된다면, 어떤 한 대기열의 반복작업이 끝나고 다른 대기열을 실행하는 형태가 됩니다. .concurrent를 적용하면 global()에서 비동기 작업을 수행할 수 있으며, 이 경우 각각의 대기열은 서로 기다리지 않고 서로 다른 쓰레드에서 반복되는 작업을 동시에 처리할 수 있습니다.

2024-02-14 00:46 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/BankManager.swift
> +    mutating func assignEmployeeTasks() {
해당 메서드는 구조 변경으로 삭제되었습니다.

2024-02-14 00:46 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +    private func triggeredBankDoorStatus(by input: String) -> Bool {
변경 사항 적용: 86ca72265225fb6a04a97e299bde17ef1d788bf0

2024-02-14 00:48 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +    private func triggeredBankDoorStatus(by input: String) -> Bool {
감사합니다! isOpen이 있어서 메서드도 비슷하게 하면 뭔가 읽히는게 is가 두번이라 이상할 것 같아 should로 적용했습니다! 

변경 사항 적용: 86ca72265225fb6a04a97e299bde17ef1d788bf0

2024-02-14 00:49 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +    private mutating func executeBankingOperation() {
감사합니다!!

2024-02-14 00:53 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        bankManager.assignEmployeeTasks()
사실... 역할 책임 협력에 몰입하다보니 메서드로 만들어주게 되었는데... init도 생성하는 메서드이니까... 그...그렇게 해주었습니다!
동시에 직원이 생성되면서 업무를 같이 배정 받도록 해주었습니다. 

변경 사항 적용: c688b6edcce2fa821e8e4252c971261cf571fa79

2024-02-14 00:54 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        customerManager.registerCustomers()
감사합니다. 메서드별로 약간 조금 책임을 1가지씩 분리하라고 들었어서 그렇게 해주었는데, createCustomer()를 prepareCusotmer()에 넣어주면서 구조 변경하였습니다.

변경 사항 적용: 136ade72dbe095b6db7fbcb897cfc1ec3e72ccb5

2024-02-14 00:57 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        operate()
다른 재실행 방식으로 변경해주었습니다,
만들다보니 저렇게 되었는데 다시 생각해보니 빼낼 수 있었습니다.

변경 사항 적용: 0307ec6d7776b36ad241dc6c6a6dfc9663725dc9

2024-02-14 00:57 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        let employees = Employee()
아래 커밋으로 구조 변경 해주었습니다. 

변경 사항 적용: c23979ae2a4563542e1248cf859a2e0e6a570238

2024-02-14 01:01 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        employees.handleTasks(with: mutableCustomerManager, bankManager: bankManager, group: group, semaphore: semaphore)
우와, 이런 부분 때문에 class를 사용한다는 사실을 알게되어서 정말 놀랍네요! 구조를 변경하면서 생각해보니 struct에서 속성을 함수로 변경해줄 때 mutating 하는 것도 메모리 관점에서는 값을 복사해서 교체하는 것이라고 과정 멘토가 설명해준 적이 있는데, 클로저에서 캡처하는 것도 약간 비슷한 맥락 처럼 느껴집니다. 클로저도 어떻게 보면 코드 블럭으로 더 넓은 범위의 함수라 설명을 본 것 같아서요. 이 부분을 조금 더 명확하게 찾아보고 싶었는데, 조금 어딜 보면 좋을지 아직 못찾았지만 혹시라도 공부할 문서가 있다면 공유 부탁드려요! 

변경 사항 적용: c23979ae2a4563542e1248cf859a2e0e6a570238

2024-02-14 01:10 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        let bankingServiceEnd = Date.timeIntervalSinceReferenceDate
음 해당 프로퍼티는 **Swift(애플)에서의 기준 시간(Reference Date)은 2001.1.1.00:00:00 UCT**을 기준으로 현재 시간의 차이를 가져오는 값입니다. 블로그에 소개 되어 있길래 가져왔고, 뭔가 애플 기준 시간이라길래 더 정확하지 않을까 생각했습니다. 

그렇지만 추가 공부를 위해 Date()를 쓰는 방법을 강구해보았습니다만, Formatter로 변환해줘서 구현해줄 수도 있을 것 같은데, 굳이 현 상황에서는 date()로 가져온 값을 변환해주고 거기서 값을 연산할 필요를 느끼질 못하겠습니다. 단지 차이만 계산하면 되는 것이어서 초단위의 값을 반환해주는 `timeIntervalSinceReferenceDate` 또는  물론 연습 차원에서 해볼 수 있을 것 같은데…  

혹시 Date()를 쓰는게 더 이점인게 있는 것인가요?

2024-02-14 01:11 UTC, hemil0102 commented on BankManagerConsoleApp/Controller/ConsoleManager.swift
> +        bankManager.reportDeadlineSummary(with: customerManager, startTime: bankingServiceStart, endTime: bankingServiceEnd)
말씀해주신대로 변경하였습니다. 혹시 함수 파라미터를 넘길 때는 말씀해주신 것 처럼 작은 단위로 넘겨주는 것을 선호하는 편인가요? 혹시 큰 것을 넘기면 오고가는게 커져서 성능에 이슈가 있어서 그런 것일까요? 

변경 사항 적용: bdb8691fdf058966d54551425e3139b91d488ebc

2024-02-14 01:12 UTC, hemil0102 commented on BankManagerConsoleApp/Enum/Task.swift
> +enum Task: CaseIterable {
BankingService로 변경해주었습니다! 

변경 사항 적용: 86ca72265225fb6a04a97e299bde17ef1d788bf0
변경 사항 적용: 27ef71bd03c818c757e8a47a9a44977cbfd34ec3

2024-02-14 01:13 UTC, hemil0102 commented on BankManagerConsoleApp/Model/Customer.swift
> +    private(set) var task: Task
처음에는 책임이 없고 let으로 간단하게 구현을 위해 적용을 해주었는데, 책임을 부여하면서 은닉화 캡슐화를 생각해보면서 구조를 현재는 변경한 상태입니다. 

변경 사항 적용: 91ab88753fd8a8ad4b48f6a18b633401f99328b0

2024-02-14 01:17 UTC, hemil0102 commented on BankManagerConsoleApp/Model/Customer.swift
> +        return (ticketNumber, task)
옵셔널을 적용한 이유는 고객이 표를 뽑았어도 기계 고장으로 기록이 안되거나 어떤 오류적인 상황이 뒤로 넘겨질 수 있다는 가정하에 옵셔널을 적용하려고 했습니다. 현재는 표와 업무에도 옵셔널을 적용하였고 또 이 두 값을 감싸는 튜플 형태도 옵셔널로 감쌌습니다. 따라서 어떤 전달 과정에서 옵셔널을 꺼내오면서 은행 업무 처리할 수 없다는 판단이 들면 작업을 처리하지 않는 것이 의도입니다! 

변경 사항 적용: 0805c84bf522d005be2ac45fa05ba22ba9913906
변경 사항 적용: 1e12fd6d973e65c2b4307c9c78f226acf52f1806

2024-02-14 01:18 UTC, hemil0102 commented on BankManagerConsoleApp/Model/Employee.swift
> +                guard let customer = mutableCustomerManager.dequeueLoanCustomerFromQueue() else { return }
오! 예전에 써봤는데 자주 사용하지 않아서 기억에 잘 남지 않았던 것 같은데 덕분에 적용해줬습니다.

변경 사항 적용: a2b35000c7cff9bf074fc50e4e272ef8a631c4e5

2024-02-14 01:18 UTC, hemil0102 commented on BankManagerConsoleApp/Model/Employee.swift
> +                guard let customerInformation = customer.askEmployeeHandleTasks() else { return }
적용해주었는데 맞게 해주었는지는 잘 모르겠습니다! 

변경 사항 적용: 0805c84bf522d005be2ac45fa05ba22ba9913906
변경 사항 적용: 1e12fd6d973e65c2b4307c9c78f226acf52f1806

2024-02-14 01:19 UTC, hemil0102 commented on BankManagerConsoleApp/Model/Employee.swift
> +                semaphore?.wait()
아 여기는 원래 loan은 semaphore을 사용하지 않아서 기본값 nil로 두고 쓰는 애들은 값을 넣어주게 구현하려다가, 구조가 변경되었는데 삭제가 안된 부분입니다. 지금은 함수를 두개로 나눠서 필요가 없어져서 옵셔널 삭제했습니다. 아 그런데 리팩토링을 하다보니 좀 더 유기적으로 은행원 업무 할당 시키고 그에 맞는 일을 동기 비동기를 선택해서 사용할 수 있게 구현하면 좋을 것 같다는 생각이 드네요.

변경 사항 적용: a2b35000c7cff9bf074fc50e4e272ef8a631c4e5
변경 사항 적용: 42f37008714639ee2b6ea32b6d1201a4e89073ae

2024-02-14 01:20 UTC, hemil0102 commented on BankManagerConsoleApp/Model/Employee.swift
> +            while mutableCustomerManager.depositTicketMachine.isEmpty == false {
생각해보니 이 부분도 확인 자체를 동시에 할 race condition이 우려되서 말씀해주신 것 같은데 맞나요? 그래서 세마폴을 앞 당겨서 적용했는데, 이런 식으로도 세마폴을 적용하는게 좋은 것인지는 조금 잘 모르겠고 제가 질문을 잘 캐치한건지 모르겠지만, 아니라면 답변 부탁드립니다! 

변경 사항 적용: a2b35000c7cff9bf074fc50e4e272ef8a631c4e5

2024-02-14 01:29 UTC, hemil0102 commented
안녕하세요 @hemil0102 , @LeeSe0ngYe0n !! STEP3 고생하셨습니다!

시간이 별로 없으셨을텐데, 너무 잘 구현해주셨어요!! 👍 아래에서는 질문주신 사항들에 대해 답변드리도록 하겠습니다. 라인별 코멘트들도 확인 부탁드려요! 😄 (타겟 브랜치가 main으로 되어있길래 이 부분은 제가 임의 변경했습니다! 올리실 때 타겟 브랜치는 꼭 확인 부탁드릴게요~~) 

## 📝 PRPoint에서
1. `operate()`를 재귀적으로 쓰셨는데요~! 제 생각을 말씀드리기에 앞서 여쭤보고 싶은 것이 있습니다. 반복문이 아닌 재귀를 선택하신 이유가 무엇인가요?? 그 이유를 알면 제가 좀 더 명확히 답변해드릴 수 있을 것 같아요!
> 해당 부분은 원래 반복문으로 구현하다가 isOpen과 ConsoleManager를 구현하면서 구조가 변경되어서 재귀로 되었습니다. 선택을 했다기 보다는 구현하다보니 되었는데, 다시 또 반복문으로 구현해주고 싶었는데 재귀 구조도 괜찮은건가? 리뷰를 받아보면 좋을 것 같아서 남겼습니다! 

2. DispatchQueue 타입의 가상의 은행원 -> 이 부분은 은행원 타입(Employee)이 되면 좋을 것 같습니다! DispatchQueue는 동시성을 이용하기 위한 애플 프레임워크 타입이다보니 은행원 타입이라고 보기에는 조금 어려울 것 같습니다. Employee가 DispatchQueue를 품고 있다던지 하는 형태는 어떨까요?
> 아래 해주신 코멘트에 반영하였습니다! 

3. Customer의 책임 -> 이 부분은 해당 라인 코멘트 참고 부탁드릴게요!
> 아래 해주신 코멘트에 반영하였습니다! 

## 🤔 고민했다고 해주신 부분
1. 객체의 역할, 책임 및 협력
  * 제가 떠올렸던 형태는 Customer 내부에 작업 관련 함수가 존재하고 그 안에 `Thread.sleep`이 있는 형태였습니다. 하지만 현재 형태도 좋다고 생각합니다! * 재귀적 호출에 대한 부분은 위 PRPoint쪽 질문 드린 내용 확인 부탁드릴게요!
> 위에 코멘트 확인 부탁드립니다! 

2. 동시성 구현
* race condition도 고려해주신점 너무 좋습니다!! 👍👍😆🙌
* 현재 step에 대한 요구사항 구현은 방법이 정말 많아서 어떤게 딱 정답이다 말씀드리기는 어려울 것 같아요!
* 다만 현재 형태에서 DispatchQueue는 Employee 내부로 이동시켜주고, BankManager에서 손님 Dequeue이후 직접 Employee에게 작업을 할당하는 방식은 어떨까 싶습니다. (DispatchQueue-Employee 1:1 매칭 형태)

* (또다른 방법으로는) BankManager에서 DispatchQueue와 semaphore를 일종의 도구로 가지고 있고 while 반복문 내에서 queue.async등을 이용하여 employee-customer 매칭을 시키는 방식도 있을 것 같습니다. (DispatchQueue-Employee 1:N 매칭 형태)
* (방법3) 개별 은행 작업(예금, 대출 등)별로 DispatchQueue를 나누고 이에 Employee를 작업시키는 방법도 있습니다. (DispatchQueue-Employee N:N 매칭 형태) ➡️ 개인적으로 저는 이 형태가 가장 좋은 것 같습니다.
> 오 이 부분 생각할 부분이 많은 것 같아서 감사합니다! 약간 컴공 수업을 들으면 이렇게 구현하는게 좋다고 알려준다고 하는 것 같은데... 아직은 머리 속에 잘 그려지질 않는데 해주신 코멘트들 참고해서 구조를 짬짬히 바꿔볼게요. 지금은 다음 프로젝트 진도가 나가고 처리할게 있어서, 아 뭔가 이게 유연한 것 같아서 해보고 싶은데 짬짬히 해보겠습니다. 

3. 리팩토링
* 위에서 말씀드렸지만 정답이 딱히 없는 부분이라서요! 제가 말씀드린 내용 포함해서 여러가지 형태 더 고민해보시고 적용해보시면 될 것 같습니다.

> 감사합니다! 

## ❓질문주신 내용
1. 공백 발생 문제

* 공백은 저도 처음 보는 문제인데요! 버그인 것 같습니다. Thread.sleep에 의해 강제 개행이 일어나고 있는 것으로 보이는데 일단은 넘어가주셔도 될 것 같습니다. (usleep은 미발생하네요)
> 오 버그 같다니 다행입니다. 감사합니다! 

2. 은행원 타입
* Employee가 은행원 타입이 되는 것이 어울릴 것 같습니다~!
> 수정 해주었습니다! 

3. Customer의 책임
* 위에서 말씀드린 내용이라 넘어가도록 할게요!

4. TimeInterval 을 활용한 업무 처리 시간 구현
* 방식이 이상한 것은 아닌데요! `timeIntervalSinceReferenceDate`를 꼭 써야 하는지는 한번 돌이켜봐주시면 좋을 것 같습니다. (잘못됐다는 것은 아닙니다!!!)
> 아래 코멘트 달았습니다!

동시성 구현이 잘못된 것은 아닌데요! Employee 타입에 대해 조금 더 고민해봐주시면 좋을 것 같아서 일단은 Request Changes로 하도록 할게요! 
고생하셨습니다~!

> 리뷰 감사드립니다~~ 건강 잘 챙기시고 새해 복 많이 받으세요!

2024-03-17 10:04 UTC, closed without merging