은행 창구 관리 앱 [STEP3] Jin, Loffy
tasty-code/ios-bank-manager pull request #91
Opened 2024-02-06 11:46 UTC by wlsdud-dev

리뷰어: 다나 @songda515

버드: Jin @wlsdud-dev, Loffy @kimdj1102

---
안녕하세요~ 다나!

Jin, Loffy 입니다! 은행 창구 관리 앱 STEP3 PR 보냅니다!
프로젝트 중 Loffy의 건강상태가 좋지 못하여서 의논은 같이 했지만
작업은 Jin이 할 수 밖에 없었습니다.
이번 은행 관리 앱 프로젝트는 STEP3를 최종 목표로 진행 하였습니다.

## 프로젝트 구현 요구사항

### **Step 3 : 다중처리**

- Step 3의 은행에는 3명의 은행원이 근무합니다.
    - 2명의 은행원은 예금업무를, 1명의 은행원은 대출업무를 처리합니다.
    - 고객의 업무 종류는 고객 생성시 임의로 지정합니다.
- 한 명의 은행원은 한 명의 고객을 응대할 수 있습니다.
- 고객이 원하는 업무의 종류와 소요시간은 아래와 같습니다.
    - 대출 : 1.1초
    - 예금 : 0.7초
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다.
    - "3번 고객 대출업무 시작"
- 고객의 업무를 처리하면 아래와 같이 출력합니다.
    - "11번 고객 예금업무 완료"

## 🤔고민이 되었던 점

### 동기와 비동기

step3는 은행원이 3명이고 각각 비동기로 처리하며 3명이 작업을 하는 도중에는 작업 처리를 미뤄야 한다는 조건이 상당히 어려운 부분이였습니다.

```swift
var depositWatingQueue = CustomerQueue<Customer>()
var loanWatingQueue = CustomerQueue<Customer>()

let depositSemaphore = DispatchSemaphore(value: 2)
let loanSemaphore = DispatchSemaphore(value: 1)

let watingGroup = DispatchGroup()
```

예금과 대출을 서로 나눠 처리 하기 위해 큐를 두개를 만들어 주었고
`Semaphore`를 이용해 `DispatchQueue`가 작업을 진행중이라면 접근을 막아 주었습니다.

`DispatchGroup` 를 이용해 비동기의 끝나는 시점에 대해 처리해 주었습니다.

**구현도중 시행착오를 겪은 부분**

1. `DispatchQueue` 를 호출하는 위치와 `Semaphore`의 위치에 난항을 겪었습니다.
2. 비동기의 끝난 시점을 캐치하는 방법
    
    `watingGroup.notify` 를 사용해 캐치하여 처리하려고 했지만 의도대로 동작하지 않았습니다.
    그래서 `watingGroup.wait()` 를 사용하여 구현은 했지만 `Semaphore` 의 동작이 제대로 되지 않는 상황입니다.
```swift
private func resetSetting() {
        depositSemaphore.signal()
        loanSemaphore.signal()
    }
```
    

### MVC패턴

콘솔창을 View라고 가정하고 MVC패턴을 적용 하였습니다.
MVC패턴을 잘 적용한건지 의문이 들었고 Bank가 너무 많은 책임과 일을 하는거 아닌가 라는 생각이 듭니다.

### 클래스와 구조체

클래스와 구조체를 이해 했다고 생각 했는데 이번 STEP3를 진행하면서 한참 모자라다는걸 깨달았습니다.
탈출 클로저와 구조체에서의 `[self] in` 이 왜 필요하고 클로저 안에서 구조체의 프로퍼티 접근을 하려면 어떻게 해야하는지 알지 못했습니다.
지역변수 였던 고객 카운트를 없애고`self.customerCount = Int.random(in: 10...30)` 로 실제 `dequeue`가 이뤄졌을때 카운트 값을 증가시키지는 못했습니다.

2024-02-06 16:21 UTC, songda515 requested changes
STEP3 작업하시느라 고생 많으셨습니다! 🙌

프로젝트를 다운받아 상세히 확인해보려고 했는데, 파일이 하나 누락되어 실행되지 않고 있습니다! 이점 먼저 수정해주시면 다시 확인해볼 수 있을 것 같아요.

동기와 비동기 관련해서는 고민해주신 부분에 대해 잘 캐치하지 못한 것 같아, 추가 질문 남겨두었습니다 🙂 다른 부분들은 개별 코멘트로 답변드렸습니다~!

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/View/BankView.swift
> +    func printConsolView(message: Any, terminator: String?)
message 파라미터는 String 이어도 될 것 같은데, Any 로 선언하신 이유가 있을까요?

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +    let task: Banking
task 받아서 처리될 수 있도록 잘 추가해주셨네요! 🙌

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +}
프로토콜로 필수 기능에 대해 잘 정의해주셨네요!
나중에 공통적으로 사용될 수 있으면 좋겠네요 🙌

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +		F3CE19072B72262B000FC3F0 /* BankingList.swift in Sources */ = {isa = PBXBuildFile; fileRef = F3CE19062B72262B000FC3F0 /* BankingList.swift */; };
BankingList 파일이 프로젝트에는 추가가 된것 같은데, 실제 추가된 코드를 찾을수가 없네요 🤔
`Banking` 타입에 대해 누락되어 코드 실행이 어려운 상태입니다. 추가적으로 반영 부탁드릴게요!

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            guard let customer = depositWatingQueue.dequeue() else { return }
고민해주신 부분중에 `[self] in` 가 왜 필요한지에 대해서는 `escaping closures` 와 관련된 부분들을 보면 도움이 될 것 같아서 링크 남겨둡니다!
- https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/#Escaping-Closures
- https://developer.apple.com/documentation/dispatch/dispatchqueue/2016098-async


escaping closure 는 함수의 범위를 벗어나서 실행되기 때문에, self 를 캡쳐해야한다는 점을 확인해주시면 좋을 것 같아요.
그리고 이렇게 캡쳐된 self 가 클래스와 구조체에 따라 어떤 차이가 발생될지는 추후에 살펴보시면 더 더 좋을것 같아요! 👍 
- 이부분은 이번 스텝의 경험과 다를 수 있기 때문에 참고차 링크만 남겨둡니다!
- https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Strong-Reference-Cycles-for-Closures

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        self.customerCount = Int.random(in: 10...30)
고민사항에 적어주신 아래 부분이 잘 이해가 안돼서 자세히 설명해주실 수 있을까요?
> 지역변수 였던 고객 카운트를 없애고self.customerCount = Int.random(in: 10...30) 로 실제 dequeue가 이뤄졌을때 카운트 값을 증가시키지는 못했습니다

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/CustomerQueue.swift
> +class CustomerQueue<T: Equatable> {
Queue 를 struct 에서 class 로 변경하셨던 이유는 어떤건가요?? 👀

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +    let bankView: BankViewProtocol
MVC 패턴을 잘 적용해주셨다고 생각하는데요!
View 에 유저의 인풋을 받는 `readLine` 도 포함될 수 있지 않을까싶네요!

그리고 현재는 콘솔이라서 View 에 그려지는 부분이 없어 더욱 로직만 있는 Controller 에 있는 로직만 더 돋보이긴 하는것 같아요.
사실 MVC 패턴에서는 로직이 Controller 에만 있기 때문에 콘솔이 아닌 ViewController 를 사용할때에도 동일한 고민이 드실 수 있어요.
추후에 MVVM, MVI, MVP 등의 패턴에 대해서 찾아보시는걸 추천드릴게요!

2024-02-06 16:21 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        watingGroup.wait()
watingGroup.notify 관련해서 고민 적어두셨는데, 의도대로 동작이 안됐을때의 코드가 아래처럼이 맞을까요? 👀
시도했던 코드와 어떤 곳에서 의도대로 동작하지 않았는지 자세하게 적어주심 좋을 것 같아요!

```swift
        watingGroup.notify(queue: DispatchQueue.global()) { [self] in
            let totalTime = caculateProcessingTime(startTime)
            BankManager().sendWorkingMessage("\(BankMessage.result(customerCount, totalTime).description)")
            resetSetting()
        }
```

2024-02-07 07:31 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +		F3CE19072B72262B000FC3F0 /* BankingList.swift in Sources */ = {isa = PBXBuildFile; fileRef = F3CE19062B72262B000FC3F0 /* BankingList.swift */; };
구현을 해보고 옮겨서 Git 작업을 하다보니 파일이 빠진줄 몰랐습니다. 좀 더 효율적이고 안전성 있는 방법을 찾아보겠습니다.
현재 구동 가능할 수 있도록 푸시 했습니다.

2024-02-08 05:08 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        watingGroup.wait()
```swift
watingGroup.notify(queue: .main) { [self] in
    let totalTime = caculateProcessingTime(startTime)
    BankManager().sendWorkingMessage("\(BankMessage.result(customerCount, totalTime).description)")
}
```

비동기 작업이 모두 끝났을때 고객의 수와 총 업무의 시간을 출력 해주기 위해 `async(group: watingGroup)` 그룹을 만들어 주었고 `watingGroup.notify(queue: .main)` 끝났을때 메시지 출력을 위해 메인 스레드에 알림을 보내주는 코드를 넣어 줬습니다. 하지만 클로저가 실행되지 않고 그냥 메서드가 끝나버립니다.

그래서 `.wait()` 을 사용 했지만 이 마저 세마포어의 값이 이상하게 동작하는것을 확인 했습니다.
`depositSemaphore,` `loanSemaphore` 세마포어의 값을 각각 2, 1로 선언 해주었는데 은행을 개시하면
세마포어의 값이 1, 0으로 변경되어 다시 개점을 실행하면 예금 업무를 2번 진행하고나서 아무 동작을 하지 않게 됩니다. 정상 동작을 위해 `.wait()` 에서 세마포어의 값을 한번 더 증가시켜주는데 올바른 처리 방식이 아니라 방안을 찾아봤는데 찾지 못했습니다.

2024-02-08 05:10 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/CustomerQueue.swift
> +class CustomerQueue<T: Equatable> {
```swift
private mutating func workDepositFirst() {
    guard !depositWatingQueue.isEmpty() else { return }
    depositSemaphore.wait()
    DispatchQueue.global().async(group: watingGroup) { [self] in
        guard let customer = depositWatingQueue.dequeue() else { return }
        BankManager().sendWorkingMessage("\(BankMessage.start(customer.number, "예금").description)")
        depositClerkFirst.depositWorking()
        depositSemaphore.signal()
        BankManager().sendWorkingMessage("\(BankMessage.done(customer.number, "예금").description)")
    }
}
```
`queue`의 `dequeue`를 하는 위치는 비동기로 처리하는 부분에서 `dequeue`를 하는게 맞다고 판단 했습니다. 그래서 `DispatchQueue.global().async` 클로저 안에서 `dequeue`를 실행 하였지만 큐의 타입이 구조체라 `Escaping closure captures mutating 'self' parameter`                                                                                                                                                                                                                                         에러가 발생하였고 `[**self**] in` 을 넣어줬지만 이번에는`Cannot use mutating member on immutable value: 'self' is an immutable capture` 라는 에러로 구조체로는 구현이 안되어 큐를 클래스로 바꾸었습니다.
구조체로 구현하려면 어떻게 해야하고 클래스와는 어떤 차이점이 있는건지 공부의 부족함을 느끼는 부분입니다.

2024-02-08 05:11 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        self.customerCount = Int.random(in: 10...30)
업무 처리를 했을때 (`DispatchQueue.global().async` 비동기 작업이 이뤄졌을때 ) 고객카운트 값을 증가시켜주고 싶었는데 `Left side of mutating operator isn't mutable: 'self' is an immutable capture` 에러로 비동기 작업 중에 카운트값을 증가시켜주지 못하고 고객의 수를 선언 해줄 때 값을 가져오는 방식으로 구현했습니다. 비동기 안에서 값을 증가시켜 주려면 어떤 방식으로 구현을 해줘야 할까요?

2024-02-08 05:49 UTC, wlsdud-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/View/BankView.swift
> +    func printConsolView(message: Any, terminator: String?)
swift에 print 함수와 똑같이 구현  해주고 싶었습니다.  print 함수가 any를 받아 any로 선언 해주었습니다.

```swift
struct BankView: BankViewProtocol {
    
    func printConsolView(message: Any..., terminator: String?) {
        if let terminator = terminator == nil ? "\n" : terminator?.description {
            print(message, separator: " ", terminator: terminator)
        }
    }
}

func printConsolView(message: String..., terminator: String?) {
    if let terminator = terminator == nil ? "\n" : terminator?.description {
        for string in message {
            print(string, terminator: terminator)
        }
    }
}
```
String으로 만들어 주는게 좋을까요?

2024-02-08 13:54 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/View/BankView.swift
> +    func printConsolView(message: Any, terminator: String?)
아하!! print 메소드랑 동일하게 하고싶으셨다면 괜찮을것 같습니다!
지금은 인자가 string 뿐인데, 다른것도 고려하신건가 해서 질문드렸어요 🙂

2024-02-08 13:57 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/CustomerQueue.swift
> +class CustomerQueue<T: Equatable> {
첫번째는 다른 코멘트로 남겨드렸던 링크 확인해주시면 될 것 같구요!
- https://github.com/tasty-code/ios-bank-manager/pull/91#discussion_r1480030055

두번째 이유에 대해서는 구조체는 value type, 클래스는 reference type 이라는 차이점을 키워드로 잡고 공부해보시면 좋을 것 같습니다! 요번 에러메세지를 통해서 배우신점이 더 많을거라 부족하다고 느끼지 않으셔도 괜찮아요 🙌

2024-02-08 14:13 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        self.customerCount = Int.random(in: 10...30)
여기서도 동일하게 Bank 가 구조체이고, customerCount 의 타입 Int 도 값 타입때문에 발생하는게 첫번째 이유입니다!
클로저에서는 캡쳐한 [self] 는 일반적으로 변경할 수 없는 형태이기 때문에, 값을 변경해줄 수 없게 된걸로 보여요.

- 해결하기 위해서는 Bank 를 클래스로 변경하거나,
- Bank 는 구조체로 두고 customerCount 를 담는 클래스의 인스턴스를 갖고있다가 변경하거나
- 두가지 방법이 있을것 같아요!

Queue 를 구조체에서 클래스로 변경했을때 값이 변경가능해졌던 점과 같이 고민해보시면 좋을것 같아요 🙏

2024-02-08 15:08 UTC, songda515 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        watingGroup.wait()
작업의 개시가 다 끝날때까지 `excuteBankWork` 메소드에서 기다리려면 `watingGroup.wait()` 도 좋은 방향인것 같습니다! 

- 기존 코드에서는 두번째 실행시 `depositSemaphore.wait()` 등의 시점에서 항상 기다리지만 signal 을 받지 못한 세마포어가 있어서 Deadlock 상황이 발생한것으로 보여요.

- 요 부분을 저도 자세히는 몰라서 테스트해봤는데요. semaphore 의 wait 해주는 시점에서 차이가 발생하고 있어요. 
- 아래처럼 `depositSemaphore.wait()` 의 시점을 async 내부로 변경했을 때엔 정상적으로 동작하는것으로 보입니다. 

```swift
private mutating func workDepositFirst() {
    guard !depositWatingQueue.isEmpty() else { return }

    DispatchQueue.global().async(group: watingGroup) { [self] in
        guard let customer = depositWatingQueue.dequeue() else { return }
        depositSemaphore.wait()
        BankManager().sendWorkingMessage("\(BankMessage.start(customer.number, "예금").description)")
        self.depositClerkFirst.depositWorking()
        self.depositSemaphore.signal()
        BankManager().sendWorkingMessage("\(BankMessage.done(customer.number, "예금").description)")
    }
}
```

- 공식 문서는 아니지만 [여기 링크](https://velog.io/@gosari/swift-semaphore.wait%EC%9D%98-%EC%9C%84%EC%B9%98%EC%97%90-%EB%94%B0%EB%A5%B8-%EC%9E%91%EB%8F%99-%EC%B0%A8%EC%9D%B4
)의 내용을 살펴보고 학습 및 테스트해보시면 좋을 것 같아요 🙏

2024-02-08 15:12 UTC, songda515 approved these changes
추가적으로 질문 답변해주셔서 감사합니다! 이번 프로젝트 고생많으셨어요 🙌

2024-02-08 15:12 UTC, merged