은행 창구 관리 앱 [Step3] 노움, 토미
tasty-code/ios-bank-manager pull request #93
Opened 2024-02-07 02:08 UTC by angryeon7

> 리뷰어 : @keeplo
버드 : @angryeon7 (토미) @Gnoam-R (노움)
> 

안녕하세요-!-! 말꼬
PR을 늦게 보내게되어서 정말 죄송해요😢  즐거운 하루 보내세요🍀

---

## 고민한 부분

DispatchSemaphore의 value를 해당 업무를 할 수 있는 은행원의 수라고 생각하여 구현했습니다.
**테스트 더미데이터 추가하여 테스트를 해보았습니다.**

```swift
let test = [
            Customer(number : 0, purpose: .deposit),
            Customer(number : 1, purpose: .deposit),
            Customer(number : 2, purpose: .loan),
            Customer(number : 3, purpose: .loan ),
            Customer(number : 4, purpose: .loan),
            Customer(number : 5, purpose: .loan),
            Customer(number : 6, purpose: .loan),
            Customer(number : 7, purpose: .loan),
            Customer(number : 8, purpose: .deposit),
            Customer(number : 9, purpose: .deposit),
            Customer(number : 10, purpose: .deposit),
            Customer(number : 11, purpose: .loan),
            Customer(number : 12, purpose: .loan)
        ]
```
<img width="521" alt="스크린샷 2024-02-07 오전 5 06 24" src="https://github.com/tasty-code/ios-bank-manager/assets/87401351/6daa552d-e954-4748-95f2-5617f1707d29">

**예금업무라서 대출업무와 무관하게 실행되어야 하는데, 1번 고객이 수행되고 모든 대출업무가 끝난후 8번업무가 수행되는 문제가 발생함**

변경 후의 코드는 수정 전과 비슷한 동작을 수행하지만, `while let customer = self.waitingQueue.dequeue()`를 사용하여 대기 중인 고객이 있는 동안 반복하는 것으로 변경하면서 고객이 처리되는 순서는 대기열에서 빠져나온 순서대로 처리되고
수정 전 코드에서는 대출(loan)과 예금(deposit) 업무를 병렬로 처리하기 위해`DispatchQueue.global().async(group: group)` 내에서 각각의 업무를 동시에 실행합니다. 따라서 대출과 예금 업무가 동시에 여러 개씩 처리될 수 있습니다. 
그러나 세마포어를 통해 동시에 처리 가능한 업무의 개수를 제한하고 있기 때문에, 예를 들어 대출 업무가 먼저 처리되어도 세마포어에 의해 예금 업무가 대기하게 됩니다. 

이러한 이유로, 수정 전 코드에서는 대출과 예금 업무가 번갈아가면서 처리되지 않고, 한 종류의 업무가 모두 처리된 후에 다른 종류의 업무가 처리되는 현상이 발생하였습니다. 따라서 이 부분을 수정하였습니다.

 `DispatchGroup`을 사용하여 모든 비동기 작업이 완료될 때까지 대기하고, 그 후에 작업 시간을 계산하였습니다.
## 🧐 조언을 얻고 싶은 부분
 
 비동기 처리를 하는 방법들중 저는 `OperationQueue`를 사용해서 비동기 처리를 진행 했습니다.

`OperationQueue`안에 은행원의 여러 업무 처리 Task를 넣고 업무 별로 쓰레드를 할당하여 관리 하고자 했습니다

`GCD`를 사용하는 경우 업무별 쓰레드 할당하는 방법으로 `Semaphore` 기능을 사용합니다.

```swift
let depositSemaphore = DispatchSemaphore(value: depositClerksCount)
let loanSemaphore = DispatchSemaphore(value: loanClerksCount)
```

`Operation`에서 해당 기능을 사용하기 위해서는 `maxConcurrentOperationCount`를 사용하는데 이 방법은

`OperationQueue`에 들어가는 각각의 `Operation`에 대한 전체적인 쓰레드를 설정하는 기능입니다.

```swift
// OperationQueue의 경우 maxConcurrentOperationCount라는 맴버 변수를 통해 제한
operationQueue.maxConcurrentOperationCount = 3

let loanTask = BlockOperation {
    print("loan task")
}
let depositTask = BlockOperation {
    print("depositTask task")    
}
// loanTask, depositTask의 경우 maxConcurrentOperationCount 맴버 변수가 없음
loanTask.maxConcurrentOperationCount = loanClerksCount
depositTask.maxConcurrentOperationCount = depositClerksCount
```

각 `Operation`이 맴버 변수로 `maxConcurrentOperationCount`를 가지고 있지는 않았기 때문에 해당 방법을 사용하지 못했는데 그렇다면 각 `Task` 별 쓰레드 갯수를 제한하려면 `Semaphore` 밖에 없는 걸까요?

2024-02-07 15:14 UTC, keeplo requested changes
처음 접하신다면 정말 댕노답 수준이고..
비동기 개념을 알아도 처음 구현해보신다면... 그래도 노답 수준일텐데...
고생 많으셨습니다!! 

PR은 정답 제출이 아니라 학습을 위한 수단이니 리뷰 확인하시면서
좀 더 개념을 잡아가고 개선하면서 많은 연습이 되시길 바라요!

---
### 고민한 부분
다양한 시도를 해보신게 이해되었습니다!
하지만 말씀해주신 `group` 관련한 구현이 뭔가 빠진 것 같은데 확인해주시고
기대동작을 수정해주시면 좋을것 같아요!

---
### 조언을 얻고 싶은 부분
우선 질문의 답변을 드리자면 
`DispatchSemaphore`는 스레드 갯수 제한이 주목적이라기 보다 호출 차단이 주목적으로 이해하고 있습니다.
공식문서도 꼭 확인해보시면 좋을것 같아요!
하지만 저 개체의 특성을 이용해서 잘 설계하면 스레드 갯수 제한하는 효과를 얻을 수는 있습니다!

여태 문제해결 하신 것처럼 GCP나 OperationQueue에서 제공되는 도구들이 
저희에게 주어진 문제를 완전하게 해결해주는 메서드나 개체는 없습니다!
다양한 도구들의 특성을 잘 파악하고 조합하면 기대하시는 스레드 제한을 구현할 수 있다고
답변드릴 수 있을것 같아요!

OperationQueue를 많이 다뤄보지 못해서 궁금한 점도 있습니다!

말씀해주신 `operationQueue.maxConcurrentOperationCount = 3`
부분을 이용하지 않은 이유가 있으신가요?
`BlockOperation`은 분명 다른 타입이라 말씀하신것처럼 변수가 없는데,

위에서 언급한 걸 이용하면 구현할 수 있을까 생각이 들었습니다!
뭔가 정답이 있어서 딱 정해진 틀이 있는건 아니고,

저는 상황에 따라서는 GCP와 혼합할 수도 있을것 같고
다양한 시도를 해보시면 좋을 것 같습니다.

업무 시작 후 모든 고객의 업무가 끝나게 하는 베이스 스레드가 꼭 메인 스레드 일 필요는 없습니다!

`메인 -> 글로벌 -> Operation Queue` 이용 같은 일례를 말씀드릴 수도 있을것 같은데
물론 경험하거나 본건 아닙니다만, 문제 해결하기 위해서 다양한 조합은 시도해보면 좋을 것 같아요!

---
### 추가 사항 - Xcode의 가상 쓰레드 -> DispatchQueue 좀 더 고민해보기!
현재 구현은

Global DispatchQueue 에 Customer Queue에 담긴 모든 요소를 while 문을 통해 전달합니다.

DispatchQueue.global().async { 
   // 이 부분 -> `{ Task }`
}

Global DispatchQueue 는
고객 5명이라고 가정
++++++++++++++++++++++++++++++
{ Task } { Task } { Task } { Task } { Task } 
++++++++++++++++++++++++++++++
이런 형태로 구성됩니다.

그리고 기대하신 구현은 

++++++++++++++++++++++++++++++
{ Task } { Task } 
++++++++++++++++++++++++++++++

Thread 1 (예금 1) => { Task }  처리중

Thread 2 (예금 2) => { Task } 처리중

Thread 3 (대출 1) => { Task } 처리중

이런 느낌으로 기대하실거에요
`Print` 중심으로 확인하면 기대한 동작은 합니다!

하지만 원리는 조금 다시 바라보셔야 하고 많은 고민이 필요합니다.

[화면 기록 2024-02-07 오후 7.46.58.zip](https://github.com/tasty-code/ios-bank-manager/files/14194901/2024-02-07.7.46.58.zip)

위 영상을 확인하시면 쓰레드가 Task 갯수만큼 늘어나는걸 보실 수 있을거에요
저도 완벽한 물리적인 구조와 동작 이해는 할 수 없기때문에 위에서 처럼 실제 동작이 그럴지 정확히 않다는 말씀은 꼭 드리고 싶어요.

실제 물리적 쓰레드는 아니고 OS에서 Xcode에 할당된 자원 내에서 
Process가 분리할 수 있는 가상 쓰레드인 걸로 알고 있어요

이렇게 긴 코멘트를 남기는 의도는 두 분이 코드 로직을 메모리 영역까지 고려해서 입체화 하는 과정을 넘어서 비동기 설계는 다른 차원까지 넘나드는 개념이고 

GCP나 CS 비동기 기초 지식이 부족하면 완전한 구현이 불가하고
`!` 강제 언래핑처럼 이유는 모르지만 계속 앱이 죽는 현상이 발생할 수 있습니다.

제가 이 프로젝트 진행할때 다른팀은 GCP - Semaphore 만으로 위 가상쓰레드가 3개가 생기게 구현한 팀도 있었습니다. 그래서 원리를 이해하면 충분히 원하는 구현으로 컨트롤 가능할거라 생각합니다!

이 부분을 좀 더 깊게 탐구해보실 필요가 있어요! 
저는 새로운 설계를 구상하기보다 현재 구현에서 어떤 오류가 있을지 어떤 형태로 동작하는지 원리를 파악하시는데 중점을 두는게 좋을것 같아요! 

---

현재 PR 브런치를 다운로드해서 빌드하면 요구사항 기대동작이 완전하지 않은 부분이 있습니다.
설계가 꼭 완전할 필요는 없습니다! 그렇게 만드는것도 쉽지 않고 해낸다면.. 천재... 가 아니라 그럴 수 없습니다. 비동기 영역 만큼은 많은 내공과 경험이 있는분 아니면 완전한 설계는 할 수 없다고 생각해요

이번 Step이야 말로 기대 요구사항을 완전히 동작하는 표면적인 구동을 완성하는게 1차
공유자원 / 경쟁상태 / 컨택스트 체인징 등의 큼직한 키워드 중심으로 사이드 이펙트 없는지 검증하는게 2차 
느낌으로 개선해보면 좋을 것 같아요!

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        self.depositClerksCount = depositClerksCount
직원의 수를 의존성 주입을 통해 유연하게 구현할 수 있도록 설계하셨군요!

아주 좋습니다! 작은 부분조차 신경쓰면 수정하는 비용이 줄 수 있는 좋은 습관이 될거라고 생각해요 👍

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            }
쓰레드를 이용하는 구현은 코드를 다차원으로 봐야하는 어려운 작업입니다!

저는 쉽게 표현할때 멀티버스라는 표현을 하는데요
하지만 실제로는 같은 코드를 접근하고, 같은 메모리 영역을 접근하는 경우가 생길 수 있습니다
`공유자원 (임계영역 Critical Section)` 이라는 표현이라거나 `경쟁상태 (Race Condition)` 키워드에 대해서 공부하시면 좋을 것 같아요!

가장 중요한건 **Context switch** 입니다.

위 코드에서 `self` 접근을 하는 부분은 모두 `공유자원`을 사용하게 됩니다.
제 예상에는 `bankDepositClerk.work(for: customer)` 부분은 동시에 작업되는 경우가 최대 2개 이기 때문에 큰 문제는 없을것 (매우 정밀히 따지면 문제가 유발됩니다.) 같지만,
`self.delegate?.showCustomerWorkDone(customerNumber: customer.number, workType: customer.purpose.name)` 은 문제가 있을 확률이 클 것 같아요.

컨텍스트 스위칭이 발생하면 예금업무가 먼저 끝났음 (work 리턴) 에도 대출업무가 먼저 출력될 수도 있습니다.

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        let loanSemaphore = DispatchSemaphore(value: loanClerksCount)
`DispatchSemaphore`를 사용해주셨군요!

좋습니다. 제가 이해하기로는 전통에 CS 에서 다루는 SemaPhore 와 유사합니다.
이 부분에 대해서 `2` 로 설정한다고 해서 Thread 가 2개 생긴다고 생각하는건 오류가 있을 수 있습니다!

혹시나 그렇게 생각한 설계라면 조금 더 고민해보시면 좋을것 같아요!

DispatchQueue 에 쌓인 Task가 wait을 지날때 2개까지 enqueue 되고
세번째 wait을 마주하면 enqueue 되지 않게 막아준다고 저는 이해하고 있습니다.
> 실제 동작이 그렇게 되는 지는 정확하지 않습니다.
> 실제론 가상 쓰레드에 Task가 할당이 되는 걸로 파악했는데,
> signal 시점에 가장 최근에 enqueue된 Task가 동작하는 형태로 표면적으로는 제 설명처럼 동작합니다.

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        group.wait()
커밋이 푸시가 빠졌거나 놓치신건 아닐까 생각했는데..

혹시 의도하신 구현이 있을까요?
현재 PR에서는 `MainThread` 로 `excuteBankWork()` 메서드가 리턴되어서
모든 고객의 업무처리가 끊나지 않았는데 은행 종료 print가 동작되고 있습니다!
<img width="955" alt="스크린샷 2024-02-07 오후 7 30 46" src="https://github.com/tasty-code/ios-bank-manager/assets/24707229/69d76809-6c4d-4f44-a988-4f0ee4125da2">



확인해주시면 좋을것 같아요

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
>  }
OOP 를 잘 활용한 설계는 아닌거 같아요.

동일한 일을 하는 직원이라면 의존성 주입으로 예금업무를 하는 직원인지 대출업무를 하는 직원인지 구분하면서
인스턴스로써 개체를 구분할 수 있을것 같아요!

프로토콜을 채택해서 다형성을 기대하는 설계는 너무 좋은데 현재 구조체를 나누는 부분은 큰 장점이 없을것 같다고 느껴집니다 ㅠㅠ

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankWorkType.swift
> +}
`enum`을 적절하게 잘 사용해주시네요! 👏🏻👏🏻

`CaseIterable`을 이용해서 모든 경우의 수를 모두 접근하는 구현도 잘 사용하시고
너무 좋습니다!

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        serveCustomer(depositClerksCount,loanClerksCount)
작아보이지만 실제로 업무에서도 이런 실수가 많이 나고, 
그렇기 때문에 파라미터의 전치사 인수명이 중요합니다!

자세히 보시면 두 변수 위치가 바뀌어서 예금업무가 1명 대출업무가 2명 할당된 동작을 합니다!

2024-02-07 15:14 UTC, Marcorable commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private var depositClerksCount: Int
작은 부분이지만.. 

명사형으로 쓴다면 `s`를 빼는게 좋을것 같아요!

2024-02-10 08:32 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        group.wait()
코드 수정중에 빼먹어버렸네요!! 수정했습니다

2024-02-10 08:33 UTC, angryeon7 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankClerk.swift
>  }
의존성 주입으로 해당 코드를 수정했습니다!!

2024-02-12 07:56 UTC, keeplo reviewed
3주간 고생 많으셨습니다!

이번 프로젝트는 단순한 코드 로직 수준을 벗어난 첫 프로젝트가 아니었나 생각합니다.
그만큼 어려운 영역이 시작되었고, 
두 분이 iOS 개발자 뿐만아니라 개발자의 길에 한발짝 내딛는 좋은 프로젝트일거라고 생각합니다!!

비동기 영역은 저 같은 주니어 개발자는 물론 많은 개발자 분들이 종종 실수가 생기기도 하는 영역입니다.
엄청 복잡하고 어렵고 헷갈립니다. 그만큼 CS 본질의 학습이 많이 필요한 영역이고 부트캠프에서 강조하는 공식문서나 정확한 정보에 중요성을 알려주는 영역이라고 생각해요 ㅠㅠ

운영체제 수업들을때 1만번 100만번 For 루프를 돌렸을때나 한 두번 나오던 공유자원 이슈가
현업이나 이런 과제 스타일 프로젝트에서는 10번만 돌려도 나오는지 의문이긴 한데...
오히려 100만명이나 쓰는 앱이전에 100명이 쓰는 앱일때 발견한다면 긍정적이라 생각하는 편이에요..

제가 Step 3 이전 스텝에서 붙잡?!던 부분이 있어 아쉬우실 수도 있지만,
기초나 기본이 충실한게 더 중요하다고 생각해서 꼭 짚었다는 점 이해해주세요..
Step 3 경험이면 충분한 고민을 해보았고 나중에 문제에 마주할때 충분히 해쳐나가실 수 있는 큰경험이라고 생각합니다!!

이번 프로젝트 마무리 코멘트에 이슈를 또 남겨서 뭔가 해결못한 찝찝함이 있으실 수 있지만..
아마 계속 고민하시고 해결해보려고 노력하실거라 기대하고, 
비밀아닌 비밀이지만 현업에서 많은 앱들이 그런채로 서비스 됩니다 ㅎㅎ;; 🤣
또 실패 레퍼런스가 많아도 그게 하나의 실패할 수 있는 선택권을 줄여주는 큰 무기가 될 수 있습니다!

주절 주절 코멘트가 길었네요
명절때도 커밋이 올라온걸 확인했는데 두 분 열정만큼 저도 좀 더 힘이 되고 싶었나봐요;; ㅎㅎ
꼭 프로젝트 아니어도 괜찮으니 궁금한점이나 도움이 필요하면 DM은 언제든 열려있습니다 (답은 좀 늦지만 ㅎㅎ;;)

2024-02-12 07:56 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        group.wait()
iOS 뿐 아니라 애플리케이션에서 UI를 담당하는 부분은 거의 Main Thread 라 불리우는 1번 쓰레드에서 동작합니다.

가장 큰 이유는 사용자의 입력을 받기 위해서죠
그런점에서 현재와 같은 콘솔앱과 print() 출력만으로는 가능할 수 있지만
애초에 프로젝트 기획처럼 Console 앱과 UI 앱에 공용으로 사용가능한 
Core 부분을 만드는 설계라서 조금 아쉬운 부분입니다.

실제로 Main Thread 의 원리를 조사해보시면 
UI 입력 및 다양한 인터럽트(푸시, 타이머 등)는 
루프를 통해서 체크합니다.
그래서 저는 Step 2 까지 구현해주신 것처럼 Main Thread에서 
모든 결과를 기다리는 동안 while 반복문으로 대기하는 방향성이 좋을것 같다고 생각합니다.

2024-02-12 07:56 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        DispatchQueue.global().sync {
<img width="624" alt="image" src="https://github.com/tasty-code/ios-bank-manager/assets/24707229/da5ba137-b1f1-4fce-bdce-968fccbf6d66">

저희 구현의도라면 1번 -> 5번 순으로 업무가 시작되면 동일한 예금업무 소요시간 후
1번 -> 5번 순서로 업무종료를 UI로 보여줘야 하는데 그렇지 못한 부분을 확인할 수 있습니다.

sync 블럭을 추가하신 의도가 있을까요? 
어떤 기대동작으로 설계하시건지 설명해주실 수 있을까요?

2024-02-12 08:42 UTC, Gnoam-R commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        DispatchQueue.global().sync {
이전에 말씀 해주신 것처럼 대출 업무와 예금 업무가 공유 자원에 대해서 동시 접근 시 `Race condition`이 발생할 수 있습니다.

```swift
private func manageWork(with customer: Customer) {
    DispatchQueue.global().sync {
        delegate?.showCustomerWorkStart(customerNumber: customer.number, workType: customer.purpose.name)
        bankLoanClerk.work(for: customer)
        delegate?.showCustomerWorkDone(customerNumber: customer.number, workType: customer.purpose.name)
    }
}
```

`sync` 를 통해서 동기적으로 공유 자원에 접근하면 외부에서 비 동기적으로 `manageWork` 를 호출 하더라도 순차적으로 함수 안의 코드를 실행하여 동시에 같은 자원에 접근하지 못할거라 생각했어요.

다른 방법들을 찾아보니 경쟁 상태를 해결하는 방법이 2가지 있는데 .

첫번쨰로 `Serial Queue` 사용시  비동기로 `manageWork` (print와 delay를 수행) 를 실행하더라도 Serial 큐를 사용하게 되면 Queue에 들어가는 task들이 하나의 스레드에서 사용되어서 모든 task가 순차적으로 수행되는거 같습니다.

```swift
private func manageWork(with customer: Customer) {
    serialQueue.sync {
        delegate?.showCustomerWorkStart(customerNumber: customer.number, workType: customer.purpose.name)
        bankLoanClerk.work(for: customer)
        delegate?.showCustomerWorkDone(customerNumber: customer.number, workType: customer.purpose.name)
    }
}
```

![image](https://github.com/tasty-code/ios-bank-manager/assets/67363759/5cf1e355-dc38-46cd-85dd-2c3134dd5c4b)

비동기적인 특성을 살리지 못한다고 생각하고 사용하지 못했습니다.

두번째로 **`Dispatch Barrier` 의 경우 get, set을 사용하여 read, write에 다른 쓰레드 작업을 부여하는 방법인데 저희 코드에서는 Delegate와 메서드를 사용하는**

프로퍼티에 간접적으로 접근하는 방식으로 구현했기 때문에 이 방법이 적절치 못하다고 생각했어요.

2024-02-15 10:32 UTC, keeplo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +        DispatchQueue.global().sync {
확인이 좀 늦었네요 ㅠㅠ

다양하게 시도해보시고 고민해보시는게 너무 좋네요!
사실 이 문제를 드라마틱하게 한가지를 사용해서는 불가능하고
다양한 조합이나 쓰레드를 다양하게 써와야 할것 같아요

저도 프로젝트 내내 고민해봤는데.. 답을 못 얻었어요
그나마 확률적으로 설계를 한거를 공유드리면,

두 개에 Serial Queue(예금, 대출)를 만들고
dequeue 자체가 global Queue 블럭에서 시작하고 Semaphore로 3개만 조절한 뒤에
예금과 대출에 따라서 시리얼 큐에 담아요

구현을 실제로 한건아니라서 될지는 실험을 해봐야하는데...
세마포어 3개중에 예금 3개나 대출 3개가 되지 않는 방법을 좀더 고민해야하는 문제점도 있을거 같아요..

---

사실 확률적으로 동작에는 큰문제가 없고 충분히 잘해내셨어요!
조금 더 완전해지길 바라는 마음에 다양한 문제점을 제기했지만,
지금처럼 다양한 고민을 해보신 것 만으로도 엄청 공부가 되셨을거라 생각합니다! 
두 분 모두 충분히 잘하셨고 찝찝하게 생각마시고 이 경험으로 앞으로 문제를 잘해결해나가시면 좋을것 같아요!

고생많으셨습니다!

2024-02-20 09:36 UTC, closed without merging