은행 창구 관리 앱 [Step3] Yuni, Paul
tasty-code/ios-bank-manager pull request #94
Opened 2024-02-07 07:37 UTC by earths-voluble

안녕하세요 마이노(@Mino777)! 유니(@Jin0Yun), 폴(@earths-voluble) 조의 은행 창구 관리 앱 프로젝트 Step 3 PR입니다! 늦어져서 죄송합니다 ㅜㅜ

## 어려웠던 점
### 생소한 동시성 프로그래밍
저희 모두 동시성 프로그래밍의 개략적인 개념은 알고 있었지만, 실제 프로젝트에서 사용해본 경험은 거의 없었습니다. 때문에 Step3을 처음 시작했을 때는 막막한 기분도 들었습니다. 하지만 앞으로 네트워크 등을 포함한 더 큰 규모의 프로젝트를 위해서는 피해갈 수 없는 개념이기 때문에 하나씩 익혀가면서 코드를 작성해 보았습니다.

## 구현
저희는 가장 기본적인(?) 동시성 프로그래밍 클래스인 `DispatchQueue`를 사용해서 프로젝트를 진행했습니다.
### 객체지향 컨셉
현실 은행의 창구가 업무별로 나뉘어 있는 것처럼, 예금과 대출 두 업무의 은행원별로 생성된 스레드와 업무별로 생성된 큐로 구현했습니다:
```swift
let bankers = [firstDepositBanker, secondDepositBanker, loanBanker]
```

```swift
...
case .deposit:
    self?.depositSemaphore.wait()
    if let depositQueue = self?.customersQueue[.deposit] {
        banker.taskProcess(queue: depositQueue)
    }
    self?.depositSemaphore.signal()
case .loan:
    if let loanQueue = self?.customersQueue[.loan] {
        banker.taskProcess(queue: loanQueue)
    }
...
```
예금 스레드는 2개이기 때문에, 2개의 스레드가 예금 큐에 동시에 접근하는 것을 막기 위해 `DispatchSemaphore`를 사용했습니다:
```swift
let depositSemaphore = DispatchSemaphore(value: 2)
```
또한 비동기 작업을 묶어서 처리하고, 해당 작업들이 끝난 후 종료 메시지가 출력되도록 하기 위해 `DispatchGroup`을 사용했습니다.

## 고민한 부분
### 지연을 줄 때 사용할 메서드에 대해서
선택지로는 크게 `thread.sleep`과 `asyncAfter`가 있었습니다.
저희가 이해한 각 메서드의 특성은 다음과 같습니다.
**thread.sleep**
- 동기 작업입니다.
- 쓰레드를 차단해서 작업을 지연시킵니다.
- 메인 쓰레드에서 사용될 경우, UI동작까지 지연시킬 수 있습니다.

**asyncAfter**
- 비동기 작업입니다.
- 쓰레드를 차단하지 않고 작업을 지연시킵니다.
- 제대로 작성되었고 무거운 작업이 아니라면 메인 쓰레드에서 사용하더라도 문제가 없습니다.

`thread.sleep`은 적용이 쉽고 간단했으며, 일단 메인 쓰레드에서 사용하지 않는 저희의 코드에서는 명세를 구현하는 데 있어서 문제가 없었습니다.
하지만 메인 쓰레드에서는 사용할 수가 없는 메서드이고, 유저와의 상호작용에 있어서 잠재적으로 문제를 일으킬 수 있는 메서드여서 그런지, 사용이 추천되는 메서드는 아닌 것 같았습니다.
그래서 저희도 `asyncAfter`를 사용해보고 싶었으나... 비동기 메서드에 대한 이해도 부족과 시간 부족으로 결국 적용해보지는 못했습니다. 추후 여유가 생긴다면 꼭 리팩토링 해보고 싶은 부분입니다.

### 두 개의 큐를 사용하면서 생긴 문제
예금과 대출 두 개의 작업별로 큐를 사용하면서 사소한 문제가 생겼습니다. 예금 큐의 실행이 먼저이기 때문에, 맨 처음은 무조건 예금 고객이 출력되는 것입니다.

<img width="200" alt="Pasted image 20240206222711" src="https://github.com/tasty-code/ios-bank-manager/assets/103843007/ba7dfeb6-aefa-4fc0-87c6-607dd083ca56">

때문에 1번 고객이 첫 번째로 처리되지 않는...다소 어색한 동작이 눈에 밟히게 되었습니다.
그래도 저희는 두 개의 창구 컨셉이 마음에 들어서 큐를 줄이지는 않았지만, 두 가지 모두를 충족시키지는 못해 다소 아쉬웠습니다.

## 궁금한 점
### 현업에서의 비동기 처리에 대해
비동기 처리에는 다양한 솔루션이 있는 것으로 알고 있습니다. 저희가 이번 프로젝트에서 사용한 `DispatchQueue`를 비롯해서, `OperationQueue`, `async/await`, `Combine`외부 라이브러리까지 고려한다면 `RxSwift` 등등 정말 다양한데요.
현업에서 활동하시면서 이렇게 많은 솔루션 중 어떤 솔루션을 주로 사용하고 계시는지, 왜 사용하시는지 궁금해졌습니다!

---

다른 개념들도 물론 마찬가지지만, 동시성 프로그래밍에 대해서는 더더욱 아직 모르는 게 많아서, PR을 작성하면서도 긴가민가한 부분이 많네요. 앞으로도 많은 공부와 연습이 필요할 부분 같습니다. 부족한 코드지만 이번 리뷰도 잘 부탁드리겠습니다!🙇‍♂️

2024-02-07 15:12 UTC, Mino777 requested changes
안녕하세요!! 유니, 폴!

STEP 3 진행하시느라 정말 수고 많으셨습니다!!🥳

GCD를 활용해서 동시성 프로그래밍을 구현해보셨네요!! 좋습니다💪
동시성 프로그래밍에 대해서는 정말 깊게, 제대로 학습하고 넘어가셔야 합니다.
왜 이렇게 중요한 개념인지, 활용할 때 어떤 문제점이 생길 수 있는지, 그 문제점들은 어떤식으로 해결할 수 있는지 등등 관련 질문에 대해서 정확하게 알고 완벽하게 답변할 수 있을 정도로 학습하시고 넘어가시면 좋습니다👍
코드에 대한 코멘트들 및 남겨주신 고민들에 대해 답변 남겨드립니다!

---------------------------------------------------------------------------------------

## 코멘트

### 고민했던점
> 지연을 줄 때 사용할 메서드에 대해서

각각의 메서드에 대해서 학습하신 부분 너무 좋습니다ㅎㅎ
정리해주신대로, Thread.sleep 메서드의 경우 보통의 어플리케이션을 개발할 때 개발자가 직접 쓰는일은 없다고 보셔도 무방합니다ㅎㅎ

> 두 개의 큐를 사용하면서 생긴 문제

해당 문제의 경우 코드 코멘트에 달아놓았습니다!

> 현업에서의 비동기 처리에 대해

우선 크게 정리해보면,
대부분의 레거시 프로젝트 -> RxSwift
신규 프로젝트 -> Async/Await + Combine
그리고 DispatchQueue, OperationQueue 등의 low level API를 추상화하여 개발자가 쓰기 편하게 도구형태로 만들어준게 위의 high level API 들이라고 볼 수 있습니다.
그래서 DispatchQueue, OperationQueue를 직접 쓸일은 많이 없지만, 이와 같은 low level을 이해하지 못하고 제대로 학습하지 않는다면 high level의 api들을 사용할 때 문제점이 생기거나, 적극적으로 활용하지 못할거에요. 결론적으로는 low level을 제대로 학습하시면, 어떤 팀에 들어가서 Rx를 사용하던, Combine을 사용하던 그저 쓰는 도구가 달라질 뿐이기에 금방 익숙해지실 수 있습니다ㅎㅎ

2024-02-07 15:12 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
>      }
customersQueue 도 외부에서 주입해주면 좋을 것 같아요!

이니셜라이저에서는 최대한 로직없이 초기화에만 집중해주는게 좋습니다!

2024-02-07 15:12 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
>      }
openBank 메서드가 하는일이 너무 많은 것 같아요!

좀 더 쪼개봅시다💪

2024-02-07 15:12 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            }
고민해보신 점에서 큐를 두개를 사용하면서 발생한 문제점의 경우 큐를 두개를 사용해서 발생하는 문제라기보단, banker가 queue를 주입받아서 발생하는 문제점 같아요!
banker.taskProcess 해당 메서드에서 queue를 받는것이 아닌, client를 주입받아서 업무를 진행하게 만들면 해결될 것 같아 보이네요.
그러려면 Bank에서 queue를 반복하면서 banker에게 일을 시키도록 해야하고, 그러면 업무에 의존하지 않고 먼저 온 고객부터 업무를 진행할 수 있겠네요!
한번 수정해보시죠💪

지금 보니 되게 애매하게 코멘트를 드렸네요ㅠㅠ 제가 말씀드리고 싶었던 부분은 client를 주입하게 되면 결국 Bank에서 client끼리 비교해서 주입할 수 있지 않을까요?! 라는 느낌을 말씀드리고 싶었어요!

2024-02-07 15:12 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankingService.swift
> +    case loan
업무 종류를 enum 타입으로 관리하신 부분 너무 좋습니다👍👍

2024-02-07 15:12 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            if let queue = customersQueue[randomTaskTime] {
randomTaskTime 이 아닌 서비스의 타입을 담는 상수네요!
네이밍 수정이 필요해보입니다💪

2024-02-07 15:12 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private let group = DispatchGroup()
semaphore와 dispatchGroup을 사용해보셨네요!
해당 객체들을 간략하게 설명해주세요💪

2024-02-08 04:36 UTC, earths-voluble commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            if let queue = customersQueue[randomTaskTime] {
수정했습니다! 72d29bf

2024-02-08 04:56 UTC, earths-voluble commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
>      }
감사합니다~수정했습니다! 044782d

2024-02-08 05:25 UTC, earths-voluble commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
>      }
쪼개보았습니다!😆 4b82814

2024-02-08 07:44 UTC, earths-voluble commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private let group = DispatchGroup()
### semaphore
교착 상태를 방지하기 위해 고안된 프로그래밍에서 오래된 개념입니다. 
semaphore의 값을 정수로 지정해 놓고, 자원에 접근하는 스레드가 있을 경우 1씩 감소시켜, 0이 될 경우 접근을 제한합니다. swift에서는 wait를 통해 신호를 감소시키고, signal을 통해 증가시킵니다.
개인적으로는 용어의 어원이 한 선로를 공유하는 여러 열차의 통행을 통제하기 위해 사용된 깃발이라는 의미를 보고 그 의미와 역할이 굉장히 잘 와닿았습니다.

### dispatchGroup
비동기 작업들을 그룹으로 묶고, 묶인 그룹들의 작업이 모두 완료되었는지 추적할 수 있습니다. enter를 통해 비동기 작업을 그룹에 넣고, leave를 사용해 작업이 끝났음을 알립니다. notify를 통해 비동기 작업 그룹의 동작이 끝난 후 동작할 코드를 지정할 수 있습니다.

2024-02-13 01:20 UTC, merged

2024-02-13 01:22 UTC, Mino777 commented
말씀드린 부분 제외하고, 코멘트 드린 부분들 수정 잘해주셔서 머지하도록 하겠습니다!

고생하셨습니다💪💪